#!/bin/sh

set -e

version="1.7.1"

echo "Building amath ${version} for Windows ..."

rm -f amath-${version}.zip
rm -Rf amath
rm -Rf dist
mkdir dist

./configure --enable-test --cross-compile="i686-w64-mingw32" CFLAGS="-DWINDOWS" LDFLAGS="-static -static-libgcc -static-libstdc++"
make clean
make static
mv amath dist/amath-${version}-x86.exe
make clean

./configure --enable-test --cross-compile="x86_64-w64-mingw32" CFLAGS="-DWINDOWS" LDFLAGS="-static -static-libgcc -static-libstdc++"
make static
mv amath dist/amath-${version}-x64.exe
make clean

cd dist
touch hashkeys
sha1sum amath-${version}-x86.exe >>hashkeys
sha1sum amath-${version}-x86.exe >>hashkeys
sha256sum amath-${version}-x86.exe >>hashkeys
sha256sum amath-${version}-x86.exe >>hashkeys
cd ..

cp LICENSE dist/
cp HISTORY dist/

mkdir dist/script
cp script/* dist/script/
date -Ru >dist/build_date

mv dist amath
zip -r amath-${version}.zip amath/*
