#!/bin/sh

version="1.7.0"

echo "Building amath ${version} for Windows ..."

touch hashkeys
rm -Rf amath
rm -Rf dist
mkdir dist

./configure --enable-test --cross-compile="i686-w64-mingw32" --cflags="-D_WIN32" --ldflags="-static -static-libgcc -static-libstdc++"
make static
mv amath dist/amath-${version}-x86.exe
make clean

./configure --enable-test --cross-compile="x86_64-w64-mingw32" --cflags="-D_WIN32" --ldflags="-static -static-libgcc -static-libstdc++"
make static
mv amath dist/amath-${version}-x64.exe
make clean

./configure --enable-test --cross-compile="i686-w64-mingw32" --cflags="-D_WIN32 -DANSICONSOLE" --ldflags="-static -static-libgcc -static-libstdc++"
make static
mv amath dist/amath-${version}-ansi-x86.exe
make clean

./configure --enable-test --cross-compile="x86_64-w64-mingw32" --cflags="-D_WIN32 -DANSICONSOLE" --ldflags="-static -static-libgcc -static-libstdc++"
make static
mv amath dist/amath-${version}-ansi-x64.exe
make clean

cd dist
touch hashkeys
sha1sum amath-${version}-x86.exe >>hashkeys
sha1sum amath-${version}-x86.exe >>hashkeys
sha1sum amath-${version}-ansi-x86.exe >>hashkeys
sha1sum amath-${version}-ansi-x64.exe >>hashkeys
sha256sum amath-${version}-x86.exe >>hashkeys
sha256sum amath-${version}-x86.exe >>hashkeys
sha256sum amath-${version}-ansi-x86.exe >>hashkeys
sha256sum amath-${version}-ansi-x64.exe >>hashkeys
cd ..

cp LICENSE dist/
cp HISTORY dist/

mkdir dist/script
cp script/* dist/script/
date -Ru >dist/build_date

mv dist amath
zip -r amath-${version}.zip amath/*
