.TH "lib Directory Reference" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBclib\fP"
.br
.ti -1c
.RI "directory \fBcplex\fP"
.br
.ti -1c
.RI "directory \fBdconv\fP"
.br
.ti -1c
.RI "directory \fBreal\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBclib\&.h\fP"
.br
.RI "\fIC functions for manipulating strings and memory\&. \fP"
.ti -1c
.RI "file \fBcomplex\&.h\fP"
.br
.RI "\fIFunctions in math library for handling complex numbers\&. \fP"
.ti -1c
.RI "file \fBdoc\&.h\fP"
.br
.RI "\fIDocumentation in doxygen format\&. \fP"
.ti -1c
.RI "file \fBdprint\&.h\fP"
.br
.RI "\fIFormat defitions used in the Dragon4 library\&. \fP"
.ti -1c
.RI "file \fBdstandard\&.h\fP"
.br
.RI "\fIType defitions for the Dragon4 library\&. \fP"
.ti -1c
.RI "file \fBmath\&.h\fP"
.br
.RI "\fIFunctions in math library for handling real numbers\&. \fP"
.ti -1c
.RI "file \fBmem\&.h\fP"
.br
.ti -1c
.RI "file \fBplatform\&.h\fP"
.br
.in -1c
