.TH "lib/dconv Directory Reference" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/dconv Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBdmath\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdmath\&.h\fP"
.br
.RI "\fIMath used in the Dragon4 library\&. \fP"
.ti -1c
.RI "file \fBdprint\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdragon4\&.cpp\fP"
.br
.ti -1c
.RI "file \fBdragon4\&.h\fP"
.br
.RI "\fIConvert floating point format to a decimal number in string format\&. \fP"
.in -1c
