.TH "app/localize Directory Reference" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/localize Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBhelp\&.h\fP"
.br
.RI "\fIHelp texts for statement\&. \fP"
.ti -1c
.RI "file \fBialias\&.h\fP"
.br
.ti -1c
.RI "file \fBident\&.h\fP"
.br
.RI "\fIHelp texts for built-in functions\&. \fP"
.ti -1c
.RI "file \fBkword\&.h\fP"
.br
.RI "\fIKeywords used by lexer\&. \fP"
.ti -1c
.RI "file \fBlex\&.h\fP"
.br
.RI "\fI\fBLexer\fP defitions used by other classes\&. \fP"
.ti -1c
.RI "file \fBstart\&.h\fP"
.br
.RI "\fIStart message and version text\&. \fP"
.ti -1c
.RI "file \fBtags\&.h\fP"
.br
.ti -1c
.RI "file \fBtext\&.h\fP"
.br
.RI "\fIStatic texts in amath\&. \fP"
.in -1c
