.TH "lib/clib Directory Reference" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/clib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalloccpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmem\&.c\fP"
.br
.ti -1c
.RI "file \fBmemcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmemset\&.c\fP"
.br
.ti -1c
.RI "file \fBstrcmp\&.c\fP"
.br
.ti -1c
.RI "file \fBstrlen\&.c\fP"
.br
.ti -1c
.RI "file \fBuntag\&.c\fP"
.br
.in -1c
