.TH "app/system Directory Reference" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbase\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBconsole\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconsole\&.h\fP"
.br
.RI "\fIGeneric console system calls\&. \fP"
.ti -1c
.RI "file \fBconsole_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconsole_amiga\&.h\fP"
.br
.ti -1c
.RI "file \fBconsole_stdc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBconsole_stdc\&.h\fP"
.br
.ti -1c
.RI "file \fBfilesystem\&.h\fP"
.br
.RI "\fIGeneric file system calls\&. \fP"
.ti -1c
.RI "file \fBfilesystem_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfilesystem_amiga\&.h\fP"
.br
.ti -1c
.RI "file \fBfilesystem_stdc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfilesystem_stdc\&.h\fP"
.br
.ti -1c
.RI "file \fBgraph\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgraph\&.h\fP"
.br
.RI "\fILogic related to graph of functions\&. \fP"
.ti -1c
.RI "file \fBgraph_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgraph_amiga\&.h\fP"
.br
.ti -1c
.RI "file \fBgraph_gtk\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgraph_gtk\&.h\fP"
.br
.ti -1c
.RI "file \fBlanguage\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlanguage\&.h\fP"
.br
.ti -1c
.RI "file \fBlanguage_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlanguage_amiga\&.h\fP"
.br
.ti -1c
.RI "file \fBlanguage_posix\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlanguage_posix\&.h\fP"
.br
.ti -1c
.RI "file \fBlanguage_stdc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlanguage_stdc\&.h\fP"
.br
.ti -1c
.RI "file \fBpreferences\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpreferences\&.h\fP"
.br
.ti -1c
.RI "file \fBpreferences_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpreferences_amiga\&.h\fP"
.br
.ti -1c
.RI "file \fBpreferences_stdc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBpreferences_stdc\&.h\fP"
.br
.ti -1c
.RI "file \fBproc_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBproc_amiga\&.h\fP"
.br
.ti -1c
.RI "file \fBprogram\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprogram\&.h\fP"
.br
.RI "\fI\fBProgram\fP flow and global states\&. \fP"
.ti -1c
.RI "file \fBprogram_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprogram_amiga\&.h\fP"
.br
.ti -1c
.RI "file \fBprogram_stdc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprogram_stdc\&.h\fP"
.br
.ti -1c
.RI "file \fBprogram_test\&.cpp\fP"
.br
.ti -1c
.RI "file \fBprogram_test\&.h\fP"
.br
.RI "\fITests for arithmetic logic\&. \fP"
.ti -1c
.RI "file \fBtask\&.h\fP"
.br
.RI "\fIGeneric task/process logic\&. \fP"
.ti -1c
.RI "file \fBtask_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtask_amiga\&.h\fP"
.br
.ti -1c
.RI "file \fBtask_stdc\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtask_stdc\&.h\fP"
.br
.ti -1c
.RI "file \fBwindow_amiga\&.cpp\fP"
.br
.ti -1c
.RI "file \fBwindow_amiga\&.h\fP"
.br
.in -1c
