.TH "app/main Directory Reference" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBevaluator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBevaluator\&.h\fP"
.br
.RI "\fITODO: Comment\&. \fP"
.ti -1c
.RI "file \fBfunctiondefs\&.h\fP"
.br
.RI "\fIFunction defitions for math logic\&. \fP"
.ti -1c
.RI "file \fBfunctions\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfunctions\&.h\fP"
.br
.RI "\fIApplication logic tied to functions\&. \fP"
.ti -1c
.RI "file \fBgraphlist\&.cpp\fP"
.br
.ti -1c
.RI "file \fBgraphlist\&.h\fP"
.br
.RI "\fIMemory maintainance for function of graphs\&. \fP"
.ti -1c
.RI "file \fBlexer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBlexer\&.h\fP"
.br
.RI "\fIApplication logic tied to \fBLexer\fP\&. \fP"
.ti -1c
.RI "file \fBnodes\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnodes\&.h\fP"
.br
.RI "\fITop nodes in syntax trees\&. \fP"
.ti -1c
.RI "file \fBoperators\&.cpp\fP"
.br
.ti -1c
.RI "file \fBoperators\&.h\fP"
.br
.RI "\fIApplication logic tied to arithmetic operators\&. \fP"
.ti -1c
.RI "file \fBoptimizer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBoptimizer\&.h\fP"
.br
.ti -1c
.RI "file \fBparser\&.cpp\fP"
.br
.ti -1c
.RI "file \fBparser\&.h\fP"
.br
.RI "\fIApplication logic tied to \fBParser\fP\&. \fP"
.ti -1c
.RI "file \fBstatements\&.cpp\fP"
.br
.ti -1c
.RI "file \fBstatements\&.h\fP"
.br
.RI "\fIGeneral statement nodes\&. \fP"
.ti -1c
.RI "file \fBtoken\&.cpp\fP"
.br
.ti -1c
.RI "file \fBtoken\&.h\fP"
.br
.RI "\fIApplication logic tied to \fBToken\fP\&. \fP"
.ti -1c
.RI "file \fBvalues\&.cpp\fP"
.br
.ti -1c
.RI "file \fBvalues\&.h\fP"
.br
.RI "\fIApplication logic tied to numbers and values\&. \fP"
.ti -1c
.RI "file \fBviewer\&.cpp\fP"
.br
.ti -1c
.RI "file \fBviewer\&.h\fP"
.br
.RI "\fIDebug class to view a syntax tree\&. \fP"
.in -1c
