.TH "lib/real Directory Reference" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/real Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBacos\&.c\fP"
.br
.ti -1c
.RI "file \fBacosh\&.c\fP"
.br
.ti -1c
.RI "file \fBasin\&.c\fP"
.br
.ti -1c
.RI "file \fBasinh\&.c\fP"
.br
.ti -1c
.RI "file \fBatan\&.c\fP"
.br
.ti -1c
.RI "file \fBatan2\&.c\fP"
.br
.ti -1c
.RI "file \fBatanh\&.c\fP"
.br
.ti -1c
.RI "file \fBcbrt\&.c\fP"
.br
.ti -1c
.RI "file \fBceil\&.c\fP"
.br
.ti -1c
.RI "file \fBcopysign\&.c\fP"
.br
.ti -1c
.RI "file \fBcos\&.c\fP"
.br
.ti -1c
.RI "file \fBcosh\&.c\fP"
.br
.ti -1c
.RI "file \fBerf\&.c\fP"
.br
.ti -1c
.RI "file \fBexp\&.c\fP"
.br
.ti -1c
.RI "file \fBexpm1\&.c\fP"
.br
.ti -1c
.RI "file \fBfabs\&.c\fP"
.br
.ti -1c
.RI "file \fBfinite\&.c\fP"
.br
.ti -1c
.RI "file \fBfloor\&.c\fP"
.br
.ti -1c
.RI "file \fBfmod\&.c\fP"
.br
.ti -1c
.RI "file \fBfrexp\&.c\fP"
.br
.ti -1c
.RI "file \fBhypot\&.c\fP"
.br
.ti -1c
.RI "file \fBisnan\&.c\fP"
.br
.ti -1c
.RI "file \fBkcos\&.c\fP"
.br
.ti -1c
.RI "file \fBkremp2\&.c\fP"
.br
.ti -1c
.RI "file \fBksin\&.c\fP"
.br
.ti -1c
.RI "file \fBkstandard\&.c\fP"
.br
.ti -1c
.RI "file \fBktan\&.c\fP"
.br
.ti -1c
.RI "file \fBlog\&.c\fP"
.br
.ti -1c
.RI "file \fBlog10\&.c\fP"
.br
.ti -1c
.RI "file \fBlog1p\&.c\fP"
.br
.ti -1c
.RI "file \fBmatherr\&.c\fP"
.br
.ti -1c
.RI "file \fBmodf\&.c\fP"
.br
.ti -1c
.RI "file \fBnextafter\&.c\fP"
.br
.ti -1c
.RI "file \fBpow\&.c\fP"
.br
.ti -1c
.RI "file \fBprim\&.h\fP"
.br
.ti -1c
.RI "file \fBremp2\&.c\fP"
.br
.ti -1c
.RI "file \fBrint\&.c\fP"
.br
.ti -1c
.RI "file \fBround\&.c\fP"
.br
.ti -1c
.RI "file \fBscalbn\&.c\fP"
.br
.ti -1c
.RI "file \fBsin\&.c\fP"
.br
.ti -1c
.RI "file \fBsinh\&.c\fP"
.br
.ti -1c
.RI "file \fBsqrt\&.c\fP"
.br
.ti -1c
.RI "file \fBtan\&.c\fP"
.br
.ti -1c
.RI "file \fBtanh\&.c\fP"
.br
.ti -1c
.RI "file \fBtrunc\&.c\fP"
.br
.in -1c
