.TH "app/lib Directory Reference" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaengine\&.cpp\fP"
.br
.ti -1c
.RI "file \fBaengine\&.h\fP"
.br
.RI "\fIANSI Conole Engine\&. \fP"
.ti -1c
.RI "file \fBcharbuf\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcharbuf\&.h\fP"
.br
.RI "\fIString and character array logic\&. \fP"
.ti -1c
.RI "file \fBcplex\&.cpp\fP"
.br
.ti -1c
.RI "file \fBcplex\&.h\fP"
.br
.RI "\fIClassbased handling of complex numbers\&. \fP"
.ti -1c
.RI "file \fBfgrid\&.cpp\fP"
.br
.ti -1c
.RI "file \fBfgrid\&.h\fP"
.br
.RI "\fIFunction grid used with graphs\&. \fP"
.ti -1c
.RI "file \fBntext\&.cpp\fP"
.br
.ti -1c
.RI "file \fBntext\&.h\fP"
.br
.RI "\fIText to numbers handling\&. \fP"
.ti -1c
.RI "file \fBnumb\&.h\fP"
.br
.RI "\fIClassbase handling of numbers\&. \fP"
.ti -1c
.RI "file \fBreal\&.cpp\fP"
.br
.ti -1c
.RI "file \fBreal\&.h\fP"
.br
.RI "\fIClassbased handling of complex numbers\&. \fP"
.in -1c
