AbsoluteFunctionNode
NAME
AbsoluteFunctionNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
AbsoluteFunctionNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 178 of file functions.h.
Constructor & Destructor Documentation
AbsoluteFunctionNode::AbsoluteFunctionNode (ExpressionNode * expression)
Definition at line 491 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                     :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * AbsoluteFunctionNode::Create (ExpressionNode * expression) [static]
Definition at line 494 of file functions.cpp.
References AbsoluteFunctionNode().
{
    return new AbsoluteFunctionNode(expression);
}
Number * AbsoluteFunctionNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 499 of file functions.cpp.
References Number::Absolute(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->Absolute();
    return result;
}
char * AbsoluteFunctionNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 505 of file functions.cpp.
{
    return (char*)"abs";
}
Author
Generated automatically by Doxygen for amath from the source code.