.TH "AbsoluteFunctionNode" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AbsoluteFunctionNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAbsoluteFunctionNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 178 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AbsoluteFunctionNode::AbsoluteFunctionNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 491 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
491                                                                      :
492     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * AbsoluteFunctionNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 494 of file functions\&.cpp\&.
.PP
References AbsoluteFunctionNode()\&.
.PP
.nf
495 {
496     return new AbsoluteFunctionNode(expression);
497 }
.fi
.SS "\fBNumber\fP * AbsoluteFunctionNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 499 of file functions\&.cpp\&.
.PP
References Number::Absolute(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result\&.
.PP
.nf
500 {
501     result = expression->Evaluate()->Absolute();
502     return result;
503 }
.fi
.SS "char * AbsoluteFunctionNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 505 of file functions\&.cpp\&.
.PP
.nf
506 {
507     return (char*)"abs";
508 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
