AbsoluteNode
NAME
AbsoluteNode -
SYNOPSIS
#include <operators.h>
Inherits ExpressionNode.
Public Member Functions
AbsoluteNode (ExpressionNode *expression)
~AbsoluteNode ()
char * GetText ()
Number * Evaluate ()
int GetPrecedence ()
SyntaxNode * GetNext ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Protected Member Functions
char * GetNodeText ()
Private Attributes
ExpressionNode * expression
Additional Inherited Members
Detailed Description
Definition at line 60 of file operators.h.
Constructor & Destructor Documentation
AbsoluteNode::AbsoluteNode (ExpressionNode * expression)
Definition at line 125 of file operators.cpp.
References expression, and ExpressionNode::ExpressionNode().
Referenced by Parser::ParseAtomic().
                                                     :
    ExpressionNode(), expression(expression) { }
AbsoluteNode::~AbsoluteNode ()
Definition at line 128 of file operators.cpp.
References expression.
{
    if (expression != NOMEM) {
        delete expression;
    }
}
Member Function Documentation
void AbsoluteNode::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 175 of file operators.cpp.
References expression, and SyntaxNode::SetParent().
{
    if (expression == NOMEM) {
        expression = (ExpressionNode*)node;
        node->SetParent(this);
    }
}
void AbsoluteNode::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 183 of file operators.cpp.
References expression.
{
    if (expression == node) {
        expression = NOMEM;
    }
}
Number * AbsoluteNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 154 of file operators.cpp.
References Number::Absolute(), ExpressionNode::Evaluate(), expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->Absolute();
    return result;
}
SyntaxNode * AbsoluteNode::GetNext () [virtual]
Implements SyntaxNode.
Definition at line 165 of file operators.cpp.
References expression, and SyntaxNode::iterator.
{
    if (iterator == NOMEM) {
        iterator = expression;
        return iterator;
    }
    return NOMEM;
}
char * AbsoluteNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 160 of file operators.cpp.
Referenced by GetText().
{
    return (char*)"|";
}
int AbsoluteNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 149 of file operators.cpp.
{
    return 8;
}
char * AbsoluteNode::GetText () [virtual]
Implements ExpressionNode.
Definition at line 135 of file operators.cpp.
References CharBuffer::Append(), CharBuffer::Empty(), CharBuffer::EnsureSize(), expression, GetNodeText(), CharBuffer::GetString(), ExpressionNode::GetText(), SyntaxNode::output, and StrLen().
{
    const char *expText = expression->GetText();
    const char *nodeText = GetNodeText();
    output->Empty();
    output->EnsureSize(StrLen(expText) + StrLen(nodeText) * 2 + 1);
    output->Append(nodeText);
    output->Append(expText);
    output->Append(nodeText);
    return output->GetString();
}
void AbsoluteNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Definition at line 190 of file operators.cpp.
References expression.
{
    if (expression == n) {
        delete expression;
        expression = (ExpressionNode*)x;
    }
}
Member Data Documentation
ExpressionNode* AbsoluteNode::expression [private]
Definition at line 77 of file operators.h.
Referenced by AbsoluteNode(), Attach(), Detach(), Evaluate(), GetNext(), GetText(), Replace(), and ~AbsoluteNode().
Author
Generated automatically by Doxygen for amath from the source code.