lib/real/acosh.c
NAME
lib/real/acosh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double acosh (double x)
Inverse hyperbolic cosine function.
Variables
static const double one = 1.0
static const double ln2 = 6.93147180559945286227e-01
Function Documentation
double acosh (double x)
Inverse hyperbolic cosine function.
Version:
1.3
Date:
95/01/18
Method :
 Based on
    acosh(x) = log [ x + sqrt(x*x-1) ]
 we have
    acosh(x) := log(x)+ln2, if x is large; else
    acosh(x) := log(2x-1/(sqrt(x*x-1)+x)) if x>2; else
    acosh(x) := log1p(t+sqrt(2.0*t+t*t)); where t=x-1.
Special cases:
 acosh(x) is NaN with signal if x<1.
 acosh(NaN) is NaN without signal.
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 75 of file acosh.c.
References ln2, log1p(), one, and sqrt().
Referenced by RealNumber::HypArcCosine(), and RealNumber::HypArcSecant().
{
    double t;
    sword hx, lx;
    GET_HIGH_WORD(hx,x);
    GET_LOW_WORD(lx,x);
    if(hx<0x3ff00000) { /* x < 1 */
        return (x-x)/(x-x);
    } else if(hx >=0x41b00000) { /* x > 2**28 */
        if(hx >=0x7ff00000) { /* x is inf of NaN */
            return x+x;
        } else
            return log(x)+ln2; /* acosh(huge)=log(2x) */
    } else if(((hx-0x3ff00000)|lx)==0) {
        return 0.0; /* acosh(1) = 0 */
    } else if (hx > 0x40000000) { /* 2**28 > x > 2 */
        t=x*x;
        return log(2.0*x-one/(x+sqrt(t-one)));
    } else { /* 1<x<2 */
        t = x-one;
        return log1p(t+sqrt(2.0*t+t*t));
    }
}
Variable Documentation
const double ln2 = 6.93147180559945286227e-01 [static]
Definition at line 49 of file acosh.c.
Referenced by acosh().
const double one = 1.0 [static]
Definition at line 48 of file acosh.c.
Referenced by acosh().
Author
Generated automatically by Doxygen for amath from the source code.