AdditionNode
NAME
AdditionNode -
SYNOPSIS
#include <operators.h>
Inherits NumericOperator.
Public Member Functions
AdditionNode (ExpressionNode *left, ExpressionNode *right)
ReductionType GetReductionType ()
int GetPrecedence ()
Number * Evaluate ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 96 of file operators.h.
Constructor & Destructor Documentation
AdditionNode::AdditionNode (ExpressionNode * left, ExpressionNode * right)
Definition at line 301 of file operators.cpp.
References NumericOperator::NumericOperator().
Referenced by Parser::ParseAddSubstract().
                                                                     :
    NumericOperator(left, right) { }
Member Function Documentation
Number * AdditionNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 314 of file operators.cpp.
References Number::Add(), ExpressionNode::Evaluate(), NumericOperator::left, ExpressionNode::result, and NumericOperator::right.
{
    result = left->Evaluate()->Add(right->Evaluate());
    return result;
}
char * AdditionNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 320 of file operators.cpp.
{
    return (char*)"+";
}
int AdditionNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 309 of file operators.cpp.
{
    return 2;
}
ReductionType AdditionNode::GetReductionType () [virtual]
Reimplemented from SyntaxNode.
Definition at line 304 of file operators.cpp.
References compladdreduc.
{
    return compladdreduc;
}
Author
Generated automatically by Doxygen for amath from the source code.