.TH "app/lib/aengine.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/aengine.h \- ANSI Conole Engine\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAnsiConoleEngine\fP"
.br
.RI "\fIANSI console controller\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
ANSI Conole Engine\&. 


.PP
Definition in file \fBaengine\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
