lib/clib/alloccpy.c
NAME
lib/clib/alloccpy.c -
SYNOPSIS
#include 'mem.h'
#include 'clib.h'
Functions
unsigned int AllocAndCopy (char **destination, const char *source)
Allocate memory and copy a string into the array.
Function Documentation
unsigned int AllocAndCopy (char ** destination, const char * source)
Allocate memory and copy a string into the array.
Definition at line 34 of file alloccpy.c.
Referenced by AnsiConoleEngine::AnsiConoleEngine(), CharBuffer::ClearAndCopy(), ConsoleBase::ConsoleBase(), AnsiConoleEngine::CopyLine(), DeleteStatement::DeleteStatement(), DrawStatement::DrawStatement(), ErrorNode::ErrorNode(), ExecuteStatement::ExecuteStatement(), HelpStatement::HelpStatement(), Lexer::Lexer(), ListStatement::ListStatement(), StandardLanguage::LoadCatalog(), LoadStatement::LoadStatement(), PlotStatement::PlotStatement(), PromptStatement::PromptStatement(), SaveStatement::SaveStatement(), PreferencesBase::SetDefaults(), PreferencesBase::SetPrompt(), ConsoleBase::SetPrompt(), AnsiConoleEngine::SetPrompt(), AnsiConoleEngine::ShowLast(), ShowStatement::ShowStatement(), Token::Token(), UserFunction::UserFunction(), and Variable::Variable().
{
    char *i, *s, *d;
    unsigned int n, size;
    if (source == NOMEM) {
        *destination = NOMEM;
        return 0;
    }
    i = (char*)source;
    s = (char*)source;
    while (*i)
        i++;
    n = i - s + 1;
    size = n;
    *destination = AllocMemSafe(size);
    d = *destination;
    while (n--)
        *d++ = *s++;
    return size;
}
Author
Generated automatically by Doxygen for amath from the source code.