.TH "amathargs" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
amathargs \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <program_amiga\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "long \fBshell\fP"
.br
.ti -1c
.RI "char * \fBinput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file program_amiga\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char* amathargs::input"

.PP
Definition at line 33 of file program_amiga\&.h\&.
.SS "long amathargs::shell"

.PP
Definition at line 32 of file program_amiga\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
