.TH "AmigaLanguage" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AmigaLanguage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <language_amiga\&.h>\fP
.PP
Inherits \fBLanguage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAmigaLanguage\fP ()"
.br
.ti -1c
.RI "\fB~AmigaLanguage\fP ()"
.br
.ti -1c
.RI "char \fBGetFractionPoint\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBCharIsAlNum\fP (unsigned long character)"
.br
.ti -1c
.RI "\fBbool\fP \fBCharIsAlpha\fP (unsigned long character)"
.br
.ti -1c
.RI "\fBbool\fP \fBCharIsDigit\fP (unsigned long character)"
.br
.ti -1c
.RI "\fBbool\fP \fBCharIsPunct\fP (unsigned long character)"
.br
.ti -1c
.RI "\fBbool\fP \fBCharIsSpace\fP (unsigned long character)"
.br
.ti -1c
.RI "\fBbool\fP \fBCharIsCntrl\fP (unsigned long character)"
.br
.ti -1c
.RI "\fBbool\fP \fBStrIsEqualLoc\fP (const char *s1, const char *s2)"
.br
.ti -1c
.RI "\fBbool\fP \fBValidate\fP (char c)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBTranslate\fP (\fBtextdef\fP *def)"
.br
.ti -1c
.RI "char * \fBTranslate\fP (\fBhelptextdef\fP *def)"
.br
.ti -1c
.RI "char * \fBTranslate\fP (\fBidenthelpdef\fP *def)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct Locale * \fBlocale\fP"
.br
.ti -1c
.RI "struct Catalog * \fBhelpcatalog\fP"
.br
.ti -1c
.RI "struct Catalog * \fBidentcatalog\fP"
.br
.ti -1c
.RI "struct Catalog * \fBtextcatalog\fP"
.br
.ti -1c
.RI "struct Catalog * \fBkeywordcatalog\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 36 of file language_amiga\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AmigaLanguage::AmigaLanguage ()"

.SS "AmigaLanguage::~AmigaLanguage ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP AmigaLanguage::CharIsAlNum (unsigned long character)\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "\fBbool\fP AmigaLanguage::CharIsAlpha (unsigned long character)\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "\fBbool\fP AmigaLanguage::CharIsCntrl (unsigned long character)\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "\fBbool\fP AmigaLanguage::CharIsDigit (unsigned long character)\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "\fBbool\fP AmigaLanguage::CharIsPunct (unsigned long character)\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "\fBbool\fP AmigaLanguage::CharIsSpace (unsigned long character)\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "char AmigaLanguage::GetFractionPoint ()\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "\fBbool\fP AmigaLanguage::StrIsEqualLoc (const char * s1, const char * s2)\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "char* AmigaLanguage::Translate (\fBtextdef\fP * def)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "char* AmigaLanguage::Translate (\fBhelptextdef\fP * def)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "char* AmigaLanguage::Translate (\fBidenthelpdef\fP * def)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SS "\fBbool\fP AmigaLanguage::Validate (char c)\fC [virtual]\fP"

.PP
Implements \fBLanguage\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct Catalog* AmigaLanguage::helpcatalog\fC [private]\fP"

.PP
Definition at line 57 of file language_amiga\&.h\&.
.SS "struct Catalog* AmigaLanguage::identcatalog\fC [private]\fP"

.PP
Definition at line 58 of file language_amiga\&.h\&.
.SS "struct Catalog* AmigaLanguage::keywordcatalog\fC [private]\fP"

.PP
Definition at line 60 of file language_amiga\&.h\&.
.SS "struct Locale* AmigaLanguage::locale\fC [private]\fP"

.PP
Definition at line 56 of file language_amiga\&.h\&.
.SS "struct Catalog* AmigaLanguage::textcatalog\fC [private]\fP"

.PP
Definition at line 59 of file language_amiga\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
