.TH "AmigaPreferences" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AmigaPreferences \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <preferences_amiga\&.h>\fP
.PP
Inherits \fBPreferencesBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBbool\fP \fBLoad\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBKeep\fP ()"
.br
.ti -1c
.RI "virtual \fBbool\fP \fBSave\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBSavePrefs\fP (const char *file)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 32 of file preferences_amiga\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBbool\fP AmigaPreferences::Keep ()\fC [virtual]\fP"

.PP
Implements \fBPreferencesBase\fP\&.
.SS "virtual \fBbool\fP AmigaPreferences::Load ()\fC [virtual]\fP"

.PP
Implements \fBPreferencesBase\fP\&.
.SS "virtual \fBbool\fP AmigaPreferences::Save ()\fC [virtual]\fP"

.PP
Implements \fBPreferencesBase\fP\&.
.SS "\fBbool\fP AmigaPreferences::SavePrefs (const char * file)\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
