AnsiConoleEngine
NAME
AnsiConoleEngine - ANSI console controller.
SYNOPSIS
#include <aengine.h>
Public Member Functions
AnsiConoleEngine (const char *prompt, CharValidator *validator)
~AnsiConoleEngine ()
void StartInput ()
bool InputDone ()
const char * GetLine ()
void SetPrompt (const char *string)
const char * ProcessChar (const unsigned char character)
Private Member Functions
void CopyLine ()
void ShowLast ()
void ShowNext ()
Private Attributes
char * prompt
char ** lines
CharBuffer * linebuf
CharValidator * validator
unsigned int len
char * cursor
char * endpos
int curline
int showline
bool lineswap
char * editline
bool escmode
bool csimode
bool delmode
bool linedone
CharBuffer * out
Static Private Attributes
static const int maxLines = 20
static const int lineSize = 1024
Detailed Description
ANSI console controller.
More info on the ANSI console is available at Wikipedia: http://en.wikipedia.org/wiki/ANSI_escape_code
Definition at line 45 of file aengine.h.
Constructor & Destructor Documentation
AnsiConoleEngine::AnsiConoleEngine (const char * prompt, CharValidator * validator)
Definition at line 32 of file aengine.cpp.
References AllocAndCopy(), CharBuffer::CharBuffer(), curline, editline, linebuf, lines, maxLines, out, prompt, and validator.
Referenced by StandardConsole::StandardConsole().
{
    this->validator = validator;
    AllocAndCopy(&this->prompt, prompt);
    linebuf = new CharBuffer();
    out = new CharBuffer();
    lines = new char*[maxLines];
    for (int i = 0; i < maxLines; i++) {
        lines[i] = NOMEM;
    }
    editline = NOMEM;
    curline = -1;
}
AnsiConoleEngine::~AnsiConoleEngine ()
Definition at line 49 of file aengine.cpp.
References linebuf, lines, maxLines, out, and prompt.
{
    for (int i = 0; i < maxLines; i++) {
        if (lines[i] != NOMEM) {
            delete [] lines[i];
        }
    }
    delete [] lines;
    delete linebuf;
    delete out;
    delete prompt;
}
Member Function Documentation
void AnsiConoleEngine::CopyLine () [private]
Definition at line 216 of file aengine.cpp.
References AllocAndCopy(), curline, editline, CharBuffer::GetString(), linebuf, lines, and maxLines.
Referenced by ProcessChar().
{
    curline++;
    if (curline == maxLines) {
        curline--;
        delete [] lines[0];
        for (int i = 0; i < maxLines - 1; i++) {
            lines[i] = lines[i + 1];
        }
    }
    AllocAndCopy(&(lines[curline]), linebuf->GetString());
    if (editline != NOMEM) {
        delete [] editline;
        editline = NOMEM;
    }
}
const char * AnsiConoleEngine::GetLine ()
Definition at line 320 of file aengine.cpp.
References CharBuffer::GetString(), and linebuf.
Referenced by StandardConsole::ReadLine().
{
    return linebuf->GetString();
}
bool AnsiConoleEngine::InputDone ()
Definition at line 315 of file aengine.cpp.
References linedone.
Referenced by StandardConsole::ReadLine().
{
    return linedone;
}
const char * AnsiConoleEngine::ProcessChar (const unsigned char character)
Definition at line 82 of file aengine.cpp.
References CharBuffer::Append(), CharBuffer::buf, CopyLine(), csimode, cursor, delmode, CharBuffer::Empty(), endpos, escmode, CharBuffer::GetString(), len, linebuf, linedone, out, CharBuffer::ptr, ShowLast(), ShowNext(), CharValidator::Validate(), and validator.
Referenced by StandardConsole::ReadLine().
{
    unsigned char ch = character;
    out->Empty();
    /*
    // -------------- DEUG ------------------
    Number *d = new RealNumber((int)ch);
    NumeralSystem *ns = new DecimalSystem(0);
    const char *dtext = ns->GetText(d);
    StrCopy(out->buf, dtext);
    StrConcat(out->buf, SPACE);
    delete ns;
    delete d;
    return out->buf;
    // -------------- DEUG ------------------
    */
    if (len == 0) {
        // TODO: double buffer
    }
    bool processed = false;
    if (ch == 0) {
        processed = true;
    } else if (ch == 27) {
        escmode = true;
        processed = true;
    } else if (ch == 155 || (escmode && ch == 91)) {
        csimode = true;
        processed = true;
    } else if (csimode) {
        switch (ch) {
        case 65: // Arrow up (27 91 65)
            ShowLast();
            break;
        case 66: // Arrow down (27 91 66)
            ShowNext();
            break;
        case 67: // Arrow right (27 91 67)
            if (cursor != endpos) {
                cursor++;
                out->Append(CURSORFORWARD);
            }
            break;
        case 68: // Arrow left (27 91 68)
            if (cursor != linebuf->buf) {
                cursor--;
                out->Append(CURSORBACKWARD);
            }
            break;
        case 51: // DEL 27 91 51 126
            delmode = true;
        default:
            // F1 27 79 80
            // F2 27 79 81
            break;
        }
        escmode = false;
        csimode = false;
        processed = true;
    } else {
        escmode = false;
        csimode = false;
    }
    // Delete one character to the right
    if (delmode && ch == 126) {
        if (cursor != endpos) {
            char *i = cursor;
            do {
                *i = *(i + 1);
                i++;
            } while (i != endpos);
            len++;
            out->Append(DELETE1CHAR);
            endpos--;
            linebuf->ptr = endpos;
        }
        processed = true;
        delmode = false;
    }
    if (processed) {
        return out->GetString();
    }
    if (ch == 13 || ch == 10) {
        out->Append(NEWLINE);
        linebuf->ptr = endpos;
        CopyLine();
        linedone = true;
    } else if (cursor != linebuf->buf && (ch == 8 || ch == 127)) {
        // Deleting in middle of line
        if (cursor != endpos) {
            char *i = cursor - 1;
            do {
                *i = *(i + 1);
                i++;
            } while (i != endpos);
        }
        len++;
        out->Append(CURSORBACKWARD);
        out->Append(DELETE1CHAR);
        cursor--;
        endpos--;
        linebuf->ptr = endpos;
    } else if (validator->Validate(ch)) {
        // Insert in middle of line
        if (cursor != endpos) {
            char *i = endpos;
            do {
                *i = *(i - 1);
                i--;
            } while (i != cursor);
            out->Append(INSERT1CHAR);
        }
        len--;
        out->Append(ch);
        *cursor++ = ch;
        endpos++;
        linebuf->ptr = endpos;
    }
    return out->GetString();
}
void AnsiConoleEngine::SetPrompt (const char * string)
Definition at line 325 of file aengine.cpp.
References AllocAndCopy(), and prompt.
Referenced by StandardConsole::SetPrompt().
{
    delete prompt;
    AllocAndCopy(&prompt, string);
}
void AnsiConoleEngine::ShowLast () [private]
Definition at line 237 of file aengine.cpp.
References AllocAndCopy(), CharBuffer::Append(), CharBuffer::buf, curline, cursor, editline, CharBuffer::Empty(), endpos, CharBuffer::EnsureSize(), CharBuffer::GetString(), len, linebuf, lines, lineSize, lineswap, out, prompt, showline, and StrLen().
Referenced by ProcessChar().
{
    if (curline == -1) {
        return;
    }
    if (!lineswap) {
        AllocAndCopy(&editline, linebuf->GetString());
        lineswap = true;
        showline = curline + 1;
    } else if (showline == curline + 1) {
        delete editline;
        AllocAndCopy(&editline, linebuf->GetString());
    }
    showline--;
    if (showline < 0) {
        showline = 0;
    }
    out->Empty();
    out->EnsureSize(
        StrLen(DELETELINE) +
        StrLen(prompt) +
        StrLen(lines[showline]) + 1);
    out->Append(DELETELINE);
    out->Append(prompt);
    out->Append(lines[showline]);
    linebuf->Empty();
    linebuf->EnsureSize(StrLen(lines[showline]));
    linebuf->Append(lines[showline]);
    unsigned int linelen = StrLen(linebuf->GetString());
    cursor = linebuf->buf + linelen;
    endpos = cursor;
    len = lineSize - linelen;
}
void AnsiConoleEngine::ShowNext () [private]
Definition at line 277 of file aengine.cpp.
References CharBuffer::Append(), CharBuffer::buf, curline, cursor, editline, CharBuffer::Empty(), endpos, CharBuffer::EnsureGrowth(), CharBuffer::EnsureSize(), CharBuffer::GetString(), len, linebuf, lines, lineSize, lineswap, out, prompt, showline, and StrLen().
Referenced by ProcessChar().
{
    if (!lineswap) {
        return;
    }
    showline++;
    if (showline > curline + 1) {
        showline = curline + 1;
        return;
    }
    out->Empty();
    out->Append(DELETELINE);
    out->Append(prompt);
    if (showline > curline) {
        out->EnsureGrowth(StrLen(editline) + 1);
        out->Append(editline);
        linebuf->Empty();
        linebuf->EnsureSize(StrLen(editline));
        linebuf->Append(editline);
    } else {
        out->EnsureGrowth(StrLen(lines[showline]) + 1);
        out->Append(lines[showline]);
        linebuf->Empty();
        linebuf->EnsureSize(StrLen(lines[showline]));
        linebuf->Append(lines[showline]);
    }
    unsigned int linelen = StrLen(linebuf->GetString());
    cursor = linebuf->buf + linelen;
    endpos = cursor;
    len = lineSize - linelen;
}
void AnsiConoleEngine::StartInput ()
Definition at line 63 of file aengine.cpp.
References CharBuffer::buf, CharBuffer::ClearAndAlloc(), csimode, cursor, delmode, endpos, escmode, len, linebuf, linedone, lineSize, and lineswap.
Referenced by StandardConsole::ReadLine().
{
    linebuf->ClearAndAlloc(lineSize + 1);
    len = lineSize;
    cursor = linebuf->buf;
    endpos = cursor;
    *endpos = '\0';
    lineswap = false;
    escmode = false;
    csimode = false;
    delmode = false;
    linedone = false;
}
Member Data Documentation
bool AnsiConoleEngine::csimode [private]
Definition at line 78 of file aengine.h.
Referenced by ProcessChar(), and StartInput().
int AnsiConoleEngine::curline [private]
Definition at line 72 of file aengine.h.
Referenced by AnsiConoleEngine(), CopyLine(), ShowLast(), and ShowNext().
char* AnsiConoleEngine::cursor [private]
Definition at line 69 of file aengine.h.
Referenced by ProcessChar(), ShowLast(), ShowNext(), and StartInput().
bool AnsiConoleEngine::delmode [private]
Definition at line 79 of file aengine.h.
Referenced by ProcessChar(), and StartInput().
char* AnsiConoleEngine::editline [private]
Definition at line 75 of file aengine.h.
Referenced by AnsiConoleEngine(), CopyLine(), ShowLast(), and ShowNext().
char* AnsiConoleEngine::endpos [private]
Definition at line 70 of file aengine.h.
Referenced by ProcessChar(), ShowLast(), ShowNext(), and StartInput().
bool AnsiConoleEngine::escmode [private]
Definition at line 77 of file aengine.h.
Referenced by ProcessChar(), and StartInput().
unsigned int AnsiConoleEngine::len [private]
Definition at line 68 of file aengine.h.
Referenced by ProcessChar(), ShowLast(), ShowNext(), and StartInput().
CharBuffer* AnsiConoleEngine::linebuf [private]
Definition at line 66 of file aengine.h.
Referenced by AnsiConoleEngine(), CopyLine(), GetLine(), ProcessChar(), ShowLast(), ShowNext(), StartInput(), and ~AnsiConoleEngine().
bool AnsiConoleEngine::linedone [private]
Definition at line 80 of file aengine.h.
Referenced by InputDone(), ProcessChar(), and StartInput().
char** AnsiConoleEngine::lines [private]
Definition at line 65 of file aengine.h.
Referenced by AnsiConoleEngine(), CopyLine(), ShowLast(), ShowNext(), and ~AnsiConoleEngine().
const int AnsiConoleEngine::lineSize = 1024 [static], [private]
Definition at line 64 of file aengine.h.
Referenced by ShowLast(), ShowNext(), and StartInput().
bool AnsiConoleEngine::lineswap [private]
Definition at line 74 of file aengine.h.
Referenced by ShowLast(), ShowNext(), and StartInput().
const int AnsiConoleEngine::maxLines = 20 [static], [private]
Definition at line 63 of file aengine.h.
Referenced by AnsiConoleEngine(), CopyLine(), and ~AnsiConoleEngine().
CharBuffer* AnsiConoleEngine::out [private]
Definition at line 81 of file aengine.h.
Referenced by AnsiConoleEngine(), ProcessChar(), ShowLast(), ShowNext(), and ~AnsiConoleEngine().
char* AnsiConoleEngine::prompt [private]
Definition at line 61 of file aengine.h.
Referenced by AnsiConoleEngine(), SetPrompt(), ShowLast(), ShowNext(), and ~AnsiConoleEngine().
int AnsiConoleEngine::showline [private]
Definition at line 73 of file aengine.h.
Referenced by ShowLast(), and ShowNext().
CharValidator* AnsiConoleEngine::validator [private]
Definition at line 67 of file aengine.h.
Referenced by AnsiConoleEngine(), and ProcessChar().
Author
Generated automatically by Doxygen for amath from the source code.