ArcCosecantNode
NAME
ArcCosecantNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
ArcCosecantNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 436 of file functions.h.
Constructor & Destructor Documentation
ArcCosecantNode::ArcCosecantNode (ExpressionNode * expression)
Definition at line 919 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                           :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * ArcCosecantNode::Create (ExpressionNode * expression) [static]
Definition at line 922 of file functions.cpp.
References ArcCosecantNode().
{
    return new ArcCosecantNode(expression);
}
Number * ArcCosecantNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 927 of file functions.cpp.
References Number::ArcCosecant(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->ArcCosecant();
    return result;
}
char * ArcCosecantNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 933 of file functions.cpp.
{
    return (char*)"acsc";
}
Author
Generated automatically by Doxygen for amath from the source code.