.TH "ArcCosineNode" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArcCosineNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArcCosineNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 406 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ArcCosineNode::ArcCosineNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 881 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
881                                                        :
882     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * ArcCosineNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 884 of file functions\&.cpp\&.
.PP
References ArcCosineNode()\&.
.PP
.nf
885 {
886     return new ArcCosineNode(expression);
887 }
.fi
.SS "\fBNumber\fP * ArcCosineNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 889 of file functions\&.cpp\&.
.PP
References Number::ArcCosine(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result\&.
.PP
.nf
890 {
891     result = expression->Evaluate()->ArcCosine();
892     return result;
893 }
.fi
.SS "char * ArcCosineNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 895 of file functions\&.cpp\&.
.PP
.nf
896 {
897     return (char*)"acos";
898 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
