.TH "ArcCosecantNode" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArcCosecantNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArcCosecantNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 436 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ArcCosecantNode::ArcCosecantNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 919 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
919                                                            :
920     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * ArcCosecantNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 922 of file functions\&.cpp\&.
.PP
References ArcCosecantNode()\&.
.PP
.nf
923 {
924     return new ArcCosecantNode(expression);
925 }
.fi
.SS "\fBNumber\fP * ArcCosecantNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 927 of file functions\&.cpp\&.
.PP
References Number::ArcCosecant(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result\&.
.PP
.nf
928 {
929     result = expression->Evaluate()->ArcCosecant();
930     return result;
931 }
.fi
.SS "char * ArcCosecantNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 933 of file functions\&.cpp\&.
.PP
.nf
934 {
935     return (char*)"acsc";
936 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
