ArcCotangentNode
NAME
ArcCotangentNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
ArcCotangentNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 426 of file functions.h.
Constructor & Destructor Documentation
ArcCotangentNode::ArcCotangentNode (ExpressionNode * expression)
Definition at line 957 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                             :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * ArcCotangentNode::Create (ExpressionNode * expression) [static]
Definition at line 961 of file functions.cpp.
References ArcCotangentNode().
{
    return new ArcCotangentNode(expression);
}
Number * ArcCotangentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 966 of file functions.cpp.
References Number::ArcCotangent(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->ArcCotangent();
    return result;
}
char * ArcCotangentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 972 of file functions.cpp.
{
    return (char*)"acot";
}
Author
Generated automatically by Doxygen for amath from the source code.