ArcCosineNode
NAME
ArcCosineNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
ArcCosineNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 406 of file functions.h.
Constructor & Destructor Documentation
ArcCosineNode::ArcCosineNode (ExpressionNode * expression)
Definition at line 881 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                       :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * ArcCosineNode::Create (ExpressionNode * expression) [static]
Definition at line 884 of file functions.cpp.
References ArcCosineNode().
{
    return new ArcCosineNode(expression);
}
Number * ArcCosineNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 889 of file functions.cpp.
References Number::ArcCosine(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->ArcCosine();
    return result;
}
char * ArcCosineNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 895 of file functions.cpp.
{
    return (char*)"acos";
}
Author
Generated automatically by Doxygen for amath from the source code.