.TH "ArcSecantNode" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArcSecantNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArcSecantNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 446 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ArcSecantNode::ArcSecantNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 938 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
938                                                        :
939     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * ArcSecantNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 941 of file functions\&.cpp\&.
.PP
References ArcSecantNode()\&.
.PP
.nf
942 {
943     return new ArcSecantNode(expression);
944 }
.fi
.SS "\fBNumber\fP * ArcSecantNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 946 of file functions\&.cpp\&.
.PP
References Number::ArcSecant(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result\&.
.PP
.nf
947 {
948     result = expression->Evaluate()->ArcSecant();
949     return result;
950 }
.fi
.SS "char * ArcSecantNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 952 of file functions\&.cpp\&.
.PP
.nf
953 {
954     return (char*)"asec";
955 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
