ArcSineNode
NAME
ArcSineNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
ArcSineNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 396 of file functions.h.
Constructor & Destructor Documentation
ArcSineNode::ArcSineNode (ExpressionNode * expression)
Definition at line 862 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                   :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * ArcSineNode::Create (ExpressionNode * expression) [static]
Definition at line 865 of file functions.cpp.
References ArcSineNode().
{
    return new ArcSineNode(expression);
}
Number * ArcSineNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 870 of file functions.cpp.
References Number::ArcSine(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->ArcSine();
    return result;
}
char * ArcSineNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 876 of file functions.cpp.
{
    return (char*)"asin";
}
Author
Generated automatically by Doxygen for amath from the source code.