ArcSecantNode
NAME
ArcSecantNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
ArcSecantNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 446 of file functions.h.
Constructor & Destructor Documentation
ArcSecantNode::ArcSecantNode (ExpressionNode * expression)
Definition at line 938 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                       :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * ArcSecantNode::Create (ExpressionNode * expression) [static]
Definition at line 941 of file functions.cpp.
References ArcSecantNode().
{
    return new ArcSecantNode(expression);
}
Number * ArcSecantNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 946 of file functions.cpp.
References Number::ArcSecant(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->ArcSecant();
    return result;
}
char * ArcSecantNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 952 of file functions.cpp.
{
    return (char*)"asec";
}
Author
Generated automatically by Doxygen for amath from the source code.