.TH "ArcTangentNode" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ArcTangentNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBArcTangentNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 416 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ArcTangentNode::ArcTangentNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 900 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
900                                                          :
901     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * ArcTangentNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 903 of file functions\&.cpp\&.
.PP
References ArcTangentNode()\&.
.PP
.nf
904 {
905     return new ArcTangentNode(expression);
906 }
.fi
.SS "\fBNumber\fP * ArcTangentNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 908 of file functions\&.cpp\&.
.PP
References Number::ArcTangent(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result\&.
.PP
.nf
909 {
910     result = expression->Evaluate()->ArcTangent();
911     return result;
912 }
.fi
.SS "char * ArcTangentNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 914 of file functions\&.cpp\&.
.PP
.nf
915 {
916     return (char*)"atan";
917 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
