ArcTangentNode
NAME
ArcTangentNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
ArcTangentNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 416 of file functions.h.
Constructor & Destructor Documentation
ArcTangentNode::ArcTangentNode (ExpressionNode * expression)
Definition at line 900 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                         :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * ArcTangentNode::Create (ExpressionNode * expression) [static]
Definition at line 903 of file functions.cpp.
References ArcTangentNode().
{
    return new ArcTangentNode(expression);
}
Number * ArcTangentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 908 of file functions.cpp.
References Number::ArcTangent(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->ArcTangent();
    return result;
}
char * ArcTangentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 914 of file functions.cpp.
{
    return (char*)"atan";
}
Author
Generated automatically by Doxygen for amath from the source code.