lib/real/asinh.c
NAME
lib/real/asinh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double asinh (double x)
Inverse hyperbolic sine function.
Variables
static const double one = 1.00000000000000000000e+00
static const double ln2 = 6.93147180559945286227e-01
static const double huge = 1.00000000000000000000e+300
Function Documentation
double asinh (double x)
Inverse hyperbolic sine function.
Version:
1.3
Date:
95/01/18
Method :
 Based on
    asinh(x) = sign(x) * log [ |x| + sqrt(x*x+1) ]
 we have
 asinh(x) := x if 1+x*x=1,
     := sign(x)*(log(x)+ln2)) for large |x|, else
     := sign(x)*log(2|x|+1/(|x|+sqrt(x*x+1))) if|x|>2, else
     := sign(x)*log1p(|x| + x^2/(1 + sqrt(1+x^2)))
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 73 of file asinh.c.
References huge, ln2, log1p(), one, and sqrt().
Referenced by RealNumber::HypArcCosecant(), and RealNumber::HypArcSine().
{
    double t,w;
    sword hx,ix;
    GET_HIGH_WORD(hx,x);
    ix = hx&0x7fffffff;
    if(ix>=0x7ff00000) return x+x; /* x is inf or NaN */
    if(ix< 0x3e300000) { /* |x|<2**-28 */
        if(huge+x>one) return x; /* return x inexact except 0 */
    }
    if(ix>0x41b00000) { /* |x| > 2**28 */
        w = log(fabs(x))+ln2;
    } else if (ix>0x40000000) { /* 2**28 > |x| > 2.0 */
        t = fabs(x);
        w = log(2.0*t+one/(sqrt(x*x+one)+t));
    } else { /* 2.0 > |x| > 2**-28 */
        t = x*x;
        w =log1p(fabs(x)+t/(one+sqrt(one+t)));
    }
    if(hx>0) return w;
    else return -w;
}
Variable Documentation
const double huge = 1.00000000000000000000e+300 [static]
Definition at line 50 of file asinh.c.
Referenced by asinh().
const double ln2 = 6.93147180559945286227e-01 [static]
Definition at line 49 of file asinh.c.
Referenced by asinh().
const double one = 1.00000000000000000000e+00 [static]
Definition at line 48 of file asinh.c.
Referenced by asinh().
Author
Generated automatically by Doxygen for amath from the source code.