.TH "lib/real/asin.c" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/real/asin.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBasin\fP (double x)"
.br
.RI "\fIInverse trigonometric sine function\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const double \fBone\fP = 1\&.00000000000000000000e+00"
.br
.ti -1c
.RI "static const double \fBhuge\fP = 1\&.000e+300"
.br
.ti -1c
.RI "static const double \fBpio2_hi\fP = 1\&.57079632679489655800e+00"
.br
.ti -1c
.RI "static const double \fBpio2_lo\fP = 6\&.12323399573676603587e\-17"
.br
.ti -1c
.RI "static const double \fBpio4_hi\fP = 7\&.85398163397448278999e\-01"
.br
.ti -1c
.RI "static const double \fBpS0\fP = 1\&.66666666666666657415e\-01"
.br
.ti -1c
.RI "static const double \fBpS1\fP = \-3\&.25565818622400915405e\-01"
.br
.ti -1c
.RI "static const double \fBpS2\fP = 2\&.01212532134862925881e\-01"
.br
.ti -1c
.RI "static const double \fBpS3\fP = \-4\&.00555345006794114027e\-02"
.br
.ti -1c
.RI "static const double \fBpS4\fP = 7\&.91534994289814532176e\-04"
.br
.ti -1c
.RI "static const double \fBpS5\fP = 3\&.47933107596021167570e\-05"
.br
.ti -1c
.RI "static const double \fBqS1\fP = \-2\&.40339491173441421878e+00"
.br
.ti -1c
.RI "static const double \fBqS2\fP = 2\&.02094576023350569471e+00"
.br
.ti -1c
.RI "static const double \fBqS3\fP = \-6\&.88283971605453293030e\-01"
.br
.ti -1c
.RI "static const double \fBqS4\fP = 7\&.70381505559019352791e\-02"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double asin (double x)"

.PP
Inverse trigonometric sine function\&. 
.PP
\fBVersion:\fP
.RS 4
1\&.3 
.RE
.PP
\fBDate:\fP
.RS 4
95/01/18
.RE
.PP
.PP
.nf

Method :
 Since  asin(x) = x + x^3/6 + x^5*3/40 + x^7*15/336 + \&.\&.\&.
 we approximate asin(x) on [0,0\&.5] by
    asin(x) = x + x*x^2*R(x^2)
 where
    R(x^2) is a rational approximation of (asin(x)-x)/x^3
 and its remez error is bounded by
    |(asin(x)-x)/x^3 - R(x^2)| < 2^(-58\&.75)
.fi
.PP
.PP
.PP
.nf
 For x in [0\&.5,1]
    asin(x) = pi/2-2*asin(sqrt((1-x)/2))
 Let y = (1-x), z = y/2, s := sqrt(z), and pio2_hi+pio2_lo=pi/2;
 then for x>0\&.98
    asin(x) = pi/2 - 2*(s+s*z*R(z))
        = pio2_hi - (2*(s+s*z*R(z)) - pio2_lo)
 For x<=0\&.98, let pio4_hi = pio2_hi/2, then
    f = hi part of s;
    c = sqrt(z) - f = (z-f*f)/(s+f)     \&.\&.\&.f+c=sqrt(z)
 and
    asin(x) = pi/2 - 2*(s+s*z*R(z))
        = pio4_hi+(pio4-2s)-(2s*z*R(z)-pio2_lo)
        = pio4_hi+(pio4-2f)-(2s*z*R(z)-(pio2_lo+2c))
.fi
.PP
.PP
.PP
.nf
Special cases:
 if x is NaN, return x itself;
 if |x|>1, return NaN with invalid signal\&.
.fi
.PP
.PP
.PP
.nf
.fi
.PP
 
.PP
\fBCopyright:\fP
.RS 4
Copyright (C) 1993 by Sun Microsystems, Inc\&. All rights reserved\&.  Developed at SunSoft, a Sun Microsystems, Inc\&. business\&. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved\&. 
.RE
.PP

.PP
Definition at line 104 of file asin\&.c\&.
.PP
References huge, one, pio2_hi, pio2_lo, pio4_hi, pS0, pS1, pS2, pS3, pS4, pS5, qS1, qS2, qS3, qS4, and sqrt()\&.
.PP
Referenced by RealNumber::ArcCosecant(), and RealNumber::ArcSine()\&.
.PP
.nf
105 {
106     double t,w,p,q,c,r,s;
107     sword hx,ix;
108     GET_HIGH_WORD(hx,x);
109     ix = hx&0x7fffffff;
110     if(ix>= 0x3ff00000) {       /* |x|>= 1 */
111         uword lx;
112         GET_LOW_WORD(lx,x);
113         if(((ix-0x3ff00000)|lx)==0)
114             /* asin(1)=+-pi/2 with inexact */
115             return x*pio2_hi+x*pio2_lo;
116         return (x-x)/(x-x);     /* asin(|x|>1) is NaN */
117     } else if (ix<0x3fe00000) { /* |x|<0\&.5 */
118         if(ix<0x3e400000) {     /* if |x| < 2**-27 */
119             if(huge+x>one) {
120                 return x;/* return x with inexact if x!=0*/
121             } else {
122                 t = 0;
123             }
124         } else {
125             t = x*x;
126         }
127 
128         p = t*(pS0+t*(pS1+t*(pS2+t*(pS3+t*(pS4+t*pS5)))));
129         q = one+t*(qS1+t*(qS2+t*(qS3+t*qS4)));
130         w = p/q;
131         return x+x*w;
132     }
133     /* 1> |x|>= 0\&.5 */
134     w = one-fabs(x);
135     t = w*0\&.5;
136     p = t*(pS0+t*(pS1+t*(pS2+t*(pS3+t*(pS4+t*pS5)))));
137     q = one+t*(qS1+t*(qS2+t*(qS3+t*qS4)));
138     s = sqrt(t);
139     if(ix>=0x3FEF3333) {    /* if |x| > 0\&.975 */
140         w = p/q;
141         t = pio2_hi-(2\&.0*(s+s*w)-pio2_lo);
142     } else {
143         w  = s;
144         SET_LOW_WORD(w,0);
145         c  = (t-w*w)/(s+w);
146         r  = p/q;
147         p  = 2\&.0*s*r-(pio2_lo-2\&.0*c);
148         q  = pio4_hi-2\&.0*w;
149         t  = pio4_hi-(p-q);
150     }
151     if(hx>0) return t;
152     else return -t;
153 }
.fi
.SH "Variable Documentation"
.PP 
.SS "const double huge = 1\&.000e+300\fC [static]\fP"

.PP
Definition at line 49 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double one = 1\&.00000000000000000000e+00\fC [static]\fP"

.PP
Definition at line 48 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pio2_hi = 1\&.57079632679489655800e+00\fC [static]\fP"

.PP
Definition at line 50 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pio2_lo = 6\&.12323399573676603587e\-17\fC [static]\fP"

.PP
Definition at line 51 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pio4_hi = 7\&.85398163397448278999e\-01\fC [static]\fP"

.PP
Definition at line 52 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pS0 = 1\&.66666666666666657415e\-01\fC [static]\fP"

.PP
Definition at line 54 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pS1 = \-3\&.25565818622400915405e\-01\fC [static]\fP"

.PP
Definition at line 55 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pS2 = 2\&.01212532134862925881e\-01\fC [static]\fP"

.PP
Definition at line 56 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pS3 = \-4\&.00555345006794114027e\-02\fC [static]\fP"

.PP
Definition at line 57 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pS4 = 7\&.91534994289814532176e\-04\fC [static]\fP"

.PP
Definition at line 58 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double pS5 = 3\&.47933107596021167570e\-05\fC [static]\fP"

.PP
Definition at line 59 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double qS1 = \-2\&.40339491173441421878e+00\fC [static]\fP"

.PP
Definition at line 60 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double qS2 = 2\&.02094576023350569471e+00\fC [static]\fP"

.PP
Definition at line 61 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double qS3 = \-6\&.88283971605453293030e\-01\fC [static]\fP"

.PP
Definition at line 62 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SS "const double qS4 = 7\&.70381505559019352791e\-02\fC [static]\fP"

.PP
Definition at line 63 of file asin\&.c\&.
.PP
Referenced by asin()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
