AssignmentNode
NAME
AssignmentNode -
SYNOPSIS
#include <operators.h>
Inherits NumericOperator.
Public Member Functions
AssignmentNode (VariableNode *variable, ExpressionNode *expression)
int GetPrecedence ()
bool IsSilent ()
Number * Evaluate ()
Protected Member Functions
char * GetNodeText ()
Private Attributes
VariableNode * variable
ExpressionNode * expression
Additional Inherited Members
Detailed Description
Definition at line 148 of file operators.h.
Constructor & Destructor Documentation
AssignmentNode::AssignmentNode (VariableNode * variable, ExpressionNode * expression)
Definition at line 427 of file operators.cpp.
References expression, NumericOperator::NumericOperator(), and variable.
Referenced by Parser::ParseIdent().
                                                                                :
    NumericOperator(variable, expression),
    variable(variable), expression(expression) { }
Member Function Documentation
Number * AssignmentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 436 of file operators.cpp.
References VariableNode::AssignValue(), ExpressionNode::Evaluate(), VariableNode::Evaluate(), expression, and variable.
{
    // NOTICE: Assignment does not generate a value itself.
    variable->AssignValue(expression->Evaluate());
    return variable->Evaluate();
}
char * AssignmentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 448 of file operators.cpp.
{
    return (char*)"=";
}
int AssignmentNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 431 of file operators.cpp.
{
    return 6;
}
bool AssignmentNode::IsSilent () [virtual]
Reimplemented from ExpressionNode.
Definition at line 443 of file operators.cpp.
{
    return true;
}
Member Data Documentation
ExpressionNode* AssignmentNode::expression [private]
Definition at line 160 of file operators.h.
Referenced by AssignmentNode(), and Evaluate().
VariableNode* AssignmentNode::variable [private]
Definition at line 159 of file operators.h.
Referenced by AssignmentNode(), and Evaluate().
Author
Generated automatically by Doxygen for amath from the source code.