lib/real/atan.c
NAME
lib/real/atan.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double atan (double x)
Inverse trigonometric tangent function.
Variables
static const double atanhi []
static const double atanlo []
static const double aT []
static const double one = 1.0
static const double huge = 1.0e300
Function Documentation
double atan (double x)
Inverse trigonometric tangent function.
Version:
1.3
Date:
95/01/18
Method
  1. Reduce x to positive by atan(x) = -atan(-x).
  2. According to the integer k=4t+0.25 chopped, t=x, the argument
     is further reduced to one of the following intervals and the
     arctangent of t is evaluated by the corresponding formula:
     [0,7/16] atan(x) = t-t^3*(a1+t^2*(a2+...(a10+t^2*a11)...)
     [7/16,11/16] atan(x) = atan(1/2) + atan( (t-0.5)/(1+t/2) )
     [11/16.19/16] atan(x) = atan( 1 ) + atan( (t-1)/(1+t) )
     [19/16,39/16] atan(x) = atan(3/2) + atan( (t-1.5)/(1+1.5t) )
     [39/16,INF] atan(x) = atan(INF) + atan( -1/t )
Constants:
The hexadecimal values are the intended ones for the following
constants. The decimal values may be used, provided that the
compiler will convert from decimal to binary accurately enough
to produce the hexadecimal values shown.
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 109 of file atan.c.
References aT, atanhi, atanlo, huge, and one.
Referenced by RealNumber::ArcCotangent(), RealNumber::ArcTangent(), and atan2().
{
    double w,s1,s2,z;
    sword ix,hx,id;
    GET_HIGH_WORD(hx,x);
    ix = hx&0x7fffffff;
    if(ix>=0x44100000) { /* if |x| >= 2^66 */
        uword low;
        GET_LOW_WORD(low,x);
        if(ix>0x7ff00000||
                (ix==0x7ff00000&&(low!=0)))
            return x+x; /* NaN */
        if(hx>0) return atanhi[3]+atanlo[3];
        else return -atanhi[3]-atanlo[3];
    }
    if (ix < 0x3fdc0000) { /* |x| < 0.4375 */
        if (ix < 0x3e200000) { /* |x| < 2^-29 */
            if(huge+x>one) return x; /* raise inexact */
        }
        id = -1;
    } else {
        x = fabs(x);
        if (ix < 0x3ff30000) { /* |x| < 1.1875 */
            if (ix < 0x3fe60000) { /* 7/16 <=|x|<11/16 */
                id = 0;
                x = (2.0*x-one)/(2.0+x);
            } else { /* 11/16<=|x|< 19/16 */
                id = 1;
                x = (x-one)/(x+one);
            }
        } else {
            if (ix < 0x40038000) { /* |x| < 2.4375 */
                id = 2;
                x = (x-1.5)/(one+1.5*x);
            } else { /* 2.4375 <= |x| < 2^66 */
                id = 3;
                x = -1.0/x;
            }
        }
    }
    /* end of argument reduction */
    z = x*x;
    w = z*z;
    /* break sum from i=0 to 10 aT[i]z**(i+1) into odd and even poly */
    s1 = z*(aT[0]+w*(aT[2]+w*(aT[4]+w*(aT[6]+w*(aT[8]+w*aT[10])))));
    s2 = w*(aT[1]+w*(aT[3]+w*(aT[5]+w*(aT[7]+w*aT[9]))));
    if (id<0) return x - x*(s1+s2);
    else {
        z = atanhi[id] - ((x*(s1+s2) - atanlo[id]) - x);
        return (hx<0)? -z:z;
    }
}
Variable Documentation
const double aT[] [static]
Initial value:
= {
    3.33333333333329318027e-01,
    -1.99999999998764832476e-01,
    1.42857142725034663711e-01,
    -1.11111104054623557880e-01,
    9.09088713343650656196e-02,
    -7.69187620504482999495e-02,
    6.66107313738753120669e-02,
    -5.83357013379057348645e-02,
    4.97687799461593236017e-02,
    -3.65315727442169155270e-02,
    1.62858201153657823623e-02,
}
Definition at line 61 of file atan.c.
Referenced by atan().
const double atanhi[] [static]
Initial value:
= {
    4.63647609000806093515e-01,
    7.85398163397448278999e-01,
    9.82793723247329054082e-01,
    1.57079632679489655800e+00,
}
Definition at line 47 of file atan.c.
Referenced by atan().
const double atanlo[] [static]
Initial value:
= {
    2.26987774529616870924e-17,
    3.06161699786838301793e-17,
    1.39033110312309984516e-17,
    6.12323399573676603587e-17,
}
Definition at line 54 of file atan.c.
Referenced by atan().
const double huge = 1.0e300 [static]
Definition at line 77 of file atan.c.
Referenced by atan().
const double one = 1.0 [static]
Definition at line 76 of file atan.c.
Referenced by atan().
Author
Generated automatically by Doxygen for amath from the source code.