lib/real/atanh.c
NAME
lib/real/atanh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double atanh (double x)
Inverse hyperbolic tangent function.
Variables
static const double one = 1.0
static const double huge = 1e300
static double zero = 0.0
Function Documentation
double atanh (double x)
Inverse hyperbolic tangent function.
Version:
1.3
Date:
95/01/18
Method :
   1.Reduced x to positive by atanh(-x) = -atanh(x)
   2.For x>=0.5
                 1 2x x
 atanh(x) = --- * log(1 + -------) = 0.5 * log1p(2 * --------)
                 2 1 - x 1 - x
    For x<0.5
 atanh(x) = 0.5*log1p(2x+2x*x/(1-x))
Special cases:
 atanh(x) is NaN if |x| > 1 with signal;
 atanh(NaN) is that NaN with no signal;
 atanh(+-1) is +-INF with signal.
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 81 of file atanh.c.
References huge, log1p(), one, and zero.
Referenced by RealNumber::HypArcCotangent(), and RealNumber::HypArcTangent().
{
    double t;
    sword hx,ix;
    uword lx;
    GET_HIGH_WORD(hx,x);
    GET_LOW_WORD(lx,x);
    ix = hx&0x7fffffff;
    if ((ix|((lx|(-lx))>>31))>0x3ff00000) /* |x|>1 */
        return (x-x)/(x-x);
    if(ix==0x3ff00000)
        return x/zero;
    if(ix<0x3e300000&&(huge+x)>zero) return x; /* x<2**-28 */
    SET_HIGH_WORD(x, ix); /* x <- |x| */
    if(ix<0x3fe00000) { /* x < 0.5 */
        t = x+x;
        t = 0.5*log1p(t+t*x/(one-x));
    } else
        t = 0.5*log1p((x+x)/(one-x));
    if(hx>=0) return t;
    else return -t;
}
Variable Documentation
const double huge = 1e300 [static]
Definition at line 51 of file atanh.c.
Referenced by atanh().
const double one = 1.0 [static]
Definition at line 51 of file atanh.c.
Referenced by atanh().
double zero = 0.0 [static]
Definition at line 52 of file atanh.c.
Referenced by atanh().
Author
Generated automatically by Doxygen for amath from the source code.