lib/real/atan2.c
NAME
lib/real/atan2.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double atan2 (double y, double x)
Variables
static const double tiny = 1.0e-300
static const double zero = 0.0
static const double pi_o_4 = 7.8539816339744827900E-01
static const double pi_o_2 = 1.5707963267948965580E+00
static const double pi = 3.1415926535897931160E+00
static const double pi_lo = 1.2246467991473531772E-16
Function Documentation
double atan2 (double y, double x)
Definition at line 86 of file atan2.c.
References atan(), pi, pi_lo, pi_o_2, pi_o_4, tiny, and zero.
Referenced by clog(), and cpow().
{
    double z;
    sword k,m,hx,hy,ix,iy;
    uword lx,ly;
    EXTRACT_WORDS(hx,lx,x);
    ix = hx&0x7fffffff;
    EXTRACT_WORDS(hy,ly,y);
    iy = hy&0x7fffffff;
    if(((ix|((lx|-lx)>>31))>0x7ff00000)||
            ((iy|((ly|-ly)>>31))>0x7ff00000)) /* x or y is NaN */
        return x+y;
    if(((hx-0x3ff00000)|lx)==0) return atan(y); /* x=1.0 */
    m = ((hy>>31)&1)|((hx>>30)&2); /* 2*sign(x)+sign(y) */
    /* when y = 0 */
    if((iy|ly)==0) {
        switch(m) {
        case 0:
        case 1:
            return y; /* atan(+-0,+anything)=+-0 */
        case 2:
            return pi+tiny;/* atan(+0,-anything) = pi */
        case 3:
            return -pi-tiny;/* atan(-0,-anything) =-pi */
        }
    }
    /* when x = 0 */
    if((ix|lx)==0) return (hy<0)? -pi_o_2-tiny: pi_o_2+tiny;
    /* when x is INF */
    if(ix==0x7ff00000) {
        if(iy==0x7ff00000) {
            switch(m) {
            case 0:
                return pi_o_4+tiny;/* atan(+INF,+INF) */
            case 1:
                return -pi_o_4-tiny;/* atan(-INF,+INF) */
            case 2:
                return 3.0*pi_o_4+tiny;/*atan(+INF,-INF)*/
            case 3:
                return -3.0*pi_o_4-tiny;/*atan(-INF,-INF)*/
            }
        } else {
            switch(m) {
            case 0:
                return zero ; /* atan(+...,+INF) */
            case 1:
                return -zero ; /* atan(-...,+INF) */
            case 2:
                return pi+tiny ; /* atan(+...,-INF) */
            case 3:
                return -pi-tiny ; /* atan(-...,-INF) */
            }
        }
    }
    /* when y is INF */
    if(iy==0x7ff00000) return (hy<0)? -pi_o_2-tiny: pi_o_2+tiny;
    /* compute y/x */
    k = (iy-ix)>>20;
    if(k > 60) z=pi_o_2+0.5*pi_lo; /* |y/x| > 2**60 */
    else if(hx<0&&k<-60) z=0.0; /* |y|/x < -2**60 */
    else z=atan(fabs(y/x)); /* safe to do y/x */
    switch (m) {
    case 0:
        return z ; /* atan(+,+) */
    case 1: {
        uword zh;
        GET_HIGH_WORD(zh,z);
        SET_HIGH_WORD(z, zh ^ 0x80000000);
    }
    return z ; /* atan(-,+) */
    case 2:
        return pi-(z-pi_lo);/* atan(+,-) */
    default: /* case 3 */
        return (z-pi_lo)-pi;/* atan(-,-) */
    }
}
Variable Documentation
const double pi = 3.1415926535897931160E+00 [static]
Definition at line 83 of file atan2.c.
Referenced by atan2().
const double pi_lo = 1.2246467991473531772E-16 [static]
Definition at line 84 of file atan2.c.
Referenced by atan2().
const double pi_o_2 = 1.5707963267948965580E+00 [static]
Definition at line 82 of file atan2.c.
Referenced by atan2().
const double pi_o_4 = 7.8539816339744827900E-01 [static]
Definition at line 81 of file atan2.c.
Referenced by atan2().
const double tiny = 1.0e-300 [static]
Definition at line 79 of file atan2.c.
Referenced by atan2().
const double zero = 0.0 [static]
Definition at line 80 of file atan2.c.
Referenced by atan2().
Author
Generated automatically by Doxygen for amath from the source code.