BinaryLogNode
NAME
BinaryLogNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
BinaryLogNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 318 of file functions.h.
Constructor & Destructor Documentation
BinaryLogNode::BinaryLogNode (ExpressionNode * expression)
Definition at line 675 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                       :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * BinaryLogNode::Create (ExpressionNode * expression) [static]
Definition at line 678 of file functions.cpp.
References BinaryLogNode().
{
    return new BinaryLogNode(expression);
}
Number * BinaryLogNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 683 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::Log2(), and ExpressionNode::result.
{
    result = expression->Evaluate()->Log2();
    return result;
}
char * BinaryLogNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 689 of file functions.cpp.
{
    return (char*)"lb";
}
Author
Generated automatically by Doxygen for amath from the source code.