lib/cplex/cacoth.c
NAME
lib/cplex/cacoth.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex cacoth (complex z)
Inverse hyperbolic cotangent of complex number.
Function Documentation
complex cacoth (complex z)
Inverse hyperbolic cotangent of complex number.
Version:
1.0
Date:
14/09/15
Inverse hyperbolic cotangent expressed using complex logarithms:
acoth(z) = 1/2 * ((log(z + 1) - log(z - 1))
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_hyperbolic_function#Logarithmic_representation
Definition at line 43 of file cacoth.c.
References cadd(), clog(), cmul(), cpack(), and csub().
Referenced by ComplexNumber::HypArcCotangent().
{
    complex half = cpack(0.5, 0.0);
    complex one = cpack(1.0, 0.0);
    complex a = clog(cadd(z, one));
    complex b = clog(csub(z, one));
    complex c = csub(a, b);
    complex w = cmul(half, c);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.