lib/cplex/cacot.c
NAME
lib/cplex/cacot.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex cacot (complex z)
Inverse cotangent of complex number.
Function Documentation
complex cacot (complex z)
Inverse cotangent of complex number.
Version:
1.1
Date:
14/10/01
Inverse cotangent expressed using complex logarithms:
arccot z = i/2 * (log(1 - i/z) - log(1 + i/z))
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Logarithmic_forms
Definition at line 43 of file cacot.c.
References cadd(), cdiv(), clog(), cmul(), cpack(), and csub().
Referenced by ComplexNumber::ArcCotangent().
{
    complex one = cpack(1.0, 0.0);
    complex two = cpack(2.0, 0.0);
    complex i = cpack(0.0, 1.0);
    complex iz = cdiv(i, z);
    complex p = clog(csub(one, iz));
    complex q = clog(cadd(one, iz));
    complex w = cmul(cdiv(i, two), csub(p, q));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.