lib/cplex/cacos.c
NAME
lib/cplex/cacos.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex cacos (complex z)
Inverse cosine of complex number.
Function Documentation
complex cacos (complex z)
Inverse cosine of complex number.
Version:
1.0
Date:
14/09/15
Inverse cosine expressed using complex logarithms:
arccos z = -i * log(z + i * sqrt(1 - z * z))
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Logarithmic_forms
Definition at line 43 of file cacos.c.
References cadd(), clog(), cmul(), cpack(), csqrt(), and csub().
Referenced by ComplexNumber::ArcCosine().
{
    complex a = cpack(1.0, 0.0);
    complex i = cpack(0.0, 1.0);
    complex j = cpack(0.0, -1.0);
    complex p = csub(a, cmul(z, z));
    complex q = clog(cadd(z, cmul(i, csqrt(p))));
    complex w = cmul(j, q);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.