lib/cplex/cacosh.c
NAME
lib/cplex/cacosh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex cacosh (complex z)
Inverse hyperbolic cosine of complex number.
Function Documentation
complex cacosh (complex z)
Inverse hyperbolic cosine of complex number.
Version:
1.1
Date:
15/03/03
Inverse hyperbolic cosine expressed using complex logarithms:
acosh(z) = log(z + sqrt(z*z - 1))
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_hyperbolic_function#Logarithmic_representation
Definition at line 43 of file cacosh.c.
References cadd(), clog(), cmul(), cpack(), csqrt(), and csub().
Referenced by ComplexNumber::HypArcCosine().
{
    complex one = cpack(1.0, 0.0);
    complex a = csub(cmul(z, z) , one);
    complex b = cadd(z, csqrt(a));
    complex w = clog(b);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.