lib/cplex/cacsc.c
NAME
lib/cplex/cacsc.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex cacsc (complex z)
Inverse cosecant of complex number.
Function Documentation
complex cacsc (complex z)
Inverse cosecant of complex number.
Version:
1.1
Date:
14/10/01
Inverse cosecant expressed using complex logarithms:
arccsc z = -i * log(sqr(1 - 1/(z*z)) + i/z)
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Logarithmic_forms
Definition at line 43 of file cacsc.c.
References cadd(), cdiv(), clog(), cmul(), cpack(), csqrt(), and csub().
Referenced by ComplexNumber::ArcCosecant().
{
    complex one = cpack(1.0, 0.0);
    complex i = cpack(0.0, 1.0);
    complex j = cpack(0.0, -1.0);
    complex iz = cdiv(i, z);
    complex z2 = cmul(z, z);
    complex p = cdiv(one, z2);
    complex q = csqrt(csub(one, p));
    complex w = cmul(j, clog(cadd(q, iz)));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.