lib/cplex/cacsch.c
NAME
lib/cplex/cacsch.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex cacsch (complex z)
Inverse hyperbolic cosecant of complex number.
Function Documentation
complex cacsch (complex z)
Inverse hyperbolic cosecant of complex number.
Version:
1.0
Date:
14/09/15
Inverse hyperbolic cosecant expressed using complex logarithms:
acsch(z) = log(sqrt(1 + 1 / (z * z)) + 1/z)
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_hyperbolic_function#Logarithmic_representation
Definition at line 43 of file cacsch.c.
References cadd(), clog(), cmul(), cpack(), creci(), and csqrt().
Referenced by ComplexNumber::HypArcCosecant().
{
    complex one = cpack(1.0, 0.0);
    complex a = creci(cmul(z, z));
    complex b = csqrt(cadd(one, a));
    complex c = cadd(b, creci(z));
    complex w = clog(c);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.