lib/cplex/casec.c
NAME
lib/cplex/casec.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex casec (complex z)
Inverse secant expressed using complex logarithms:
Function Documentation
complex casec (complex z)
Inverse secant expressed using complex logarithms:
Version:
1.1
Date:
14/10/01
Inverse secant expressed using complex logarithms:
arcsec z = -i * log(i * sqr(1 - 1/(z*z)) + 1/z)
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Logarithmic_forms
Definition at line 43 of file casec.c.
References cadd(), cdiv(), clog(), cmul(), cpack(), creci(), csqrt(), and csub().
Referenced by ComplexNumber::ArcSecant().
{
    complex one = cpack(1.0, 0.0);
    complex i = cpack(0.0, 1.0);
    complex j = cpack(0.0, -1.0);
    complex rz = creci(z);
    complex z2 = cmul(z, z);
    complex p = cdiv(one, z2);
    complex q = csqrt(csub(one, p));
    complex w = cmul(j, clog(cadd(cmul(i, q), rz)));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.