lib/cplex/casech.c
NAME
lib/cplex/casech.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex casech (complex z)
Inverse hyperbolic secant of complex numbers.
Function Documentation
complex casech (complex z)
Inverse hyperbolic secant of complex numbers.
Version:
1.1
Date:
15/03/03
Inverse hyperbolic secant expressed using complex logarithms:
asech(z) = log(sqrt(1 / (z * z) - 1) + 1/z)
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_hyperbolic_function#Logarithmic_representation
Definition at line 44 of file casech.c.
References cadd(), clog(), cmul(), cpack(), creci(), csqrt(), and csub().
Referenced by ComplexNumber::HypArcSecant().
{
    complex one = cpack(1.0, 0.0);
    complex a = creci(cmul(z, z));
    complex b = csqrt(csub(a, one));
    complex c = cadd(b, creci(z));
    complex w = clog(c);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.