lib/cplex/casin.c
NAME
lib/cplex/casin.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex casin (complex z)
Inverse sine of complex number.
Function Documentation
complex casin (complex z)
Inverse sine of complex number.
Version:
1.1
Date:
14/10/01
Inverse sine expressed using complex logarithms:
arcsin z = -i * log(iz + sqrt(1 - z*z))
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Logarithmic_forms
Definition at line 43 of file casin.c.
References cadd(), clog(), cmul(), cpack(), csqrt(), and csub().
Referenced by ComplexNumber::ArcSine().
{
    complex one = cpack(1.0, 0.0);
    complex i = cpack(0.0, 1.0);
    complex j = cpack(0.0, -1.0);
    complex iz = cmul(i, z);
    complex z2 = cmul(z, z);
    complex p = csqrt(csub(one, z2));
    complex q = clog(cadd(iz, p));
    complex w = cmul(j, q);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.