.TH "lib/cplex/casin.c" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/casin.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBcasin\fP (\fBcomplex\fP z)"
.br
.RI "\fIInverse sine of complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP casin (\fBcomplex\fP z)"

.PP
Inverse sine of complex number\&. 
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
14/10/01
.RE
.PP
Inverse sine expressed using complex logarithms: 
.PP
.nf

arcsin z = -i * log(iz + sqrt(1 - z*z))
.fi
.PP
 More info is available at Wikipedia: 
.br
 http://en.wikipedia.org/wiki/Inverse_trigonometric_functions#Logarithmic_forms 
.PP
Definition at line 43 of file casin\&.c\&.
.PP
References cadd(), clog(), cmul(), cpack(), csqrt(), and csub()\&.
.PP
Referenced by ComplexNumber::ArcSine()\&.
.PP
.nf
44 {
45     complex one = cpack(1\&.0, 0\&.0);
46     complex i = cpack(0\&.0, 1\&.0);
47     complex j = cpack(0\&.0, -1\&.0);
48     complex iz = cmul(i, z);
49     complex z2 = cmul(z, z);
50     complex p = csqrt(csub(one, z2));
51     complex q = clog(cadd(iz, p));
52     complex w = cmul(j, q);
53     return w;
54 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
