lib/cplex/casinh.c
NAME
lib/cplex/casinh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex casinh (complex z)
Inverse hyperbolic sine of complex number.
Function Documentation
complex casinh (complex z)
Inverse hyperbolic sine of complex number.
Version:
1.0
Date:
14/09/15
Inverse hyperbolic sine expressed using complex logarithms:
asinh(z) = log(z + sqrt(z*z + 1))
With branch cuts: -i INF to -i and i to i INF
Domain: -INF to INF
Range: -INF to INF
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_hyperbolic_function#Logarithmic_representation
Definition at line 48 of file casinh.c.
References cadd(), clog(), cmul(), cpack(), and csqrt().
Referenced by ComplexNumber::HypArcSine().
{
    complex one = cpack(1.0, 0.0);
    complex a = cadd(cmul(z, z), one);
    complex b = cadd(z, csqrt(a));
    complex w = clog(b);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.