.TH "lib/cplex/catanh.c" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/catanh.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBcatanh\fP (\fBcomplex\fP z)"
.br
.RI "\fIInverse hyperbolic tangent of complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP catanh (\fBcomplex\fP z)"

.PP
Inverse hyperbolic tangent of complex number\&. 
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP
\fBDate:\fP
.RS 4
14/09/15
.RE
.PP
Inverse hyperbolic tangent expressed using complex logarithms: 
.PP
.nf

atanh(z) = 1/2 * ((log(1 + z) - log(1 - z))
.fi
.PP
 More info is available at Wikipedia: 
.br
 http://en.wikipedia.org/wiki/Inverse_hyperbolic_function#Logarithmic_representation 
.PP
Definition at line 43 of file catanh\&.c\&.
.PP
References cadd(), clog(), cmul(), cpack(), and csub()\&.
.PP
Referenced by ComplexNumber::HypArcTangent()\&.
.PP
.nf
44 {
45     complex half = cpack(0\&.5, 0\&.0);
46     complex one = cpack(1\&.0, 0\&.0);
47     complex a = clog(cadd(one, z));
48     complex b = clog(csub(one, z));
49     complex c = csub(a, b);
50     complex w = cmul(half, c);
51     return w;
52 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
