lib/cplex/catanh.c
NAME
lib/cplex/catanh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex catanh (complex z)
Inverse hyperbolic tangent of complex number.
Function Documentation
complex catanh (complex z)
Inverse hyperbolic tangent of complex number.
Version:
1.0
Date:
14/09/15
Inverse hyperbolic tangent expressed using complex logarithms:
atanh(z) = 1/2 * ((log(1 + z) - log(1 - z))
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Inverse_hyperbolic_function#Logarithmic_representation
Definition at line 43 of file catanh.c.
References cadd(), clog(), cmul(), cpack(), and csub().
Referenced by ComplexNumber::HypArcTangent().
{
    complex half = cpack(0.5, 0.0);
    complex one = cpack(1.0, 0.0);
    complex a = clog(cadd(one, z));
    complex b = clog(csub(one, z));
    complex c = csub(a, b);
    complex w = cmul(half, c);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.