.TH "lib/cplex/ccbrt.c" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/ccbrt.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBccbrt\fP (\fBcomplex\fP z)"
.br
.RI "\fICube root of complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP ccbrt (\fBcomplex\fP z)"

.PP
Cube root of complex number\&. 
.PP
.nf

cbrt z = exp(1/3 * log(z))
.fi
.PP
 More info is available at Wikipedia: 
.br
 http://en.wikipedia.org/wiki/Cube_root 
.PP
Definition at line 40 of file ccbrt\&.c\&.
.PP
References cexp(), clog(), cmul(), and cpack()\&.
.PP
Referenced by ComplexNumber::CubeRoot()\&.
.PP
.nf
41 {
42     complex onethird = cpack(1\&.0 / 3\&.0, 0\&.0);
43     complex a = cmul(onethird, clog(z));
44     complex w = cexp(a);
45     return w;
46 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
