lib/cplex/ccbrt.c
NAME
lib/cplex/ccbrt.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ccbrt (complex z)
Cube root of complex number.
Function Documentation
complex ccbrt (complex z)
Cube root of complex number.
cbrt z = exp(1/3 * log(z))
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Cube_root
Definition at line 40 of file ccbrt.c.
References cexp(), clog(), cmul(), and cpack().
Referenced by ComplexNumber::CubeRoot().
{
    complex onethird = cpack(1.0 / 3.0, 0.0);
    complex a = cmul(onethird, clog(z));
    complex w = cexp(a);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.