lib/cplex/ccosh.c
NAME
lib/cplex/ccosh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ccosh (complex z)
Hyperbolic cosine of a complex number.
Function Documentation
complex ccosh (complex z)
Hyperbolic cosine of a complex number.
Version:
1.1
Date:
2007/08/20
a+bi
real = cosh(a) * cos(b)
imag = sinh(a) * sin(b)
Definition at line 51 of file ccosh.c.
References cchsh(), cimag(), cos(), cpack(), creal(), and sin().
Referenced by ComplexNumber::HypCosine().
{
    complex w;
    double a, b;
    double ch, sh;
    a = creal(z);
    b = cimag(z);
    cchsh(a, &ch, &sh);
    w = cpack(cos(b) * ch, sin(b) * sh);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.