lib/cplex/ccos.c
NAME
lib/cplex/ccos.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ccos (complex z)
Cosine of complex number.
Function Documentation
complex ccos (complex z)
Cosine of complex number.
Version:
1.1
Date:
2007/08/20
a+bi
real = cos(a) * cosh(b)
imag = -sin(a) * sinh(b)
Definition at line 51 of file ccos.c.
References cchsh(), cimag(), cos(), cpack(), creal(), and sin().
Referenced by ComplexNumber::Cosine().
{
    complex w;
    double a, b;
    double ch, sh;
    a = creal(z);
    b = cimag(z);
    cchsh(b, &ch, &sh);
    w = cpack((cos(a) * ch), (-sin(a) * sh));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.