lib/cplex/ccot.c
NAME
lib/cplex/ccot.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ccot (complex z)
Cotangent of a complex number.
Function Documentation
complex ccot (complex z)
Cotangent of a complex number. Calculated as in Open Office:
a+bi
                sin(2.0 * a)
real = ------------------------------
         cosh(2.0 * b) - cos(2.0 * a)
               -sinh(2.0 * b)
imag = ------------------------------
         cosh(2.0 * b) - cos(2.0 * a)
 https://wiki.openoffice.org/wiki/Documentation/How_Tos/Calc:_IMCOT_function
Definition at line 47 of file ccot.c.
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh().
Referenced by ComplexNumber::Cotangent().
{
    complex w;
    double a, b;
    double d;
    a = creal(z);
    b = cimag(z);
    d = cosh(2.0 * b) - cos(2.0 * a);
    if (d == 0.0) {
        w = cpack(HUGE, HUGE); // TODO: INF, INF
    } else {
        w = cpack((sin(2.0 * a) / d), (-sinh(2.0 * b) / d));
    }
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.