.TH "lib/cplex/ccot.c" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/ccot.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBccot\fP (\fBcomplex\fP z)"
.br
.RI "\fICotangent of a complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP ccot (\fBcomplex\fP z)"

.PP
Cotangent of a complex number\&. Calculated as in Open Office: 
.PP
.nf

a+bi
                sin(2\&.0 * a)
real  = ------------------------------
         cosh(2\&.0 * b) - cos(2\&.0 * a)
.fi
.PP
.PP
.PP
.nf
               -sinh(2\&.0 * b)
imag  = ------------------------------
         cosh(2\&.0 * b) - cos(2\&.0 * a)
.fi
.PP
 https://wiki.openoffice.org/wiki/Documentation/How_Tos/Calc:_IMCOT_function 
.PP
Definition at line 47 of file ccot\&.c\&.
.PP
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh()\&.
.PP
Referenced by ComplexNumber::Cotangent()\&.
.PP
.nf
48 {
49     complex w;
50     double a, b;
51     double d;
52 
53     a = creal(z);
54     b = cimag(z);
55     d = cosh(2\&.0 * b) - cos(2\&.0 * a);
56 
57     if (d == 0\&.0) {
58         w = cpack(HUGE, HUGE); // TODO: INF, INF
59     } else {
60         w = cpack((sin(2\&.0 * a) / d), (-sinh(2\&.0 * b) / d));
61     }
62 
63     return w;
64 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
