lib/cplex/ccoth.c
NAME
lib/cplex/ccoth.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ccoth (complex z)
Hyperbolic cotangent of a complex number.
Function Documentation
complex ccoth (complex z)
Hyperbolic cotangent of a complex number.
acoth(z) = 0.5 * (log(1 + 1/z) - log(1 - 1/z))
 or
a+bi
               sinh(2.0 * a)
real = ------------------------------
         cosh(2.0 * a) - cos(2.0 * b)
  -sin(2.0 * b)
imag = ------------------------------
         cosh(2.0 * a) - cos(2.0 * b)
Definition at line 49 of file ccoth.c.
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh().
Referenced by ComplexNumber::HypCotangent().
{
    complex w;
    double a, b;
    double d;
    a = creal(z);
    b = cimag(z);
    d = cosh(2.0 * a) - cos(2.0 * b);
    w = cpack(sinh(2.0 * a) / d, -sin(2.0 * b) / d);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.