.TH "lib/cplex/ccoth.c" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/ccoth.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBccoth\fP (\fBcomplex\fP z)"
.br
.RI "\fIHyperbolic cotangent of a complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP ccoth (\fBcomplex\fP z)"

.PP
Hyperbolic cotangent of a complex number\&. 
.PP
.nf

acoth(z) = 0\&.5 * (log(1 + 1/z) - log(1 - 1/z))
.fi
.PP
 or 
.PP
.nf

a+bi
               sinh(2\&.0 * a)
real  = ------------------------------
         cosh(2\&.0 * a) - cos(2\&.0 * b)
.PP
.nf
  -sin(2.0 * b)
.fi
.PP

imag  = ------------------------------
         cosh(2\&.0 * a) - cos(2\&.0 * b)
.fi
.PP
 
.PP
Definition at line 49 of file ccoth\&.c\&.
.PP
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh()\&.
.PP
Referenced by ComplexNumber::HypCotangent()\&.
.PP
.nf
50 {
51     complex w;
52     double a, b;
53     double d;
54 
55     a = creal(z);
56     b = cimag(z);
57     d = cosh(2\&.0 * a) - cos(2\&.0 * b);
58     w = cpack(sinh(2\&.0 * a) / d, -sin(2\&.0 * b) / d);
59 
60     return w;
61 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
