lib/cplex/ccsc.c
NAME
lib/cplex/ccsc.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ccsc (complex z)
Cosecant of a complex number.
Function Documentation
complex ccsc (complex z)
Cosecant of a complex number. Calculated as in Open Office:
a+bi
            2.0 * sin(a) * cosh(b)
real = ------------------------------
         cosh(2.0 * b) - cos(2.0 * a)
           -2.0 * cos(a) * sinh(b)
imag = ------------------------------
         cosh(2.0 * b) - cos(2.0 * a)
 https://wiki.openoffice.org/wiki/Documentation/How_Tos/Calc:_IMCSC_function
Definition at line 47 of file ccsc.c.
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh().
Referenced by ComplexNumber::Cosecant().
{
    complex w;
    double a, b;
    double d;
    a = creal(z);
    b = cimag(z);
    d = cosh(2.0 * b) - cos(2.0 * a);
    if (d == 0.0) {
        w = cpack(HUGE, HUGE); // TODO: INF, INF
    } else {
        w = cpack((2.0 * sin(a) * cosh(b) / d), (-2.0 * cos(a) * sinh(b) / d));
    }
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.