lib/cplex/ccsch.c
NAME
lib/cplex/ccsch.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ccsch (complex z)
Hyperbolic secant of a complex number.
Function Documentation
complex ccsch (complex z)
Hyperbolic secant of a complex number. Calculated as in Open Office:
a+bi
            2.0 * sinh(a) * cos(b)
real = ------------------------------
         cosh(2.0 * a) - cos(2.0 * b)
        -2.0 * cosh(2.0 * a) * sin(b)
imag = ------------------------------
         cosh(2.0 * a) - cos(2.0 * b)
 https://wiki.openoffice.org/wiki/Documentation/How_Tos/Calc:_IMCSCH_function
Definition at line 47 of file ccsch.c.
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh().
Referenced by ComplexNumber::HypCosecant().
{
    complex w;
    double a, b;
    double d;
    a = creal(z);
    b = cimag(z);
    d = cosh(2.0 * a) - cos(2.0 * b);
    w = cpack((2.0 * sinh(a) * cos(b) / d), (-2.0 * cosh(a) * sin(b) / d));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.