.TH "CeilingNode" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CeilingNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCeilingNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 260 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CeilingNode::CeilingNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 606 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
606                                                    :
607     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * CeilingNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 609 of file functions\&.cpp\&.
.PP
References CeilingNode()\&.
.PP
.nf
610 {
611     return new CeilingNode(expression);
612 }
.fi
.SS "\fBNumber\fP * CeilingNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 614 of file functions\&.cpp\&.
.PP
References Number::Ceiling(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result\&.
.PP
.nf
615 {
616     result = expression->Evaluate()->Ceiling();
617     return result;
618 }
.fi
.SS "char * CeilingNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 620 of file functions\&.cpp\&.
.PP
.nf
621 {
622     return (char*)"ceil";
623 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
