CeilingNode
NAME
CeilingNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
CeilingNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 260 of file functions.h.
Constructor & Destructor Documentation
CeilingNode::CeilingNode (ExpressionNode * expression)
Definition at line 606 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                   :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * CeilingNode::Create (ExpressionNode * expression) [static]
Definition at line 609 of file functions.cpp.
References CeilingNode().
{
    return new CeilingNode(expression);
}
Number * CeilingNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 614 of file functions.cpp.
References Number::Ceiling(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->Ceiling();
    return result;
}
char * CeilingNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 620 of file functions.cpp.
{
    return (char*)"ceil";
}
Author
Generated automatically by Doxygen for amath from the source code.