lib/cplex/cexp.c
NAME
lib/cplex/cexp.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex cexp (complex z)
Returns e to the power of a complex number.
Function Documentation
complex cexp (complex z)
Returns e to the power of a complex number.
Version:
1.1
Date:
2007/08/20
Definition at line 46 of file cexp.c.
References cimag(), cos(), cpack(), creal(), exp(), and sin().
Referenced by ccbrt().
{
    complex w;
    double r, x, y;
    x = creal(z);
    y = cimag(z);
    r = exp(x);
    w = cpack(r * cos(y), r * sin(y));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.