.TH "app/lib/charbuf.h" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/charbuf.h \- String and character array logic\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lib/aengine\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCharBuffer\fP"
.br
.RI "\fIEncapsulate an character array which can be used as a string\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
String and character array logic\&. 


.PP
Definition in file \fBcharbuf\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
