CharBuffer
NAME
CharBuffer - Encapsulate an character array which can be used as a string.
SYNOPSIS
#include <charbuf.h>
Public Member Functions
CharBuffer ()
Initialize without allocating memory.
CharBuffer (unsigned int size)
Initialize while allocating specified amount of memory.
~CharBuffer ()
void ClearBuffer ()
Release memory in buffer.
void ClearAndCopy (const char *source)
Release memory, allocate and copy source.
void ClearAndAlloc (unsigned int size)
Release memory and allocate new size.
void EnsureSize (unsigned int size)
Ensure a memory block of speficied size is allocated.
void EnsureSize (unsigned int blocksize, unsigned int blocks)
void EnsureMinimumSize ()
void EnsureGrowth (unsigned int size)
void Empty ()
bool Is (const char *string)
Compare content of CharBuffer with string)
void Copy (CharBuffer *buf)
void Append (const char *source)
void Append (const char c)
void Append (const char c, unsigned int count)
void DeleteLastChar ()
bool RemoveTrailing (const char c)
bool RemoveTrailing (const char *string)
char * GetString ()
Private Attributes
char * buf
char * ptr
unsigned int cursize
Static Private Attributes
static const unsigned int minimumSize = 64
Friends
class AnsiConoleEngine
Detailed Description
Encapsulate an character array which can be used as a string.
The CharBuffer class eases the task of allocating a releasing memory.
Definition at line 43 of file charbuf.h.
Constructor & Destructor Documentation
CharBuffer::CharBuffer ()
Initialize without allocating memory.
Definition at line 38 of file charbuf.cpp.
References buf, cursize, and ptr.
Referenced by AnsiConoleEngine::AnsiConoleEngine(), ErrorNode::ErrorNode(), Evaluator::Evaluator(), PromptStatement::Execute(), FunctionList::FunctionList(), StandardFilesystem::ListDirectory(), StandardPreferences::Load(), StandardFilesystem::LoadTextFile(), NumeralSystem::NumeralSystem(), PreferencesBase::PreferencesBase(), SyntaxNode::SyntaxNode(), UserFunction::UserFunction(), and VariableList::VariableList().
{
    buf = NOMEM;
    ptr = buf;
    cursize = 0;
}
CharBuffer::CharBuffer (unsigned int size)
Initialize while allocating specified amount of memory.
Definition at line 49 of file charbuf.cpp.
References buf, cursize, minimumSize, and ptr.
Referenced by SaveStatement::Execute(), PositionalNumeralSystem::GetText(), and StandardProgram::Initialize().
{
    cursize = (size < minimumSize ? minimumSize : size);
    buf = new char[cursize];
    ptr = buf;
}
CharBuffer::~CharBuffer ()
Definition at line 56 of file charbuf.cpp.
References ClearBuffer().
{
    ClearBuffer();
}
Member Function Documentation
void CharBuffer::Append (const char * source)
Definition at line 211 of file charbuf.cpp.
References ptr.
Referenced by ErrorNode::ErrorNode(), VersionStatement::Execute(), MemoryStatement::Execute(), ErrorNode::Execute(), EvalStatement::Execute(), StatementBlockNode::Execute(), DeleteStatement::Execute(), InputStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), SaveStatement::Execute(), PlotStatement::Execute(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetName(), DecimalSystem::GetRealText(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), PositionalNumeralSystem::GetText(), NumericOperator::GetText(), StandardProgram::Initialize(), UserFunction::InitializeTexts(), VariableList::ListContent(), FunctionList::ListContent(), StandardFilesystem::ListDirectory(), StandardPreferences::Load(), AnsiConoleEngine::ProcessChar(), AnsiConoleEngine::ShowLast(), and AnsiConoleEngine::ShowNext().
{
    while ((*ptr++ = *source++));
    ptr--;
}
void CharBuffer::Append (const char c)
Definition at line 195 of file charbuf.cpp.
References ptr.
Referenced by PromptStatement::Execute(), ErrorNode::Execute(), PlotStatement::Execute(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetText(), DecimalSystem::GetText(), StandardProgram::Initialize(), UserFunction::InitializeTexts(), PositionalNumeralSystem::IntegerToBuffer(), VariableList::ListContent(), FunctionList::ListContent(), StandardFilesystem::LoadTextFile(), and AnsiConoleEngine::ProcessChar().
{
    *ptr++ = c;
}
void CharBuffer::Append (const char c, unsigned int count)
Definition at line 200 of file charbuf.cpp.
References ptr.
Referenced by ErrorNode::Execute(), and StandardFilesystem::ListDirectory().
{
    if (count == 0) {
        return;
    }
    unsigned int n = count;
    while (n--)
        *ptr++ = c;
}
void CharBuffer::ClearAndAlloc (unsigned int size)
Release memory and allocate new size.
Definition at line 91 of file charbuf.cpp.
References buf, ClearBuffer(), cursize, minimumSize, and ptr.
Referenced by ErrorNode::Execute(), and AnsiConoleEngine::StartInput().
{
    ClearBuffer();
    cursize = (size < minimumSize ? minimumSize : size);
    buf = new char[cursize];
    ptr = buf;
}
void CharBuffer::ClearAndCopy (const char * source)
Release memory, allocate and copy source.
Definition at line 80 of file charbuf.cpp.
References AllocAndCopy(), buf, ClearBuffer(), cursize, and ptr.
Referenced by Evaluator::Evaluate(), PromptStatement::Execute(), HelpStatement::Execute(), ExecuteStatement::Execute(), and NumericValueNode::GetNodeText().
{
    ClearBuffer();
    cursize = AllocAndCopy(&buf, source);
    ptr = buf + cursize - sizeof(char);
}
void CharBuffer::ClearBuffer ()
Release memory in buffer.
Definition at line 65 of file charbuf.cpp.
References buf, cursize, and ptr.
Referenced by VariableList::Clear(), FunctionList::Clear(), ClearAndAlloc(), ClearAndCopy(), Evaluator::Evaluate(), StatementBlockNode::Execute(), and ~CharBuffer().
{
    if (buf != NOMEM) {
        delete [] buf;
    }
    buf = NOMEM;
    ptr = buf;
    cursize = 0;
}
void CharBuffer::Copy (CharBuffer * buf)
Definition at line 183 of file charbuf.cpp.
References buf, cursize, EnsureSize(), GetString(), and ptr.
Referenced by PositionalNumeralSystem::GetText().
{
    EnsureSize(source->cursize);
    const char *s = source->GetString();
    ptr = buf;
    while ((*ptr++ = *s++))
        ;
    ptr--;
}
void CharBuffer::DeleteLastChar ()
Definition at line 177 of file charbuf.cpp.
References ptr.
Referenced by StandardProgram::Initialize().
{
    ptr--;
}
void CharBuffer::Empty ()
Definition at line 168 of file charbuf.cpp.
References buf, EnsureMinimumSize(), and ptr.
Referenced by VersionStatement::Execute(), MemoryStatement::Execute(), ErrorNode::Execute(), EvalStatement::Execute(), StatementBlockNode::Execute(), DeleteStatement::Execute(), InputStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), SaveStatement::Execute(), PlotStatement::Execute(), FunctionDefinitionNode::FunctionDefinitionNode(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetName(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), PositionalNumeralSystem::GetText(), NumericOperator::GetText(), DecimalSystem::GetText(), StandardProgram::Initialize(), UserFunction::InitializeTexts(), VariableList::ListContent(), FunctionList::ListContent(), StandardFilesystem::ListDirectory(), StandardPreferences::Load(), StandardFilesystem::LoadTextFile(), NumeralSystem::NumeralSystem(), AnsiConoleEngine::ProcessChar(), AnsiConoleEngine::ShowLast(), and AnsiConoleEngine::ShowNext().
{
    if (buf == NOMEM) {
        EnsureMinimumSize();
    }
    ptr = buf;
}
void CharBuffer::EnsureGrowth (unsigned int size)
Definition at line 158 of file charbuf.cpp.
References buf, EnsureSize(), and ptr.
Referenced by StatementBlockNode::Execute(), PlotStatement::Execute(), DecimalSystem::GetRealText(), StandardFilesystem::ListDirectory(), and AnsiConoleEngine::ShowNext().
{
    EnsureSize((ptr - buf) + size);
}
void CharBuffer::EnsureMinimumSize ()
Definition at line 99 of file charbuf.cpp.
References buf, minimumSize, and ptr.
Referenced by Empty(), and FunctionDefinitionNode::FunctionDefinitionNode().
{
    if (buf == NOMEM) {
        unsigned int size = minimumSize;
        buf = new char[size];
        ptr = buf;
    }
}
void CharBuffer::EnsureSize (unsigned int size)
Ensure a memory block of speficied size is allocated.
Definition at line 112 of file charbuf.cpp.
References buf, cursize, MemCopy(), minimumSize, and ptr.
Referenced by Copy(), EnsureGrowth(), ErrorNode::ErrorNode(), VersionStatement::Execute(), MemoryStatement::Execute(), EvalStatement::Execute(), DeleteStatement::Execute(), InputStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetName(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), NumericOperator::GetText(), VariableList::ListContent(), FunctionList::ListContent(), StandardFilesystem::ListDirectory(), StandardPreferences::Load(), AnsiConoleEngine::ShowLast(), and AnsiConoleEngine::ShowNext().
{
    if (cursize < size) {
        unsigned int tempsize = cursize;
        cursize = (size < minimumSize ? minimumSize : size);
        if (buf == NOMEM) { // Nothing allocated yet. Just allocate requested size.
            buf = new char[cursize];
            ptr = buf;
        } else if (buf == ptr) { // Already allocated but buffer is empty.
            delete [] buf;
            buf = new char[cursize];
            ptr = buf;
        } else { // Buffer already in use.
            // Make at least double size
            cursize = cursize < tempsize * 2 ? tempsize * 2 : cursize;
            unsigned int offset = ptr - buf;
            char *temp = new char[cursize];
            MemCopy(temp, buf, tempsize);
            delete [] buf;
            buf = temp;
            ptr = buf + offset;
        }
    }
}
void CharBuffer::EnsureSize (unsigned int blocksize, unsigned int blocks)
Definition at line 139 of file charbuf.cpp.
References buf, cursize, MemCopy(), and ptr.
Referenced by StandardFilesystem::LoadTextFile().
{
    if (cursize < blocksize * blocks) {
        if (buf == NOMEM) {
            cursize = blocksize * blocks;
            buf = new char[cursize];
            ptr = buf;
        } else {
            unsigned int tptr = ptr - buf;
            char *temp = new char[blocksize * blocks];
            MemCopy(temp, buf, cursize);
            delete [] buf;
            cursize = blocksize * blocks;
            buf = temp;
            ptr = buf + tptr;
        }
    }
}
char * CharBuffer::GetString ()
Definition at line 250 of file charbuf.cpp.
References buf, and ptr.
Referenced by Copy(), AnsiConoleEngine::CopyLine(), ErrorNode::ErrorNode(), VersionStatement::Execute(), MemoryStatement::Execute(), PromptStatement::Execute(), ErrorNode::Execute(), FunctionDefinitionNode::Execute(), EvalStatement::Execute(), StatementBlockNode::Execute(), HelpStatement::Execute(), DeleteStatement::Execute(), InputStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), ShowStatement::Execute(), ListStatement::Execute(), LoadStatement::Execute(), SaveStatement::Execute(), ExecuteStatement::Execute(), PlotStatement::Execute(), UserFunction::GetDefitionName(), UserFunction::GetDefitionText(), PreferencesBase::GetDescription(), AnsiConoleEngine::GetLine(), PositionalNumeralSystem::GetName(), NumericValueNode::GetNodeText(), DecimalSystem::GetRealText(), Evaluator::GetResult(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), PositionalNumeralSystem::GetText(), NumericOperator::GetText(), DecimalSystem::GetText(), FunctionDefinitionNode::GetText(), UserFunction::InitializeTexts(), Is(), VariableList::ListContent(), FunctionList::ListContent(), StandardFilesystem::ListDirectory(), StandardPreferences::Load(), StandardLanguage::LoadCatalog(), AnsiConoleEngine::ProcessChar(), StandardProgram::Run(), AnsiConoleEngine::ShowLast(), and AnsiConoleEngine::ShowNext().
{
    *ptr = '\0';
    return buf;
}
bool CharBuffer::Is (const char * string)
Compare content of CharBuffer with string)
Definition at line 163 of file charbuf.cpp.
References GetString(), and StrIsEqual().
Referenced by PositionalNumeralSystem::GetText(), and StandardProgram::Initialize().
{
    return StrIsEqual(GetString(), string);
}
bool CharBuffer::RemoveTrailing (const char c)
Definition at line 218 of file charbuf.cpp.
References buf, and ptr.
Referenced by PromptStatement::Execute(), DecimalSystem::GetRealText(), and PositionalNumeralSystem::GetText().
{
    if (ptr == buf) {
        return false;
    }
    if (*(--ptr) == c) {
        return true;
    }
    ptr++;
    return false;
}
bool CharBuffer::RemoveTrailing (const char * string)
Definition at line 232 of file charbuf.cpp.
References buf, ptr, StrIsEqual(), and StrLen().
{
    int len = StrLen(string) * sizeof(char);
    char* s = ptr - len;
    if (s < buf) {
        return false;
    }
    *ptr = '\0';
    if (StrIsEqual(s, string)) {
        ptr = s;
        return true;
    }
    return false;
}
Friends And Related Function Documentation
friend class AnsiConoleEngine [friend]
Definition at line 74 of file charbuf.h.
Member Data Documentation
char* CharBuffer::buf [private]
Definition at line 76 of file charbuf.h.
Referenced by CharBuffer(), ClearAndAlloc(), ClearAndCopy(), ClearBuffer(), Copy(), Empty(), EnsureGrowth(), EnsureMinimumSize(), EnsureSize(), GetString(), AnsiConoleEngine::ProcessChar(), RemoveTrailing(), AnsiConoleEngine::ShowLast(), AnsiConoleEngine::ShowNext(), and AnsiConoleEngine::StartInput().
unsigned int CharBuffer::cursize [private]
Definition at line 78 of file charbuf.h.
Referenced by CharBuffer(), ClearAndAlloc(), ClearAndCopy(), ClearBuffer(), Copy(), and EnsureSize().
const unsigned int CharBuffer::minimumSize = 64 [static], [private]
Definition at line 79 of file charbuf.h.
Referenced by CharBuffer(), ClearAndAlloc(), EnsureMinimumSize(), and EnsureSize().
char* CharBuffer::ptr [private]
Definition at line 77 of file charbuf.h.
Referenced by Append(), CharBuffer(), ClearAndAlloc(), ClearAndCopy(), ClearBuffer(), Copy(), DeleteLastChar(), Empty(), EnsureGrowth(), EnsureMinimumSize(), EnsureSize(), GetString(), AnsiConoleEngine::ProcessChar(), and RemoveTrailing().
Author
Generated automatically by Doxygen for amath from the source code.