.TH "ClearStatement" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ClearStatement \- Clear the console window\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statements\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClearStatement\fP ()"
.br
.ti -1c
.RI "\fB~ClearStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Clear the console window\&. 
.PP
Definition at line 47 of file statements\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ClearStatement::ClearStatement ()\fC [inline]\fP"

.PP
Definition at line 49 of file statements\&.h\&.
.PP
Referenced by Parser::ParseStatement()\&.
.PP
.nf
49 { }
.fi
.SS "ClearStatement::~ClearStatement ()\fC [inline]\fP"

.PP
Definition at line 50 of file statements\&.h\&.
.PP
.nf
50 { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * ClearStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 44 of file statements\&.cpp\&.
.PP
References ConsoleBase::Clear(), and Program::Console\&.
.PP
.nf
45 {
46     Program->Console->Clear();
47     return (char*)EMPTYSTRING;
48 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
