lib/clib.h
NAME
lib/clib.h - C functions for manipulating strings and memory.
SYNOPSIS
#include 'platform.h'
Classes
struct texttag
Functions
int StrLen (const char *string)
Get the length of a null terminated string.
bool StrIsEqual (const char *s1, const char *s2)
Compare two null terminated strings to each other.
void MemSet (void *destination, int c0, unsigned int length)
void MemCopy (void *destination, const void *source, unsigned int length)
Copy a block of memory, handling overlap.
unsigned int AllocAndCopy (char **destination, const char *source)
Allocate memory and copy a string into the array.
void Untag (char *destination, const char *source, texttag tags[], unsigned int tagcount)
Detailed Description
C functions for manipulating strings and memory.
Definition in file clib.h.
Function Documentation
unsigned int AllocAndCopy (char ** destination, const char * source)
Allocate memory and copy a string into the array.
Definition at line 34 of file alloccpy.c.
Referenced by AnsiConoleEngine::AnsiConoleEngine(), CharBuffer::ClearAndCopy(), ConsoleBase::ConsoleBase(), AnsiConoleEngine::CopyLine(), DeleteStatement::DeleteStatement(), DrawStatement::DrawStatement(), ErrorNode::ErrorNode(), ExecuteStatement::ExecuteStatement(), HelpStatement::HelpStatement(), Lexer::Lexer(), ListStatement::ListStatement(), StandardLanguage::LoadCatalog(), LoadStatement::LoadStatement(), PlotStatement::PlotStatement(), PromptStatement::PromptStatement(), SaveStatement::SaveStatement(), PreferencesBase::SetDefaults(), PreferencesBase::SetPrompt(), ConsoleBase::SetPrompt(), AnsiConoleEngine::SetPrompt(), AnsiConoleEngine::ShowLast(), ShowStatement::ShowStatement(), Token::Token(), UserFunction::UserFunction(), and Variable::Variable().
{
    char *i, *s, *d;
    unsigned int n, size;
    if (source == NOMEM) {
        *destination = NOMEM;
        return 0;
    }
    i = (char*)source;
    s = (char*)source;
    while (*i)
        i++;
    n = i - s + 1;
    size = n;
    *destination = AllocMemSafe(size);
    d = *destination;
    while (n--)
        *d++ = *s++;
    return size;
}
void MemCopy (void * destination, const void * source, unsigned int length)
Copy a block of memory, handling overlap. Original file can be found at: https://svnweb.freebsd.org/base/release/9.0.0/lib/libc/string/bcopy.c?revision=229286
Definition at line 60 of file memcpy.c.
Referenced by CharBuffer::EnsureSize(), FormatPositional(), FormatScientific(), Lexer::GetDigitValue(), Lexer::GetLitteral(), Lexer::GetQuotedIdent(), PrintInfNan(), and Language::UntagText().
{
    char *dst = (char*) destination;
    const char *src = (const char*) source;
    unsigned int t;
    if (length == 0 || dst == src) // nothing to do
        return;
    if ((unsigned long)dst < (unsigned long)src) {
        // Copy forward
        t = (unsigned long)src; // only need low bits
        if ((t | (unsigned long)dst) & wmask) {
            // Try to align operands. This cannot be done unless the low bits match.
            if ((t ^ (unsigned long)dst) & wmask || length < wsize)
                t = length;
            else
                t = wsize - (t & wmask);
            length -= t;
            TLOOP1(*dst++ = *src++);
        }
        // Copy whole words, then mop up any trailing bytes.
        t = length / wsize;
        TLOOP(*(word *)dst = *(word *)src; src += wsize; dst += wsize);
        t = length & wmask;
        TLOOP(*dst++ = *src++);
    } else {
        // Copy backwards. Otherwise essentially the same.
        // Alignment works as before, except that it takes
        // (t&wmask) bytes to align, not wsize-(t&wmask).
        src += length;
        dst += length;
        t = (unsigned long)src;
        if ((t | (unsigned long)dst) & wmask) {
            if ((t ^ (unsigned long)dst) & wmask || length <= wsize)
                t = length;
            else
                t &= wmask;
            length -= t;
            TLOOP1(*--dst = *--src);
        }
        t = length / wsize;
        TLOOP(src -= wsize; dst -= wsize; *(word *)dst = *(word *)src);
        t = length & wmask;
        TLOOP(*--dst = *--src);
    }
}
void MemSet (void * destination, int c0, unsigned int length)
Definition at line 42 of file memset.c.
{
    unsigned char *dst = (unsigned char*) dst0;
    unsigned int t;
    unsigned int c;
    /*
     * If not enough words, just fill bytes. A length >= 2 words
     * guarantees that at least one of them is `complete' after
     * any necessary alignment. For instance:
     *
     * |-----------|-----------|-----------|
     * |00|01|02|03|04|05|06|07|08|09|0A|00|
     * ^---------------------^
     * dst dst+length-1
     *
     * but we use a minimum of 3 here since the overhead of the code
     * to do word writes is substantial.
     */
    if (length < 3 * wsize) {
        while (length != 0) {
            *dst++ = c0;
            --length;
        }
    }
    if ((c = (unsigned char)c0) != 0) { /* Fill the word. */
        c = (c << 8) | c; /* u_int is 16 bits. */
#if UINT_MAX > 0xffff
        c = (c << 16) | c; /* u_int is 32 bits. */
#endif
#if UINT_MAX > 0xffffffff
        c = (c << 32) | c; /* u_int is 64 bits. */
#endif
    }
    /* Align destination by filling in bytes. */
    if ((t = (long)dst & wmask) != 0) {
        t = wsize - t;
        length -= t;
        do {
            *dst++ = c0;
        } while (--t != 0);
    }
    /* Fill words. Length was >= 2*words so we know t >= 1 here. */
    t = length / wsize;
    do {
        *(unsigned int*)dst = c;
        dst += wsize;
    } while (--t != 0);
    /* Mop up trailing bytes, if any. */
    t = length & wmask;
    if (t != 0)
        do {
            *dst++ = c0;
        } while (--t != 0);
}
bool StrIsEqual (const char * s1, const char * s2)
Compare two null terminated strings to each other.
Definition at line 48 of file strcmp.c.
Referenced by VariableList::CreateVariable(), FunctionList::Delete(), Language::FindAlias(), FunctionList::GetFunctionCall(), FunctionList::GetFunctionDef(), Language::GetHelpText(), FunctionList::GetSystemFunction(), VariableList::GetVariable(), CharBuffer::Is(), StandardFilesystem::ListDirectory(), CharBuffer::RemoveTrailing(), StandardLanguage::StrIsEqualLoc(), and PosixLanguage::StrIsEqualLoc().
{
    int r;
    while (*s1 == *s2++)
        if (*s1++ == '\0')
            return true;
    r = (*(const unsigned char *)s1 - *(const unsigned char *)(s2 - 1));
    return r == 0;
}
int StrLen (const char * string)
Get the length of a null terminated string.
Definition at line 31 of file strlen.c.
Referenced by ErrorNode::ErrorNode(), VersionStatement::Execute(), MemoryStatement::Execute(), ErrorNode::Execute(), EvalStatement::Execute(), StatementBlockNode::Execute(), DeleteStatement::Execute(), InputStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), SaveStatement::Execute(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetName(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), NumericOperator::GetText(), StandardProgram::Initialize(), VariableList::ListContent(), FunctionList::ListContent(), StandardFilesystem::ListDirectory(), CharBuffer::RemoveTrailing(), StandardConsole::Run(), AnsiConoleEngine::ShowLast(), AnsiConoleEngine::ShowNext(), Language::UntagText(), and StandardConsole::WriteString().
{
    char *i = (char*)string;
    char *s = i;
    while (*i)
        i++;
    return i - s;
}
void Untag (char * destination, const char * source, texttag tags[], unsigned int tagcount)
Definition at line 29 of file untag.c.
References texttag::tag, and texttag::text.
Referenced by Language::UntagText().
{
    const char *pos, *tmp, *tag;
    char *dest;
    int unsigned i, j, found;
    pos = source;
    dest = destination;
    while (*pos != '\0') {
        if (*pos != '#') {
            (*dest++ = *pos++);
        } else {
            // Try to replace tag
            found = 0;
            for (i = 0; i < tagcount; i++) {
                tag = tags[i].tag;
                tmp = pos;
                j = 0;
                while (*tmp != '\0' && *tag != '\0' && *tmp == *tag) {
                    tmp++;
                    tag++;
                    j++;
                }
                if (j > 1 && *(--tag) == '#') {
                    // Tag found. Now replace.
                    tag = tags[i].text;
                    while ((*dest++ = *tag++));
                    dest--;
                    pos = tmp;
                    found = 1;
                    break;
                }
            }
            if(!found) {
                (*dest++ = *pos++);
            }
        }
    }
    *dest = '\0';
}
Author
Generated automatically by Doxygen for amath from the source code.