lib/cplex/clog.c
NAME
lib/cplex/clog.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex clog (complex z)
Natural logarithm of a complex number.
Function Documentation
complex clog (complex z)
Natural logarithm of a complex number.
Version:
1.1
Date:
2007/08/20
Definition at line 46 of file clog.c.
References atan2(), cabs(), cimag(), cpack(), and creal().
Referenced by cacos(), cacosh(), cacot(), cacoth(), cacsc(), cacsch(), casec(), casech(), casin(), casinh(), catan(), catanh(), ccbrt(), clog10(), clogb(), and ComplexNumber::Log().
{
    complex w;
    double p, q;
    p = log(cabs(z));
    q = atan2(cimag(z), creal(z));
    w = cpack(p, q);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.