lib/cplex/clogb.c
NAME
lib/cplex/clogb.c -
SYNOPSIS
#include 'prim.h'
#include 'complex.h'
Functions
complex clogb (complex z)
Base 2 logarithmic value of complex number.
Function Documentation
complex clogb (complex z)
Base 2 logarithmic value of complex number.
lb z = log(z) / log(2)
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Complex_logarithm
Definition at line 39 of file clogb.c.
References cdiv(), clog(), and cpack().
Referenced by ComplexNumber::Log2().
{
    complex two = cpack(2.0, 0.0);
    complex w = cdiv(clog(z), clog(two));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.