.TH "lib/cplex/clog.c" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/clog.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBclog\fP (\fBcomplex\fP z)"
.br
.RI "\fINatural logarithm of a complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP clog (\fBcomplex\fP z)"

.PP
Natural logarithm of a complex number\&. 
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2007/08/20 
.RE
.PP

.PP
Definition at line 46 of file clog\&.c\&.
.PP
References atan2(), cabs(), cimag(), cpack(), and creal()\&.
.PP
Referenced by cacos(), cacosh(), cacot(), cacoth(), cacsc(), cacsch(), casec(), casech(), casin(), casinh(), catan(), catanh(), ccbrt(), clog10(), clogb(), and ComplexNumber::Log()\&.
.PP
.nf
47 {
48     complex w;
49     double p, q;
50     p = log(cabs(z));
51     q = atan2(cimag(z), creal(z));
52     w = cpack(p, q);
53     return w;
54 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
