lib/cplex/clog10.c
NAME
lib/cplex/clog10.c -
SYNOPSIS
#include 'prim.h'
#include 'complex.h'
Functions
complex clog10 (complex z)
Base 10 logarithmic value of complex number.
Function Documentation
complex clog10 (complex z)
Base 10 logarithmic value of complex number.
log z = log(z) / log(10)
 More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Complex_logarithm
Definition at line 39 of file clog10.c.
References cdiv(), clog(), and cpack().
Referenced by ComplexNumber::Log10().
{
    complex teen = cpack(10.0, 0.0);
    complex w = cdiv(clog(z), clog(teen));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.