.TH "lib/cplex/clog10.c" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/clog10.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBclog10\fP (\fBcomplex\fP z)"
.br
.RI "\fIBase 10 logarithmic value of complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP clog10 (\fBcomplex\fP z)"

.PP
Base 10 logarithmic value of complex number\&. 
.PP
.nf

log z = log(z) / log(10)
.fi
.PP
 More info is available at Wikipedia: 
.br
 http://en.wikipedia.org/wiki/Complex_logarithm 
.PP
Definition at line 39 of file clog10\&.c\&.
.PP
References cdiv(), clog(), and cpack()\&.
.PP
Referenced by ComplexNumber::Log10()\&.
.PP
.nf
40 {
41     complex teen = cpack(10\&.0, 0\&.0);
42     complex w = cdiv(clog(z), clog(teen));
43     return w;
44 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
