.TH "complex" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <complex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBparts\fP [2]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file complex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "double complex::parts[2]"

.PP
Definition at line 41 of file complex\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
