ComplexNumber
NAME
ComplexNumber - Represent a complex number with 2 componts of 15 siginificant digits.
SYNOPSIS
#include <cplex.h>
Inherits Number.
Public Member Functions
ComplexNumber ()
ComplexNumber (complex z)
ComplexNumber (double real, double imag)
~ComplexNumber ()
Number * Clone ()
int GetIntegerValue ()
double GetRealValue ()
double GetImagValue ()
complex GetComplexValue ()
bool PureComplexValue ()
int GetPrecedence ()
int GetDefaultPrecedence ()
Number * Unary ()
Number * Add (Number *other)
Number * Sub (Number *other)
Number * Mul (Number *other)
Number * Div (Number *other)
Number * Raise (Number *exponent)
Number * Signum ()
Number * Trunc ()
Number * Round ()
Number * Floor ()
Number * Ceiling ()
Number * Absolute ()
Number * SquareRoot ()
Number * CubeRoot ()
Number * Reciprocal ()
Number * Log ()
Number * Log2 ()
Number * Log10 ()
Number * Sine ()
Number * Cosine ()
Number * Tangent ()
Number * Cosecant ()
Number * Secant ()
Number * Cotangent ()
Number * ArcSine ()
Number * ArcCosine ()
Number * ArcTangent ()
Number * ArcCosecant ()
Number * ArcSecant ()
Number * ArcCotangent ()
Number * HypSine ()
Number * HypCosine ()
Number * HypTangent ()
Number * HypCosecant ()
Number * HypSecant ()
Number * HypCotangent ()
Number * HypArcSine ()
Number * HypArcCosine ()
Number * HypArcTangent ()
Number * HypArcCosecant ()
Number * HypArcSecant ()
Number * HypArcCotangent ()
Private Attributes
complex z
Additional Inherited Members
Detailed Description
Represent a complex number with 2 componts of 15 siginificant digits.
Calculations are done using 64 bit IEEE 754 arithmetics.
Definition at line 46 of file cplex.h.
Constructor & Destructor Documentation
ComplexNumber::ComplexNumber ()
Definition at line 33 of file cplex.cpp.
References cpack(), nsyscomplex, Number::Number(), and z.
Referenced by Add(), Div(), Mul(), Raise(), and Sub().
                             :
    Number(nsyscomplex) {
    z = cpack(0.0, 0.0);
}
ComplexNumber::ComplexNumber (complex z)
Definition at line 38 of file cplex.cpp.
References nsyscomplex, Number::Number(), and z.
Referenced by Add(), ArcCosecant(), ArcCosine(), ArcCotangent(), ArcSecant(), ArcSine(), ArcTangent(), Ceiling(), Clone(), Cosecant(), Cosine(), Cotangent(), CubeRoot(), Div(), Floor(), HypArcCosecant(), HypArcCosine(), HypArcCotangent(), HypArcSecant(), HypArcSine(), HypArcTangent(), HypCosecant(), HypCosine(), HypCotangent(), HypSecant(), HypSine(), HypTangent(), Log(), Log10(), Log2(), Mul(), Raise(), Reciprocal(), Round(), Secant(), Sine(), SquareRoot(), Sub(), Tangent(), Trunc(), and Unary().
                                      :
    Number(nsyscomplex) {
    this->z = z;
}
ComplexNumber::ComplexNumber (double real, double imag)
Definition at line 43 of file cplex.cpp.
References cpack(), nsyscomplex, Number::Number(), and z.
Referenced by ComplexiNode::ComplexiNode(), Parser::ParseNumber(), RealNumber::Raise(), and RealNumber::SquareRoot().
                                                     :
    Number(nsyscomplex) {
    z = cpack(real, imag);
}
ComplexNumber::~ComplexNumber ()
Definition at line 48 of file cplex.cpp.
{ }
Member Function Documentation
Number * ComplexNumber::Absolute () [virtual]
Implements Number.
Definition at line 173 of file cplex.cpp.
References cabs(), RealNumber::RealNumber(), and z.
{
    return new RealNumber(cabs(z));
}
Number * ComplexNumber::Add (Number * other) [virtual]
Implements Number.
Definition at line 103 of file cplex.cpp.
References cadd(), ComplexNumber(), cpack(), nsyscomplex, nsysreal, Number::system, RealNumber::x, and z.
{
    if (other->system == nsyscomplex) {
        ComplexNumber *w = (ComplexNumber*)other;
        return new ComplexNumber(cadd(z, w->z));
    } else if (other->system == nsysreal) {
        RealNumber *a = (RealNumber*)other;
        return new ComplexNumber(cadd(z, cpack(a->x, 0.0)));
    } else {
        return new ComplexNumber();
    }
}
Number * ComplexNumber::ArcCosecant () [virtual]
Implements Number.
Definition at line 278 of file cplex.cpp.
References cacsc(), ComplexNumber(), and z.
{
    return new ComplexNumber(cacsc(z));
}
Number * ComplexNumber::ArcCosine () [virtual]
Implements Number.
Definition at line 263 of file cplex.cpp.
References cacos(), ComplexNumber(), and z.
{
    return new ComplexNumber(cacos(z));
}
Number * ComplexNumber::ArcCotangent () [virtual]
Implements Number.
Definition at line 283 of file cplex.cpp.
References cacot(), ComplexNumber(), and z.
{
    return new ComplexNumber(cacot(z));
}
Number * ComplexNumber::ArcSecant () [virtual]
Implements Number.
Definition at line 273 of file cplex.cpp.
References casec(), ComplexNumber(), and z.
{
    return new ComplexNumber(casec(z));
}
Number * ComplexNumber::ArcSine () [virtual]
Implements Number.
Definition at line 258 of file cplex.cpp.
References casin(), ComplexNumber(), and z.
{
    return new ComplexNumber(casin(z));
}
Number * ComplexNumber::ArcTangent () [virtual]
Implements Number.
Definition at line 268 of file cplex.cpp.
References catan(), ComplexNumber(), and z.
{
    return new ComplexNumber(catan(z));
}
Number * ComplexNumber::Ceiling () [virtual]
Implements Number.
Definition at line 193 of file cplex.cpp.
References cceil(), ComplexNumber(), and z.
{
    return new ComplexNumber(cceil(z));
}
Number * ComplexNumber::Clone () [virtual]
Implements Number.
Definition at line 51 of file cplex.cpp.
References ComplexNumber(), and z.
{
    return new ComplexNumber(z);
}
Number * ComplexNumber::Cosecant () [virtual]
Implements Number.
Definition at line 248 of file cplex.cpp.
References ccsc(), ComplexNumber(), and z.
{
    return new ComplexNumber(ccsc(z));
}
Number * ComplexNumber::Cosine () [virtual]
Implements Number.
Definition at line 233 of file cplex.cpp.
References ccos(), ComplexNumber(), and z.
{
    return new ComplexNumber(ccos(z));
}
Number * ComplexNumber::Cotangent () [virtual]
Implements Number.
Definition at line 253 of file cplex.cpp.
References ccot(), ComplexNumber(), and z.
{
    return new ComplexNumber(ccot(z));
}
Number * ComplexNumber::CubeRoot () [virtual]
Implements Number.
Definition at line 208 of file cplex.cpp.
References ccbrt(), ComplexNumber(), and z.
{
    return new ComplexNumber(ccbrt(z));
}
Number * ComplexNumber::Div (Number * other) [virtual]
Implements Number.
Definition at line 142 of file cplex.cpp.
References cdiv(), ComplexNumber(), cpack(), nsyscomplex, nsysreal, Number::system, RealNumber::x, and z.
{
    if (other->system == nsyscomplex) {
        ComplexNumber *w = (ComplexNumber*)other;
        return new ComplexNumber(cdiv(z, w->z));
    } else if (other->system == nsysreal) {
        RealNumber *a = (RealNumber*)other;
        return new ComplexNumber(cdiv(z, cpack(a->x, 0.0)));
    } else {
        return new ComplexNumber();
    }
}
Number * ComplexNumber::Floor () [virtual]
Implements Number.
Definition at line 188 of file cplex.cpp.
References cfloor(), ComplexNumber(), and z.
{
    return new ComplexNumber(cfloor(z));
}
complex ComplexNumber::GetComplexValue ()
Definition at line 71 of file cplex.cpp.
References z.
Referenced by PositionalNumeralSystem::GetText(), and DecimalSystem::GetText().
{
    return z;
}
int ComplexNumber::GetDefaultPrecedence () [virtual]
Implements Number.
Definition at line 92 of file cplex.cpp.
References cimag(), creal(), and z.
{
    return (creal(z) != 0.0 && cimag(z) != 0.0) ? 2 : 0;
}
double ComplexNumber::GetImagValue ()
Definition at line 66 of file cplex.cpp.
References cimag(), and z.
{
    return cimag(z);
}
int ComplexNumber::GetIntegerValue () [virtual]
Implements Number.
Definition at line 56 of file cplex.cpp.
References creal(), and z.
{
    return (int) creal(z);
}
int ComplexNumber::GetPrecedence () [virtual]
Implements Number.
Definition at line 81 of file cplex.cpp.
References cimag(), creal(), and z.
{
    if ((creal(z) < 0.0) || (creal(z) == 0.0 && cimag(z) < 0.0)) {
        return -1;
    } else if (creal(z) != 0.0 && cimag(z) != 0.0) {
        return 2;
    } else {
        return 0;
    }
}
double ComplexNumber::GetRealValue () [virtual]
Implements Number.
Definition at line 61 of file cplex.cpp.
References creal(), and z.
{
    return creal(z);
}
Number * ComplexNumber::HypArcCosecant () [virtual]
Implements Number.
Definition at line 338 of file cplex.cpp.
References cacsch(), ComplexNumber(), and z.
{
    return new ComplexNumber(cacsch(z));
}
Number * ComplexNumber::HypArcCosine () [virtual]
Implements Number.
Definition at line 323 of file cplex.cpp.
References cacosh(), ComplexNumber(), and z.
{
    return new ComplexNumber(cacosh(z));
}
Number * ComplexNumber::HypArcCotangent () [virtual]
Implements Number.
Definition at line 343 of file cplex.cpp.
References cacoth(), ComplexNumber(), and z.
{
    return new ComplexNumber(cacoth(z));
}
Number * ComplexNumber::HypArcSecant () [virtual]
Implements Number.
Definition at line 333 of file cplex.cpp.
References casech(), ComplexNumber(), and z.
{
    return new ComplexNumber(casech(z));
}
Number * ComplexNumber::HypArcSine () [virtual]
Implements Number.
Definition at line 318 of file cplex.cpp.
References casinh(), ComplexNumber(), and z.
{
    return new ComplexNumber(casinh(z));
}
Number * ComplexNumber::HypArcTangent () [virtual]
Implements Number.
Definition at line 328 of file cplex.cpp.
References catanh(), ComplexNumber(), and z.
{
    return new ComplexNumber(catanh(z));
}
Number * ComplexNumber::HypCosecant () [virtual]
Implements Number.
Definition at line 308 of file cplex.cpp.
References ccsch(), ComplexNumber(), and z.
{
    return new ComplexNumber(ccsch(z));
}
Number * ComplexNumber::HypCosine () [virtual]
Implements Number.
Definition at line 293 of file cplex.cpp.
References ccosh(), ComplexNumber(), and z.
{
    return new ComplexNumber(ccosh(z));
}
Number * ComplexNumber::HypCotangent () [virtual]
Implements Number.
Definition at line 313 of file cplex.cpp.
References ccoth(), ComplexNumber(), and z.
{
    return new ComplexNumber(ccoth(z));
}
Number * ComplexNumber::HypSecant () [virtual]
Implements Number.
Definition at line 303 of file cplex.cpp.
References ComplexNumber(), csech(), and z.
{
    return new ComplexNumber(csech(z));
}
Number * ComplexNumber::HypSine () [virtual]
Implements Number.
Definition at line 288 of file cplex.cpp.
References ComplexNumber(), csinh(), and z.
{
    return new ComplexNumber(csinh(z));
}
Number * ComplexNumber::HypTangent () [virtual]
Implements Number.
Definition at line 298 of file cplex.cpp.
References ComplexNumber(), ctanh(), and z.
{
    return new ComplexNumber(ctanh(z));
}
Number * ComplexNumber::Log () [virtual]
Implements Number.
Definition at line 213 of file cplex.cpp.
References clog(), ComplexNumber(), and z.
{
    return new ComplexNumber(clog(z));
}
Number * ComplexNumber::Log10 () [virtual]
Implements Number.
Definition at line 223 of file cplex.cpp.
References clog10(), ComplexNumber(), and z.
{
    return new ComplexNumber(clog10(z));
}
Number * ComplexNumber::Log2 () [virtual]
Implements Number.
Definition at line 218 of file cplex.cpp.
References clogb(), ComplexNumber(), and z.
{
    return new ComplexNumber(clogb(z));
}
Number * ComplexNumber::Mul (Number * other) [virtual]
Implements Number.
Definition at line 129 of file cplex.cpp.
References cmul(), ComplexNumber(), cpack(), nsyscomplex, nsysreal, Number::system, RealNumber::x, and z.
{
    if (other->system == nsyscomplex) {
        ComplexNumber *w = (ComplexNumber*)other;
        return new ComplexNumber(cmul(z, w->z));
    } else if (other->system == nsysreal) {
        RealNumber *a = (RealNumber*)other;
        return new ComplexNumber(cmul(z, cpack(a->x, 0.0)));
    } else {
        return new ComplexNumber();
    }
}
bool ComplexNumber::PureComplexValue () [virtual]
Implements Number.
Definition at line 76 of file cplex.cpp.
References creal(), and z.
{
    return (creal(z) == 0.0);
}
Number * ComplexNumber::Raise (Number * exponent) [virtual]
Implements Number.
Definition at line 155 of file cplex.cpp.
References ComplexNumber(), cpack(), cpow(), nsyscomplex, nsysreal, Number::system, RealNumber::x, and z.
Referenced by RealNumber::Raise().
{
    if (exponent->system == nsyscomplex) {
        ComplexNumber *w = (ComplexNumber*)exponent;
        return new ComplexNumber(cpow(z, w->z));
    } else if (exponent->system == nsysreal) {
        RealNumber *a = (RealNumber*)exponent;
        return new ComplexNumber(cpow(z, cpack(a->x, 0.0)));
    } else {
        return new ComplexNumber();
    }
}
Number * ComplexNumber::Reciprocal () [virtual]
Implements Number.
Definition at line 203 of file cplex.cpp.
References ComplexNumber(), creci(), and z.
{
    return new ComplexNumber(creci(z));
}
Number * ComplexNumber::Round () [virtual]
Implements Number.
Definition at line 183 of file cplex.cpp.
References ComplexNumber(), cround(), and z.
{
    return new ComplexNumber(cround(z));
}
Number * ComplexNumber::Secant () [virtual]
Implements Number.
Definition at line 243 of file cplex.cpp.
References ComplexNumber(), csec(), and z.
{
    return new ComplexNumber(csec(z));
}
Number * ComplexNumber::Signum () [virtual]
Implements Number.
Definition at line 168 of file cplex.cpp.
References csgn(), RealNumber::RealNumber(), and z.
{
    return new RealNumber(csgn(z));
}
Number * ComplexNumber::Sine () [virtual]
Implements Number.
Definition at line 228 of file cplex.cpp.
References ComplexNumber(), csin(), and z.
{
    return new ComplexNumber(csin(z));
}
Number * ComplexNumber::SquareRoot () [virtual]
Implements Number.
Definition at line 198 of file cplex.cpp.
References ComplexNumber(), csqrt(), and z.
{
    return new ComplexNumber(csqrt(z));
}
Number * ComplexNumber::Sub (Number * other) [virtual]
Implements Number.
Definition at line 116 of file cplex.cpp.
References ComplexNumber(), cpack(), csub(), nsyscomplex, nsysreal, Number::system, RealNumber::x, and z.
{
    if (other->system == nsyscomplex) {
        ComplexNumber *w = (ComplexNumber*)other;
        return new ComplexNumber(csub(z, w->z));
    } else if (other->system == nsysreal) {
        RealNumber *a = (RealNumber*)other;
        return new ComplexNumber(csub(z, cpack(a->x, 0.0)));
    } else {
        return new ComplexNumber();
    }
}
Number * ComplexNumber::Tangent () [virtual]
Implements Number.
Definition at line 238 of file cplex.cpp.
References ComplexNumber(), ctan(), and z.
{
    return new ComplexNumber(ctan(z));
}
Number * ComplexNumber::Trunc () [virtual]
Implements Number.
Definition at line 178 of file cplex.cpp.
References ComplexNumber(), ctrunc(), and z.
{
    return new ComplexNumber(ctrunc(z));
}
Number * ComplexNumber::Unary () [virtual]
Implements Number.
Definition at line 97 of file cplex.cpp.
References cimag(), ComplexNumber(), cpack(), creal(), and z.
{
    complex w = cpack(-creal(z), -cimag(z));
    return new ComplexNumber(w);
}
Member Data Documentation
complex ComplexNumber::z [private]
Definition at line 112 of file cplex.h.
Referenced by Absolute(), Add(), ArcCosecant(), ArcCosine(), ArcCotangent(), ArcSecant(), ArcSine(), ArcTangent(), Ceiling(), Clone(), ComplexNumber(), Cosecant(), Cosine(), Cotangent(), CubeRoot(), Div(), Floor(), GetComplexValue(), GetDefaultPrecedence(), GetImagValue(), GetIntegerValue(), GetPrecedence(), GetRealValue(), HypArcCosecant(), HypArcCosine(), HypArcCotangent(), HypArcSecant(), HypArcSine(), HypArcTangent(), HypCosecant(), HypCosine(), HypCotangent(), HypSecant(), HypSine(), HypTangent(), Log(), Log10(), Log2(), Mul(), PureComplexValue(), Raise(), Reciprocal(), Round(), Secant(), Signum(), Sine(), SquareRoot(), Sub(), Tangent(), Trunc(), and Unary().
Author
Generated automatically by Doxygen for amath from the source code.