ComplexiNode
NAME
ComplexiNode - Use of the square root of -2 in a syntax tree.
SYNOPSIS
#include <values.h>
Inherits NumericValueNode.
Public Member Functions
ComplexiNode ()
ReductionType GetReductionType ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Use of the square root of -2 in a syntax tree.
Definition at line 191 of file values.h.
Constructor & Destructor Documentation
ComplexiNode::ComplexiNode ()
Definition at line 434 of file values.cpp.
References ComplexNumber::ComplexNumber(), and NumericValueNode::NumericValueNode().
Referenced by Parser::ParseAtomic().
                           :
    NumericValueNode(new ComplexNumber(0.0, 1.0)) { }
Member Function Documentation
char * ComplexiNode::GetNodeText () [protected], [virtual]
Reimplemented from NumericValueNode.
Definition at line 442 of file values.cpp.
{
    return (char*)"i";
}
ReductionType ComplexiNode::GetReductionType () [virtual]
Reimplemented from NumericValueNode.
Definition at line 437 of file values.cpp.
References nonereduc.
{
    return nonereduc;
}
Author
Generated automatically by Doxygen for amath from the source code.