ConsoleBase
NAME
ConsoleBase - Abstract base class encapsulating console logic.
SYNOPSIS
#include <console.h>
Inherits ThreadBase.
Inherited by StandardConsole.
Public Member Functions
ConsoleBase (const char *prompt)
virtual ~ConsoleBase ()
const char * GetName ()
virtual void Clear ()
virtual void Exit ()=0
virtual void SetPrompt (const char *string)
virtual void WriteString (const char *string)=0
Protected Member Functions
void StartMessage ()
void Prompt ()
Private Attributes
char * prompt
Detailed Description
Abstract base class encapsulating console logic.
Definition at line 42 of file console.h.
Constructor & Destructor Documentation
ConsoleBase::ConsoleBase (const char * prompt)
Definition at line 32 of file console.cpp.
References AllocAndCopy(), and prompt.
Referenced by StandardConsole::StandardConsole().
{
    AllocAndCopy(&this->prompt, prompt);
}
ConsoleBase::~ConsoleBase () [virtual]
Definition at line 37 of file console.cpp.
References prompt.
{
    delete prompt;
}
Member Function Documentation
void ConsoleBase::Clear () [virtual]
Definition at line 47 of file console.cpp.
References WriteString().
Referenced by ClearStatement::Execute().
{
    WriteString(CLEARWINDOW);
    WriteString(NORMALTEXT);
}
virtual void ConsoleBase::Exit () [pure virtual]
Implemented in StandardConsole.
Referenced by StandardProgram::Exit().
const char * ConsoleBase::GetName () [virtual]
Implements ThreadBase.
Definition at line 42 of file console.cpp.
{
    return CPROCNAME;
}
void ConsoleBase::Prompt () [protected]
Definition at line 59 of file console.cpp.
References prompt, and WriteString().
Referenced by StandardConsole::Run().
{
    WriteString(NORMALTEXT);
    WriteString(prompt);
    WriteString(NORMALTEXT);
}
void ConsoleBase::SetPrompt (const char * string) [virtual]
Reimplemented in StandardConsole.
Definition at line 66 of file console.cpp.
References AllocAndCopy(), and prompt.
Referenced by PrefsStatement::Execute(), StandardConsole::SetPrompt(), and Program::SetPrompt().
{
    delete prompt;
    AllocAndCopy(&prompt, string);
}
void ConsoleBase::StartMessage () [protected]
Definition at line 53 of file console.cpp.
References WriteString().
Referenced by StandardConsole::Run().
{
    WriteString(INTROMSG);
    WriteString(NORMALTEXT);
}
virtual void ConsoleBase::WriteString (const char * string) [pure virtual]
Implemented in StandardConsole.
Referenced by Clear(), Prompt(), and StartMessage().
Member Data Documentation
char* ConsoleBase::prompt [private]
Definition at line 57 of file console.h.
Referenced by ConsoleBase(), Prompt(), SetPrompt(), and ~ConsoleBase().
Author
Generated automatically by Doxygen for amath from the source code.