.TH "app/system/console_stdc.cpp" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/console_stdc.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'main/nodes\&.h'\fP
.br
\fC#include 'main/evaluator\&.h'\fP
.br
\fC#include 'system/console_stdc\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
