.TH "app/system/console_amiga.cpp" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/console_amiga.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'main/nodes\&.h'\fP
.br
\fC#include 'main/evaluator\&.h'\fP
.br
\fC#include 'system/console_amiga\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
