lib/real/cos.c
NAME
lib/real/cos.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double cos (double x)
Trigonometric cosine function.
Function Documentation
double cos (double x)
Trigonometric cosine function.
Version:
1.3
Date:
95/01/18
Return cosine function of x.
kernel function:
 __kernel_sin ... sine function on [-pi/4,pi/4]
 __kernel_cos ... cosine function on [-pi/4,pi/4]
 rem_pio2 ... argument reduction routine
Method.
     Let S,C and T denote the sin, cos and tan respectively on
 [-PI/4, +PI/4]. Reduce the argument x to y1+y2 = x-k*pi/2
 in [-pi/4 , +pi/4], and let n = k mod 4.
 We have
         n sin(x) cos(x) tan(x)
    ----------------------------------------------------------
     0 S C T
     1 C -S -1/T
     2 -S -C T
     3 -C S -1/T
    ----------------------------------------------------------
Special cases:
     Let trig be any of sin, cos, or tan.
     trig(+-INF) is NaN, with signals;
     trig(NaN) is that NaN;
Accuracy:
 TRIG(x) returns trig(x) nearly rounded
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 87 of file cos.c.
References __kernel_cos(), __kernel_sin(), and rempio2().
Referenced by cchc(), ccos(), ccosh(), ccot(), ccoth(), ccsc(), ccsch(), cexp(), RealNumber::Cosine(), cpow(), csec(), csech(), csin(), csinh(), ctan(), ctanh(), and RealNumber::Secant().
{
    double y[2],z=0.0;
    sword n, ix;
    /* High word of x. */
    GET_HIGH_WORD(ix,x);
    /* |x| ~< pi/4 */
    ix &= 0x7fffffff;
    if(ix <= 0x3fe921fb) return __kernel_cos(x,z);
    /* cos(Inf or NaN) is NaN */
    else if (ix>=0x7ff00000) return x-x;
    /* argument reduction needed */
    else {
        n = rempio2(x,y);
        switch(n&3) {
        case 0:
            return __kernel_cos(y[0],y[1]);
        case 1:
            return -__kernel_sin(y[0],y[1],1);
        case 2:
            return -__kernel_cos(y[0],y[1]);
        default:
            return __kernel_sin(y[0],y[1],1);
        }
    }
}
Author
Generated automatically by Doxygen for amath from the source code.