CosecantNode
NAME
CosecantNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
CosecantNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 372 of file functions.h.
Constructor & Destructor Documentation
CosecantNode::CosecantNode (ExpressionNode * expression)
Definition at line 801 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                     :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * CosecantNode::Create (ExpressionNode * expression) [static]
Definition at line 804 of file functions.cpp.
References CosecantNode().
{
    return new CosecantNode(expression);
}
Number * CosecantNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 809 of file functions.cpp.
References Number::Cosecant(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->Cosecant();
    return result;
}
char * CosecantNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 815 of file functions.cpp.
{
    return (char*)"csc";
}
Author
Generated automatically by Doxygen for amath from the source code.