lib/real/cosh.c
NAME
lib/real/cosh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double cosh (double x)
Hyperbolic cosine function.
Variables
static const double one = 1.0
static const double half =0.5
static const double huge = 1.0e300
Function Documentation
double cosh (double x)
Hyperbolic cosine function.
Version:
1.3
Date:
95/01/18
Method :
mathematically cosh(x) if defined to be (exp(x)+exp(-x))/2
 1. Replace x by |x| (cosh(x) = cosh(-x)).
 2.
                                            [ exp(x) - 1 ]^2
     0 <= x <= ln2/2 : cosh(x) := 1 + -------------------
                                   2*exp(x)
                                      exp(x) + 1/exp(x)
     ln2/2 <= x <= 22 : cosh(x) := -------------------
                                  2
     22 <= x <= lnovft : cosh(x) := exp(x)/2
     lnovft <= x <= ln2ovft: cosh(x) := exp(x/2)/2 * exp(x/2)
     ln2ovft < x : cosh(x) := huge*huge (overflow)
Special cases:
 cosh(x) is |x| if x is +INF, -INF, or NaN.
 only cosh(0)=1 is exact for finite x.
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 84 of file cosh.c.
References exp(), expm1(), half, huge, and one.
Referenced by cchc(), cchsh(), ccot(), ccoth(), ccsc(), ccsch(), csec(), csech(), ctan(), ctanh(), RealNumber::HypCosine(), and RealNumber::HypSecant().
{
    double t,w;
    sword ix;
    uword lx;
    /* High word of |x|. */
    GET_HIGH_WORD(ix,x);
    ix &= 0x7fffffff;
    /* x is INF or NaN */
    if(ix>=0x7ff00000) return x*x;
    /* |x| in [0,0.5*ln2], return 1+expm1(|x|)^2/(2*exp(|x|)) */
    if(ix<0x3fd62e43) {
        t = expm1(fabs(x));
        w = one+t;
        if (ix<0x3c800000) return w; /* cosh(tiny) = 1 */
        return one+(t*t)/(w+w);
    }
    /* |x| in [0.5*ln2,22], return (exp(|x|)+1/exp(|x|)/2; */
    if (ix < 0x40360000) {
        t = exp(fabs(x));
        return half*t+half/t;
    }
    /* |x| in [22, log(maxdouble)] return half*exp(|x|) */
    if (ix < 0x40862E42) return half*exp(fabs(x));
    /* |x| in [log(maxdouble), overflowthresold] */
    lx = *( (((*(unsigned*)&one)>>29)) + (unsigned*)&x);
    if (ix<0x408633CE ||
            ((ix==0x408633ce)&&(lx<=(unsigned)0x8fb9f87d))) {
        w = exp(half*fabs(x));
        t = half*w;
        return t*w;
    }
    /* |x| > overflowthresold, cosh(x) overflow */
    return huge*huge;
}
Variable Documentation
const double half =0.5 [static]
Definition at line 51 of file cosh.c.
Referenced by cosh().
const double huge = 1.0e300 [static]
Definition at line 51 of file cosh.c.
Referenced by cosh().
const double one = 1.0 [static]
Definition at line 51 of file cosh.c.
Referenced by cosh().
Author
Generated automatically by Doxygen for amath from the source code.