CosineNode
NAME
CosineNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
CosineNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 342 of file functions.h.
Constructor & Destructor Documentation
CosineNode::CosineNode (ExpressionNode * expression)
Definition at line 763 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                 :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * CosineNode::Create (ExpressionNode * expression) [static]
Definition at line 766 of file functions.cpp.
References CosineNode().
{
    return new CosineNode(expression);
}
Number * CosineNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 771 of file functions.cpp.
References Number::Cosine(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->Cosine();
    return result;
}
char * CosineNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 777 of file functions.cpp.
{
    return (char*)"cos";
}
Author
Generated automatically by Doxygen for amath from the source code.