CotangentNode
NAME
CotangentNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
CotangentNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 362 of file functions.h.
Constructor & Destructor Documentation
CotangentNode::CotangentNode (ExpressionNode * expression)
Definition at line 839 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                       :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * CotangentNode::Create (ExpressionNode * expression) [static]
Definition at line 842 of file functions.cpp.
References CotangentNode().
{
    return new CotangentNode(expression);
}
Number * CotangentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 847 of file functions.cpp.
References Number::Cotangent(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->Cotangent();
    return result;
}
char * CotangentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 853 of file functions.cpp.
{
    return (char*)"cot";
}
Author
Generated automatically by Doxygen for amath from the source code.