.TH "app/lib/cplex.h" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/cplex.h \- Classbased handling of complex numbers\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'complex\&.h'\fP
.br
\fC#include 'lib/numb\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBComplexNumber\fP"
.br
.RI "\fIRepresent a complex number with 2 componts of 15 siginificant digits\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Classbased handling of complex numbers\&. 


.PP
Definition in file \fBcplex\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
