lib/cplex/cpow.c
NAME
lib/cplex/cpow.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex cpow (complex a, complex z)
Complex number raised to a power.
Function Documentation
complex cpow (complex a, complex z)
Complex number raised to a power.
Version:
1.1
Date:
2007/08/20
Definition at line 46 of file cpow.c.
References atan2(), cabs(), cimag(), cos(), cpack(), creal(), exp(), pow(), and sin().
Referenced by ComplexNumber::Raise().
{
    complex w;
    double x, y, r, theta, absa, arga;
    x = creal(z);
    y = cimag(z);
    absa = cabs(a);
    if (absa == 0.0) {
        return cpack(0.0, + 0.0);
    }
    arga = atan2(cimag(a), creal(a));
    r = pow(absa, x);
    theta = x * arga;
    if (y != 0.0) {
        r = r * exp(-y * arga);
        theta = theta + y * log(absa);
    }
    w = cpack(r * cos(theta), r * sin(theta));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.