.TH "lib/cplex/csec.c" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/csec.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBcsec\fP (\fBcomplex\fP z)"
.br
.RI "\fISecant of a complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP csec (\fBcomplex\fP z)"

.PP
Secant of a complex number\&. Calculated as in Open Office:
.br
 https://wiki.openoffice.org/wiki/Documentation/How_Tos/Calc:_IMSEC_function 
.PP
.nf

a+bi
            2\&.0 * cos(a) * cosh(b)
real  = ------------------------------
         cosh(2\&.0 * b) + cos(2\&.0 * a)
.fi
.PP
.PP
.PP
.nf
            2\&.0 * sin(a) * sinh(b)
imag  = ------------------------------
         cosh(2\&.0 * b) + cos(2\&.0 * a)
.fi
.PP
 
.PP
Definition at line 47 of file csec\&.c\&.
.PP
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh()\&.
.PP
Referenced by ComplexNumber::Secant()\&.
.PP
.nf
48 {
49     complex w;
50     double a, b;
51     double d;
52 
53     a = creal(z);
54     b = cimag(z);
55     d = cosh(2\&.0 * b) + cos(2\&.0 * a);
56 
57     if (d == 0\&.0) {
58         w = cpack(HUGE, HUGE); // TODO: INF, INF
59     } else {
60         w = cpack((2\&.0 * cos(a) * cosh(b) / d), (2\&.0 * sin(a) * sinh(b) / d));
61     }
62 
63     return w;
64 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
