lib/cplex/csec.c
NAME
lib/cplex/csec.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex csec (complex z)
Secant of a complex number.
Function Documentation
complex csec (complex z)
Secant of a complex number. Calculated as in Open Office:
 https://wiki.openoffice.org/wiki/Documentation/How_Tos/Calc:_IMSEC_function
a+bi
            2.0 * cos(a) * cosh(b)
real = ------------------------------
         cosh(2.0 * b) + cos(2.0 * a)
            2.0 * sin(a) * sinh(b)
imag = ------------------------------
         cosh(2.0 * b) + cos(2.0 * a)
Definition at line 47 of file csec.c.
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh().
Referenced by ComplexNumber::Secant().
{
    complex w;
    double a, b;
    double d;
    a = creal(z);
    b = cimag(z);
    d = cosh(2.0 * b) + cos(2.0 * a);
    if (d == 0.0) {
        w = cpack(HUGE, HUGE); // TODO: INF, INF
    } else {
        w = cpack((2.0 * cos(a) * cosh(b) / d), (2.0 * sin(a) * sinh(b) / d));
    }
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.