lib/cplex/csgn.c
NAME
lib/cplex/csgn.c -
SYNOPSIS
#include 'prim.h'
Functions
double csgn (complex z)
Complex signum.
Function Documentation
double csgn (complex z)
Complex signum. More info is available at Wikipedia:
 http://en.wikipedia.org/wiki/Sign_function#Complex_signum
Definition at line 36 of file csgn.c.
References cimag(), and creal().
Referenced by ComplexNumber::Signum().
{
    double a = creal(z);
    if (a > 0.0) {
        return 1.0;
    } else if (a < 0.0) {
        return -1.0;
    } else {
        double b = cimag(z);
        return b > 0.0 ? 1.0 : b < 0.0 ? -1.0 : 0.0;
    }
}
Author
Generated automatically by Doxygen for amath from the source code.