lib/cplex/csin.c
NAME
lib/cplex/csin.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex csin (complex z)
Sine of a complex number.
Function Documentation
complex csin (complex z)
Sine of a complex number.
Version:
1.1
Date:
2007/08/20
Calculated according to description at wikipedia:
 http://en.wikipedia.org/wiki/Sine#Sine_with_a_complex_argument
a+bi
real = sin(a) * cosh(b)
imag = cos(a) * sinh(b)
Definition at line 53 of file csin.c.
References cchsh(), cimag(), cos(), cpack(), creal(), and sin().
Referenced by ComplexNumber::Sine().
{
    complex w;
    double a, b;
    double ch, sh;
    a = creal(z);
    b = cimag(z);
    cchsh(b, &ch, &sh);
    w = cpack((sin(a) * ch), (cos(a) * sh));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.