lib/cplex/csinh.c
NAME
lib/cplex/csinh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex csinh (complex z)
Hyperbolic sine of a complex number.
Function Documentation
complex csinh (complex z)
Hyperbolic sine of a complex number.
Version:
1.1
Date:
2007/08/20
Calculated as in Open Office:
 https://wiki.openoffice.org/wiki/Documentation/How_Tos/Calc:_IMSINH_function
a+bi
real = sinh(a) * cos(b)
imag = cosh(a) * sin(b)
Definition at line 53 of file csinh.c.
References cchsh(), cimag(), cos(), cpack(), creal(), and sin().
Referenced by ComplexNumber::HypSine().
{
    complex w;
    double a, b;
    double ch, sh;
    a = creal(z);
    b = cimag(z);
    cchsh(a, &ch, &sh);
    w = cpack(cos(b) * sh, sin(b) * ch);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.