lib/cplex/csqrt.c
NAME
lib/cplex/csqrt.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex csqrt (complex z)
Square root of complex number.
Function Documentation
complex csqrt (complex z)
Square root of complex number.
Version:
1.1
Date:
2007/08/20
Definition at line 46 of file csqrt.c.
References cabs(), cimag(), cpack(), creal(), and sqrt().
Referenced by cacos(), cacosh(), cacsc(), cacsch(), casec(), casech(), casin(), casinh(), and ComplexNumber::SquareRoot().
{
    complex w;
    double x, y, r, t, scale;
    x = creal (z);
    y = cimag (z);
    if (y == 0.0) {
        if (x == 0.0) {
            w = cpack(0.0, y);
        } else {
            r = fabs(x);
            r = sqrt(r);
            if (x < 0.0) {
                w = cpack(0.0, r);
            } else {
                w = cpack(r, y);
            }
        }
        return w;
    }
    if (x == 0.0) {
        r = fabs(y);
        r = sqrt(0.5 * r);
        if (y > 0)
            w = cpack(r, r);
        else
            w = cpack(r, -r);
        return w;
    }
    /* Rescale to avoid internal overflow or underflow. */
    if ((fabs(x) > 4.0) || (fabs(y) > 4.0)) {
        x *= 0.25;
        y *= 0.25;
        scale = 2.0;
    } else {
#if 1
        x *= 1.8014398509481984e16; /* 2^54 */
        y *= 1.8014398509481984e16;
        scale = 7.450580596923828125e-9; /* 2^-27 */
#else
        x *= 4.0;
        y *= 4.0;
        scale = 0.5;
#endif
    }
    w = cpack(x, y);
    r = cabs(w);
    if (x > 0) {
        t = sqrt(0.5 * r + 0.5 * x);
        r = scale * fabs((0.5 * y) / t );
        t *= scale;
    } else {
        r = sqrt(0.5 * r - 0.5 * x);
        t = scale * fabs((0.5 * y) / r);
        r *= scale;
    }
    if (y < 0)
        w = cpack(t, -r);
    else
        w = cpack(t, r);
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.