lib/cplex/ctanh.c
NAME
lib/cplex/ctanh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ctanh (complex z)
Hyperbolic tangent of a complex number.
Function Documentation
complex ctanh (complex z)
Hyperbolic tangent of a complex number.
Version:
1.1
Date:
2007/08/20
a+bi
               sinh(2.0 * a)
real = ------------------------------
         cosh(2.0 * a) + cos(2.0 * b)
  sin(2.0 * b)
imag = ------------------------------
         cosh(2.0 * a) + cos(2.0 * b)
Definition at line 56 of file ctanh.c.
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh().
Referenced by ComplexNumber::HypTangent().
{
    complex w;
    double a, b;
    double d;
    a = creal(z);
    b = cimag(z);
    d = cosh(2.0 * a) + cos(2.0 * b);
    w = cpack((sinh(2.0 * a) / d), (sin(2.0 * b) / d));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.