lib/cplex/ctan.c
NAME
lib/cplex/ctan.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
#include 'complex.h'
Functions
complex ctan (complex z)
Tangent of a complex number.
Function Documentation
complex ctan (complex z)
Tangent of a complex number.
Version:
1.1
Date:
2007/08/20
Calculated as in Open Office:
 https://wiki.openoffice.org/wiki/Documentation/How_Tos/Calc:_IMTAN_function
a+bi
               sin(2.0 * a)
real = ------------------------------
         cos(2.0 * a) + cosh(2.0 * b)
  sinh(2.0 * b)
imag = ------------------------------
         cos(2.0 * a) + cosh(2.0 * b)
Definition at line 58 of file ctan.c.
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh().
Referenced by ComplexNumber::Tangent().
{
    complex w;
    double a, b;
    double d;
    a = creal(z);
    b = cimag(z);
    d = cos(2.0 * a) + cosh(2.0 * b);
    if (d == 0.0) {
        w = cpack(HUGE, HUGE); // TODO: INF, INF
    } else {
        w = cpack((sin(2.0 * a) / d), (sinh(2.0 * b) / d));
    }
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.