.TH "lib/cplex/ctanh.c" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/cplex/ctanh.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBcomplex\fP \fBctanh\fP (\fBcomplex\fP z)"
.br
.RI "\fIHyperbolic tangent of a complex number\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBcomplex\fP ctanh (\fBcomplex\fP z)"

.PP
Hyperbolic tangent of a complex number\&. 
.PP
\fBVersion:\fP
.RS 4
1\&.1 
.RE
.PP
\fBDate:\fP
.RS 4
2007/08/20
.RE
.PP
.PP
.nf

a+bi
               sinh(2\&.0 * a)
real  = ------------------------------
         cosh(2\&.0 * a) + cos(2\&.0 * b)
.PP
.nf
  sin(2.0 * b)
.fi
.PP

imag  = ------------------------------
         cosh(2\&.0 * a) + cos(2\&.0 * b)
.fi
.PP
 
.PP
Definition at line 56 of file ctanh\&.c\&.
.PP
References cimag(), cos(), cosh(), cpack(), creal(), sin(), and sinh()\&.
.PP
Referenced by ComplexNumber::HypTangent()\&.
.PP
.nf
57 {
58     complex w;
59     double a, b;
60     double d;
61 
62     a = creal(z);
63     b = cimag(z);
64     d = cosh(2\&.0 * a) + cos(2\&.0 * b);
65     w = cpack((sinh(2\&.0 * a) / d), (sin(2\&.0 * b) / d));
66 
67     return w;
68 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
