CubeRootNode
NAME
CubeRootNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
CubeRootNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 284 of file functions.h.
Constructor & Destructor Documentation
CubeRootNode::CubeRootNode (ExpressionNode * expression)
Definition at line 652 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                     :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * CubeRootNode::Create (ExpressionNode * expression) [static]
Definition at line 655 of file functions.cpp.
References CubeRootNode().
{
    return new CubeRootNode(expression);
}
Number * CubeRootNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 660 of file functions.cpp.
References Number::CubeRoot(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result.
{
    result = expression->Evaluate()->CubeRoot();
    return result;
}
char * CubeRootNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 666 of file functions.cpp.
{
    return (char*)"cbrt";
}
Author
Generated automatically by Doxygen for amath from the source code.