.TH "CubeRootNode" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CubeRootNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCubeRootNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 284 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "CubeRootNode::CubeRootNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 652 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
652                                                      :
653     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * CubeRootNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 655 of file functions\&.cpp\&.
.PP
References CubeRootNode()\&.
.PP
.nf
656 {
657     return new CubeRootNode(expression);
658 }
.fi
.SS "\fBNumber\fP * CubeRootNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 660 of file functions\&.cpp\&.
.PP
References Number::CubeRoot(), ExpressionNode::Evaluate(), FunctionNode::expression, and ExpressionNode::result\&.
.PP
.nf
661 {
662     result = expression->Evaluate()->CubeRoot();
663     return result;
664 }
.fi
.SS "char * CubeRootNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 666 of file functions\&.cpp\&.
.PP
.nf
667 {
668     return (char*)"cbrt";
669 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
