DecimalSystem
NAME
DecimalSystem -
SYNOPSIS
#include <ntext.h>
Inherits PositionalNumeralSystem.
Public Member Functions
DecimalSystem ()
DecimalSystem (unsigned int digits)
DecimalSystem (unsigned int digits, const char fractionpoint)
~DecimalSystem ()
virtual const char * GetText (Number *number)
Private Member Functions
const char * GetRealText (double value)
Additional Inherited Members
Detailed Description
Definition at line 98 of file ntext.h.
Constructor & Destructor Documentation
DecimalSystem::DecimalSystem ()
Definition at line 355 of file ntext.cpp.
References PositionalNumeralSystem::PositionalNumeralSystem().
                             :
    PositionalNumeralSystem(10, 5, '\0')
{ }
DecimalSystem::DecimalSystem (unsigned int digits)
Definition at line 359 of file ntext.cpp.
References PositionalNumeralSystem::PositionalNumeralSystem().
Referenced by MemoryStatement::Execute(), DigitsStatement::Execute(), PlotStatement::Execute(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetName(), Parser::ParseDigistStatement(), and Parser::ParseNumeralStatement().
                                                :
    PositionalNumeralSystem(10, digits, '.')
{ }
DecimalSystem::DecimalSystem (unsigned int digits, const char fractionpoint)
Definition at line 363 of file ntext.cpp.
References PositionalNumeralSystem::PositionalNumeralSystem().
Referenced by Program::NewPositionalInput(), Program::NewPositionalOutput(), and Program::Program().
                              :
    PositionalNumeralSystem(10, digits, fractionpoint)
{ }
DecimalSystem::~DecimalSystem ()
Definition at line 369 of file ntext.cpp.
{ }
Member Function Documentation
const char * DecimalSystem::GetRealText (double value) [private]
Definition at line 405 of file ntext.cpp.
References CharBuffer::Append(), NumeralSystem::buf, PositionalNumeralSystem::digits, CharBuffer::EnsureGrowth(), PositionalNumeralSystem::fractionpoint, CharBuffer::GetString(), log10(), pow(), PrintFloat64(), PrintFloatFormat_Positional, PrintFloatFormat_Scientific, CharBuffer::RemoveTrailing(), round(), and trunc().
Referenced by GetText().
{
    double exponent = log10(fabs(value));
    int formatdigits = digits - (int)trunc(exponent) - 1;
    double rounddigits = digits - 1;
    if (exponent < 0.0) {
        rounddigits++;
        formatdigits++;
    }
    // Remove output of inaccuracy
    if (formatdigits > (int)digits) {
        formatdigits = digits;
    }
    double roundfactor = pow(10.0, rounddigits);
    double roundedvalue = round(value * roundfactor) / roundfactor;
    if (roundedvalue == 0.0) {
        return "0";
    }
    double ulimit = pow(10.0, (double)digits);
    double llimit = pow(10.0, -(double)digits);
    if (fabs(roundedvalue) > ulimit) {
        return "INF";
    } else if (fabs(roundedvalue) < llimit) {
        return "-INF";
    }
    double expborder = log10(fabs(roundedvalue));
    tPrintFloatFormat format = (expborder > 6.0 || expborder < -5.0) ?
                               PrintFloatFormat_Scientific :
                               PrintFloatFormat_Positional;
    static const int size = 32;
    char *out = new char[size];
    PrintFloat64(out, size, roundedvalue, format, formatdigits, fractionpoint);
    buf->EnsureGrowth(size);
    buf->Append(out);
    while (buf->RemoveTrailing('0'))
        ;
    buf->RemoveTrailing(fractionpoint);
    delete[] out;
    return buf->GetString();
}
const char * DecimalSystem::GetText (Number * number) [virtual]
Reimplemented from PositionalNumeralSystem.
Definition at line 372 of file ntext.cpp.
References CharBuffer::Append(), NumeralSystem::buf, cimag(), creal(), CharBuffer::Empty(), ComplexNumber::GetComplexValue(), GetRealText(), Number::GetRealValue(), CharBuffer::GetString(), nsysreal, and Number::system.
{
    buf->Empty();
    if (number->system == nsysreal) {
        return GetRealText(number->GetRealValue());
    }
    complex w = ((ComplexNumber*)number)->GetComplexValue();
    double a = creal(w);
    double b = cimag(w);
    if (a == 0.0 && b == 0.0) {
        buf->Append('0');
        return buf->GetString();
    }
    if (a != 0.0) {
        GetRealText(a);
    }
    if (a != 0.0 && b > 0.0) {
        buf->Append('+');
    }
    if (b != 0.0) {
        GetRealText(b);
        buf->Append('i');
    }
    return buf->GetString();
}
Author
Generated automatically by Doxygen for amath from the source code.