DeleteStatement
NAME
DeleteStatement - Delete variable or function.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
DeleteStatement (Symbol symbol)
Constructor used to delete either all variable or functions.
DeleteStatement (const char *name)
Constructor used to delete a Variable.
DeleteStatement (const char *name, const char *argument)
Constructor used to delete a function.
~DeleteStatement ()
char * Execute ()
Private Attributes
Symbol type
char * name
char * argument
Additional Inherited Members
Detailed Description
Delete variable or function.
Definition at line 191 of file statements.h.
Constructor & Destructor Documentation
DeleteStatement::DeleteStatement (Symbol symbol)
Constructor used to delete either all variable or functions.
Definition at line 361 of file statements.cpp.
References argument, name, and type.
Referenced by Parser::ParseDeleteStatement().
{
    type = symbol;
    name = NOMEM;
    argument = NOMEM;
}
DeleteStatement::DeleteStatement (const char * name)
Constructor used to delete a Variable.
Definition at line 372 of file statements.cpp.
References AllocAndCopy(), argument, name, StatementNode::StatementNode(), symvariable, and type.
Referenced by Parser::ParseDeleteStatement().
                                                 :
    StatementNode()
{
    type = symvariable;
    AllocAndCopy(&this->name, name);
    argument = NOMEM;
}
DeleteStatement::DeleteStatement (const char * name, const char * argument)
Constructor used to delete a function.
Definition at line 384 of file statements.cpp.
References AllocAndCopy(), argument, name, StatementNode::StatementNode(), symfunction, and type.
Referenced by Parser::ParseDeleteStatement().
                                                                       :
    StatementNode()
{
    type = symfunction;
    AllocAndCopy(&this->name, name);
    AllocAndCopy(&this->argument, argument);
}
DeleteStatement::~DeleteStatement ()
Definition at line 393 of file statements.cpp.
References argument, and name.
{
    if (name != NOMEM) {
        delete [] name;
    }
    if (argument != NOMEM) {
        delete [] argument;
    }
}
Member Function Documentation
char * DeleteStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 404 of file statements.cpp.
References CharBuffer::Append(), argument, VariableList::Clear(), FunctionList::Clear(), VariableList::Delete(), FunctionList::Delete(), CharBuffer::Empty(), CharBuffer::EnsureSize(), Program::Functions, CharBuffer::GetString(), name, SyntaxNode::output, StrLen(), symfunction, symvariable, type, and Program::Variables.
{
    bool success = true;
    output->Empty();
    if (type == symvariable && name == NOMEM) {
        Program->Variables->Clear();
    } else if (type == symvariable && name != NOMEM) {
        success = Program->Variables->Delete(name);
        const char *msg = HELPVARNDEF;
        output->EnsureSize(
            StrLen(msg) +
            StrLen(name) +
            StrLen(NEWLINE) + 1);
        output->Append(msg);
        output->Append(name);
        output->Append(NEWLINE);
    } else if (type == symfunction && name == NOMEM) {
        Program->Functions->Clear();
    } else if (type == symfunction && name != NOMEM) {
        success = Program->Functions->Delete(name, argument);
        const char *msg = HELPFUNNDEF;
        output->EnsureSize(
            StrLen(msg) +
            StrLen(name) + 2 +
            StrLen(argument) +
            StrLen(NEWLINE) + 1);
        output->Append(msg);
        output->Append(name);
        output->Append("(");
        output->Append(argument);
        output->Append(")");
        output->Append(NEWLINE);
    }
    return (char*)(success ? EMPTYSTRING : output->GetString());
}
Member Data Documentation
char* DeleteStatement::argument [private]
Definition at line 202 of file statements.h.
Referenced by DeleteStatement(), Execute(), and ~DeleteStatement().
char* DeleteStatement::name [private]
Definition at line 201 of file statements.h.
Referenced by DeleteStatement(), Execute(), and ~DeleteStatement().
Symbol DeleteStatement::type [private]
Definition at line 200 of file statements.h.
Referenced by DeleteStatement(), and Execute().
Author
Generated automatically by Doxygen for amath from the source code.