DigitsStatement
NAME
DigitsStatement - Set number of significant digits to show.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
DigitsStatement ()
Constructor used to show number of active digits.
DigitsStatement (unsigned int digits)
Constructor used to show number of active digits.
~DigitsStatement ()
char * Execute ()
Private Attributes
bool show
unsigned int digits
Additional Inherited Members
Detailed Description
Set number of significant digits to show.
Definition at line 239 of file statements.h.
Constructor & Destructor Documentation
DigitsStatement::DigitsStatement ()
Constructor used to show number of active digits.
Definition at line 534 of file statements.cpp.
References show.
Referenced by Parser::ParseDigistStatement().
{
    show = true;
}
DigitsStatement::DigitsStatement (unsigned int digits)
Constructor used to show number of active digits.
Definition at line 543 of file statements.cpp.
References digits, and show.
Referenced by Parser::ParseDigistStatement().
                                                    :
    digits(digits) {
    show = false;
}
DigitsStatement::~DigitsStatement () [inline]
Definition at line 243 of file statements.h.
{ }
Member Function Documentation
char * DigitsStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 548 of file statements.cpp.
References CharBuffer::Append(), DecimalSystem::DecimalSystem(), digits, CharBuffer::Empty(), CharBuffer::EnsureSize(), NumeralSystem::GetDigits(), CharBuffer::GetString(), NumeralSystem::GetText(), Program::Input, Program::Output, SyntaxNode::output, Program::Preferences, RealNumber::RealNumber(), PreferencesBase::SetDigits(), NumeralSystem::SetDigits(), show, and StrLen().
{
    const char *text;
    if (!show) {
        Program->Input->SetDigits(digits);
        Program->Output->SetDigits(digits);
        Program->Preferences->SetDigits(digits);
        text = HELPDIGISETT;
    } else {
        text = HELPDIGISHOW;
        digits = Program->Output->GetDigits();
    }
    Number *d = new RealNumber(digits);
    NumeralSystem *ns = new DecimalSystem(2);
    const char *dtext = ns->GetText(d);
    delete d;
    output->Empty();
    output->EnsureSize(StrLen(text) + StrLen(dtext) + StrLen(NEWLINE) + 1);
    output->Append(text);
    output->Append(dtext);
    output->Append(NEWLINE);
    delete ns;
    return output->GetString();
}
Member Data Documentation
unsigned int DigitsStatement::digits [private]
Definition at line 248 of file statements.h.
Referenced by DigitsStatement(), and Execute().
bool DigitsStatement::show [private]
Definition at line 247 of file statements.h.
Referenced by DigitsStatement(), and Execute().
Author
Generated automatically by Doxygen for amath from the source code.