.TH "DigitsStatement" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DigitsStatement \- Set number of significant digits to show\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statements\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDigitsStatement\fP ()"
.br
.RI "\fIConstructor used to show number of active digits\&. \fP"
.ti -1c
.RI "\fBDigitsStatement\fP (unsigned int \fBdigits\fP)"
.br
.RI "\fIConstructor used to show number of active digits\&. \fP"
.ti -1c
.RI "\fB~DigitsStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBshow\fP"
.br
.ti -1c
.RI "unsigned int \fBdigits\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Set number of significant digits to show\&. 
.PP
Definition at line 239 of file statements\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DigitsStatement::DigitsStatement ()"

.PP
Constructor used to show number of active digits\&. 
.PP
Definition at line 534 of file statements\&.cpp\&.
.PP
References show\&.
.PP
Referenced by Parser::ParseDigistStatement()\&.
.PP
.nf
535 {
536     show = true;
537 }
.fi
.SS "DigitsStatement::DigitsStatement (unsigned int digits)"

.PP
Constructor used to show number of active digits\&. 
.PP
Definition at line 543 of file statements\&.cpp\&.
.PP
References digits, and show\&.
.PP
Referenced by Parser::ParseDigistStatement()\&.
.PP
.nf
543                                                     :
544     digits(digits) {
545     show = false;
546 }
.fi
.SS "DigitsStatement::~DigitsStatement ()\fC [inline]\fP"

.PP
Definition at line 243 of file statements\&.h\&.
.PP
.nf
243 { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * DigitsStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 548 of file statements\&.cpp\&.
.PP
References CharBuffer::Append(), DecimalSystem::DecimalSystem(), digits, CharBuffer::Empty(), CharBuffer::EnsureSize(), NumeralSystem::GetDigits(), CharBuffer::GetString(), NumeralSystem::GetText(), Program::Input, Program::Output, SyntaxNode::output, Program::Preferences, RealNumber::RealNumber(), PreferencesBase::SetDigits(), NumeralSystem::SetDigits(), show, and StrLen()\&.
.PP
.nf
549 {
550     const char *text;
551 
552     if (!show) {
553         Program->Input->SetDigits(digits);
554         Program->Output->SetDigits(digits);
555         Program->Preferences->SetDigits(digits);
556         text = HELPDIGISETT;
557     } else {
558         text = HELPDIGISHOW;
559         digits = Program->Output->GetDigits();
560     }
561 
562     Number *d = new RealNumber(digits);
563     NumeralSystem *ns = new DecimalSystem(2);
564     const char *dtext = ns->GetText(d);
565     delete d;
566 
567     output->Empty();
568     output->EnsureSize(StrLen(text) + StrLen(dtext) + StrLen(NEWLINE) + 1);
569     output->Append(text);
570     output->Append(dtext);
571     output->Append(NEWLINE);
572 
573     delete ns;
574     return output->GetString();
575 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "unsigned int DigitsStatement::digits\fC [private]\fP"

.PP
Definition at line 248 of file statements\&.h\&.
.PP
Referenced by DigitsStatement(), and Execute()\&.
.SS "\fBbool\fP DigitsStatement::show\fC [private]\fP"

.PP
Definition at line 247 of file statements\&.h\&.
.PP
Referenced by DigitsStatement(), and Execute()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
