DivisionNode
NAME
DivisionNode -
SYNOPSIS
#include <operators.h>
Inherits NumericOperator.
Public Member Functions
DivisionNode (ExpressionNode *left, ExpressionNode *right)
int GetPrecedence ()
Number * Evaluate ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 128 of file operators.h.
Constructor & Destructor Documentation
DivisionNode::DivisionNode (ExpressionNode * left, ExpressionNode * right)
Definition at line 380 of file operators.cpp.
References NumericOperator::NumericOperator().
Referenced by Parser::ParseFactor().
                                                                      :
    NumericOperator(left, right) { }
Member Function Documentation
Number * DivisionNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 388 of file operators.cpp.
References Number::Div(), ExpressionNode::Evaluate(), NumericOperator::left, ExpressionNode::result, and NumericOperator::right.
{
    result = left->Evaluate()->Div(right->Evaluate());
    return result;
}
char * DivisionNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 394 of file operators.cpp.
{
    return (char*)"/";
}
int DivisionNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 383 of file operators.cpp.
{
    return 3;
}
Author
Generated automatically by Doxygen for amath from the source code.