.TH "lib/dconv/dmath.cpp" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/dconv/dmath.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'dstandard\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtU32\fP \fBLogBase2\fP (\fBtU32\fP val)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBtU32\fP LogBase2 (\fBtU32\fP val)"

.PP
Definition at line 59 of file dmath\&.cpp\&.
.PP
Referenced by Dragon4(), LogBase2(), and PrintFloat32()\&.
.PP
.nf
60 {
61     static const tU8 logTable[256] =
62     {
63         0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
64         4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
65         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
66         5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
67         6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
68         6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
69         6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
70         6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
71         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
72         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
73         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
74         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
75         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
76         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
77         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
78         7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7
79     };
80 
81     tU32 temp;
82 
83     temp = val >> 24;
84     if (temp)
85         return 24 + logTable[temp];
86 
87     temp = val >> 16;
88     if (temp)
89         return 16 + logTable[temp];
90 
91     temp = val >> 8;
92     if (temp)
93         return 8 + logTable[temp];
94 
95     return logTable[val];
96 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
