lib/dconv/dmath.h
NAME
lib/dconv/dmath.h - Math used in the Dragon4 library.
SYNOPSIS
#include 'dstandard.h'
Functions
tU32 LogBase2 (tU32 val)
tU32 LogBase2 (tU64 val)
Detailed Description
Math used in the Dragon4 library.
Definition in file dmath.h.
Function Documentation
tU32 LogBase2 (tU32 val)
Definition at line 59 of file dmath.cpp.
Referenced by Dragon4(), LogBase2(), and PrintFloat32().
{
    static const tU8 logTable[256] =
    {
        0, 0, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7
    };
    tU32 temp;
    temp = val >> 24;
    if (temp)
        return 24 + logTable[temp];
    temp = val >> 16;
    if (temp)
        return 16 + logTable[temp];
    temp = val >> 8;
    if (temp)
        return 8 + logTable[temp];
    return logTable[val];
}
tU32 LogBase2 (tU64 val) [inline]
Definition at line 73 of file dmath.h.
References LogBase2().
Referenced by PrintFloat64().
{
    tU64 temp;
    temp = val >> 32;
    if (temp)
        return 32 + LogBase2((tU32)temp);
    return LogBase2((tU32)val);
}
Author
Generated automatically by Doxygen for amath from the source code.