.TH "lib/doc.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/doc.h \- Documentation in doxygen format\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Documentation in doxygen format\&. 


.PP
Definition in file \fBdoc\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
