lib/dprint.h
NAME
lib/dprint.h - Format defitions used in the Dragon4 library.
SYNOPSIS
#include 'dstandard.h'
Enumerations
enum tPrintFloatFormat { PrintFloatFormat_Positional, PrintFloatFormat_Scientific }
Functions
tU32 PrintFloat32 (tC8 *pOutBuffer, tU32 bufferSize, tF32 value, tPrintFloatFormat format, tS32 precision, tC8 decimalPoint)
tU32 PrintFloat64 (tC8 *pOutBuffer, tU32 bufferSize, tF64 value, tPrintFloatFormat format, tS32 precision, tC8 decimalPoint)
Detailed Description
Format defitions used in the Dragon4 library.
Definition in file dprint.h.
Enumeration Type Documentation
enum tPrintFloatFormat
Enumerator
PrintFloatFormat_Positional
PrintFloatFormat_Scientific
Definition at line 70 of file dprint.h.
{
    PrintFloatFormat_Positional, // [-]ddddd.dddd
    PrintFloatFormat_Scientific, // [-]d.dddde[sign]ddd
};
Function Documentation
tU32 PrintFloat32 (tC8 * pOutBuffer, tU32 bufferSize, tF32 value, tPrintFloatFormat format, tS32 precision, tC8 decimalPoint)
Definition at line 465 of file dprint.cpp.
References FormatPositional(), FormatScientific(), tFloatUnion32::GetExponent(), tFloatUnion32::GetMantissa(), tFloatUnion32::IsNegative(), LogBase2(), tFloatUnion32::m_floatingPoint, PrintFloatFormat_Positional, PrintFloatFormat_Scientific, and PrintInfNan().
{
    if (bufferSize == 0)
        return 0;
    if (bufferSize == 1)
    {
        pOutBuffer[0] = '\0';
        return 1;
    }
    // deconstruct the floating point value
    tFloatUnion32 floatUnion;
    floatUnion.m_floatingPoint = value;
    tU32 floatExponent = floatUnion.GetExponent();
    tU32 floatMantissa = floatUnion.GetMantissa();
    // output the sign
    if (floatUnion.IsNegative())
    {
        pOutBuffer[0] = '-';
        ++pOutBuffer;
        --bufferSize;
        RJ_ASSERT(bufferSize > 0);
    }
    // if this is a special value
    if (floatExponent == 0xFF)
    {
        return PrintInfNan(pOutBuffer, bufferSize, floatMantissa, 6);
    }
    // else this is a number
    else
    {
        // factor the value into its parts
        tU32 mantissa;
        tS32 exponent;
        tU32 mantissaHighBitIdx;
        tB hasUnequalMargins;
        if (floatExponent != 0)
        {
            // normalized
            // The floating point equation is:
            // value = (1 + mantissa/2^23) * 2 ^ (exponent-127)
            // We convert the integer equation by factoring a 2^23 out of the exponent
            // value = (1 + mantissa/2^23) * 2^23 * 2 ^ (exponent-127-23)
            // value = (2^23 + mantissa) * 2 ^ (exponent-127-23)
            // Because of the implied 1 in front of the mantissa we have 24 bits of precision.
            // m = (2^23 + mantissa)
            // e = (exponent-127-23)
            mantissa = (1UL << 23) | floatMantissa;
            exponent = floatExponent - 127 - 23;
            mantissaHighBitIdx = 23;
            hasUnequalMargins = (floatExponent != 1) && (floatMantissa == 0);
        }
        else
        {
            // denormalized
            // The floating point equation is:
            // value = (mantissa/2^23) * 2 ^ (1-127)
            // We convert the integer equation by factoring a 2^23 out of the exponent
            // value = (mantissa/2^23) * 2^23 * 2 ^ (1-127-23)
            // value = mantissa * 2 ^ (1-127-23)
            // We have up to 23 bits of precision.
            // m = (mantissa)
            // e = (1-127-23)
            mantissa = floatMantissa;
            exponent = 1 - 127 - 23;
            mantissaHighBitIdx = LogBase2(mantissa);
            hasUnequalMargins = false;
        }
        // format the value
        switch (format)
        {
        case PrintFloatFormat_Positional:
            return FormatPositional( pOutBuffer,
                                        bufferSize,
                                        mantissa,
                                        exponent,
                                        mantissaHighBitIdx,
                                        hasUnequalMargins,
                                        precision,
                                        decimalPoint );
        case PrintFloatFormat_Scientific:
            return FormatScientific( pOutBuffer,
                                        bufferSize,
                                        mantissa,
                                        exponent,
                                        mantissaHighBitIdx,
                                        hasUnequalMargins,
                                        precision,
                                        decimalPoint );
        default:
            pOutBuffer[0] = '\0';
            return 0;
        }
    }
}
tU32 PrintFloat64 (tC8 * pOutBuffer, tU32 bufferSize, tF64 value, tPrintFloatFormat format, tS32 precision, tC8 decimalPoint)
Definition at line 582 of file dprint.cpp.
References FormatPositional(), FormatScientific(), tFloatUnion64::GetExponent(), tFloatUnion64::GetMantissa(), tFloatUnion64::IsNegative(), LogBase2(), tFloatUnion64::m_floatingPoint, PrintFloatFormat_Positional, PrintFloatFormat_Scientific, and PrintInfNan().
Referenced by DecimalSystem::GetRealText().
{
    if (bufferSize == 0)
        return 0;
    if (bufferSize == 1)
    {
        pOutBuffer[0] = '\0';
        return 1;
    }
    // deconstruct the floating point value
    tFloatUnion64 floatUnion;
    floatUnion.m_floatingPoint = value;
    tU32 floatExponent = floatUnion.GetExponent();
    tU64 floatMantissa = floatUnion.GetMantissa();
    // output the sign
    if (floatUnion.IsNegative())
    {
        pOutBuffer[0] = '-';
        ++pOutBuffer;
        --bufferSize;
        RJ_ASSERT(bufferSize > 0);
    }
    // if this is a special value
    if (floatExponent == 0x7FF)
    {
        return PrintInfNan(pOutBuffer, bufferSize, floatMantissa, 13);
    }
    // else this is a number
    else
    {
        // factor the value into its parts
        tU64 mantissa;
        tS32 exponent;
        tU32 mantissaHighBitIdx;
        tB hasUnequalMargins;
        if (floatExponent != 0)
        {
            // normal
            // The floating point equation is:
            // value = (1 + mantissa/2^52) * 2 ^ (exponent-1023)
            // We convert the integer equation by factoring a 2^52 out of the exponent
            // value = (1 + mantissa/2^52) * 2^52 * 2 ^ (exponent-1023-52)
            // value = (2^52 + mantissa) * 2 ^ (exponent-1023-52)
            // Because of the implied 1 in front of the mantissa we have 53 bits of precision.
            // m = (2^52 + mantissa)
            // e = (exponent-1023+1-53)
            mantissa = (1ull << 52) | floatMantissa;
            exponent = floatExponent - 1023 - 52;
            mantissaHighBitIdx = 52;
            hasUnequalMargins = (floatExponent != 1) && (floatMantissa == 0);
        }
        else
        {
            // subnormal
            // The floating point equation is:
            // value = (mantissa/2^52) * 2 ^ (1-1023)
            // We convert the integer equation by factoring a 2^52 out of the exponent
            // value = (mantissa/2^52) * 2^52 * 2 ^ (1-1023-52)
            // value = mantissa * 2 ^ (1-1023-52)
            // We have up to 52 bits of precision.
            // m = (mantissa)
            // e = (1-1023-52)
            mantissa = floatMantissa;
            exponent = 1 - 1023 - 52;
            mantissaHighBitIdx = LogBase2(mantissa);
            hasUnequalMargins = false;
        }
        // format the value
        switch (format)
        {
        case PrintFloatFormat_Positional:
            return FormatPositional( pOutBuffer,
                                        bufferSize,
                                        mantissa,
                                        exponent,
                                        mantissaHighBitIdx,
                                        hasUnequalMargins,
                                        precision,
                                        decimalPoint );
        case PrintFloatFormat_Scientific:
            return FormatScientific( pOutBuffer,
                                        bufferSize,
                                        mantissa,
                                        exponent,
                                        mantissaHighBitIdx,
                                        hasUnequalMargins,
                                        precision,
                                        decimalPoint );
        default:
            pOutBuffer[0] = '\0';
            return 0;
        }
    }
}
Author
Generated automatically by Doxygen for amath from the source code.