DrawStatement
NAME
DrawStatement -
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
DrawStatement (const char *name, const char *parameter)
~DrawStatement ()
char * Execute ()
Private Attributes
char * name
char * parameter
Additional Inherited Members
Detailed Description
Definition at line 315 of file statements.h.
Constructor & Destructor Documentation
DrawStatement::DrawStatement (const char * name, const char * parameter)
Definition at line 853 of file statements.cpp.
References AllocAndCopy(), name, and parameter.
Referenced by Parser::ParseDrawStatement().
{
    AllocAndCopy(&this->name, name);
    AllocAndCopy(&this->parameter, parameter);
}
DrawStatement::~DrawStatement ()
Definition at line 859 of file statements.cpp.
References name, and parameter.
{
    delete [] name;
    delete [] parameter;
}
Member Function Documentation
char * DrawStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 865 of file statements.cpp.
References GraphList::CreateNewWindow(), GraphWindow::DrawGraph(), Program::Functions, FunctionList::GetFunctionDef(), Program::Graphs, name, GraphWindow::OpenGraphWindow(), and parameter.
{
    UserFunction *function = Program->Functions->GetFunctionDef(name, parameter);
    if (function == NOMEM) {
        return (char*)("Function does not exists." NEWLINE);
    }
    GraphWindow *graph = Program->Graphs->CreateNewWindow();
    if (graph == NOMEM) {
        return (char*)"Graphs are not supported in this version.";
    }
    graph->OpenGraphWindow(function);
    graph->DrawGraph(function);
    return (char*)EMPTYSTRING;
}
Member Data Documentation
char* DrawStatement::name [private]
Definition at line 322 of file statements.h.
Referenced by DrawStatement(), Execute(), and ~DrawStatement().
char* DrawStatement::parameter [private]
Definition at line 323 of file statements.h.
Referenced by DrawStatement(), Execute(), and ~DrawStatement().
Author
Generated automatically by Doxygen for amath from the source code.