.TH "lib/dstandard.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/dstandard.h \- Type defitions for the Dragon4 library\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRJ_ASSERT\fP(condition)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBbool\fP \fBtB\fP"
.br
.ti -1c
.RI "typedef char \fBtC8\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBtU8\fP"
.br
.ti -1c
.RI "typedef uint16_t \fBtU16\fP"
.br
.ti -1c
.RI "typedef uint32_t \fBtU32\fP"
.br
.ti -1c
.RI "typedef uint64_t \fBtU64\fP"
.br
.ti -1c
.RI "typedef int8_t \fBtS8\fP"
.br
.ti -1c
.RI "typedef int16_t \fBtS16\fP"
.br
.ti -1c
.RI "typedef int32_t \fBtS32\fP"
.br
.ti -1c
.RI "typedef int64_t \fBtS64\fP"
.br
.ti -1c
.RI "typedef float \fBtF32\fP"
.br
.ti -1c
.RI "typedef double \fBtF64\fP"
.br
.ti -1c
.RI "typedef size_t \fBtSize\fP"
.br
.ti -1c
.RI "typedef ptrdiff_t \fBtPtrDiff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Type defitions for the Dragon4 library\&. 


.PP
Definition in file \fBdstandard\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define RJ_ASSERT(condition)"

.PP
Definition at line 63 of file dstandard\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBbool\fP \fBtB\fP"

.PP
Definition at line 70 of file dstandard\&.h\&.
.SS "typedef char \fBtC8\fP"

.PP
Definition at line 73 of file dstandard\&.h\&.
.SS "typedef float \fBtF32\fP"

.PP
Definition at line 88 of file dstandard\&.h\&.
.SS "typedef double \fBtF64\fP"

.PP
Definition at line 89 of file dstandard\&.h\&.
.SS "typedef ptrdiff_t \fBtPtrDiff\fP"

.PP
Definition at line 93 of file dstandard\&.h\&.
.SS "typedef int16_t \fBtS16\fP"

.PP
Definition at line 83 of file dstandard\&.h\&.
.SS "typedef int32_t \fBtS32\fP"

.PP
Definition at line 84 of file dstandard\&.h\&.
.SS "typedef int64_t \fBtS64\fP"

.PP
Definition at line 85 of file dstandard\&.h\&.
.SS "typedef int8_t \fBtS8\fP"

.PP
Definition at line 82 of file dstandard\&.h\&.
.SS "typedef size_t \fBtSize\fP"

.PP
Definition at line 92 of file dstandard\&.h\&.
.SS "typedef uint16_t \fBtU16\fP"

.PP
Definition at line 77 of file dstandard\&.h\&.
.SS "typedef uint32_t \fBtU32\fP"

.PP
Definition at line 78 of file dstandard\&.h\&.
.SS "typedef uint64_t \fBtU64\fP"

.PP
Definition at line 79 of file dstandard\&.h\&.
.SS "typedef uint8_t \fBtU8\fP"

.PP
Definition at line 76 of file dstandard\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
