ErrorNode
NAME
ErrorNode - Represents an error message encapsulated in a syntax tree.
SYNOPSIS
#include <nodes.h>
Inherits SyntaxNode.
Public Member Functions
ErrorNode (const char *input, int pos)
ErrorNode (const char *input, const char *message, const char *parameter, int pos)
virtual ~ErrorNode ()
NodeType GetNodeType ()
SyntaxNode * GetNext ()
char * GetTextCode ()
char * Execute ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Private Member Functions
void StrCopyVisible (char *destination, const char *source)
Private Attributes
char * message
char * input
int pos
Additional Inherited Members
Detailed Description
Represents an error message encapsulated in a syntax tree.
Definition at line 129 of file nodes.h.
Constructor & Destructor Documentation
ErrorNode::ErrorNode (const char * input, int pos)
Definition at line 170 of file nodes.cpp.
References AllocAndCopy(), input, message, pos, StrCopyVisible(), StrLen(), and SyntaxNode::SyntaxNode().
Referenced by Parser::Parse(), and Parser::TryParseStatement().
                                               :
    SyntaxNode(), pos(pos) {
    char *temp = HELPSYNTAX;
    this->input = new char[StrLen(input) + 1];
    StrCopyVisible(this->input, input);
    AllocAndCopy(&this->message, temp);
}
ErrorNode::ErrorNode (const char * input, const char * message, const char * parameter, int pos)
Definition at line 157 of file nodes.cpp.
References AllocAndCopy(), CharBuffer::Append(), CharBuffer::CharBuffer(), CharBuffer::EnsureSize(), CharBuffer::GetString(), input, message, pos, StrCopyVisible(), StrLen(), and SyntaxNode::SyntaxNode().
Referenced by Parser::ParseDigistStatement(), Parser::ParseFileStatement(), Parser::ParseFunctionDef(), Parser::ParseIdent(), and Parser::ParseNumeralStatement().
                                                                                           :
    SyntaxNode(), pos(pos) {
    this->input = new char[StrLen(input) + 1];
    StrCopyVisible(this->input, input);
    CharBuffer *temp = new CharBuffer();
    temp->EnsureSize(StrLen(message) + StrLen(parameter) + 1);
    temp->Append(message);
    temp->Append(parameter);
    AllocAndCopy(&this->message, temp->GetString());
    delete temp;
}
ErrorNode::~ErrorNode () [virtual]
Definition at line 178 of file nodes.cpp.
References input, and message.
{
    delete [] input;
    delete [] message;
}
Member Function Documentation
void ErrorNode::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 223 of file nodes.cpp.
{ }
void ErrorNode::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 226 of file nodes.cpp.
{ }
char * ErrorNode::Execute () [virtual]
Implements SyntaxNode.
Definition at line 194 of file nodes.cpp.
References CharBuffer::Append(), CharBuffer::ClearAndAlloc(), CharBuffer::Empty(), CharBuffer::GetString(), input, message, SyntaxNode::output, pos, and StrLen().
{
    output->ClearAndAlloc(StrLen(message) + StrLen(input) + pos + 1 + StrLen(NEWLINE) * 3 + 1);
    output->Empty();
    output->Append(message);
    output->Append(NEWLINE);
    output->Append(input);
    output->Append(NEWLINE);
    output->Append(' ', pos);
    output->Append('^');
    output->Append(NEWLINE);
    return output->GetString();
}
SyntaxNode * ErrorNode::GetNext () [virtual]
Implements SyntaxNode.
Definition at line 218 of file nodes.cpp.
{
    return NOMEM;
}
NodeType ErrorNode::GetNodeType () [virtual]
Implements SyntaxNode.
Definition at line 184 of file nodes.cpp.
References othernodetype.
{
    return othernodetype;
}
char * ErrorNode::GetTextCode () [virtual]
Implements SyntaxNode.
Definition at line 189 of file nodes.cpp.
{
    return (char*)"ERRND";
}
void ErrorNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Definition at line 229 of file nodes.cpp.
{ }
void ErrorNode::StrCopyVisible (char * destination, const char * source) [private]
Definition at line 209 of file nodes.cpp.
Referenced by ErrorNode().
{
    while (*source != '\0' && *source >= 32 && *source <= 126) {
        *destination++ = *source++;
    }
    *destination = '\0';
}
Member Data Documentation
char* ErrorNode::input [private]
Definition at line 146 of file nodes.h.
Referenced by ErrorNode(), Execute(), and ~ErrorNode().
char* ErrorNode::message [private]
Definition at line 145 of file nodes.h.
Referenced by ErrorNode(), Execute(), and ~ErrorNode().
int ErrorNode::pos [private]
Definition at line 147 of file nodes.h.
Referenced by ErrorNode(), and Execute().
Author
Generated automatically by Doxygen for amath from the source code.