EulersNumberNode
NAME
EulersNumberNode - Use of Eulers number in a syntax tree.
SYNOPSIS
#include <values.h>
Inherits NumericValueNode.
Public Member Functions
EulersNumberNode ()
ReductionType GetReductionType ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Use of Eulers number in a syntax tree.
Definition at line 165 of file values.h.
Constructor & Destructor Documentation
EulersNumberNode::EulersNumberNode ()
Definition at line 400 of file values.cpp.
References NumericValueNode::NumericValueNode(), and RealNumber::RealNumber().
Referenced by Parser::ParseAtomic().
                                   :
    NumericValueNode(new RealNumber(EULERS)) { }
Member Function Documentation
char * EulersNumberNode::GetNodeText () [protected], [virtual]
Reimplemented from NumericValueNode.
Definition at line 408 of file values.cpp.
{
    return (char*)"e";
}
ReductionType EulersNumberNode::GetReductionType () [virtual]
Reimplemented from NumericValueNode.
Definition at line 403 of file values.cpp.
References nonereduc.
{
    return nonereduc;
}
Author
Generated automatically by Doxygen for amath from the source code.