.TH "app/main/evaluator.cpp" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/evaluator.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'main/parser\&.h'\fP
.br
\fC#include 'main/viewer\&.h'\fP
.br
\fC#include 'main/optimizer\&.h'\fP
.br
\fC#include 'main/evaluator\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
