.TH "Evaluator" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Evaluator \- TODO: Comment\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <evaluator\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvaluator\fP (const char *\fBinput\fP)"
.br
.ti -1c
.RI "\fB~Evaluator\fP ()"
.br
.ti -1c
.RI "void \fBEvaluate\fP ()"
.br
.ti -1c
.RI "char * \fBGetResult\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "const char * \fBinput\fP"
.br
.ti -1c
.RI "\fBCharBuffer\fP * \fBoutput\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TODO: Comment\&. 
.PP
Definition at line 43 of file evaluator\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Evaluator::Evaluator (const char * input)"

.PP
Definition at line 33 of file evaluator\&.cpp\&.
.PP
References CharBuffer::CharBuffer(), input, and output\&.
.PP
Referenced by StandardProgram::Run(), and StandardConsole::Run()\&.
.PP
.nf
34 {
35     this->input = input;
36     output = new CharBuffer();
37 }
.fi
.SS "Evaluator::~Evaluator ()"

.PP
Definition at line 39 of file evaluator\&.cpp\&.
.PP
References output\&.
.PP
.nf
40 {
41     if (output != NOMEM) {
42         delete output;
43     }
44 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void Evaluator::Evaluate ()"

.PP
Definition at line 46 of file evaluator\&.cpp\&.
.PP
References CharBuffer::ClearAndCopy(), CharBuffer::ClearBuffer(), SyntaxNode::Execute(), Optimizer::GetRoot(), input, Optimizer::Optimize(), Optimizer::Optimizer(), output, Parser::Parse(), and Parser::Parser()\&.
.PP
Referenced by StandardProgram::Run(), and StandardConsole::Run()\&.
.PP
.nf
47 {
48     output->ClearBuffer();
49 
50     Parser* parser = new Parser(input);
51     SyntaxNode* node = parser->Parse();
52     delete parser;
53 
54 #ifdef DEBUGTREE
55     Viewer *viewer = new Viewer(node);
56     const char *vout = viewer->GetTree();
57     output->EnsureGrowth(StrLen(vout));
58     output->Append(vout);
59     delete viewer;
60 #endif
61 
62     Optimizer* optimizer = new Optimizer(node);
63     optimizer->Optimize();
64     node = optimizer->GetRoot();
65     delete optimizer;
66 
67 #ifdef DEBUGTREE
68     viewer = new Viewer(node);
69     vout = viewer->GetTree();
70     output->EnsureGrowth(StrLen(vout));
71     output->Append(vout);
72     delete viewer;
73 
74     const char *out = node->Execute();
75     output->EnsureGrowth(StrLen(out));
76     output->Append(out);
77 #endif
78 
79 #ifndef DEBUGTREE
80     const char *out = node->Execute();
81     output->ClearAndCopy(out);
82 #endif
83 
84     delete node;
85 }
.fi
.SS "char * Evaluator::GetResult ()"

.PP
Definition at line 87 of file evaluator\&.cpp\&.
.PP
References CharBuffer::GetString(), and output\&.
.PP
Referenced by StandardProgram::Run(), and StandardConsole::Run()\&.
.PP
.nf
88 {
89     return output->GetString();
90 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "const char* Evaluator::input\fC [private]\fP"

.PP
Definition at line 51 of file evaluator\&.h\&.
.PP
Referenced by Evaluate(), and Evaluator()\&.
.SS "\fBCharBuffer\fP* Evaluator::output\fC [private]\fP"

.PP
Definition at line 52 of file evaluator\&.h\&.
.PP
Referenced by Evaluate(), Evaluator(), GetResult(), and ~Evaluator()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
