Evaluator
NAME
Evaluator - TODO: Comment.
SYNOPSIS
#include <evaluator.h>
Public Member Functions
Evaluator (const char *input)
~Evaluator ()
void Evaluate ()
char * GetResult ()
Private Attributes
const char * input
CharBuffer * output
Detailed Description
TODO: Comment.
Definition at line 43 of file evaluator.h.
Constructor & Destructor Documentation
Evaluator::Evaluator (const char * input)
Definition at line 33 of file evaluator.cpp.
References CharBuffer::CharBuffer(), input, and output.
Referenced by StandardProgram::Run(), and StandardConsole::Run().
{
    this->input = input;
    output = new CharBuffer();
}
Evaluator::~Evaluator ()
Definition at line 39 of file evaluator.cpp.
References output.
{
    if (output != NOMEM) {
        delete output;
    }
}
Member Function Documentation
void Evaluator::Evaluate ()
Definition at line 46 of file evaluator.cpp.
References CharBuffer::ClearAndCopy(), CharBuffer::ClearBuffer(), SyntaxNode::Execute(), Optimizer::GetRoot(), input, Optimizer::Optimize(), Optimizer::Optimizer(), output, Parser::Parse(), and Parser::Parser().
Referenced by StandardProgram::Run(), and StandardConsole::Run().
{
    output->ClearBuffer();
    Parser* parser = new Parser(input);
    SyntaxNode* node = parser->Parse();
    delete parser;
#ifdef DEBUGTREE
    Viewer *viewer = new Viewer(node);
    const char *vout = viewer->GetTree();
    output->EnsureGrowth(StrLen(vout));
    output->Append(vout);
    delete viewer;
#endif
    Optimizer* optimizer = new Optimizer(node);
    optimizer->Optimize();
    node = optimizer->GetRoot();
    delete optimizer;
#ifdef DEBUGTREE
    viewer = new Viewer(node);
    vout = viewer->GetTree();
    output->EnsureGrowth(StrLen(vout));
    output->Append(vout);
    delete viewer;
    const char *out = node->Execute();
    output->EnsureGrowth(StrLen(out));
    output->Append(out);
#endif
#ifndef DEBUGTREE
    const char *out = node->Execute();
    output->ClearAndCopy(out);
#endif
    delete node;
}
char * Evaluator::GetResult ()
Definition at line 87 of file evaluator.cpp.
References CharBuffer::GetString(), and output.
Referenced by StandardProgram::Run(), and StandardConsole::Run().
{
    return output->GetString();
}
Member Data Documentation
const char* Evaluator::input [private]
Definition at line 51 of file evaluator.h.
Referenced by Evaluate(), and Evaluator().
CharBuffer* Evaluator::output [private]
Definition at line 52 of file evaluator.h.
Referenced by Evaluate(), Evaluator(), GetResult(), and ~Evaluator().
Author
Generated automatically by Doxygen for amath from the source code.