.TH "app/main/evaluator.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/evaluator.h \- TODO: Comment\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lib/charbuf\&.h'\fP
.br
\fC#include 'main/token\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEvaluator\fP"
.br
.RI "\fITODO: Comment\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
TODO: Comment\&. 


.PP
Definition in file \fBevaluator\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
