EvalStatement
NAME
EvalStatement - Evaluate arithmetic expression.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
EvalStatement (ExpressionNode *expression)
~EvalStatement ()
char * Execute ()
SyntaxNode * GetNext ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Private Attributes
ExpressionNode * expression
Additional Inherited Members
Detailed Description
Evaluate arithmetic expression.
Definition at line 155 of file statements.h.
Constructor & Destructor Documentation
EvalStatement::EvalStatement (ExpressionNode * expression)
Definition at line 251 of file statements.cpp.
References expression, and StatementNode::StatementNode().
Referenced by Parser::ParseEvaluation(), and Parser::ParseStatement().
                                                       :
    StatementNode(), expression(expression) { }
EvalStatement::~EvalStatement ()
Definition at line 254 of file statements.cpp.
References expression.
{
    if (expression != NOMEM) {
        delete expression;
    }
}
Member Function Documentation
void EvalStatement::Attach (SyntaxNode * node) [virtual]
Reimplemented from StatementNode.
Definition at line 292 of file statements.cpp.
References expression, and SyntaxNode::SetParent().
{
    if (expression == NOMEM) {
        expression = (ExpressionNode*)node;
        node->SetParent(this);
    }
}
void EvalStatement::Detach (SyntaxNode * node) [virtual]
Reimplemented from StatementNode.
Definition at line 300 of file statements.cpp.
References expression.
{
    if (expression == node) {
        expression = NOMEM;
    }
}
char * EvalStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 261 of file statements.cpp.
References CharBuffer::Append(), CharBuffer::Empty(), CharBuffer::EnsureSize(), ExpressionNode::Evaluate(), expression, CharBuffer::GetString(), NumeralSystem::GetText(), ExpressionNode::GetText(), Program::Output, SyntaxNode::output, Program::SetLastResult(), and StrLen().
{
    Number* result = expression->Evaluate();
    Program->SetLastResult(result);
    const char *text = expression->GetText();
    const char *val = Program->Output->GetText(result);
    output->Empty();
    output->EnsureSize(
        StrLen(text) + 3 +
        StrLen(val) +
        StrLen(NEWLINE) + 1);
    output->Append(text);
    output->Append(" = ");
    output->Append(val);
    output->Append(NEWLINE);
    return output->GetString();
}
SyntaxNode * EvalStatement::GetNext () [virtual]
Reimplemented from StatementNode.
Definition at line 282 of file statements.cpp.
References expression, and SyntaxNode::iterator.
{
    if (iterator == NOMEM) {
        iterator = expression;
        return iterator;
    }
    return NOMEM;
}
void EvalStatement::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Reimplemented from StatementNode.
Definition at line 307 of file statements.cpp.
References expression.
{
    if (expression == n) {
        delete expression;
        expression = (ExpressionNode*)x;
    }
}
Member Data Documentation
ExpressionNode* EvalStatement::expression [private]
Definition at line 167 of file statements.h.
Referenced by Attach(), Detach(), EvalStatement(), Execute(), GetNext(), Replace(), and ~EvalStatement().
Author
Generated automatically by Doxygen for amath from the source code.