.TH "ExecuteStatement" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExecuteStatement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statements\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExecuteStatement\fP (const char *\fBfile\fP)"
.br
.ti -1c
.RI "\fB~ExecuteStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "char * \fBfile\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 292 of file statements\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExecuteStatement::ExecuteStatement (const char * file)"

.PP
Definition at line 721 of file statements\&.cpp\&.
.PP
References AllocAndCopy(), and file\&.
.PP
Referenced by Parser::ParseFileStatement()\&.
.PP
.nf
722 {
723     AllocAndCopy(&this->file, file);
724 }
.fi
.SS "ExecuteStatement::~ExecuteStatement ()"

.PP
Definition at line 726 of file statements\&.cpp\&.
.PP
References file\&.
.PP
.nf
727 {
728     delete [] file;
729 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * ExecuteStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 731 of file statements\&.cpp\&.
.PP
References CharBuffer::ClearAndCopy(), SyntaxNode::Execute(), file, Program::Filesystem, CharBuffer::GetString(), FilesystemBase::LoadTextFile(), SyntaxNode::output, Parser::Parse(), and Parser::Parser()\&.
.PP
.nf
732 {
733     CharBuffer *input = Program->Filesystem->LoadTextFile(file);
734     if (input == NOMEM)
735     {
736         return (char*)(MSGNOFILE);
737     }
738 
739     Parser *parser = new Parser(input->GetString());
740     delete input;
741 
742     SyntaxNode *node = parser->Parse();
743     delete parser;
744 
745     const char *res = node->Execute();
746     output->ClearAndCopy(res);
747     delete node;
748 
749     return output->GetString();
750 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "char* ExecuteStatement::file\fC [private]\fP"

.PP
Definition at line 299 of file statements\&.h\&.
.PP
Referenced by Execute(), ExecuteStatement(), and ~ExecuteStatement()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
