ExecuteStatement
NAME
ExecuteStatement -
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
ExecuteStatement (const char *file)
~ExecuteStatement ()
char * Execute ()
Private Attributes
char * file
Additional Inherited Members
Detailed Description
Definition at line 292 of file statements.h.
Constructor & Destructor Documentation
ExecuteStatement::ExecuteStatement (const char * file)
Definition at line 721 of file statements.cpp.
References AllocAndCopy(), and file.
Referenced by Parser::ParseFileStatement().
{
    AllocAndCopy(&this->file, file);
}
ExecuteStatement::~ExecuteStatement ()
Definition at line 726 of file statements.cpp.
References file.
{
    delete [] file;
}
Member Function Documentation
char * ExecuteStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 731 of file statements.cpp.
References CharBuffer::ClearAndCopy(), SyntaxNode::Execute(), file, Program::Filesystem, CharBuffer::GetString(), FilesystemBase::LoadTextFile(), SyntaxNode::output, Parser::Parse(), and Parser::Parser().
{
    CharBuffer *input = Program->Filesystem->LoadTextFile(file);
    if (input == NOMEM)
    {
        return (char*)(MSGNOFILE);
    }
    Parser *parser = new Parser(input->GetString());
    delete input;
    SyntaxNode *node = parser->Parse();
    delete parser;
    const char *res = node->Execute();
    output->ClearAndCopy(res);
    delete node;
    return output->GetString();
}
Member Data Documentation
char* ExecuteStatement::file [private]
Definition at line 299 of file statements.h.
Referenced by Execute(), ExecuteStatement(), and ~ExecuteStatement().
Author
Generated automatically by Doxygen for amath from the source code.