.TH "ExitStatement" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExitStatement \- Exit program\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statements\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExitStatement\fP ()"
.br
.ti -1c
.RI "\fB~ExitStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Exit program\&. 
.PP
Definition at line 58 of file statements\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ExitStatement::ExitStatement ()\fC [inline]\fP"

.PP
Definition at line 60 of file statements\&.h\&.
.PP
Referenced by Parser::ParseStatement()\&.
.PP
.nf
60 { }
.fi
.SS "ExitStatement::~ExitStatement ()\fC [inline]\fP"

.PP
Definition at line 61 of file statements\&.h\&.
.PP
.nf
61 { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * ExitStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 54 of file statements\&.cpp\&.
.PP
References Program::Exit()\&.
.PP
.nf
55 {
56     Program->Exit();
57     return (char*)EMPTYSTRING;
58 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
