ExpressionNode
NAME
ExpressionNode - Base class for all nodes related to mathematical expressions.
SYNOPSIS
#include <nodes.h>
Inherits SyntaxNode.
Inherited by AbsoluteNode [virtual], FunctionNode, NumericOperator [virtual], NumericValueNode, UnaryNode [virtual], and VariableNode.
Public Member Functions
ExpressionNode ()
ExpressionNode (Number *value)
virtual ~ExpressionNode ()
NodeType GetNodeType ()
virtual bool IsSilent ()
virtual char * GetText ()=0
virtual Number * Evaluate ()=0
virtual int GetPrecedence ()=0
char * GetTextCode ()
char * Execute ()
Protected Member Functions
virtual char * GetNodeText ()=0
Protected Attributes
Number * result
Detailed Description
Base class for all nodes related to mathematical expressions.
Nodes of this type is used to build trees representing an mathematical expressions. Each node in the tree consist of a number, an operator or any other element in an expression.
Definition at line 88 of file nodes.h.
Constructor & Destructor Documentation
ExpressionNode::ExpressionNode ()
Definition at line 116 of file nodes.cpp.
References result, and SyntaxNode::SyntaxNode().
Referenced by AbsoluteNode::AbsoluteNode(), FunctionNode::FunctionNode(), NumericOperator::NumericOperator(), UnaryNode::UnaryNode(), and VariableNode::VariableNode().
                               :
    SyntaxNode() {
    result = NOMEM;
}
ExpressionNode::ExpressionNode (Number * value)
Definition at line 121 of file nodes.cpp.
References result, and SyntaxNode::SyntaxNode().
Referenced by NumericValueNode::NumericValueNode().
                                            :
    SyntaxNode() {
    result = value;
}
ExpressionNode::~ExpressionNode () [virtual]
Definition at line 126 of file nodes.cpp.
References result.
{
    if (result != NOMEM) {
        delete result;
    }
}
Member Function Documentation
virtual Number* ExpressionNode::Evaluate () [pure virtual]
Implemented in HyperbolicArcSecantNode, HyperbolicArcCosecantNode, HyperbolicArcCotangentNode, HyperbolicArctangentNode, HyperbolicArcsineNode, HyperbolicArccosineNode, HyperbolicCosecantNode, HyperbolicSecantNode, HyperbolicCotangentNode, HyperbolicTangentNode, HyperbolicCosineNode, HyperbolicSineNode, ArcSecantNode, ArcCosecantNode, ArcCotangentNode, ArcTangentNode, ArcCosineNode, ArcSineNode, SecantNode, CosecantNode, CotangentNode, TangentNode, CosineNode, SineNode, BinaryLogNode, LnRootNode, LogNode, CubeRootNode, SquareRootNode, CeilingNode, FloorNode, TruncNode, RoundNode, SignumNode, AbsoluteFunctionNode, UserFunctionNode, AssignmentNode, NumericValueNode, PowerNode, InsVariableNode, DivisionNode, MultiplicationNode, SubtractionNode, VariableNode, AdditionNode, AbsoluteNode, and UnaryNode.
Referenced by UnaryNode::Evaluate(), AbsoluteNode::Evaluate(), AdditionNode::Evaluate(), SubtractionNode::Evaluate(), MultiplicationNode::Evaluate(), DivisionNode::Evaluate(), PowerNode::Evaluate(), AssignmentNode::Evaluate(), UserFunctionNode::Evaluate(), AbsoluteFunctionNode::Evaluate(), SignumNode::Evaluate(), RoundNode::Evaluate(), TruncNode::Evaluate(), FloorNode::Evaluate(), CeilingNode::Evaluate(), SquareRootNode::Evaluate(), CubeRootNode::Evaluate(), LogNode::Evaluate(), LnRootNode::Evaluate(), BinaryLogNode::Evaluate(), SineNode::Evaluate(), CosineNode::Evaluate(), TangentNode::Evaluate(), CotangentNode::Evaluate(), CosecantNode::Evaluate(), SecantNode::Evaluate(), ArcSineNode::Evaluate(), ArcCosineNode::Evaluate(), ArcTangentNode::Evaluate(), ArcCotangentNode::Evaluate(), ArcCosecantNode::Evaluate(), ArcSecantNode::Evaluate(), HyperbolicSineNode::Evaluate(), HyperbolicCosineNode::Evaluate(), HyperbolicTangentNode::Evaluate(), HyperbolicCotangentNode::Evaluate(), HyperbolicSecantNode::Evaluate(), HyperbolicCosecantNode::Evaluate(), HyperbolicArccosineNode::Evaluate(), HyperbolicArcsineNode::Evaluate(), HyperbolicArctangentNode::Evaluate(), HyperbolicArcCotangentNode::Evaluate(), HyperbolicArcCosecantNode::Evaluate(), HyperbolicArcSecantNode::Evaluate(), EvalStatement::Execute(), and Grid::FunctionValue().
char * ExpressionNode::Execute () [virtual]
Implements SyntaxNode.
Definition at line 148 of file nodes.cpp.
{
    return NOMEM;
}
virtual char* ExpressionNode::GetNodeText () [protected], [pure virtual]
Implemented in HyperbolicArcSecantNode, HyperbolicArcCosecantNode, HyperbolicArcCotangentNode, HyperbolicArctangentNode, HyperbolicArcsineNode, HyperbolicArccosineNode, HyperbolicCosecantNode, HyperbolicSecantNode, HyperbolicCotangentNode, HyperbolicTangentNode, HyperbolicCosineNode, HyperbolicSineNode, ArcSecantNode, ArcCosecantNode, ArcCotangentNode, ArcTangentNode, ArcCosineNode, ArcSineNode, SecantNode, CosecantNode, CotangentNode, TangentNode, CosineNode, SineNode, BinaryLogNode, LnRootNode, LogNode, CubeRootNode, SquareRootNode, CeilingNode, FloorNode, TruncNode, RoundNode, SignumNode, ComplexiNode, AbsoluteFunctionNode, PiNode, EulersNumberNode, UserFunctionNode, NumericValueNode, AssignmentNode, PowerNode, InsVariableNode, DivisionNode, MultiplicationNode, VariableNode, SubtractionNode, AdditionNode, AbsoluteNode, and UnaryNode.
Referenced by FunctionNode::GetText(), NumericOperator::GetText(), and GetTextCode().
NodeType ExpressionNode::GetNodeType () [virtual]
Implements SyntaxNode.
Definition at line 133 of file nodes.cpp.
References expression.
{
    return expression;
}
virtual int ExpressionNode::GetPrecedence () [pure virtual]
Implemented in AssignmentNode, NumericValueNode, PowerNode, DivisionNode, MultiplicationNode, SubtractionNode, VariableNode, AdditionNode, AbsoluteNode, FunctionNode, and UnaryNode.
Referenced by Optimizer::BalanceTree(), UnaryNode::GetText(), and NumericOperator::GetText().
virtual char* ExpressionNode::GetText () [pure virtual]
Implemented in NumericValueNode, InsVariableNode, VariableNode, NumericOperator, AbsoluteNode, FunctionNode, and UnaryNode.
Referenced by EvalStatement::Execute(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), NumericOperator::GetText(), UserFunction::InitializeTexts(), and FunctionList::ListContent().
char * ExpressionNode::GetTextCode () [virtual]
Implements SyntaxNode.
Definition at line 143 of file nodes.cpp.
References GetNodeText().
{
    return GetNodeText();
}
bool ExpressionNode::IsSilent () [virtual]
Reimplemented in AssignmentNode.
Definition at line 138 of file nodes.cpp.
Referenced by Parser::ParseEvaluation().
{
    return false;
}
Member Data Documentation
Number* ExpressionNode::result [protected]
Definition at line 104 of file nodes.h.
Referenced by UnaryNode::Evaluate(), AbsoluteNode::Evaluate(), AdditionNode::Evaluate(), VariableNode::Evaluate(), SubtractionNode::Evaluate(), MultiplicationNode::Evaluate(), DivisionNode::Evaluate(), PowerNode::Evaluate(), NumericValueNode::Evaluate(), AbsoluteFunctionNode::Evaluate(), SignumNode::Evaluate(), RoundNode::Evaluate(), TruncNode::Evaluate(), FloorNode::Evaluate(), CeilingNode::Evaluate(), SquareRootNode::Evaluate(), CubeRootNode::Evaluate(), LogNode::Evaluate(), LnRootNode::Evaluate(), BinaryLogNode::Evaluate(), SineNode::Evaluate(), CosineNode::Evaluate(), TangentNode::Evaluate(), CotangentNode::Evaluate(), CosecantNode::Evaluate(), SecantNode::Evaluate(), ArcSineNode::Evaluate(), ArcCosineNode::Evaluate(), ArcTangentNode::Evaluate(), ArcCotangentNode::Evaluate(), ArcCosecantNode::Evaluate(), ArcSecantNode::Evaluate(), HyperbolicSineNode::Evaluate(), HyperbolicCosineNode::Evaluate(), HyperbolicTangentNode::Evaluate(), HyperbolicCotangentNode::Evaluate(), HyperbolicSecantNode::Evaluate(), HyperbolicCosecantNode::Evaluate(), HyperbolicArccosineNode::Evaluate(), HyperbolicArcsineNode::Evaluate(), HyperbolicArctangentNode::Evaluate(), HyperbolicArcCotangentNode::Evaluate(), HyperbolicArcCosecantNode::Evaluate(), HyperbolicArcSecantNode::Evaluate(), ExpressionNode(), NumericValueNode::GetNodeText(), NumericValueNode::GetPrecedence(), NumericValueNode::ReplaceWith(), and ~ExpressionNode().
Author
Generated automatically by Doxygen for amath from the source code.