.TH "app/lib/fgrid.h" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/fgrid.h \- Function grid used with graphs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lib/real\&.h'\fP
.br
\fC#include 'main/functions\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGrid\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function grid used with graphs\&. 


.PP
Definition in file \fBfgrid\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
