.TH "app/system/filesystem_stdc.cpp" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/filesystem_stdc.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br
\fC#include 'localize/text\&.h'\fP
.br
\fC#include 'system/program\&.h'\fP
.br
\fC#include 'system/filesystem\&.h'\fP
.br
\fC#include 'system/filesystem_stdc\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
