.TH "app/system/filesystem.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/filesystem.h \- Generic file system calls\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lib/charbuf\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFilesystemBase\fP"
.br
.RI "\fIAbstract base class encapsulating file system calls\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Generic file system calls\&. 


.PP
Definition in file \fBfilesystem\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
