FilesystemBase
NAME
FilesystemBase - Abstract base class encapsulating file system calls.
SYNOPSIS
#include <filesystem.h>
Inherited by StandardFilesystem.
Public Member Functions
virtual ~FilesystemBase ()
virtual CharBuffer * ListDirectory (const char *path)=0
virtual CharBuffer * LoadTextFile (const char *name)=0
virtual bool SaveTextFile (const char *name, const char *text)=0
Detailed Description
Abstract base class encapsulating file system calls.
Definition at line 42 of file filesystem.h.
Constructor & Destructor Documentation
virtual FilesystemBase::~FilesystemBase () [inline], [virtual]
Definition at line 44 of file filesystem.h.
{ }
Member Function Documentation
virtual CharBuffer* FilesystemBase::ListDirectory (const char * path) [pure virtual]
Implemented in StandardFilesystem.
Referenced by ListStatement::Execute().
virtual CharBuffer* FilesystemBase::LoadTextFile (const char * name) [pure virtual]
Implemented in StandardFilesystem.
Referenced by ShowStatement::Execute(), LoadStatement::Execute(), ExecuteStatement::Execute(), and StandardLanguage::LoadCatalog().
virtual bool FilesystemBase::SaveTextFile (const char * name, const char * text) [pure virtual]
Implemented in StandardFilesystem.
Referenced by SaveStatement::Execute().
Author
Generated automatically by Doxygen for amath from the source code.