FloorNode
NAME
FloorNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
FloorNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 250 of file functions.h.
Constructor & Destructor Documentation
FloorNode::FloorNode (ExpressionNode * expression)
Definition at line 583 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                               :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * FloorNode::Create (ExpressionNode * expression) [static]
Definition at line 586 of file functions.cpp.
References FloorNode().
{
    return new FloorNode(expression);
}
Number * FloorNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 591 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::Floor(), and ExpressionNode::result.
{
    result = expression->Evaluate()->Floor();
    return result;
}
char * FloorNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 597 of file functions.cpp.
{
    return (char*)"floor";
}
Author
Generated automatically by Doxygen for amath from the source code.