FunctionNode
NAME
FunctionNode - Represents a mathematical function in a syntax tree.
SYNOPSIS
#include <functions.h>
Inherits ExpressionNode.
Inherited by AbsoluteFunctionNode, ArcCosecantNode, ArcCosineNode, ArcCotangentNode, ArcSecantNode, ArcSineNode, ArcTangentNode, BinaryLogNode, CeilingNode, CosecantNode, CosineNode, CotangentNode, CubeRootNode, FloorNode, HyperbolicArcCosecantNode, HyperbolicArccosineNode, HyperbolicArcCotangentNode, HyperbolicArcSecantNode, HyperbolicArcsineNode, HyperbolicArctangentNode, HyperbolicCosecantNode, HyperbolicCosineNode, HyperbolicCotangentNode, HyperbolicSecantNode, HyperbolicSineNode, HyperbolicTangentNode, LnRootNode, LogNode, RoundNode, SecantNode, SignumNode, SineNode, SquareRootNode, TangentNode, TruncNode, and UserFunctionNode.
Public Member Functions
FunctionNode (ExpressionNode *expression)
~FunctionNode ()
int GetPrecedence ()
char * GetText ()
virtual SyntaxNode * GetNext ()
virtual void Attach (SyntaxNode *node)
virtual void Detach (SyntaxNode *node)
virtual void Replace (SyntaxNode *n, SyntaxNode *x)
Protected Attributes
ExpressionNode * expression
Additional Inherited Members
Detailed Description
Represents a mathematical function in a syntax tree.
Function nodes in syntax trees can both be well known functions like cosine (cos) and also user defined functions. The function node represents a function call and not a function definition.
A formal description of mathematical functions can be found at Wikipedia: http://en.wikipedia.org/wiki/Function_(mathematics)
When instantiating a function node an argument must be supplied. The argument is a pointer to an expression node representing the value which should be used when computing the function value.
Definition at line 55 of file functions.h.
Constructor & Destructor Documentation
FunctionNode::FunctionNode (ExpressionNode * expression)
Definition at line 39 of file functions.cpp.
References expression, and ExpressionNode::ExpressionNode().
Referenced by AbsoluteFunctionNode::AbsoluteFunctionNode(), ArcCosecantNode::ArcCosecantNode(), ArcCosineNode::ArcCosineNode(), ArcCotangentNode::ArcCotangentNode(), ArcSecantNode::ArcSecantNode(), ArcSineNode::ArcSineNode(), ArcTangentNode::ArcTangentNode(), BinaryLogNode::BinaryLogNode(), CeilingNode::CeilingNode(), CosecantNode::CosecantNode(), CosineNode::CosineNode(), CotangentNode::CotangentNode(), CubeRootNode::CubeRootNode(), FloorNode::FloorNode(), HyperbolicArcCosecantNode::HyperbolicArcCosecantNode(), HyperbolicArccosineNode::HyperbolicArccosineNode(), HyperbolicArcCotangentNode::HyperbolicArcCotangentNode(), HyperbolicArcSecantNode::HyperbolicArcSecantNode(), HyperbolicArcsineNode::HyperbolicArcsineNode(), HyperbolicArctangentNode::HyperbolicArctangentNode(), HyperbolicCosecantNode::HyperbolicCosecantNode(), HyperbolicCosineNode::HyperbolicCosineNode(), HyperbolicCotangentNode::HyperbolicCotangentNode(), HyperbolicSecantNode::HyperbolicSecantNode(), HyperbolicSineNode::HyperbolicSineNode(), HyperbolicTangentNode::HyperbolicTangentNode(), LnRootNode::LnRootNode(), LogNode::LogNode(), RoundNode::RoundNode(), SecantNode::SecantNode(), SignumNode::SignumNode(), SineNode::SineNode(), SquareRootNode::SquareRootNode(), TangentNode::TangentNode(), TruncNode::TruncNode(), and UserFunctionNode::UserFunctionNode().
                                                     :
    ExpressionNode(), expression(expression) { }
FunctionNode::~FunctionNode ()
Definition at line 42 of file functions.cpp.
References expression.
{
    if (expression != NOMEM) {
        delete expression;
    }
}
Member Function Documentation
void FunctionNode::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Reimplemented in UserFunctionNode.
Definition at line 79 of file functions.cpp.
References expression, and SyntaxNode::SetParent().
{
    if (expression == NOMEM) {
        expression = (ExpressionNode*)node;
        node->SetParent(this);
    }
}
void FunctionNode::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Reimplemented in UserFunctionNode.
Definition at line 87 of file functions.cpp.
References expression.
{
    if (expression == node) {
        expression = NOMEM;
    }
}
SyntaxNode * FunctionNode::GetNext () [virtual]
Implements SyntaxNode.
Reimplemented in UserFunctionNode.
Definition at line 69 of file functions.cpp.
References expression, and SyntaxNode::iterator.
{
    if (iterator == NOMEM) {
        iterator = expression;
        return expression;
    }
    return NOMEM;
}
int FunctionNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 49 of file functions.cpp.
{
    return 5;
}
char * FunctionNode::GetText () [virtual]
Implements ExpressionNode.
Definition at line 54 of file functions.cpp.
References CharBuffer::Append(), CharBuffer::Empty(), CharBuffer::EnsureSize(), expression, ExpressionNode::GetNodeText(), CharBuffer::GetString(), ExpressionNode::GetText(), SyntaxNode::output, and StrLen().
{
    const char *functionText = GetNodeText();
    const char *expText = expression->GetText();
    output->EnsureSize(StrLen(functionText) + StrLen(expText) + 2 + 1);
    output->Empty();
    output->Append(functionText);
    output->Append("(");
    output->Append(expText);
    output->Append(")");
    return output->GetString();
}
void FunctionNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Reimplemented in UserFunctionNode.
Definition at line 94 of file functions.cpp.
References expression.
{
    if (expression == n) {
        delete expression;
        expression = (ExpressionNode*)x;
    }
}
Member Data Documentation
ExpressionNode* FunctionNode::expression [protected]
Definition at line 68 of file functions.h.
Referenced by Attach(), Detach(), UserFunctionNode::Evaluate(), AbsoluteFunctionNode::Evaluate(), SignumNode::Evaluate(), RoundNode::Evaluate(), TruncNode::Evaluate(), FloorNode::Evaluate(), CeilingNode::Evaluate(), SquareRootNode::Evaluate(), CubeRootNode::Evaluate(), LogNode::Evaluate(), LnRootNode::Evaluate(), BinaryLogNode::Evaluate(), SineNode::Evaluate(), CosineNode::Evaluate(), TangentNode::Evaluate(), CotangentNode::Evaluate(), CosecantNode::Evaluate(), SecantNode::Evaluate(), ArcSineNode::Evaluate(), ArcCosineNode::Evaluate(), ArcTangentNode::Evaluate(), ArcCotangentNode::Evaluate(), ArcCosecantNode::Evaluate(), ArcSecantNode::Evaluate(), HyperbolicSineNode::Evaluate(), HyperbolicCosineNode::Evaluate(), HyperbolicTangentNode::Evaluate(), HyperbolicCotangentNode::Evaluate(), HyperbolicSecantNode::Evaluate(), HyperbolicCosecantNode::Evaluate(), HyperbolicArccosineNode::Evaluate(), HyperbolicArcsineNode::Evaluate(), HyperbolicArctangentNode::Evaluate(), HyperbolicArcCotangentNode::Evaluate(), HyperbolicArcCosecantNode::Evaluate(), HyperbolicArcSecantNode::Evaluate(), FunctionNode(), GetNext(), GetText(), Replace(), and ~FunctionNode().
Author
Generated automatically by Doxygen for amath from the source code.