FunctionList
NAME
FunctionList - A list of user defined functions.
SYNOPSIS
#include <functions.h>
Public Member Functions
FunctionList ()
~FunctionList ()
void Clear ()
bool Delete (const char *name, const char *argument)
bool IsSystemFunction (const char *name)
UserFunction * GetFirstFunction ()
UserFunction * GetFunctionDef (const char *name)
UserFunction * GetFunctionDef (const char *name, const char *argument)
FunctionNode * GetFunctionCall (const char *function, ExpressionNode *value)
char * List ()
char * ListDefinitions ()
Private Member Functions
char * ListContent (bool cmdFormat)
functiondef * GetSystemFunction (const char *ident)
Private Attributes
CharBuffer * buf
UserFunction * first
Detailed Description
A list of user defined functions.
Definition at line 78 of file functions.h.
Constructor & Destructor Documentation
FunctionList::FunctionList ()
Definition at line 279 of file functions.cpp.
References buf, CharBuffer::CharBuffer(), and first.
Referenced by Program::Program().
{
    first = NOMEM;
    buf = new CharBuffer();
}
FunctionList::~FunctionList ()
Definition at line 285 of file functions.cpp.
References buf, and first.
{
    if (first != NOMEM) {
        delete first;
    }
    delete buf;
}
Member Function Documentation
void FunctionList::Clear ()
Definition at line 294 of file functions.cpp.
References buf, CharBuffer::ClearBuffer(), and first.
Referenced by DeleteStatement::Execute().
{
    if (first != NOMEM) {
        delete first;
        first = NOMEM;
    }
    buf->ClearBuffer();
}
bool FunctionList::Delete (const char * name, const char * argument)
Definition at line 304 of file functions.cpp.
References UserFunction::chainDelete, first, Variable::GetName(), UserFunction::GetName(), UserFunction::GetVariable(), UserFunction::Next, and StrIsEqual().
Referenced by DeleteStatement::Execute().
{
    if (first == NOMEM)
    {
        return false;
    }
    if (first != NOMEM && StrIsEqual(first->GetName(), name) && StrIsEqual(first->GetVariable()->GetName(), argument)) {
        UserFunction *func = first;
        first = first->Next;
        func->chainDelete = false;
        delete func;
        return true;
    }
    UserFunction *current = first->Next;
    UserFunction *last = first;
    while (current != NOMEM && !StrIsEqual(current->GetName(), name)) {
        current = current->Next;
        last = last->Next;
    }
    if (current == NOMEM) {
        return false;
    } else if (!StrIsEqual(current->GetVariable()->GetName(), argument)) {
        return false;
    }
    last->Next = current->Next;
    // Only delete this variable. Not the whole chain.
    current->chainDelete = false;
    delete current;
    return true;
}
UserFunction * FunctionList::GetFirstFunction ()
Definition at line 342 of file functions.cpp.
References first.
{
    return first;
}
FunctionNode * FunctionList::GetFunctionCall (const char * function, ExpressionNode * value)
Definition at line 388 of file functions.cpp.
References functiondef::create, first, UserFunction::GetName(), GetSystemFunction(), UserFunction::Next, StrIsEqual(), and UserFunctionNode::UserFunctionNode().
Referenced by Parser::ParseIdent().
{
    const functiondef *systemFunction = GetSystemFunction(function);
    if (systemFunction != NOMEM) {
        return (systemFunction->create)(parameter);
    }
    UserFunction *current = first;
    while (current != NOMEM && !StrIsEqual(current->GetName(), function)) {
        current = current->Next;
    }
    if (current != NOMEM) {
        return new UserFunctionNode(current, parameter);
    }
    return NOMEM;
}
UserFunction * FunctionList::GetFunctionDef (const char * name)
Definition at line 347 of file functions.cpp.
References first, UserFunction::GetName(), UserFunction::Next, StrIsEqual(), and UserFunction::UserFunction().
Referenced by Parser::ParseFunctionDef().
{
    // Search the list for function definition. If function not found then create a new definition.
    if (first == NOMEM) {
        first = new UserFunction(name);
        return first;
    }
    UserFunction *current = first;
    UserFunction *last = NOMEM;
    while (current != NOMEM) {
        if (StrIsEqual(current->GetName(), name)) {
            return current;
        }
        last = current;
        current = current->Next;
    }
    current = new UserFunction(name);
    last->Next = current;
    return current;
}
UserFunction * FunctionList::GetFunctionDef (const char * name, const char * argument)
Definition at line 373 of file functions.cpp.
References first, Variable::GetName(), UserFunction::GetName(), UserFunction::GetVariable(), UserFunction::Next, and StrIsEqual().
Referenced by PlotStatement::Execute(), and DrawStatement::Execute().
{
    UserFunction *current = first;
    while (current != NOMEM) {
        if (StrIsEqual(current->GetName(), name) && StrIsEqual(current->GetVariable()->GetName(), argument)) {
            return current;
        }
        current = current->Next;
    }
    return NOMEM;
}
functiondef * FunctionList::GetSystemFunction (const char * ident) [private]
Definition at line 463 of file functions.cpp.
References functiondefs, functiondef::name, and StrIsEqual().
Referenced by GetFunctionCall(), and IsSystemFunction().
{
    static const unsigned int count = sizeof(functiondefs) / sizeof(functiondef);
    for (unsigned int i = 0; i < count; i++) {
        if (StrIsEqual(functiondefs[i].name, ident)) {
            return (functiondef*)&functiondefs[i];
        }
    }
    return NOMEM;
}
bool FunctionList::IsSystemFunction (const char * name)
Definition at line 458 of file functions.cpp.
References GetSystemFunction().
Referenced by Parser::ParseFunctionDef().
{
    return (GetSystemFunction(name) != NOMEM);
}
char * FunctionList::List ()
Definition at line 407 of file functions.cpp.
References ListContent().
Referenced by ListFunctionsStatement::Execute().
{
    return ListContent(false);
}
char * FunctionList::ListContent (bool cmdFormat) [private]
Definition at line 417 of file functions.cpp.
References CharBuffer::Append(), buf, CharBuffer::Empty(), CharBuffer::EnsureSize(), first, UserFunction::GetExpression(), Variable::GetName(), UserFunction::GetName(), CharBuffer::GetString(), ExpressionNode::GetText(), UserFunction::GetVariable(), UserFunction::Next, and StrLen().
Referenced by List(), and ListDefinitions().
{
    if (first == NOMEM) {
        return (char*)(cmdFormat ? NOMEM : HELPFUNCNDEF);
    }
    int len = 0;
    UserFunction *current = first;
    while (current != NOMEM) {
        len += StrLen(current->GetName());
        len += 1;
        len += StrLen(current->GetVariable()->GetName());
        len += 2;
        len += StrLen(current->GetExpression()->GetText());
        len += cmdFormat ? 2 : 1;
        current = current->Next;
    }
    buf->Empty();
    buf->EnsureSize(len + StrLen(NEWLINE) + 1);
    current = first;
    while (current != NOMEM) {
        buf->Append(current->GetName());
        buf->Append("(");
        buf->Append(current->GetVariable()->GetName());
        buf->Append(")=");
        buf->Append(current->GetExpression()->GetText());
        if (cmdFormat) {
            buf->Append(';');
        }
        buf->Append(NEWLINE);
        current = current->Next;
    }
    return buf->GetString();
}
char * FunctionList::ListDefinitions ()
Definition at line 412 of file functions.cpp.
References ListContent().
Referenced by SaveStatement::Execute().
{
    return ListContent(true);
}
Member Data Documentation
CharBuffer* FunctionList::buf [private]
Definition at line 96 of file functions.h.
Referenced by Clear(), FunctionList(), ListContent(), and ~FunctionList().
UserFunction* FunctionList::first [private]
Definition at line 97 of file functions.h.
Referenced by Clear(), Delete(), FunctionList(), GetFirstFunction(), GetFunctionCall(), GetFunctionDef(), ListContent(), and ~FunctionList().
Author
Generated automatically by Doxygen for amath from the source code.