FunctionDefinitionNode
NAME
FunctionDefinitionNode - A syntax node able to define a user defined function.
SYNOPSIS
#include <functions.h>
Inherits StatementNode.
Public Member Functions
FunctionDefinitionNode ()
char * GetText ()
char * Execute ()
Additional Inherited Members
Detailed Description
A syntax node able to define a user defined function.
Definition at line 147 of file functions.h.
Constructor & Destructor Documentation
FunctionDefinitionNode::FunctionDefinitionNode ()
Definition at line 258 of file functions.cpp.
References CharBuffer::Empty(), CharBuffer::EnsureMinimumSize(), SyntaxNode::output, and StatementNode::StatementNode().
Referenced by Parser::ParseFunctionDef().
                                               :
    StatementNode() {
    output->EnsureMinimumSize();
    output->Empty();
}
Member Function Documentation
char * FunctionDefinitionNode::Execute () [virtual]
Implements StatementNode.
Definition at line 264 of file functions.cpp.
References CharBuffer::GetString(), and SyntaxNode::output.
{
    // TODO: Move function definition logic from parser to here.
    return output->GetString();
}
char * FunctionDefinitionNode::GetText ()
Definition at line 270 of file functions.cpp.
References CharBuffer::GetString(), and SyntaxNode::output.
{
    return output->GetString();
}
Author
Generated automatically by Doxygen for amath from the source code.