.TH "FunctionDefinitionNode" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FunctionDefinitionNode \- A syntax node able to define a user defined function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionDefinitionNode\fP ()"
.br
.ti -1c
.RI "char * \fBGetText\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A syntax node able to define a user defined function\&. 
.PP
Definition at line 147 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FunctionDefinitionNode::FunctionDefinitionNode ()"

.PP
Definition at line 258 of file functions\&.cpp\&.
.PP
References CharBuffer::Empty(), CharBuffer::EnsureMinimumSize(), SyntaxNode::output, and StatementNode::StatementNode()\&.
.PP
Referenced by Parser::ParseFunctionDef()\&.
.PP
.nf
258                                                :
259     StatementNode() {
260     output->EnsureMinimumSize();
261     output->Empty();
262 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * FunctionDefinitionNode::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 264 of file functions\&.cpp\&.
.PP
References CharBuffer::GetString(), and SyntaxNode::output\&.
.PP
.nf
265 {
266     // TODO: Move function definition logic from parser to here\&.
267     return output->GetString();
268 }
.fi
.SS "char * FunctionDefinitionNode::GetText ()"

.PP
Definition at line 270 of file functions\&.cpp\&.
.PP
References CharBuffer::GetString(), and SyntaxNode::output\&.
.PP
.nf
271 {
272     return output->GetString();
273 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
