.TH "functiondef" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
functiondef \- Function defitions of known mathematical functions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functiondefs\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBCreateFunctionNode\fP \fBcreate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Function defitions of known mathematical functions\&. 
.PP
Definition at line 46 of file functiondefs\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBCreateFunctionNode\fP functiondef::create"

.PP
Definition at line 48 of file functiondefs\&.h\&.
.PP
Referenced by FunctionList::GetFunctionCall()\&.
.SS "const char* functiondef::name"

.PP
Definition at line 47 of file functiondefs\&.h\&.
.PP
Referenced by FunctionList::GetSystemFunction()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
