GraphList
NAME
GraphList - A list of open graph windows.
SYNOPSIS
#include <graphlist.h>
Public Member Functions
GraphList ()
~GraphList ()
GraphWindow * CreateNewWindow ()
Private Attributes
GraphWindow * first
Detailed Description
A list of open graph windows.
Definition at line 42 of file graphlist.h.
Constructor & Destructor Documentation
GraphList::GraphList ()
Definition at line 32 of file graphlist.cpp.
References first.
Referenced by Program::Program().
{
    first = NOMEM;
}
GraphList::~GraphList ()
Definition at line 37 of file graphlist.cpp.
References first.
{
    if (first != NOMEM) {
        delete first;
    }
}
Member Function Documentation
GraphWindow * GraphList::CreateNewWindow ()
Definition at line 44 of file graphlist.cpp.
References CreateGraphWindow(), first, and GraphWindow::next.
Referenced by DrawStatement::Execute().
{
    if (first == NOMEM) {
        first = CreateGraphWindow();
        return first;
    }
    GraphWindow *current = first;
    GraphWindow *last = NOMEM;
    do {
        last = current;
        current = current->next;
    } while (current != NOMEM);
    current = CreateGraphWindow();
    last->next = current;
    return current;
}
Member Data Documentation
GraphWindow* GraphList::first [private]
Definition at line 50 of file graphlist.h.
Referenced by CreateNewWindow(), GraphList(), and ~GraphList().
Author
Generated automatically by Doxygen for amath from the source code.