.TH "app/main/graphlist.cpp" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/graphlist.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/numb\&.h'\fP
.br
\fC#include 'main/graphlist\&.h'\fP
.br
\fC#include 'system/base/io\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
