.TH "app/system/graph.h" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/graph.h \- Logic related to graph of functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/fgrid\&.h'\fP
.br
\fC#include 'main/functions\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphWindow\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logic related to graph of functions\&. 


.PP
Definition in file \fBgraph\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
