.TH "app/system/graph_amiga.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/graph_amiga.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/real\&.h'\fP
.br
\fC#include 'lib/fgrid\&.h'\fP
.br
\fC#include 'main/functions\&.h'\fP
.br
\fC#include 'system/graph\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
