.TH "app/main/graphlist.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/graphlist.h \- Memory maintainance for function of graphs\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'system/graph\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphList\fP"
.br
.RI "\fIA list of open graph windows\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Memory maintainance for function of graphs\&. 


.PP
Definition in file \fBgraphlist\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
