.TH "app/localize/help.h" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/localize/help.h \- Help texts for statement\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'localize/lex\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBhelptextdef\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBsymzero\fP   \fBSymbol\fP(0)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBhelptextdef\fP \fBhelptexts\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Help texts for statement\&. 


.PP
Definition in file \fBhelp\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define symzero   \fBSymbol\fP(0)"

.PP
Definition at line 42 of file help\&.h\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBhelptextdef\fP helptexts[]\fC [static]\fP"

.PP
Definition at line 50 of file help\&.h\&.
.PP
Referenced by Language::GetHelpText(), Language::Language(), and StandardLanguage::LoadCatalogs()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
