.TH "HelpStatement" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpStatement \- Logic related to the help statement\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statements\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpStatement\fP ()"
.br
.ti -1c
.RI "\fBHelpStatement\fP (\fBSymbol\fP \fBargument\fP)"
.br
.ti -1c
.RI "\fBHelpStatement\fP (const char *\fBident\fP)"
.br
.ti -1c
.RI "\fB~HelpStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBSymbol\fP \fBargument\fP"
.br
.ti -1c
.RI "char * \fBident\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Logic related to the help statement\&. 
.PP
Definition at line 174 of file statements\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HelpStatement::HelpStatement ()"

.PP
Definition at line 319 of file statements\&.cpp\&.
.PP
References argument, ident, and StatementNode::StatementNode()\&.
.PP
Referenced by Parser::ParseHelpStatement()\&.
.PP
.nf
319                              :
320     StatementNode() {
321     argument = (Symbol)0;
322     ident = NOMEM;
323 }
.fi
.SS "HelpStatement::HelpStatement (\fBSymbol\fP argument)"

.PP
Definition at line 325 of file statements\&.cpp\&.
.PP
References argument, ident, and StatementNode::StatementNode()\&.
.PP
Referenced by Parser::ParseHelpStatement()\&.
.PP
.nf
325                                             :
326     StatementNode(), argument(argument) {
327     ident = NOMEM;
328 }
.fi
.SS "HelpStatement::HelpStatement (const char * ident)"

.PP
Definition at line 330 of file statements\&.cpp\&.
.PP
References AllocAndCopy(), argument, ident, and symident\&.
.PP
Referenced by Parser::ParseHelpStatement()\&.
.PP
.nf
331 {
332     argument = symident;
333     AllocAndCopy(&this->ident, ident);
334 }
.fi
.SS "HelpStatement::~HelpStatement ()"

.PP
Definition at line 336 of file statements\&.cpp\&.
.PP
References ident\&.
.PP
.nf
337 {
338     if (ident != NOMEM) {
339         delete [] ident;
340     }
341 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * HelpStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 343 of file statements\&.cpp\&.
.PP
References argument, CharBuffer::ClearAndCopy(), Language::GetHelpText(), CharBuffer::GetString(), ident, SyntaxNode::output, and symident\&.
.PP
.nf
344 {
345     char *text = argument != symident ?
346                  Program->Language->GetHelpText(argument) :
347                  Program->Language->GetHelpText(ident);
348 
349     output->ClearAndCopy(text);
350     return output->GetString();
351 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBSymbol\fP HelpStatement::argument\fC [private]\fP"

.PP
Definition at line 183 of file statements\&.h\&.
.PP
Referenced by Execute(), and HelpStatement()\&.
.SS "char* HelpStatement::ident\fC [private]\fP"

.PP
Definition at line 184 of file statements\&.h\&.
.PP
Referenced by Execute(), HelpStatement(), and ~HelpStatement()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
