.TH "helptextdef" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helptextdef \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <help\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBSymbol\fP \fBsymbol\fP"
.br
.ti -1c
.RI "const char * \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file help\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int helptextdef::id"

.PP
Definition at line 45 of file help\&.h\&.
.PP
Referenced by StandardLanguage::LoadCatalogs(), and StandardLanguage::Translate()\&.
.SS "\fBSymbol\fP helptextdef::symbol"

.PP
Definition at line 46 of file help\&.h\&.
.PP
Referenced by Language::GetHelpText(), and StandardLanguage::LoadCatalogs()\&.
.SS "const char* helptextdef::text"

.PP
Definition at line 47 of file help\&.h\&.
.PP
Referenced by StandardLanguage::LoadCatalogs(), StandardLanguage::Translate(), and PosixLanguage::Translate()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
