HelpStatement
NAME
HelpStatement - Logic related to the help statement.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
HelpStatement ()
HelpStatement (Symbol argument)
HelpStatement (const char *ident)
~HelpStatement ()
char * Execute ()
Private Attributes
Symbol argument
char * ident
Additional Inherited Members
Detailed Description
Logic related to the help statement.
Definition at line 174 of file statements.h.
Constructor & Destructor Documentation
HelpStatement::HelpStatement ()
Definition at line 319 of file statements.cpp.
References argument, ident, and StatementNode::StatementNode().
Referenced by Parser::ParseHelpStatement().
                             :
    StatementNode() {
    argument = (Symbol)0;
    ident = NOMEM;
}
HelpStatement::HelpStatement (Symbol argument)
Definition at line 325 of file statements.cpp.
References argument, ident, and StatementNode::StatementNode().
Referenced by Parser::ParseHelpStatement().
                                            :
    StatementNode(), argument(argument) {
    ident = NOMEM;
}
HelpStatement::HelpStatement (const char * ident)
Definition at line 330 of file statements.cpp.
References AllocAndCopy(), argument, ident, and symident.
Referenced by Parser::ParseHelpStatement().
{
    argument = symident;
    AllocAndCopy(&this->ident, ident);
}
HelpStatement::~HelpStatement ()
Definition at line 336 of file statements.cpp.
References ident.
{
    if (ident != NOMEM) {
        delete [] ident;
    }
}
Member Function Documentation
char * HelpStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 343 of file statements.cpp.
References argument, CharBuffer::ClearAndCopy(), Language::GetHelpText(), CharBuffer::GetString(), ident, SyntaxNode::output, and symident.
{
    char *text = argument != symident ?
                 Program->Language->GetHelpText(argument) :
                 Program->Language->GetHelpText(ident);
    output->ClearAndCopy(text);
    return output->GetString();
}
Member Data Documentation
Symbol HelpStatement::argument [private]
Definition at line 183 of file statements.h.
Referenced by Execute(), and HelpStatement().
char* HelpStatement::ident [private]
Definition at line 184 of file statements.h.
Referenced by Execute(), HelpStatement(), and ~HelpStatement().
Author
Generated automatically by Doxygen for amath from the source code.