HyperbolicTangentNode
NAME
HyperbolicTangentNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicTangentNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 480 of file functions.h.
Constructor & Destructor Documentation
HyperbolicTangentNode::HyperbolicTangentNode (ExpressionNode * expression)
Definition at line 1019 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                       :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicTangentNode::Create (ExpressionNode * expression) [static]
Definition at line 1022 of file functions.cpp.
References HyperbolicTangentNode().
{
    return new HyperbolicTangentNode(expression);
}
Number * HyperbolicTangentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1027 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypTangent(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypTangent();
    return result;
}
char * HyperbolicTangentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1033 of file functions.cpp.
{
    return (char*)"tanh";
}
Author
Generated automatically by Doxygen for amath from the source code.