HyperbolicArcsineNode
NAME
HyperbolicArcsineNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicArcsineNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 534 of file functions.h.
Constructor & Destructor Documentation
HyperbolicArcsineNode::HyperbolicArcsineNode (ExpressionNode * expression)
Definition at line 1099 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                       :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicArcsineNode::Create (ExpressionNode * expression) [static]
Definition at line 1102 of file functions.cpp.
References HyperbolicArcsineNode().
{
    return new HyperbolicArcsineNode(expression);
}
Number * HyperbolicArcsineNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1107 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcSine(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypArcSine();
    return result;
}
char * HyperbolicArcsineNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1113 of file functions.cpp.
{
    return (char*)"asinh";
}
Author
Generated automatically by Doxygen for amath from the source code.