HyperbolicArcCosecantNode
NAME
HyperbolicArcCosecantNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicArcCosecantNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 564 of file functions.h.
Constructor & Destructor Documentation
HyperbolicArcCosecantNode::HyperbolicArcCosecantNode (ExpressionNode * expression)
Definition at line 1194 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                               :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicArcCosecantNode::Create (ExpressionNode * expression) [static]
Definition at line 1197 of file functions.cpp.
References HyperbolicArcCosecantNode().
{
    return new HyperbolicArcCosecantNode(expression);
}
Number * HyperbolicArcCosecantNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1202 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcCosecant(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypArcCosecant();
    return result;
}
char * HyperbolicArcCosecantNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1208 of file functions.cpp.
{
    return (char*)"acsch";
}
Author
Generated automatically by Doxygen for amath from the source code.