.TH "HyperbolicCosecantNode" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HyperbolicCosecantNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHyperbolicCosecantNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 510 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HyperbolicCosecantNode::HyperbolicCosecantNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 1076 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
1076                                                                          :
1077     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * HyperbolicCosecantNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 1079 of file functions\&.cpp\&.
.PP
References HyperbolicCosecantNode()\&.
.PP
.nf
1080 {
1081     return new HyperbolicCosecantNode(expression);
1082 }
.fi
.SS "\fBNumber\fP * HyperbolicCosecantNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 1084 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypCosecant(), and ExpressionNode::result\&.
.PP
.nf
1085 {
1086     result = expression->Evaluate()->HypCosecant();
1087     return result;
1088 }
.fi
.SS "char * HyperbolicCosecantNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 1090 of file functions\&.cpp\&.
.PP
.nf
1091 {
1092     return (char*)"csch";
1093 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
