HyperbolicArccosineNode
NAME
HyperbolicArccosineNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicArccosineNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 524 of file functions.h.
Constructor & Destructor Documentation
HyperbolicArccosineNode::HyperbolicArccosineNode (ExpressionNode * expression)
Definition at line 1118 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                           :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicArccosineNode::Create (ExpressionNode * expression) [static]
Definition at line 1121 of file functions.cpp.
References HyperbolicArccosineNode().
{
    return new HyperbolicArccosineNode(expression);
}
Number * HyperbolicArccosineNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1126 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcCosine(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypArcCosine();
    return result;
}
char * HyperbolicArccosineNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1132 of file functions.cpp.
{
    return (char*)"acosh";
}
Author
Generated automatically by Doxygen for amath from the source code.