.TH "HyperbolicSineNode" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HyperbolicSineNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHyperbolicSineNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 460 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HyperbolicSineNode::HyperbolicSineNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 981 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
981                                                                  :
982     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * HyperbolicSineNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 984 of file functions\&.cpp\&.
.PP
References HyperbolicSineNode()\&.
.PP
.nf
985 {
986     return new HyperbolicSineNode(expression);
987 }
.fi
.SS "\fBNumber\fP * HyperbolicSineNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 989 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypSine(), and ExpressionNode::result\&.
.PP
.nf
990 {
991     result = expression->Evaluate()->HypSine();
992     return result;
993 }
.fi
.SS "char * HyperbolicSineNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 995 of file functions\&.cpp\&.
.PP
.nf
996 {
997     return (char*)"sinh";
998 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
