HyperbolicArctangentNode
NAME
HyperbolicArctangentNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicArctangentNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 544 of file functions.h.
Constructor & Destructor Documentation
HyperbolicArctangentNode::HyperbolicArctangentNode (ExpressionNode * expression)
Definition at line 1137 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                             :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicArctangentNode::Create (ExpressionNode * expression) [static]
Definition at line 1140 of file functions.cpp.
References HyperbolicArctangentNode().
{
    return new HyperbolicArctangentNode(expression);
}
Number * HyperbolicArctangentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1145 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcTangent(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypArcTangent();
    return result;
}
char * HyperbolicArctangentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1151 of file functions.cpp.
{
    return (char*)"atanh";
}
Author
Generated automatically by Doxygen for amath from the source code.