.TH "HyperbolicArcCotangentNode" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HyperbolicArcCotangentNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHyperbolicArcCotangentNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 554 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HyperbolicArcCotangentNode::HyperbolicArcCotangentNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 1156 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
1156                                                                                  :
1157     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * HyperbolicArcCotangentNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 1159 of file functions\&.cpp\&.
.PP
References HyperbolicArcCotangentNode()\&.
.PP
.nf
1160 {
1161     return new HyperbolicArcCotangentNode(expression);
1162 }
.fi
.SS "\fBNumber\fP * HyperbolicArcCotangentNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 1164 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcCotangent(), and ExpressionNode::result\&.
.PP
.nf
1165 {
1166     result = expression->Evaluate()->HypArcCotangent();
1167     return result;
1168 }
.fi
.SS "char * HyperbolicArcCotangentNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 1170 of file functions\&.cpp\&.
.PP
.nf
1171 {
1172     return (char*)"acoth";
1173 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
