HyperbolicArcSecantNode
NAME
HyperbolicArcSecantNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicArcSecantNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 574 of file functions.h.
Constructor & Destructor Documentation
HyperbolicArcSecantNode::HyperbolicArcSecantNode (ExpressionNode * expression)
Definition at line 1175 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                           :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicArcSecantNode::Create (ExpressionNode * expression) [static]
Definition at line 1178 of file functions.cpp.
References HyperbolicArcSecantNode().
{
    return new HyperbolicArcSecantNode(expression);
}
Number * HyperbolicArcSecantNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1183 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcSecant(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypArcSecant();
    return result;
}
char * HyperbolicArcSecantNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1189 of file functions.cpp.
{
    return (char*)"asech";
}
Author
Generated automatically by Doxygen for amath from the source code.