HyperbolicCotangentNode
NAME
HyperbolicCotangentNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicCotangentNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 490 of file functions.h.
Constructor & Destructor Documentation
HyperbolicCotangentNode::HyperbolicCotangentNode (ExpressionNode * expression)
Definition at line 1038 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                           :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicCotangentNode::Create (ExpressionNode * expression) [static]
Definition at line 1041 of file functions.cpp.
References HyperbolicCotangentNode().
{
    return new HyperbolicCotangentNode(expression);
}
Number * HyperbolicCotangentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1046 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypCotangent(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypCotangent();
    return result;
}
char * HyperbolicCotangentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1052 of file functions.cpp.
{
    return (char*)"coth";
}
Author
Generated automatically by Doxygen for amath from the source code.