HyperbolicSecantNode
NAME
HyperbolicSecantNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicSecantNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 500 of file functions.h.
Constructor & Destructor Documentation
HyperbolicSecantNode::HyperbolicSecantNode (ExpressionNode * expression)
Definition at line 1057 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                     :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicSecantNode::Create (ExpressionNode * expression) [static]
Definition at line 1060 of file functions.cpp.
References HyperbolicSecantNode().
{
    return new HyperbolicSecantNode(expression);
}
Number * HyperbolicSecantNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1065 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypSecant(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypSecant();
    return result;
}
char * HyperbolicSecantNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1071 of file functions.cpp.
{
    return (char*)"sech";
}
Author
Generated automatically by Doxygen for amath from the source code.