.TH "HyperbolicArctangentNode" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HyperbolicArctangentNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHyperbolicArctangentNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 544 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HyperbolicArctangentNode::HyperbolicArctangentNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 1137 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
1137                                                                              :
1138     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * HyperbolicArctangentNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 1140 of file functions\&.cpp\&.
.PP
References HyperbolicArctangentNode()\&.
.PP
.nf
1141 {
1142     return new HyperbolicArctangentNode(expression);
1143 }
.fi
.SS "\fBNumber\fP * HyperbolicArctangentNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 1145 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcTangent(), and ExpressionNode::result\&.
.PP
.nf
1146 {
1147     result = expression->Evaluate()->HypArcTangent();
1148     return result;
1149 }
.fi
.SS "char * HyperbolicArctangentNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 1151 of file functions\&.cpp\&.
.PP
.nf
1152 {
1153     return (char*)"atanh";
1154 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
