HyperbolicArcCotangentNode
NAME
HyperbolicArcCotangentNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicArcCotangentNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 554 of file functions.h.
Constructor & Destructor Documentation
HyperbolicArcCotangentNode::HyperbolicArcCotangentNode (ExpressionNode * expression)
Definition at line 1156 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                                 :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicArcCotangentNode::Create (ExpressionNode * expression) [static]
Definition at line 1159 of file functions.cpp.
References HyperbolicArcCotangentNode().
{
    return new HyperbolicArcCotangentNode(expression);
}
Number * HyperbolicArcCotangentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1164 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcCotangent(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypArcCotangent();
    return result;
}
char * HyperbolicArcCotangentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1170 of file functions.cpp.
{
    return (char*)"acoth";
}
Author
Generated automatically by Doxygen for amath from the source code.