HyperbolicCosecantNode
NAME
HyperbolicCosecantNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicCosecantNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 510 of file functions.h.
Constructor & Destructor Documentation
HyperbolicCosecantNode::HyperbolicCosecantNode (ExpressionNode * expression)
Definition at line 1076 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                         :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicCosecantNode::Create (ExpressionNode * expression) [static]
Definition at line 1079 of file functions.cpp.
References HyperbolicCosecantNode().
{
    return new HyperbolicCosecantNode(expression);
}
Number * HyperbolicCosecantNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1084 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypCosecant(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypCosecant();
    return result;
}
char * HyperbolicCosecantNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1090 of file functions.cpp.
{
    return (char*)"csch";
}
Author
Generated automatically by Doxygen for amath from the source code.