HyperbolicCosineNode
NAME
HyperbolicCosineNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicCosineNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 470 of file functions.h.
Constructor & Destructor Documentation
HyperbolicCosineNode::HyperbolicCosineNode (ExpressionNode * expression)
Definition at line 1000 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
    : FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicCosineNode::Create (ExpressionNode * expression) [static]
Definition at line 1003 of file functions.cpp.
References HyperbolicCosineNode().
{
    return new HyperbolicCosineNode(expression);
}
Number * HyperbolicCosineNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 1008 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypCosine(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypCosine();
    return result;
}
char * HyperbolicCosineNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 1014 of file functions.cpp.
{
    return (char*)"cosh";
}
Author
Generated automatically by Doxygen for amath from the source code.