.TH "HyperbolicArccosineNode" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HyperbolicArccosineNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHyperbolicArccosineNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 524 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "HyperbolicArccosineNode::HyperbolicArccosineNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 1118 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
1118                                                                            :
1119     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * HyperbolicArccosineNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 1121 of file functions\&.cpp\&.
.PP
References HyperbolicArccosineNode()\&.
.PP
.nf
1122 {
1123     return new HyperbolicArccosineNode(expression);
1124 }
.fi
.SS "\fBNumber\fP * HyperbolicArccosineNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 1126 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypArcCosine(), and ExpressionNode::result\&.
.PP
.nf
1127 {
1128     result = expression->Evaluate()->HypArcCosine();
1129     return result;
1130 }
.fi
.SS "char * HyperbolicArccosineNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 1132 of file functions\&.cpp\&.
.PP
.nf
1133 {
1134     return (char*)"acosh";
1135 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
