HyperbolicSineNode
NAME
HyperbolicSineNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
HyperbolicSineNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 460 of file functions.h.
Constructor & Destructor Documentation
HyperbolicSineNode::HyperbolicSineNode (ExpressionNode * expression)
Definition at line 981 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                                 :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * HyperbolicSineNode::Create (ExpressionNode * expression) [static]
Definition at line 984 of file functions.cpp.
References HyperbolicSineNode().
{
    return new HyperbolicSineNode(expression);
}
Number * HyperbolicSineNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 989 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::HypSine(), and ExpressionNode::result.
{
    result = expression->Evaluate()->HypSine();
    return result;
}
char * HyperbolicSineNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 995 of file functions.cpp.
{
    return (char*)"sinh";
}
Author
Generated automatically by Doxygen for amath from the source code.