.TH "lib/real/hypot.c" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/real/hypot.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'prim\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBhypot\fP (double x, double y)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double hypot (double x, double y)"

.PP
Definition at line 79 of file hypot\&.c\&.
.PP
References sqrt()\&.
.PP
Referenced by cabs()\&.
.PP
.nf
80 {
81     double a=x,b=y,t1,t2,y1,y2,w;
82     uword j,k,ha,hb,hx,hy;
83 
84     GET_HIGH_WORD(hx,x);
85     GET_HIGH_WORD(hy,y);
86     ha = hx&0x7fffffff; /* high word of  x */
87     hb = hy&0x7fffffff; /* high word of  y */
88     if(hb > ha) {
89         a=y;
90         b=x;
91         j=ha;
92         ha=hb;
93         hb=j;
94     }
95     else {
96         a=x;
97         b=y;
98     }
99     SET_HIGH_WORD(a,ha); /* a <- |a| */
100     SET_HIGH_WORD(b,hb); /* b <- |b| */
101     if((ha-hb)>0x3c00000) {
102         return a+b;   /* x/y > 2**60 */
103     }
104     k=0;
105     if(ha > 0x5f300000) {   /* a>2**500 */
106         if(ha >= 0x7ff00000) {  /* Inf or NaN */
107             uword la, lb;
108             w = a+b;            /* for sNaN */
109             GET_LOW_WORD(la,a);
110             GET_LOW_WORD(lb,b);
111             if(((ha&0xfffff)|la)==0) w = a;
112             if(((hb^0x7ff00000)|lb)==0) w = b;
113             return w;
114         }
115         /* scale a and b by 2**-600 */
116         ha -= 0x25800000;
117         hb -= 0x25800000;
118         k += 600;
119         SET_HIGH_WORD(a,ha);
120         SET_HIGH_WORD(b,hb);
121     }
122     if(hb < 0x20b00000) {   /* b < 2**-500 */
123         if(hb <= 0x000fffff) {  /* subnormal b or 0 */
124             uword lb;
125             GET_LOW_WORD(lb,b);
126             if((hb|lb)==0) return a;
127             t1=0;
128             SET_HIGH_WORD(t1, 0x7fd00000);  /* t1=2^1022 */
129             b *= t1;
130             a *= t1;
131             k -= 1022;
132         } else {        /* scale a and b by 2^600 */
133             ha += 0x25800000;   /* a *= 2^600 */
134             hb += 0x25800000;   /* b *= 2^600 */
135             k -= 600;
136 
137             SET_HIGH_WORD(a,ha);
138             SET_HIGH_WORD(b,hb);
139         }
140     }
141     /* medium size a and b */
142     w = a-b;
143     if (w>b) {
144         t1 = 0;
145         SET_HIGH_WORD(t1, ha);
146         t2 = a-t1;
147         w  = sqrt(t1*t1-(b*(-b)-t2*(a+t1)));
148     } else {
149         a  = a+a;
150         y1 = 0;
151         SET_HIGH_WORD(y1, hb);
152         y2 = b - y1;
153         t1 = 0;
154         SET_HIGH_WORD(t1, ha+0x00100000);
155         t2 = a - t1;
156         w  = sqrt(t1*y1-(w*(-w)-(t1*y2+t2*b)));
157     }
158     if(k!=0) {
159         uword ht1;
160 
161         t1 = 1\&.0;
162         GET_HIGH_WORD(ht1, t1);
163         SET_HIGH_WORD(t1, ht1 + (k<<20));
164         return t1*w;
165     } else return w;
166 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
