.TH "app/localize/ialias.h" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/localize/ialias.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBidentalias\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBidentalias\fP \fBidentaliases\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBidentalias\fP identaliases[]\fC [static]\fP"

.PP
Definition at line 35 of file ialias\&.h\&.
.PP
Referenced by Language::FindAlias(), and Language::Language()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
