.TH "identhelpdef" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identhelpdef \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ident\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "const char * \fBident\fP"
.br
.ti -1c
.RI "const char * \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file ident\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int identhelpdef::id"

.PP
Definition at line 42 of file ident\&.h\&.
.PP
Referenced by StandardLanguage::LoadCatalogs(), and StandardLanguage::Translate()\&.
.SS "const char* identhelpdef::ident"

.PP
Definition at line 43 of file ident\&.h\&.
.PP
Referenced by Language::GetHelpText(), and StandardLanguage::LoadCatalogs()\&.
.SS "const char* identhelpdef::text"

.PP
Definition at line 44 of file ident\&.h\&.
.PP
Referenced by StandardLanguage::LoadCatalogs(), StandardLanguage::Translate(), and PosixLanguage::Translate()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
