.TH "identalias" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identalias \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ialias\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBident\fP"
.br
.ti -1c
.RI "const char * \fBalias\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file ialias\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* identalias::alias"

.PP
Definition at line 32 of file ialias\&.h\&.
.PP
Referenced by Language::FindAlias()\&.
.SS "const char* identalias::ident"

.PP
Definition at line 31 of file ialias\&.h\&.
.PP
Referenced by Language::FindAlias()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
