.TH "app/localize/ident.h" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/localize/ident.h \- Help texts for built-in functions\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBidenthelpdef\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBidenthelpdef\fP \fBidenttexts\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Help texts for built-in functions\&. 


.PP
Definition in file \fBident\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBidenthelpdef\fP identtexts[]\fC [static]\fP"

.PP
Definition at line 47 of file ident\&.h\&.
.PP
Referenced by Language::GetHelpText(), and Language::Language()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
