.TH "ieee_float_shape_type" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ieee_float_shape_type \- A union which permits us to convert between a float and a 32 bit int\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <prim\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "float \fBvalue\fP"
.br
.ti -1c
.RI "\fBuword\fP \fBword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A union which permits us to convert between a float and a 32 bit int\&. 
.PP
Definition at line 227 of file prim\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "float ieee_float_shape_type::value"

.PP
Definition at line 229 of file prim\&.h\&.
.SS "\fBuword\fP ieee_float_shape_type::word"

.PP
Definition at line 230 of file prim\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
