InputStatement
NAME
InputStatement - Change numeral input system.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
InputStatement ()
Constructor used to show number of active digits.
InputStatement (unsigned int base)
Constructor used to set number of active digits.
~InputStatement ()
char * Execute ()
Private Attributes
unsigned int base
Additional Inherited Members
Detailed Description
Change numeral input system.
Definition at line 209 of file statements.h.
Constructor & Destructor Documentation
InputStatement::InputStatement ()
Constructor used to show number of active digits.
Definition at line 455 of file statements.cpp.
References base.
Referenced by Parser::ParseNumeralStatement().
                               :
    base(0) { }
InputStatement::InputStatement (unsigned int base)
Constructor used to set number of active digits.
Definition at line 462 of file statements.cpp.
References base, and StatementNode::StatementNode().
Referenced by Parser::ParseNumeralStatement().
                                                :
    StatementNode(), base(base) { }
InputStatement::~InputStatement () [inline]
Definition at line 213 of file statements.h.
{ }
Member Function Documentation
char * InputStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 465 of file statements.cpp.
References CharBuffer::Append(), base, CharBuffer::Empty(), CharBuffer::EnsureSize(), NumeralSystem::GetDigits(), NumeralSystem::GetName(), CharBuffer::GetString(), Program::Input, Program::NewPositionalInput(), SyntaxNode::output, and StrLen().
{
    const char *text;
    if (base != 0) {
        int digits = Program->Input->GetDigits();
        Program->NewPositionalInput(base, digits);
        text = HELPINPUSETT;
    } else {
        text = HELPINPUSHOW;
    }
    const char *desc = Program->Input->GetName();
    output->Empty();
    output->EnsureSize(StrLen(text) + StrLen(desc) + StrLen(NEWLINE) + 1);
    output->Append(text);
    output->Append(desc);
    output->Append(NEWLINE);
    return output->GetString();
}
Member Data Documentation
unsigned int InputStatement::base [private]
Definition at line 217 of file statements.h.
Referenced by Execute(), and InputStatement().
Author
Generated automatically by Doxygen for amath from the source code.