InsVariableNode
NAME
InsVariableNode - Use of last result in a syntax tree.
SYNOPSIS
#include <values.h>
Inherits VariableNode.
Public Member Functions
InsVariableNode ()
char * GetText ()
Number * Evaluate ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Use of last result in a syntax tree.
Definition at line 128 of file values.h.
Constructor & Destructor Documentation
InsVariableNode::InsVariableNode ()
Definition at line 318 of file values.cpp.
References VariableNode::VariableNode().
Referenced by Parser::ParseAtomic().
                                 :
    VariableNode(NOMEM)
{ }
Member Function Documentation
Number * InsVariableNode::Evaluate () [virtual]
Reimplemented from VariableNode.
Definition at line 322 of file values.cpp.
References Program::GetLastResult().
{
    return Program->GetLastResult();
}
char * InsVariableNode::GetNodeText () [protected], [virtual]
Reimplemented from VariableNode.
Definition at line 332 of file values.cpp.
{
    return (char*)"ins";
}
char * InsVariableNode::GetText () [virtual]
Reimplemented from VariableNode.
Definition at line 327 of file values.cpp.
{
    return (char*)"ins";
}
Author
Generated automatically by Doxygen for amath from the source code.