app/system/base/io.cpp
NAME
app/system/base/io.cpp -
SYNOPSIS
#include 'mem.h'
#include 'clib.h'
#include 'localize/start.h'
#include 'system/program.h'
#include 'system/program_stdc.h'
#include 'system/program_amiga.h'
#include 'system/program_test.h'
#include 'system/console.h'
#include 'system/console_stdc.h'
#include 'system/console_amiga.h'
#include 'system/language.h'
#include 'system/language_stdc.h'
#include 'system/language_amiga.h'
#include 'system/language_posix.h'
#include 'system/filesystem.h'
#include 'system/filesystem_stdc.h'
#include 'system/filesystem_amiga.h'
#include 'system/preferences.h'
#include 'system/preferences_stdc.h'
#include 'system/preferences_amiga.h'
#include 'system/window_amiga.h'
#include 'system/graph_amiga.h'
#include 'system/base/io.h'
Functions
class Program * CreateProgram (int argc, char **argv)
class Language * CreateLanguage ()
class PreferencesBase * CreatePreferences ()
class FilesystemBase * CreateFilesystem ()
GraphWindow * CreateGraphWindow ()
void WriteToShell (const char *out)
void Cleanup ()
Variables
const char * vers = TXTDOSVERSION
class Program * Program = NULL
Function Documentation
void Cleanup ()
Definition at line 155 of file io.cpp.
References FreeAllSafe().
Referenced by main().
{
#ifdef AMIGA
    if (DosBase != NULL) {
        CloseLibrary((struct Library*)DosBase);
    }
    if (LocaleBase != NULL) {
        CloseLibrary((struct Library*)LocaleBase);
    }
    if (GfxBase != NULL) {
        CloseLibrary((struct Library*)GfxBase);
    }
    if (IntuitionBase != NULL) {
        CloseLibrary((struct Library*)IntuitionBase);
    }
#endif
    delete Program;
    FreeAllSafe();
}
class FilesystemBase* CreateFilesystem ()
Definition at line 125 of file io.cpp.
Referenced by StandardLanguage::LoadCatalog(), and Program::Program().
{
#ifdef AMIGA
    DosBase = (struct DosBase*)OpenLibrary(AMIGADOS_NAME, AMIGADOS_REV);
    if (DosBase == NULL) {
        return NULL;
    }
    return new AmigaFilesystem();
#else
    return new StandardFilesystem();
#endif
}
GraphWindow* CreateGraphWindow ()
Definition at line 138 of file io.cpp.
Referenced by GraphList::CreateNewWindow().
                                 {
#ifdef AMIGA
    return new AmigaGraphWindow();
#else
    return NOMEM;
#endif
}
class Language* CreateLanguage ()
Definition at line 100 of file io.cpp.
References PosixLanguage::PosixLanguage(), and StandardLanguage::StandardLanguage().
Referenced by Program::Program().
{
#ifdef UNIX
    return new PosixLanguage();
#endif
#ifdef AMIGA
    LocaleBase = (struct LocaleBase*)OpenLibrary(LOCALE_NAME, LOCALE_REV);
    if (LocaleBase != NULL) {
        return new AmigaLanguage();
    } else
#endif
    {
        return new StandardLanguage();
    }
}
class PreferencesBase* CreatePreferences ()
Definition at line 116 of file io.cpp.
Referenced by Program::Program().
{
#ifdef AMIGA
    return new AmigaPreferences();
#else
    return new StandardPreferences();
#endif
}
class Program* CreateProgram (int argc, char ** argv)
Definition at line 77 of file io.cpp.
References StandardProgram::StandardProgram().
Referenced by main().
                                                    {
#ifdef WITHTEST
    if (argc == 2 && StrIsEqual(argv[1], "test")) {
        return new TestProgram();
    } else
#endif
    {
#ifdef AMIGA
        IntuitionBase = (struct IntuitionBase*)OpenLibrary(INTUITION_NAME, INTUITION_REV);
        GfxBase = (struct GfxBase*)OpenLibrary(GRAPHICS_NAME, GRAPHICS_REV);
        if (IntuitionBase != NULL && GfxBase != NULL) {
            return new AmigaProgram();
        } else {
            return new StandardProgram();
        }
#else
        return new StandardProgram();
#endif
    }
    return NULL;
}
void WriteToShell (const char * out)
Definition at line 146 of file io.cpp.
Referenced by StandardProgram::Run().
                                   {
#ifdef AMIGA
    Write(Output(), (APTR)out, StrLen(out));
    Write(Output(), (APTR)NORMALTEXT, StrLen(NORMALTEXT));
#else
    printf("%s%s", out, NORMALTEXT);
#endif
}
Variable Documentation
class Program* Program = NULL
Definition at line 69 of file io.cpp.
const char* vers = TXTDOSVERSION
Definition at line 68 of file io.cpp.
Author
Generated automatically by Doxygen for amath from the source code.