.TH "keyworddef" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
keyworddef \- Character representation of keyword tied with its symbol\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kword\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "\fBSymbol\fP \fBsymbol\fP"
.br
.ti -1c
.RI "const char * \fBname\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Character representation of keyword tied with its symbol\&. 
.PP
Definition at line 46 of file kword\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int keyworddef::id"

.PP
Definition at line 47 of file kword\&.h\&.
.SS "const char* keyworddef::name"

.PP
Definition at line 49 of file kword\&.h\&.
.PP
Referenced by Language::FindKeyword(), and Lexer::FindKeyword()\&.
.SS "\fBSymbol\fP keyworddef::symbol"

.PP
Definition at line 48 of file kword\&.h\&.
.PP
Referenced by Language::FindKeyword(), and Lexer::FindKeyword()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
