.TH "app/localize/kword.h" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/localize/kword.h \- Keywords used by lexer\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'localize/lex\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBkeyworddef\fP"
.br
.RI "\fICharacter representation of keyword tied with its symbol\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBkeyworddef\fP \fBkeywords\fP []"
.br
.in -1c
.SH "Detailed Description"
.PP 
Keywords used by lexer\&. 


.PP
Definition in file \fBkword\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "const \fBkeyworddef\fP keywords[]\fC [static]\fP"

.PP
Definition at line 52 of file kword\&.h\&.
.PP
Referenced by Language::FindKeyword(), Lexer::FindKeyword(), and Language::Language()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
