.TH "app/system/language_stdc.h" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/language_stdc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'localize/lex\&.h'\fP
.br
\fC#include 'localize/help\&.h'\fP
.br
\fC#include 'localize/text\&.h'\fP
.br
\fC#include 'system/language\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStandardLanguage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
