.TH "app/system/language_posix.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/language_posix.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'localize/lex\&.h'\fP
.br
\fC#include 'localize/help\&.h'\fP
.br
\fC#include 'localize/text\&.h'\fP
.br
\fC#include 'localize/kword\&.h'\fP
.br
\fC#include 'system/language\&.h'\fP
.br
\fC#include <ctype\&.h>\fP
.br
\fC#include <locale\&.h>\fP
.br
\fC#include <nl_types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPosixLanguage\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
