.TH "app/system/language_amiga.cpp" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/language_amiga.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'localize/lex\&.h'\fP
.br
\fC#include 'localize/help\&.h'\fP
.br
\fC#include 'localize/text\&.h'\fP
.br
\fC#include 'localize/ident\&.h'\fP
.br
\fC#include 'localize/kword\&.h'\fP
.br
\fC#include 'localize/tags\&.h'\fP
.br
\fC#include 'system/program\&.h'\fP
.br
\fC#include 'system/base/io\&.h'\fP
.br
\fC#include 'system/language_amiga\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
