Language
NAME
Language -
SYNOPSIS
#include <language.h>
Inherited by AmigaLanguage, PosixLanguage, and StandardLanguage.
Public Member Functions
Language ()
virtual ~Language ()
char * GetText (int id)
char * GetHelpText (char *ident)
char * GetHelpText (Symbol symbol)
Symbol FindKeyword (const char *ident)
virtual char GetFractionPoint ()=0
virtual bool CharIsAlNum (unsigned long character)=0
virtual bool CharIsAlpha (unsigned long character)=0
virtual bool CharIsDigit (unsigned long character)=0
virtual bool CharIsPunct (unsigned long character)=0
virtual bool CharIsSpace (unsigned long character)=0
virtual bool CharIsCntrl (unsigned long character)=0
virtual bool StrIsEqualLoc (const char *s1, const char *s2)=0
Protected Member Functions
virtual char * Translate (textdef *def)=0
virtual char * Translate (helptextdef *def)=0
virtual char * Translate (identhelpdef *def)=0
Protected Attributes
keyworddef * keywordsloc
unsigned int keywordcount
unsigned int textcount
unsigned int identcount
unsigned int helpcount
unsigned int aliascount
Private Member Functions
char * FindAlias (const char *ident)
char * UntagText (const char *text)
Private Attributes
char * lastText
Detailed Description
Definition at line 36 of file language.h.
Constructor & Destructor Documentation
Language::Language ()
Definition at line 38 of file language.cpp.
References aliascount, helpcount, helptexts, identaliases, identcount, identtexts, keywordcount, keywords, keywordsloc, lastText, textcount, and textdefs.
Referenced by PosixLanguage::PosixLanguage(), and StandardLanguage::StandardLanguage().
{
    lastText = NOMEM;
    keywordsloc = NOMEM;
    keywordcount = sizeof(keywords) / sizeof(keyworddef);
    textcount = sizeof(textdefs) / sizeof(textdef);
    identcount = sizeof(identtexts) / sizeof(identhelpdef);
    helpcount = sizeof(helptexts) / sizeof(helptextdef);
    aliascount = sizeof(identaliases) / sizeof(identalias);
}
Language::~Language () [virtual]
Definition at line 49 of file language.cpp.
References keywordsloc, and lastText.
{
    if (lastText != NOMEM) {
        delete lastText;
    }
    if (keywordsloc != NOMEM) {
        delete [] keywordsloc;
    }
}
Member Function Documentation
virtual bool Language::CharIsAlNum (unsigned long character) [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
virtual bool Language::CharIsAlpha (unsigned long character) [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by Lexer::GetLitteral().
virtual bool Language::CharIsCntrl (unsigned long character) [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by Lexer::GetQuotedIdent(), and Lexer::ShouldSkip().
virtual bool Language::CharIsDigit (unsigned long character) [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by Lexer::GetLitteral().
virtual bool Language::CharIsPunct (unsigned long character) [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
virtual bool Language::CharIsSpace (unsigned long character) [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by Lexer::GetNextToken(), and Lexer::ShouldSkip().
char * Language::FindAlias (const char * ident) [private]
Definition at line 60 of file language.cpp.
References identalias::alias, aliascount, identalias::ident, identaliases, and StrIsEqual().
Referenced by GetHelpText().
{
    for (unsigned int i = 0; i < aliascount; i++) {
        if (StrIsEqual(identaliases[i].ident, ident)) {
            return (char*)identaliases[i].alias;
        }
    }
    return (char*)ident;
}
Symbol Language::FindKeyword (const char * ident)
Definition at line 70 of file language.cpp.
References keywordcount, keywords, keywordsloc, keyworddef::name, StrIsEqualLoc(), and keyworddef::symbol.
Referenced by Lexer::FindKeyword().
{
    for (unsigned int i = 0; i < keywordcount; i++) {
        if (
            Program->Language->StrIsEqualLoc(keywords[i].name, ident) ||
            (keywordsloc != NULL &&
             Program->Language->StrIsEqualLoc(keywordsloc[i].name, ident))) {
            return keywords[i].symbol;
        }
    }
    return (Symbol)0;
}
virtual char Language::GetFractionPoint () [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by Program::NewPositionalInput(), Program::NewPositionalOutput(), and Program::Program().
char * Language::GetHelpText (char * ident)
Definition at line 102 of file language.cpp.
References FindAlias(), identhelpdef::ident, identcount, identtexts, StrIsEqual(), Translate(), and UntagText().
Referenced by HelpStatement::Execute().
{
    char *s = FindAlias(ident);
    identhelpdef *def = NOMEM;
    for (unsigned int i = 0; i < identcount; i++) {
        if (StrIsEqual(identtexts[i].ident, s)) {
            def = (identhelpdef*)&identtexts[i];
            break;
        }
    }
    if (def == NOMEM) {
        return (char*)(HELPNOHELP);
    }
    char *text = Translate(def);
    char *untagged = UntagText(text);
    return untagged;
}
char * Language::GetHelpText (Symbol symbol)
Definition at line 122 of file language.cpp.
References helpcount, helptexts, helptextdef::symbol, Translate(), and UntagText().
Referenced by HelpStatement::Execute().
{
    helptextdef *def = NOMEM;
    for (unsigned int i = 0; i < helpcount; i++) {
        if (helptexts[i].symbol == symbol) {
            def = (helptextdef*)&helptexts[i];
            break;
        }
    }
    if (def == NOMEM) {
        return (char*)(HELPNOHELP);
    }
    char *text = Translate(def);
    char *untagged = UntagText(text);
    return untagged;
}
char * Language::GetText (int id)
Definition at line 83 of file language.cpp.
References textdef::id, textcount, textdefs, Translate(), and UntagText().
{
    textdef *def = NOMEM;
    for (unsigned int i = 0; i < textcount; i++) {
        if (textdefs[i].id == id) {
            def = (textdef*)&textdefs[i];
            break;
        }
    }
    if (def == NOMEM) {
        return (char*)(HELPNOHELP);
    }
    char *text = Translate(def);
    char *untagged = UntagText(text);
    return untagged;
}
virtual bool Language::StrIsEqualLoc (const char * s1, const char * s2) [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by FindKeyword().
virtual char* Language::Translate (textdef * def) [protected], [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by GetText().
virtual char* Language::Translate (helptextdef * def) [protected], [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by GetHelpText().
virtual char* Language::Translate (identhelpdef * def) [protected], [pure virtual]
Implemented in PosixLanguage, AmigaLanguage, and StandardLanguage.
Referenced by GetHelpText().
char * Language::UntagText (const char * text) [private]
Definition at line 141 of file language.cpp.
References lastText, MemCopy(), StrLen(), texttags, and Untag().
Referenced by GetHelpText(), and GetText().
{
    if (lastText != NOMEM) {
        delete lastText;
        lastText = NULL;
    }
    if (text == NOMEM) {
        return NOMEM;
    }
    unsigned int count = sizeof(texttags) / sizeof(texttag);
    char *untagged = new char[StrLen(text) * 2];
    Untag(untagged, text, (texttag*)texttags, count);
    unsigned int len = StrLen(untagged) + 1;
    lastText = new char[len];
    MemCopy(lastText, untagged, len);
    delete [] untagged;
    return lastText;
}
Member Data Documentation
unsigned int Language::aliascount [protected]
Definition at line 63 of file language.h.
Referenced by FindAlias(), and Language().
unsigned int Language::helpcount [protected]
Definition at line 62 of file language.h.
Referenced by GetHelpText(), and Language().
unsigned int Language::identcount [protected]
Definition at line 61 of file language.h.
Referenced by GetHelpText(), and Language().
unsigned int Language::keywordcount [protected]
Definition at line 59 of file language.h.
Referenced by FindKeyword(), and Language().
keyworddef* Language::keywordsloc [protected]
Definition at line 58 of file language.h.
Referenced by FindKeyword(), Language(), and ~Language().
char* Language::lastText [private]
Definition at line 68 of file language.h.
Referenced by Language(), UntagText(), and ~Language().
unsigned int Language::textcount [protected]
Definition at line 60 of file language.h.
Referenced by GetText(), and Language().
Author
Generated automatically by Doxygen for amath from the source code.