.TH "app/system/language.cpp" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/language.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'localize/lex\&.h'\fP
.br
\fC#include 'localize/help\&.h'\fP
.br
\fC#include 'localize/kword\&.h'\fP
.br
\fC#include 'localize/ident\&.h'\fP
.br
\fC#include 'localize/text\&.h'\fP
.br
\fC#include 'localize/tags\&.h'\fP
.br
\fC#include 'localize/ialias\&.h'\fP
.br
\fC#include 'system/language\&.h'\fP
.br
\fC#include 'system/program\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
