Lexer
NAME
Lexer - Encapsulates an lexical analyzer. Provides token for the parser.
SYNOPSIS
#include <lexer.h>
Public Member Functions
Lexer (const char *input)
~Lexer ()
void Tokenize ()
Token * GetFirstToken ()
char * GetInput ()
Static Public Member Functions
static char * FindKeyword (Symbol symbol)
Private Member Functions
void GetNextToken ()
bool GetOperator ()
bool GetQuotedIdent ()
bool GetLitteral ()
bool GetDigitValue ()
bool ShouldSkip (char character)
Symbol FindKeyword (const char *ident)
Private Attributes
char * input
char * str
unsigned int pos
Token * first
Token * current
Detailed Description
Encapsulates an lexical analyzer. Provides token for the parser.
More info on lexical analysis is available at Wikipedia: http://en.wikipedia.org/wiki/Lexical_analysis
Definition at line 45 of file lexer.h.
Constructor & Destructor Documentation
Lexer::Lexer (const char * input)
Definition at line 34 of file lexer.cpp.
References AllocAndCopy(), current, first, input, pos, and str.
Referenced by Parser::Parser().
{
    AllocAndCopy(&this->input, input);
    pos = 0;
    str = this->input;
    first = NOMEM;
    current = NOMEM;
}
Lexer::~Lexer ()
Definition at line 43 of file lexer.cpp.
References first, and input.
{
    delete [] input;
    if (first != NOMEM) {
        delete first;
    }
}
Member Function Documentation
char * Lexer::FindKeyword (Symbol symbol) [static]
Definition at line 221 of file lexer.cpp.
References operatordef::chr, keywords, keyworddef::name, operators, keyworddef::symbol, and operatordef::symbol.
Referenced by PreferencesBase::GetDescription().
{
    static const unsigned int kwcount = sizeof(keywords) / sizeof(keyworddef);
    for (unsigned int i = 0; i < kwcount; i++) {
        if (keywords[i].symbol == symbol) {
            return (char*)keywords[i].name;
        }
    }
    static const unsigned int ocount = sizeof(operators) / sizeof(operatordef);
    for (unsigned int i = 0; i < ocount; i++) {
        if (operators[i].symbol == symbol) {
            return (char*)&(operators[i].chr);
        }
    }
    return NOMEM;
}
Symbol Lexer::FindKeyword (const char * ident) [private]
Definition at line 216 of file lexer.cpp.
References Language::FindKeyword().
Referenced by GetLitteral().
{
    return Program->Language->FindKeyword(ident);
}
bool Lexer::GetDigitValue () [private]
Definition at line 190 of file lexer.cpp.
References current, Program::Input, MemCopy(), NumeralSystem::Parse(), pos, str, symnumber, and Token::Token().
Referenced by GetNextToken().
{
    unsigned int len;
    char *end;
    // Only the numeral parser can determine if next token is a value
    Number *number = Program->Input->Parse(str, &len, &end);
    if (str == end) {
        delete number;
        return false;
    }
    char *text = new char[len + 1];
    MemCopy(text, str, len);
    *(text + len) = '\0';
    current = new Token(current, symnumber, text, pos);
    delete [] text;
    delete number;
    pos += len;
    str = end;
    return true;
}
Token * Lexer::GetFirstToken ()
Definition at line 57 of file lexer.cpp.
References first.
Referenced by Parser::GetToken().
{
    return first;
}
char * Lexer::GetInput ()
Definition at line 52 of file lexer.cpp.
References input.
Referenced by Parser::Parse(), Parser::ParseDigistStatement(), Parser::ParseFileStatement(), Parser::ParseFunctionDef(), Parser::ParseIdent(), Parser::ParseNumeralStatement(), and Parser::TryParseStatement().
{
    return input;
}
bool Lexer::GetLitteral () [private]
Definition at line 150 of file lexer.cpp.
References Language::CharIsAlpha(), Language::CharIsDigit(), current, FindKeyword(), MemCopy(), pos, str, symident, and Token::Token().
Referenced by GetNextToken().
{
    const char *start = str;
    const unsigned int startPos = pos;
    int unsigned len = 0;
    bool found = true;
    Symbol ksymbol;
    while (found) {
        if (Program->Language->CharIsAlpha(*str)) {
            str++;
            len++;
        } else if (len != 0 && Program->Language->CharIsDigit(*str)) {
            str++;
            len++;
        } else {
            found = false;
        }
    }
    if (len == 0) {
        return false;
    }
    char *ident = new char[len + 1];
    MemCopy(ident, start, len);
    ident[len] = 0;
    if ((ksymbol = FindKeyword(ident))) {
        current = new Token(current, ksymbol, startPos);
    } else {
        current = new Token(current, symident, ident, startPos);
    }
    pos += len;
    delete [] ident;
    return true;
}
void Lexer::GetNextToken () [private]
Definition at line 79 of file lexer.cpp.
References Language::CharIsSpace(), current, GetDigitValue(), GetLitteral(), GetOperator(), GetQuotedIdent(), pos, ShouldSkip(), str, symend, symunknown, and Token::Token().
Referenced by Tokenize().
{
    // Skip spaces and non visible characters
    while (*str != 0 && ShouldSkip(*str)) {
        str++;
        if (Program->Language->CharIsSpace(*str)) {
            pos++;
        }
    }
    if (*str == 0)
    {
        current = new Token(current, symend, pos);
    } else if (GetOperator() || GetQuotedIdent() || GetDigitValue() || GetLitteral()) {
        return;
    } else {
        str++;
        pos++;
        current = new Token(current, symunknown, pos - 1);
    }
}
bool Lexer::GetOperator () [private]
Definition at line 101 of file lexer.cpp.
References operatordef::chr, current, operators, pos, str, operatordef::symbol, and Token::Token().
Referenced by GetNextToken().
{
    static const unsigned int count = sizeof(operators) / sizeof(operatordef);
    for (unsigned int i = 0; i < count; i++) {
        if (operators[i].chr == *str) {
            current = new Token(current, operators[i].symbol, pos);
            str++;
            pos++;
            return true;
        }
    }
    return false;
}
bool Lexer::GetQuotedIdent () [private]
Definition at line 116 of file lexer.cpp.
References Language::CharIsCntrl(), current, MemCopy(), pos, str, symqident, and Token::Token().
Referenced by GetNextToken().
{
    if (*str != '"') {
        return false;
    }
    char *start = str;
    const unsigned int startPos = pos;
    int unsigned len = 0;
    str++;
    while (*str != 0 && *str != '"' && !Program->Language->CharIsCntrl(*str)) {
        str++;
        len++;
    }
    if (len == 0 || *str != '"') {
        str = start;
        return false;
    }
    char *ident = new char[len + 1];
    MemCopy(ident, start + 1, len);
    ident[len] = 0;
    current = new Token(current, symqident, ident, startPos);
    str++;
    pos += len + 1;
    delete [] ident;
    return true;
}
bool Lexer::ShouldSkip (char character) [private]
Definition at line 240 of file lexer.cpp.
References Language::CharIsCntrl(), and Language::CharIsSpace().
Referenced by GetNextToken().
{
    if (character == '\n') {
        return false;
    }
    if (Program->Language->CharIsCntrl(character)) {
        return true;
    }
    if (Program->Language->CharIsSpace(character)) {
        return true;
    }
    return false;
}
void Lexer::Tokenize ()
Definition at line 62 of file lexer.cpp.
References current, first, GetNextToken(), input, Token::next, pos, str, Token::symbol, and symend.
Referenced by Parser::Parse().
{
    pos = 0;
    str = input;
    first = NOMEM;
    current = NOMEM;
    GetNextToken();
    first = current;
    do {
        Token* last = current;
        GetNextToken();
        last->next = current;
    } while (current->symbol != symend);
}
Member Data Documentation
Token* Lexer::current [private]
Definition at line 60 of file lexer.h.
Referenced by GetDigitValue(), GetLitteral(), GetNextToken(), GetOperator(), GetQuotedIdent(), Lexer(), and Tokenize().
Token* Lexer::first [private]
Definition at line 59 of file lexer.h.
Referenced by GetFirstToken(), Lexer(), Tokenize(), and ~Lexer().
char* Lexer::input [private]
Definition at line 56 of file lexer.h.
Referenced by GetInput(), Lexer(), Tokenize(), and ~Lexer().
unsigned int Lexer::pos [private]
Definition at line 58 of file lexer.h.
Referenced by GetDigitValue(), GetLitteral(), GetNextToken(), GetOperator(), GetQuotedIdent(), Lexer(), and Tokenize().
char* Lexer::str [private]
Definition at line 57 of file lexer.h.
Referenced by GetDigitValue(), GetLitteral(), GetNextToken(), GetOperator(), GetQuotedIdent(), Lexer(), and Tokenize().
Author
Generated automatically by Doxygen for amath from the source code.