.TH "app/main/lexer.cpp" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/lexer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'main/lexer\&.h'\fP
.br
\fC#include 'main/token\&.h'\fP
.br
\fC#include 'localize/lex\&.h'\fP
.br
\fC#include 'localize/kword\&.h'\fP
.br
\fC#include 'system/program\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
