ListFunctionsStatement
NAME
ListFunctionsStatement - A syntax node able to list all user defined functions.
SYNOPSIS
#include <functions.h>
Inherits StatementNode.
Public Member Functions
ListFunctionsStatement ()
char * Execute ()
Additional Inherited Members
Detailed Description
A syntax node able to list all user defined functions.
Definition at line 137 of file functions.h.
Constructor & Destructor Documentation
ListFunctionsStatement::ListFunctionsStatement ()
Definition at line 479 of file functions.cpp.
References StatementNode::StatementNode().
Referenced by Parser::ParseStatement().
                                               :
    StatementNode() { }
Member Function Documentation
char * ListFunctionsStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 482 of file functions.cpp.
References Program::Functions, and FunctionList::List().
{
    return Program->Functions->List();
}
Author
Generated automatically by Doxygen for amath from the source code.