ListStatement
NAME
ListStatement -
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
ListStatement ()
ListStatement (const char *directory)
~ListStatement ()
char * Execute ()
Private Attributes
char * directory
Additional Inherited Members
Detailed Description
Definition at line 261 of file statements.h.
Constructor & Destructor Documentation
ListStatement::ListStatement ()
Definition at line 608 of file statements.cpp.
References directory, and StatementNode::StatementNode().
Referenced by Parser::ParseListStatement().
                             :
    StatementNode()
{
    directory = NOMEM;
}
ListStatement::ListStatement (const char * directory)
Definition at line 614 of file statements.cpp.
References AllocAndCopy(), directory, and StatementNode::StatementNode().
Referenced by Parser::ParseListStatement().
                                                  :
    StatementNode()
{
    AllocAndCopy(&this->directory, directory);
}
ListStatement::~ListStatement ()
Definition at line 620 of file statements.cpp.
References directory.
{
    if (directory != NOMEM) {
        delete [] directory;
    }
}
Member Function Documentation
char * ListStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 627 of file statements.cpp.
References directory, Program::Filesystem, CharBuffer::GetString(), FilesystemBase::ListDirectory(), and SyntaxNode::output.
{
    CharBuffer *text = Program->Filesystem->ListDirectory(directory);
    if (text == NOMEM)
    {
        return (char*)(MSGNODIR);
    }
    delete output;
    output = text;
    return text->GetString();
}
Member Data Documentation
char* ListStatement::directory [private]
Definition at line 269 of file statements.h.
Referenced by Execute(), ListStatement(), and ~ListStatement().
Author
Generated automatically by Doxygen for amath from the source code.