ListVariablesStatement
NAME
ListVariablesStatement - Statement to list all user defined variables.
SYNOPSIS
#include <values.h>
Inherits StatementNode.
Public Member Functions
ListVariablesStatement ()
char * Execute ()
Additional Inherited Members
Detailed Description
Statement to list all user defined variables.
Definition at line 94 of file values.h.
Constructor & Destructor Documentation
ListVariablesStatement::ListVariablesStatement ()
Definition at line 259 of file values.cpp.
References StatementNode::StatementNode().
Referenced by Parser::ParseStatement().
    : StatementNode() { }
Member Function Documentation
char * ListVariablesStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 262 of file values.cpp.
References VariableList::List(), and Program::Variables.
{
    return Program->Variables->List();
}
Author
Generated automatically by Doxygen for amath from the source code.