.TH "ListVariablesStatement" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ListVariablesStatement \- Statement to list all user defined variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <values\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBListVariablesStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Statement to list all user defined variables\&. 
.PP
Definition at line 94 of file values\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ListVariablesStatement::ListVariablesStatement ()"

.PP
Definition at line 259 of file values\&.cpp\&.
.PP
References StatementNode::StatementNode()\&.
.PP
Referenced by Parser::ParseStatement()\&.
.PP
.nf
260     : StatementNode() { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * ListVariablesStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 262 of file values\&.cpp\&.
.PP
References VariableList::List(), and Program::Variables\&.
.PP
.nf
263 {
264     return Program->Variables->List();
265 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
