LnRootNode
NAME
LnRootNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
LnRootNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 308 of file functions.h.
Constructor & Destructor Documentation
LnRootNode::LnRootNode (ExpressionNode * expression)
Definition at line 698 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                 :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * LnRootNode::Create (ExpressionNode * expression) [static]
Definition at line 701 of file functions.cpp.
References LnRootNode().
{
    return new LnRootNode(expression);
}
Number * LnRootNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 706 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::Log(), and ExpressionNode::result.
{
    result = expression->Evaluate()->Log();
    return result;
}
char * LnRootNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 712 of file functions.cpp.
{
    return (char*)"ln";
}
Author
Generated automatically by Doxygen for amath from the source code.