LoadStatement
NAME
LoadStatement -
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
LoadStatement (const char *file)
~LoadStatement ()
char * Execute ()
Private Attributes
char * file
Additional Inherited Members
Detailed Description
Definition at line 272 of file statements.h.
Constructor & Destructor Documentation
LoadStatement::LoadStatement (const char * file)
Definition at line 644 of file statements.cpp.
References AllocAndCopy(), and file.
Referenced by Parser::ParseFileStatement().
{
    AllocAndCopy(&this->file, file);
}
LoadStatement::~LoadStatement ()
Definition at line 649 of file statements.cpp.
References file.
{
    delete [] file;
}
Member Function Documentation
char * LoadStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 654 of file statements.cpp.
References SyntaxNode::Execute(), file, Program::Filesystem, CharBuffer::GetString(), FilesystemBase::LoadTextFile(), Parser::Parse(), and Parser::Parser().
{
    CharBuffer *input = Program->Filesystem->LoadTextFile(file);
    if (input == NOMEM)
    {
        return (char*)(MSGNOFILE);
    }
    Parser *parser = new Parser(input->GetString());
    delete input;
    SyntaxNode *node = parser->Parse();
    delete parser;
    node->Execute();
    delete node;
    return (char*)HELPLOADSUCC;
}
Member Data Documentation
char* LoadStatement::file [private]
Definition at line 279 of file statements.h.
Referenced by Execute(), LoadStatement(), and ~LoadStatement().
Author
Generated automatically by Doxygen for amath from the source code.