.TH "LogNode" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LogNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLogNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 298 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "LogNode::LogNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 721 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
721                                            :
722     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * LogNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 724 of file functions\&.cpp\&.
.PP
References LogNode()\&.
.PP
.nf
725 {
726     return new LogNode(expression);
727 }
.fi
.SS "\fBNumber\fP * LogNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 729 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::Log10(), and ExpressionNode::result\&.
.PP
.nf
730 {
731     result = expression->Evaluate()->Log10();
732     return result;
733 }
.fi
.SS "char * LogNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 735 of file functions\&.cpp\&.
.PP
.nf
736 {
737     return (char*)"lg";
738 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
