LogNode
NAME
LogNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
LogNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 298 of file functions.h.
Constructor & Destructor Documentation
LogNode::LogNode (ExpressionNode * expression)
Definition at line 721 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                           :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * LogNode::Create (ExpressionNode * expression) [static]
Definition at line 724 of file functions.cpp.
References LogNode().
{
    return new LogNode(expression);
}
Number * LogNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 729 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, Number::Log10(), and ExpressionNode::result.
{
    result = expression->Evaluate()->Log10();
    return result;
}
char * LogNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 735 of file functions.cpp.
{
    return (char*)"lg";
}
Author
Generated automatically by Doxygen for amath from the source code.