.TH "app/main.cpp" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'system/program\&.h'\fP
.br
\fC#include 'system/base/io\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Definition at line 30 of file main\&.cpp\&.
.PP
References Cleanup(), CreateProgram(), Program::Initialize(), and Program::Run()\&.
.PP
.nf
31 {
32     Program = CreateProgram(argc, argv);
33     Program->Initialize(argc, argv);
34     Program->Run();
35     Cleanup();
36     return 0;
37 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
