app/main.cpp
NAME
app/main.cpp -
SYNOPSIS
#include 'system/program.h'
#include 'system/base/io.h'
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
Definition at line 30 of file main.cpp.
References Cleanup(), CreateProgram(), Program::Initialize(), and Program::Run().
{
    Program = CreateProgram(argc, argv);
    Program->Initialize(argc, argv);
    Program->Run();
    Cleanup();
    return 0;
}
Author
Generated automatically by Doxygen for amath from the source code.