lib/clib/mem.c
NAME
lib/clib/mem.c -
SYNOPSIS
#include 'mem.h'
#include 'clib.h'
#include <stdlib.h>
Classes
struct MemoryBlock
Block of allocated memory.
struct MemoryList
List of allocated memory. Uses the LIFO principle.
Macros
#define ALLOC_MEM(x) calloc(1L,x)
#define FREE_MEM(x) free(x)
#define Debug(x, y, z)
Functions
void alloc_error (char *descr, size_t size)
Log a mememory allocation error.
void dealloc_error (char *descr, void *p)
Log a mememory deallocation error.
void * AllocMemSafe (size_t size)
Allocate memory and add it to the global memory list.
void FreeMemSafe (void *block)
Deallocate memory from the global memory list.
void FreeAllSafe ()
Deallocate all memory in the global memory list.
void MemUsage (long *blocks, long *size, long *peak)
Get memory usage in the global memory list.
Variables
struct MemoryList * list = NULL
Global list of allocated memory.
Macro Definition Documentation
#define ALLOC_MEM(x) calloc(1L,x)
Definition at line 41 of file mem.c.
#define Debug(x, y, z)
Definition at line 43 of file mem.c.
#define FREE_MEM(x) free(x)
Definition at line 42 of file mem.c.
Function Documentation
void alloc_error (char * descr, size_t size)
Log a mememory allocation error.
Definition at line 217 of file mem.c.
Referenced by AllocMemSafe().
{
    Debug("Mememory allocation error (%s) with size (%d)\n", descr, size);
}
void* AllocMemSafe (size_t size)
Allocate memory and add it to the global memory list.
Definition at line 78 of file mem.c.
References MemoryBlock::address, alloc_error(), MemoryList::count, MemoryList::first, list, MemoryBlock::next, MemoryList::peak, and MemoryList::size.
{
    struct MemoryBlock *newblock;
    size_t allocsize;
    if (list == NULL) {
        list = (struct MemoryList*)ALLOC_MEM(sizeof(struct MemoryList));
        if (!list) {
            alloc_error("list", sizeof(struct MemoryList));
            return 0;
        }
        list->first = NULL;
        list->peak = 0;
        list->size = 0;
        list->count = 0;
    }
#if defined(__x86_64__) || defined(__aarch64__) || defined(_M_AMD64) || defined(_M_ARM64)
    // Align to bytes of 8
    allocsize = (size + 7) & ~0x07;
#else
    // Align to bytes of 4
    allocsize = (size + 3) & ~0x03;
#endif
    newblock = (struct MemoryBlock*)ALLOC_MEM(sizeof(struct MemoryBlock));
    if (!newblock) {
        alloc_error("block", sizeof(struct MemoryBlock));
        return 0;
    }
    newblock->address = (struct MemoryBlock*)ALLOC_MEM(allocsize);
    if (!newblock->address) {
        FREE_MEM(newblock);
        alloc_error("memory", allocsize);
        return 0;
    }
    newblock->size = allocsize;
    newblock->next = list->first;
    list->first = newblock;
    list->size += allocsize;
    list->count++;
    if (list->size > list->peak) {
        list->peak = list->size;
    }
    // DEBUG code
    // Debug(NULL, "Mememory allocated at address (%x)\n", newblock->address);
    return newblock->address;
}
void dealloc_error (char * descr, void * p)
Log a mememory deallocation error.
Definition at line 225 of file mem.c.
Referenced by FreeMemSafe().
{
    Debug("Mememory deallocation error (%s) address (%x)\n", descr, p);
}
void FreeAllSafe ()
Deallocate all memory in the global memory list.
Definition at line 184 of file mem.c.
References MemoryBlock::address, MemoryList::first, list, and MemoryBlock::next.
Referenced by Cleanup().
{
    struct MemoryBlock *current, *next;
    if (list == NULL) {
        return;
    }
    current = list->first;
    while (current != NULL) {
        next = current->next;
        FREE_MEM(current->address);
        FREE_MEM(current);
        current = next;
    }
    FREE_MEM(list);
    list = NULL;
}
void FreeMemSafe (void * block)
Deallocate memory from the global memory list.
Definition at line 136 of file mem.c.
References MemoryBlock::address, MemoryList::count, dealloc_error(), MemoryList::first, list, and MemoryBlock::next.
{
    struct MemoryBlock *current, *previous;
    if (list == NULL || block == NULL) {
        dealloc_error("list", 0);
        return;
    }
    if (block == NULL) {
        dealloc_error("memory", 0);
        return;
    }
    previous = NULL;
    current = list->first;
    while (current != NULL && current->address != block) {
        previous = current;
        current = current->next;
    }
    if (current == NULL) {
        dealloc_error("address not found", block);
        return;
    }
    if (previous == NULL) {
        list->first = current->next;
    } else {
        previous->next = current->next;
    }
    list->size -= current->size;
    list->count--;
    FREE_MEM(current->address);
    current->address = NULL;
    current->next = NULL;
    current->size = 0;
    FREE_MEM(current);
    // DEBUG code
    // Debug("Mememory deallocated at address (%x)\n", block);
}
void MemUsage (long * blocks, long * size, long * peak)
Get memory usage in the global memory list.
Definition at line 207 of file mem.c.
References MemoryList::count, list, MemoryList::peak, and MemoryList::size.
Referenced by MemoryStatement::Execute().
{
    *blocks = list->count;
    *size = list->size;
    *peak = list->peak;;
}
Variable Documentation
struct MemoryList* list = NULL
Global list of allocated memory.
Definition at line 70 of file mem.c.
Referenced by AllocMemSafe(), FreeAllSafe(), FreeMemSafe(), and MemUsage().
Author
Generated automatically by Doxygen for amath from the source code.