lib/clib/memcpy.c
NAME
lib/clib/memcpy.c -
SYNOPSIS
#include 'clib.h'
Macros
#define TLOOP(s) if (t) TLOOP1(s)
#define TLOOP1(s) do { s; } while (--t)
Typedefs
typedef int word
Functions
void MemCopy (void *destination, const void *source, unsigned int length)
Copy a block of memory, handling overlap.
Macro Definition Documentation
#define TLOOP(s) if (t) TLOOP1(s)
Macros: loop-t-times; and loop-t-times, t>0
Definition at line 50 of file memcpy.c.
#define TLOOP1(s) do { s; } while (--t)
Definition at line 51 of file memcpy.c.
Typedef Documentation
typedef int word
sizeof(word) MUST BE A POWER OF TWO SO THAT wmask BELOW IS ALL ONES
Definition at line 44 of file memcpy.c.
Function Documentation
void MemCopy (void * destination, const void * source, unsigned int length)
Copy a block of memory, handling overlap. Original file can be found at: https://svnweb.freebsd.org/base/release/9.0.0/lib/libc/string/bcopy.c?revision=229286
Definition at line 60 of file memcpy.c.
Referenced by CharBuffer::EnsureSize(), FormatPositional(), FormatScientific(), Lexer::GetDigitValue(), Lexer::GetLitteral(), Lexer::GetQuotedIdent(), PrintInfNan(), and Language::UntagText().
{
    char *dst = (char*) destination;
    const char *src = (const char*) source;
    unsigned int t;
    if (length == 0 || dst == src) // nothing to do
        return;
    if ((unsigned long)dst < (unsigned long)src) {
        // Copy forward
        t = (unsigned long)src; // only need low bits
        if ((t | (unsigned long)dst) & wmask) {
            // Try to align operands. This cannot be done unless the low bits match.
            if ((t ^ (unsigned long)dst) & wmask || length < wsize)
                t = length;
            else
                t = wsize - (t & wmask);
            length -= t;
            TLOOP1(*dst++ = *src++);
        }
        // Copy whole words, then mop up any trailing bytes.
        t = length / wsize;
        TLOOP(*(word *)dst = *(word *)src; src += wsize; dst += wsize);
        t = length & wmask;
        TLOOP(*dst++ = *src++);
    } else {
        // Copy backwards. Otherwise essentially the same.
        // Alignment works as before, except that it takes
        // (t&wmask) bytes to align, not wsize-(t&wmask).
        src += length;
        dst += length;
        t = (unsigned long)src;
        if ((t | (unsigned long)dst) & wmask) {
            if ((t ^ (unsigned long)dst) & wmask || length <= wsize)
                t = length;
            else
                t &= wmask;
            length -= t;
            TLOOP1(*--dst = *--src);
        }
        t = length / wsize;
        TLOOP(src -= wsize; dst -= wsize; *(word *)dst = *(word *)src);
        t = length & wmask;
        TLOOP(*--dst = *--src);
    }
}
Author
Generated automatically by Doxygen for amath from the source code.