.TH "MemoryList" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryList \- List of allocated memory\&. Uses the LIFO principle\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBMemoryBlock\fP * \fBfirst\fP"
.br
.ti -1c
.RI "long \fBpeak\fP"
.br
.ti -1c
.RI "long \fBsize\fP"
.br
.ti -1c
.RI "long \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
List of allocated memory\&. Uses the LIFO principle\&. 
.PP
Definition at line 59 of file mem\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "long MemoryList::count"

.PP
Definition at line 64 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), FreeMemSafe(), and MemUsage()\&.
.SS "struct \fBMemoryBlock\fP* MemoryList::first"

.PP
Definition at line 61 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), FreeAllSafe(), and FreeMemSafe()\&.
.SS "long MemoryList::peak"

.PP
Definition at line 62 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), and MemUsage()\&.
.SS "long MemoryList::size"

.PP
Definition at line 63 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), and MemUsage()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
