.TH "MemoryStatement" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryStatement \- Show memory usage\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statements\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemoryStatement\fP ()"
.br
.ti -1c
.RI "\fB~MemoryStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Show memory usage\&. 
.PP
Definition at line 94 of file statements\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemoryStatement::MemoryStatement ()\fC [inline]\fP"

.PP
Definition at line 96 of file statements\&.h\&.
.PP
Referenced by Parser::ParseStatement()\&.
.PP
.nf
96 { }
.fi
.SS "MemoryStatement::~MemoryStatement ()\fC [inline]\fP"

.PP
Definition at line 97 of file statements\&.h\&.
.PP
.nf
97 { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * MemoryStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 163 of file statements\&.cpp\&.
.PP
References CharBuffer::Append(), DecimalSystem::DecimalSystem(), CharBuffer::Empty(), CharBuffer::EnsureSize(), CharBuffer::GetString(), NumeralSystem::GetText(), MemUsage(), SyntaxNode::output, RealNumber::RealNumber(), and StrLen()\&.
.PP
.nf
164 {
165     long blocks, size, peak;
166     MemUsage(&blocks, &size, &peak);
167     Number *a = new RealNumber((int)blocks);
168     Number *b = new RealNumber((int)size);
169     Number *c = new RealNumber((int)peak);
170 
171     NumeralSystem *ns = new DecimalSystem(8);
172     output->Empty();
173     output->EnsureSize(
174         StrLen(TXTMEMBLOCKS) + 8 +
175         StrLen(TXTMEMSIZE) + 12 +
176         StrLen(TXTMEMMAXSIZE) + 12);
177     output->Append(TXTMEMBLOCKS);
178     output->Append(ns->GetText(a));
179     output->Append(NEWLINE);
180     output->Append(TXTMEMSIZE);
181     output->Append(ns->GetText(b));
182     output->Append(NEWLINE);
183     output->Append(TXTMEMMAXSIZE);
184     output->Append(ns->GetText(c));
185     output->Append(NEWLINE);
186 
187     delete a;
188     delete b;
189     delete c;
190     delete ns;
191     return output->GetString();
192 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
