MemoryStatement
NAME
MemoryStatement - Show memory usage.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
MemoryStatement ()
~MemoryStatement ()
char * Execute ()
Additional Inherited Members
Detailed Description
Show memory usage.
Definition at line 94 of file statements.h.
Constructor & Destructor Documentation
MemoryStatement::MemoryStatement () [inline]
Definition at line 96 of file statements.h.
Referenced by Parser::ParseStatement().
{ }
MemoryStatement::~MemoryStatement () [inline]
Definition at line 97 of file statements.h.
{ }
Member Function Documentation
char * MemoryStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 163 of file statements.cpp.
References CharBuffer::Append(), DecimalSystem::DecimalSystem(), CharBuffer::Empty(), CharBuffer::EnsureSize(), CharBuffer::GetString(), NumeralSystem::GetText(), MemUsage(), SyntaxNode::output, RealNumber::RealNumber(), and StrLen().
{
    long blocks, size, peak;
    MemUsage(&blocks, &size, &peak);
    Number *a = new RealNumber((int)blocks);
    Number *b = new RealNumber((int)size);
    Number *c = new RealNumber((int)peak);
    NumeralSystem *ns = new DecimalSystem(8);
    output->Empty();
    output->EnsureSize(
        StrLen(TXTMEMBLOCKS) + 8 +
        StrLen(TXTMEMSIZE) + 12 +
        StrLen(TXTMEMMAXSIZE) + 12);
    output->Append(TXTMEMBLOCKS);
    output->Append(ns->GetText(a));
    output->Append(NEWLINE);
    output->Append(TXTMEMSIZE);
    output->Append(ns->GetText(b));
    output->Append(NEWLINE);
    output->Append(TXTMEMMAXSIZE);
    output->Append(ns->GetText(c));
    output->Append(NEWLINE);
    delete a;
    delete b;
    delete c;
    delete ns;
    return output->GetString();
}
Author
Generated automatically by Doxygen for amath from the source code.