.TH "MemoryList" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryList \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBMemoryBlock\fP * \fBfirst\fP"
.br
.ti -1c
.RI "struct \fBMemoryBlock\fP * \fBlast\fP"
.br
.ti -1c
.RI "long \fBpeak\fP"
.br
.ti -1c
.RI "long \fBsize\fP"
.br
.ti -1c
.RI "long \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file mem\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "long MemoryList::count"

.PP
Definition at line 59 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), FreeMemSafe(), and MemUsage()\&.
.SS "struct \fBMemoryBlock\fP* MemoryList::first"

.PP
Definition at line 55 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), FreeAllSafe(), and FreeMemSafe()\&.
.SS "struct \fBMemoryBlock\fP* MemoryList::last"

.PP
Definition at line 56 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), and FreeMemSafe()\&.
.SS "long MemoryList::peak"

.PP
Definition at line 57 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), and MemUsage()\&.
.SS "long MemoryList::size"

.PP
Definition at line 58 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), and MemUsage()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
