.TH "MemoryBlock" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MemoryBlock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBMemoryBlock\fP * \fBnext\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "void * \fBaddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file mem\&.c\&.
.SH "Member Data Documentation"
.PP 
.SS "void* MemoryBlock::address"

.PP
Definition at line 50 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), FreeAllSafe(), and FreeMemSafe()\&.
.SS "struct \fBMemoryBlock\fP* MemoryBlock::next"

.PP
Definition at line 48 of file mem\&.c\&.
.PP
Referenced by AllocMemSafe(), FreeAllSafe(), and FreeMemSafe()\&.
.SS "size_t MemoryBlock::size"

.PP
Definition at line 49 of file mem\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
