MultiplicationNode
NAME
MultiplicationNode -
SYNOPSIS
#include <operators.h>
Inherits NumericOperator.
Public Member Functions
MultiplicationNode (ExpressionNode *left, ExpressionNode *right)
int GetPrecedence ()
Number * Evaluate ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 118 of file operators.h.
Constructor & Destructor Documentation
MultiplicationNode::MultiplicationNode (ExpressionNode * left, ExpressionNode * right)
Definition at line 357 of file operators.cpp.
References NumericOperator::NumericOperator().
Referenced by Parser::ParseFactor().
                                                                                  :
    NumericOperator(left, right) { }
Member Function Documentation
Number * MultiplicationNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 365 of file operators.cpp.
References ExpressionNode::Evaluate(), NumericOperator::left, Number::Mul(), ExpressionNode::result, and NumericOperator::right.
{
    result = left->Evaluate()->Mul(right->Evaluate());
    return result;
}
char * MultiplicationNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 371 of file operators.cpp.
{
    return (char*)"*";
}
int MultiplicationNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 360 of file operators.cpp.
{
    return 3;
}
Author
Generated automatically by Doxygen for amath from the source code.