.TH "app/main/nodes.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/nodes.h \- Top nodes in syntax trees\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/numb\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyntaxNode\fP"
.br
.RI "\fIBase class for all nodes in a syntax tree\&. \fP"
.ti -1c
.RI "class \fBExpressionNode\fP"
.br
.RI "\fIBase class for all nodes related to mathematical expressions\&. \fP"
.ti -1c
.RI "class \fBStatementNode\fP"
.br
.RI "\fIBase class for all statements in a syntax tree\&. \fP"
.ti -1c
.RI "class \fBErrorNode\fP"
.br
.RI "\fIRepresents an error message encapsulated in a syntax tree\&. \fP"
.ti -1c
.RI "class \fBStatementBlockNode\fP"
.br
.RI "\fIA sequence of statements in a syntax tree\&. \fP"
.ti -1c
.RI "struct \fBStatementBlockElement\fP"
.br
.RI "\fIUsed to create a linked list of statements\&. \fP"
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNodeType\fP { \fBothernodetype\fP, \fBstatement\fP, \fBexpression\fP }"
.br
.ti -1c
.RI "enum \fBReductionType\fP { \fBnonereduc\fP, \fBunaryreduc\fP, \fBvaluereduc\fP, \fBcompladdreduc\fP, \fBcomplsubreduc\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Top nodes in syntax trees\&. 


.PP
Definition in file \fBnodes\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNodeType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIothernodetype \fP\fP
.TP
\fB\fIstatement \fP\fP
.TP
\fB\fIexpression \fP\fP
.PP
Definition at line 40 of file nodes\&.h\&.
.PP
.nf
40              {
41     othernodetype, statement, expression
42 } NodeType;
.fi
.SS "enum \fBReductionType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fInonereduc \fP\fP
.TP
\fB\fIunaryreduc \fP\fP
.TP
\fB\fIvaluereduc \fP\fP
.TP
\fB\fIcompladdreduc \fP\fP
.TP
\fB\fIcomplsubreduc \fP\fP
.PP
Definition at line 44 of file nodes\&.h\&.
.PP
.nf
44              {
45     nonereduc, unaryreduc, valuereduc, compladdreduc, complsubreduc
46 } ReductionType;
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
