.TH "app/lib/ntext.h" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/ntext.h \- Text to numbers handling\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lib/numb\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNumeralSystem\fP"
.br
.RI "\fIBase class for all numeral systems\&. \fP"
.ti -1c
.RI "class \fBPositionalNumeralSystem\fP"
.br
.RI "\fIBase class for all numeral systems with a positional notation\&. \fP"
.ti -1c
.RI "class \fBDecimalSystem\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Text to numbers handling\&. 

Converts both between text and numbers AND between numbers and text\&. 
.PP
Definition in file \fBntext\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
