.TH "app/lib/ntext.cpp" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/ntext.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'dprint\&.h'\fP
.br
\fC#include 'complex\&.h'\fP
.br
\fC#include 'lib/real\&.h'\fP
.br
\fC#include 'lib/cplex\&.h'\fP
.br
\fC#include 'lib/ntext\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
