Number
NAME
Number -
SYNOPSIS
#include <numb.h>
Inherited by ComplexNumber, and RealNumber.
Public Member Functions
Number (NumberSystem system)
virtual ~Number ()
virtual Number * Clone ()=0
virtual int GetIntegerValue ()=0
virtual double GetRealValue ()=0
virtual bool PureComplexValue ()=0
virtual int GetPrecedence ()=0
virtual int GetDefaultPrecedence ()=0
virtual Number * Unary ()=0
virtual Number * Add (Number *other)=0
virtual Number * Sub (Number *other)=0
virtual Number * Mul (Number *other)=0
virtual Number * Div (Number *other)=0
virtual Number * Raise (Number *exponent)=0
virtual Number * Signum ()=0
virtual Number * Trunc ()=0
virtual Number * Round ()=0
virtual Number * Floor ()=0
virtual Number * Ceiling ()=0
virtual Number * Absolute ()=0
virtual Number * SquareRoot ()=0
virtual Number * CubeRoot ()=0
virtual Number * Reciprocal ()=0
virtual Number * Log ()=0
virtual Number * Log2 ()=0
virtual Number * Log10 ()=0
virtual Number * Sine ()=0
virtual Number * Cosine ()=0
virtual Number * Tangent ()=0
virtual Number * Cosecant ()=0
virtual Number * Secant ()=0
virtual Number * Cotangent ()=0
virtual Number * ArcSine ()=0
virtual Number * ArcCosine ()=0
virtual Number * ArcTangent ()=0
virtual Number * ArcCosecant ()=0
virtual Number * ArcSecant ()=0
virtual Number * ArcCotangent ()=0
virtual Number * HypSine ()=0
virtual Number * HypCosine ()=0
virtual Number * HypTangent ()=0
virtual Number * HypCosecant ()=0
virtual Number * HypSecant ()=0
virtual Number * HypCotangent ()=0
virtual Number * HypArcSine ()=0
virtual Number * HypArcCosine ()=0
virtual Number * HypArcTangent ()=0
virtual Number * HypArcCosecant ()=0
virtual Number * HypArcSecant ()=0
virtual Number * HypArcCotangent ()=0
Protected Attributes
NumberSystem system
Friends
class PositionalNumeralSystem
class DecimalSystem
struct RealNumber
struct ComplexNumber
Detailed Description
Definition at line 48 of file numb.h.
Constructor & Destructor Documentation
Number::Number (NumberSystem system) [inline]
Definition at line 50 of file numb.h.
References system.
Referenced by ComplexNumber::ComplexNumber(), and RealNumber::RealNumber().
: system(system) { }
virtual Number::~Number () [inline], [virtual]
Definition at line 51 of file numb.h.
{ }
Member Function Documentation
virtual Number* Number::Absolute () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by AbsoluteNode::Evaluate(), and AbsoluteFunctionNode::Evaluate().
virtual Number* Number::Add (Number * other) [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by RealNumber::Add(), AdditionNode::Evaluate(), Optimizer::ReduceValueNodes(), and RealNumber::Sub().
virtual Number* Number::ArcCosecant () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by ArcCosecantNode::Evaluate().
virtual Number* Number::ArcCosine () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by ArcCosineNode::Evaluate().
virtual Number* Number::ArcCotangent () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by ArcCotangentNode::Evaluate().
virtual Number* Number::ArcSecant () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by ArcSecantNode::Evaluate().
virtual Number* Number::ArcSine () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by ArcSineNode::Evaluate().
virtual Number* Number::ArcTangent () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by ArcTangentNode::Evaluate().
virtual Number* Number::Ceiling () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by CeilingNode::Evaluate().
virtual Number* Number::Clone () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by Variable::AssignValue(), Variable::GetValue(), and Program::SetLastResult().
virtual Number* Number::Cosecant () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by CosecantNode::Evaluate().
virtual Number* Number::Cosine () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by CosineNode::Evaluate().
virtual Number* Number::Cotangent () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by CotangentNode::Evaluate().
virtual Number* Number::CubeRoot () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by CubeRootNode::Evaluate().
virtual Number* Number::Div (Number * other) [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by DivisionNode::Evaluate().
virtual Number* Number::Floor () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by FloorNode::Evaluate().
virtual int Number::GetDefaultPrecedence () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by NumericValueNode::GetPrecedence().
virtual int Number::GetIntegerValue () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by Parser::ParseDigistStatement(), and Parser::ParseNumeralStatement().
virtual int Number::GetPrecedence () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by NumericValueNode::GetPrecedence().
virtual double Number::GetRealValue () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by Grid::FunctionValue(), PositionalNumeralSystem::GetText(), DecimalSystem::GetText(), and Parser::ParseNumber().
virtual Number* Number::HypArcCosecant () [pure virtual]
Implemented in ComplexNumber, and RealNumber.
Referenced by HyperbolicArcCosecantNode::Evaluate().
virtual Number* Number::HypArcCosine () [pure virtual]
Implemented in ComplexNumber, and RealNumber.
Referenced by HyperbolicArccosineNode::Evaluate().
virtual Number* Number::HypArcCotangent () [pure virtual]
Implemented in ComplexNumber, and RealNumber.
Referenced by HyperbolicArcCotangentNode::Evaluate().
virtual Number* Number::HypArcSecant () [pure virtual]
Implemented in ComplexNumber, and RealNumber.
Referenced by HyperbolicArcSecantNode::Evaluate().
virtual Number* Number::HypArcSine () [pure virtual]
Implemented in ComplexNumber, and RealNumber.
Referenced by HyperbolicArcsineNode::Evaluate().
virtual Number* Number::HypArcTangent () [pure virtual]
Implemented in ComplexNumber, and RealNumber.
Referenced by HyperbolicArctangentNode::Evaluate().
virtual Number* Number::HypCosecant () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by HyperbolicCosecantNode::Evaluate().
virtual Number* Number::HypCosine () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by HyperbolicCosineNode::Evaluate().
virtual Number* Number::HypCotangent () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by HyperbolicCotangentNode::Evaluate().
virtual Number* Number::HypSecant () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by HyperbolicSecantNode::Evaluate().
virtual Number* Number::HypSine () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by HyperbolicSineNode::Evaluate().
virtual Number* Number::HypTangent () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by HyperbolicTangentNode::Evaluate().
virtual Number* Number::Log () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by LnRootNode::Evaluate().
virtual Number* Number::Log10 () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by LogNode::Evaluate().
virtual Number* Number::Log2 () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by BinaryLogNode::Evaluate().
virtual Number* Number::Mul (Number * other) [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by MultiplicationNode::Evaluate(), and RealNumber::Mul().
virtual bool Number::PureComplexValue () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by Optimizer::ReduceValueNodes().
virtual Number* Number::Raise (Number * exponent) [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by PowerNode::Evaluate().
virtual Number* Number::Reciprocal () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by RealNumber::Div().
virtual Number* Number::Round () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by RoundNode::Evaluate().
virtual Number* Number::Secant () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by SecantNode::Evaluate().
virtual Number* Number::Signum () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by SignumNode::Evaluate().
virtual Number* Number::Sine () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by SineNode::Evaluate().
virtual Number* Number::SquareRoot () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by SquareRootNode::Evaluate(), and RealNumber::SquareRoot().
virtual Number* Number::Sub (Number * other) [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by SubtractionNode::Evaluate(), and Optimizer::ReduceValueNodes().
virtual Number* Number::Tangent () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by TangentNode::Evaluate().
virtual Number* Number::Trunc () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by TruncNode::Evaluate().
virtual Number* Number::Unary () [pure virtual]
Implemented in RealNumber, and ComplexNumber.
Referenced by UnaryNode::Evaluate(), Optimizer::ReduceUnaryNodes(), and RealNumber::Sub().
Friends And Related Function Documentation
friend struct ComplexNumber [friend]
Definition at line 111 of file numb.h.
friend class DecimalSystem [friend]
Definition at line 109 of file numb.h.
friend class PositionalNumeralSystem [friend]
Definition at line 108 of file numb.h.
friend struct RealNumber [friend]
Definition at line 110 of file numb.h.
Member Data Documentation
NumberSystem Number::system [protected]
Definition at line 114 of file numb.h.
Referenced by ComplexNumber::Add(), RealNumber::Add(), ComplexNumber::Div(), RealNumber::Div(), PositionalNumeralSystem::GetText(), DecimalSystem::GetText(), ComplexNumber::Mul(), RealNumber::Mul(), Number(), ComplexNumber::Raise(), RealNumber::Raise(), ComplexNumber::Sub(), and RealNumber::Sub().
Author
Generated automatically by Doxygen for amath from the source code.