.TH "app/lib/numb.h" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/numb.h \- Classbase handling of numbers\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBNumber\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNumberSystem\fP { \fBnsysnatural\fP, \fBnsysintegers\fP, \fBnsysrational\fP, \fBnsysreal\fP, \fBnsyscomplex\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Classbase handling of numbers\&. 


.PP
Definition in file \fBnumb\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBNumberSystem\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fInsysnatural \fP\fP
.TP
\fB\fInsysintegers \fP\fP
.TP
\fB\fInsysrational \fP\fP
.TP
\fB\fInsysreal \fP\fP
.TP
\fB\fInsyscomplex \fP\fP
.PP
Definition at line 40 of file numb\&.h\&.
.PP
.nf
40              {
41     nsysnatural,
42     nsysintegers,
43     nsysrational,
44     nsysreal,
45     nsyscomplex
46 } NumberSystem;
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
