NumericValueNode
NAME
NumericValueNode - Use of a numeric value in a syntax tree.
SYNOPSIS
#include <values.h>
Inherits ExpressionNode.
Inherited by ComplexiNode, EulersNumberNode, and PiNode.
Public Member Functions
NumericValueNode ()
NumericValueNode (Number *value)
virtual ReductionType GetReductionType ()
int GetPrecedence ()
char * GetText ()
SyntaxNode * GetNext ()
Number * Evaluate ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
void ReplaceWith (Number *value)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Use of a numeric value in a syntax tree.
Definition at line 142 of file values.h.
Constructor & Destructor Documentation
NumericValueNode::NumericValueNode ()
Definition at line 341 of file values.cpp.
References ExpressionNode::ExpressionNode(), and RealNumber::RealNumber().
Referenced by Parser::ParseAtomic(), and Parser::ParseIdent().
                                   :
    ExpressionNode(new RealNumber()) { }
NumericValueNode::NumericValueNode (Number * value)
Definition at line 344 of file values.cpp.
References ExpressionNode::ExpressionNode().
Referenced by ComplexiNode::ComplexiNode(), EulersNumberNode::EulersNumberNode(), Parser::ParseNumber(), PiNode::PiNode(), and Optimizer::ReduceValueNodes().
                                                :
    ExpressionNode(value) { }
Member Function Documentation
void NumericValueNode::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 381 of file values.cpp.
{ }
void NumericValueNode::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 384 of file values.cpp.
{ }
Number * NumericValueNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 359 of file values.cpp.
References ExpressionNode::result.
Referenced by Optimizer::ReduceUnaryNodes(), and Optimizer::ReduceValueNodes().
{
    return result;
}
SyntaxNode * NumericValueNode::GetNext () [virtual]
Implements SyntaxNode.
Definition at line 376 of file values.cpp.
{
    return NOMEM;
}
char * NumericValueNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Reimplemented in ComplexiNode, PiNode, and EulersNumberNode.
Definition at line 369 of file values.cpp.
References CharBuffer::ClearAndCopy(), CharBuffer::GetString(), NumeralSystem::GetText(), Program::Input, SyntaxNode::output, and ExpressionNode::result.
Referenced by GetText().
{
    const char *val = Program->Input->GetText(result);
    output->ClearAndCopy(val);
    return output->GetString();
}
int NumericValueNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 352 of file values.cpp.
References Number::GetDefaultPrecedence(), Number::GetPrecedence(), SyntaxNode::leftBottom, and ExpressionNode::result.
{
    return !leftBottom ?
           result->GetPrecedence() :
           result->GetDefaultPrecedence();
}
ReductionType NumericValueNode::GetReductionType () [virtual]
Reimplemented from SyntaxNode.
Reimplemented in ComplexiNode, PiNode, and EulersNumberNode.
Definition at line 347 of file values.cpp.
References valuereduc.
Referenced by Optimizer::ReduceValueNodes().
{
    return valuereduc;
}
char * NumericValueNode::GetText () [virtual]
Implements ExpressionNode.
Definition at line 364 of file values.cpp.
References GetNodeText().
{
    return GetNodeText();
}
void NumericValueNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Definition at line 387 of file values.cpp.
{ }
void NumericValueNode::ReplaceWith (Number * value)
Definition at line 390 of file values.cpp.
References ExpressionNode::result.
Referenced by Optimizer::ReduceUnaryNodes().
{
    delete result;
    result = value;
}
Author
Generated automatically by Doxygen for amath from the source code.