NumeralSystem
NAME
NumeralSystem - Base class for all numeral systems.
SYNOPSIS
#include <ntext.h>
Inherited by PositionalNumeralSystem.
Public Member Functions
NumeralSystem ()
virtual ~NumeralSystem ()
virtual const char * GetName ()=0
virtual const char * GetPrefix ()=0
virtual unsigned int GetDigits ()=0
virtual void SetDigits (unsigned int digits)=0
virtual const char GetFractionPoint ()=0
virtual void SetFractionPoint (const char fractionpoint)=0
virtual const char * GetText (Number *number)=0
virtual Number * Parse (const char *text, unsigned int *length, char **end)=0
virtual Number * Parse (const char *text)
Protected Attributes
CharBuffer * buf
Detailed Description
Base class for all numeral systems.
More info on numeral systems is available at Wikipedia: http://en.wikipedia.org/wiki/Numeral_system
Definition at line 48 of file ntext.h.
Constructor & Destructor Documentation
NumeralSystem::NumeralSystem ()
Definition at line 38 of file ntext.cpp.
References buf, CharBuffer::CharBuffer(), and CharBuffer::Empty().
{
    buf = new CharBuffer();
    buf->Empty();
}
NumeralSystem::~NumeralSystem () [virtual]
Definition at line 44 of file ntext.cpp.
References buf.
{
    delete buf;
}
Member Function Documentation
virtual unsigned int NumeralSystem::GetDigits () [pure virtual]
Implemented in PositionalNumeralSystem.
Referenced by InputStatement::Execute(), OutputStatement::Execute(), and DigitsStatement::Execute().
virtual const char NumeralSystem::GetFractionPoint () [pure virtual]
Implemented in PositionalNumeralSystem.
virtual const char* NumeralSystem::GetName () [pure virtual]
Implemented in PositionalNumeralSystem.
Referenced by InputStatement::Execute(), and OutputStatement::Execute().
virtual const char* NumeralSystem::GetPrefix () [pure virtual]
Implemented in PositionalNumeralSystem.
virtual const char* NumeralSystem::GetText (Number * number) [pure virtual]
Implemented in DecimalSystem, and PositionalNumeralSystem.
Referenced by MemoryStatement::Execute(), EvalStatement::Execute(), DigitsStatement::Execute(), PlotStatement::Execute(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetName(), NumericValueNode::GetNodeText(), and VariableList::ListContent().
virtual Number* NumeralSystem::Parse (const char * text, unsigned int * length, char ** end) [pure virtual]
Implemented in PositionalNumeralSystem.
Referenced by Lexer::GetDigitValue(), and Parse().
Number * NumeralSystem::Parse (const char * text) [virtual]
Definition at line 49 of file ntext.cpp.
References Parse().
Referenced by Parser::ParseDigistStatement(), Parser::ParseNumber(), and Parser::ParseNumeralStatement().
{
    unsigned int length;
    char *end;
    return Parse(text, &length, &end);
}
virtual void NumeralSystem::SetDigits (unsigned int digits) [pure virtual]
Implemented in PositionalNumeralSystem.
Referenced by PrefsStatement::Execute(), and DigitsStatement::Execute().
virtual void NumeralSystem::SetFractionPoint (const char fractionpoint) [pure virtual]
Implemented in PositionalNumeralSystem.
Member Data Documentation
CharBuffer* NumeralSystem::buf [protected]
Definition at line 63 of file ntext.h.
Referenced by PositionalNumeralSystem::GetName(), DecimalSystem::GetRealText(), PositionalNumeralSystem::GetText(), DecimalSystem::GetText(), PositionalNumeralSystem::IntegerToBuffer(), NumeralSystem(), and ~NumeralSystem().
Author
Generated automatically by Doxygen for amath from the source code.