NumericOperator
NAME
NumericOperator -
SYNOPSIS
#include <operators.h>
Inherits ExpressionNode.
Inherited by AdditionNode, AssignmentNode, DivisionNode, MultiplicationNode, PowerNode, and SubtractionNode.
Public Member Functions
NumericOperator (ExpressionNode *left, ExpressionNode *right)
~NumericOperator ()
SyntaxNode * GetNext ()
char * GetText ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Protected Attributes
ExpressionNode * left
ExpressionNode * right
Additional Inherited Members
Detailed Description
Definition at line 80 of file operators.h.
Constructor & Destructor Documentation
NumericOperator::NumericOperator (ExpressionNode * left, ExpressionNode * right)
Definition at line 202 of file operators.cpp.
References ExpressionNode::ExpressionNode(), left, and right.
Referenced by AdditionNode::AdditionNode(), AssignmentNode::AssignmentNode(), DivisionNode::DivisionNode(), MultiplicationNode::MultiplicationNode(), PowerNode::PowerNode(), and SubtractionNode::SubtractionNode().
                                                                            :
    ExpressionNode(), left(left), right(right) { }
NumericOperator::~NumericOperator ()
Definition at line 205 of file operators.cpp.
References left, and right.
{
    if (left != NOMEM) {
        delete left;
    }
    if (right != NOMEM) {
        delete right;
    }
}
Member Function Documentation
void NumericOperator::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 259 of file operators.cpp.
References left, right, and SyntaxNode::SetParent().
{
    if(left == NOMEM) {
        left = (ExpressionNode*)node;
        node->SetParent(this);
    } else if (right == NOMEM) {
        right = (ExpressionNode*)node;
        node->SetParent(this);
    }
}
void NumericOperator::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 270 of file operators.cpp.
References left, and right.
{
    if (left == node) {
        left = NOMEM;
    } else if (right == node) {
        right = NOMEM;
    }
}
SyntaxNode * NumericOperator::GetNext () [virtual]
Implements SyntaxNode.
Definition at line 246 of file operators.cpp.
References SyntaxNode::iterator, left, and right.
{
    if (iterator == NOMEM) {
        iterator = left;
        return left;
    } else if (iterator == left) {
        iterator = right;
        return right;
    } else {
        return NOMEM;
    }
}
char * NumericOperator::GetText () [virtual]
Implements ExpressionNode.
Definition at line 216 of file operators.cpp.
References CharBuffer::Append(), CharBuffer::Empty(), CharBuffer::EnsureSize(), ExpressionNode::GetNodeText(), ExpressionNode::GetPrecedence(), CharBuffer::GetString(), ExpressionNode::GetText(), left, SyntaxNode::output, right, and StrLen().
{
    const char *leftText = left->GetText();
    const char *nodeText = GetNodeText();
    const char *rightText = right->GetText();
    output->Empty();
    output->EnsureSize(StrLen(leftText) + 2 + StrLen(nodeText) + StrLen(rightText) + 2 + 1);
    if (left->GetPrecedence() != 0 && left->GetPrecedence() < GetPrecedence()) {
        output->Append("(");
        output->Append(leftText);
        output->Append(")");
    } else {
        output->Append(leftText);
    }
    output->Append(nodeText);
    if (right->GetPrecedence() != 0 && GetPrecedence() > right->GetPrecedence()) {
        output->Append("(");
        output->Append(rightText);
        output->Append(")");
    } else {
        output->Append(rightText);
    }
    return output->GetString();
}
void NumericOperator::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Definition at line 279 of file operators.cpp.
References SyntaxNode::iterator, left, and right.
{
    if (left == n) {
        if(iterator == left) {
            iterator = (ExpressionNode*)x;
        }
        delete left;
        left = (ExpressionNode*)x;
    } else if (right == n) {
        if(iterator == right) {
            iterator = (ExpressionNode*)x;
        }
        delete right;
        right = (ExpressionNode*)x;
    }
}
Member Data Documentation
ExpressionNode* NumericOperator::left [protected]
Definition at line 92 of file operators.h.
Referenced by Attach(), Detach(), AdditionNode::Evaluate(), SubtractionNode::Evaluate(), MultiplicationNode::Evaluate(), DivisionNode::Evaluate(), PowerNode::Evaluate(), GetNext(), GetText(), NumericOperator(), Replace(), and ~NumericOperator().
ExpressionNode* NumericOperator::right [protected]
Definition at line 93 of file operators.h.
Referenced by Attach(), Detach(), AdditionNode::Evaluate(), SubtractionNode::Evaluate(), MultiplicationNode::Evaluate(), DivisionNode::Evaluate(), PowerNode::Evaluate(), GetNext(), GetText(), NumericOperator(), Replace(), and ~NumericOperator().
Author
Generated automatically by Doxygen for amath from the source code.