.TH "operatordef" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
operatordef \- Character representation of operator tied with its symbol\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <lex\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBchr\fP"
.br
.ti -1c
.RI "\fBSymbol\fP \fBsymbol\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Character representation of operator tied with its symbol\&. 
.PP
Definition at line 60 of file lex\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "char operatordef::chr"

.PP
Definition at line 61 of file lex\&.h\&.
.PP
Referenced by Lexer::FindKeyword(), and Lexer::GetOperator()\&.
.SS "\fBSymbol\fP operatordef::symbol"

.PP
Definition at line 62 of file lex\&.h\&.
.PP
Referenced by Lexer::FindKeyword(), and Lexer::GetOperator()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
