.TH "app/main/operators.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/operators.h \- Application logic tied to arithmetic operators\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main/nodes\&.h'\fP
.br
\fC#include 'main/values\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUnaryNode\fP"
.br
.ti -1c
.RI "class \fBAbsoluteNode\fP"
.br
.ti -1c
.RI "class \fBNumericOperator\fP"
.br
.ti -1c
.RI "class \fBAdditionNode\fP"
.br
.ti -1c
.RI "class \fBSubtractionNode\fP"
.br
.ti -1c
.RI "class \fBMultiplicationNode\fP"
.br
.ti -1c
.RI "class \fBDivisionNode\fP"
.br
.ti -1c
.RI "class \fBPowerNode\fP"
.br
.ti -1c
.RI "class \fBAssignmentNode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Application logic tied to arithmetic operators\&. 


.PP
Definition in file \fBoperators\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
