Optimizer
NAME
Optimizer -
SYNOPSIS
#include <optimizer.h>
Public Member Functions
Optimizer (SyntaxNode *root)
~Optimizer ()
void Optimize ()
SyntaxNode * GetRoot ()
int GetTreeDepth (SyntaxNode *node, int depth)
Private Member Functions
void TagChildren (SyntaxNode *node)
void BalanceTree (SyntaxNode *node)
void ReduceUnaryNodes (SyntaxNode *node)
void ReduceValueNodes (SyntaxNode *node)
void TagStartNode (SyntaxNode *node)
Private Attributes
SyntaxNode * root
Detailed Description
Definition at line 42 of file optimizer.h.
Constructor & Destructor Documentation
Optimizer::Optimizer (SyntaxNode * root)
Definition at line 31 of file optimizer.cpp.
References root.
Referenced by Evaluator::Evaluate().
{
    this->root = root;
}
Optimizer::~Optimizer ()
Definition at line 36 of file optimizer.cpp.
{ }
Member Function Documentation
void Optimizer::BalanceTree (SyntaxNode * node) [private]
Definition at line 63 of file optimizer.cpp.
References SyntaxNode::Attach(), BalanceTree(), SyntaxNode::Detach(), expression, SyntaxNode::GetNext(), SyntaxNode::GetNodeType(), SyntaxNode::GetParent(), ExpressionNode::GetPrecedence(), GetTreeDepth(), and SyntaxNode::ResetIterator().
Referenced by BalanceTree(), and Optimize().
{
    if (node == NOMEM) {
        return;
    } else {
        node->ResetIterator();
    }
    SyntaxNode* current = node->GetNext();
    while (current != NOMEM) {
        if (current->GetNodeType() == expression) {
            ExpressionNode *troot = (ExpressionNode*)current;
            troot->ResetIterator();
            ExpressionNode *pivot = (ExpressionNode*)troot->GetNext();
            if (pivot != NOMEM && troot->GetPrecedence() == pivot->GetPrecedence()) {
                int rdepth = GetTreeDepth(troot, 1);
                int pdepth = GetTreeDepth(pivot, 0);
                if (rdepth - pdepth > 1 || rdepth - pdepth < -1) {
                    pivot->ResetIterator();
                    pivot->GetNext();
                    ExpressionNode *child = (ExpressionNode*)pivot->GetNext();
                    if (child != NOMEM) {
                        SyntaxNode* parent = troot->GetParent();
                        parent->Detach(troot);
                        troot->Detach(pivot);
                        pivot->Detach(child);
                        troot->Attach(child);
                        pivot->Attach(troot);
                        parent->Attach(pivot);
                        current = pivot;
                        current->ResetIterator();
                    }
                }
            }
        }
        current = node->GetNext();
        BalanceTree(current);
    }
}
SyntaxNode * Optimizer::GetRoot ()
Definition at line 39 of file optimizer.cpp.
References root.
Referenced by Evaluator::Evaluate().
{
    return root;
}
int Optimizer::GetTreeDepth (SyntaxNode * node, int depth)
Definition at line 106 of file optimizer.cpp.
References SyntaxNode::GetNext(), GetTreeDepth(), and SyntaxNode::ResetIterator().
Referenced by BalanceTree(), and GetTreeDepth().
{
    int max = depth;
    SyntaxNode* current;
    node->ResetIterator();
    while ((current = node->GetNext()) != NOMEM) {
        int a = GetTreeDepth(current, depth + 1);
        if (a > max) {
            max = a;
        }
    }
    return max;
}
void Optimizer::Optimize ()
Definition at line 44 of file optimizer.cpp.
References BalanceTree(), ReduceUnaryNodes(), ReduceValueNodes(), root, TagChildren(), and TagStartNode().
Referenced by Evaluator::Evaluate().
{
    TagChildren(root);
    ReduceUnaryNodes(root);
    BalanceTree(root);
    ReduceValueNodes(root);
    TagStartNode(root);
}
void Optimizer::ReduceUnaryNodes (SyntaxNode * node) [private]
Definition at line 122 of file optimizer.cpp.
References SyntaxNode::Detach(), NumericValueNode::Evaluate(), SyntaxNode::GetNext(), SyntaxNode::GetParent(), SyntaxNode::GetReductionType(), ReduceUnaryNodes(), SyntaxNode::Replace(), NumericValueNode::ReplaceWith(), SyntaxNode::ResetIterator(), Number::Unary(), unaryreduc, and valuereduc.
Referenced by Optimize(), and ReduceUnaryNodes().
{
    SyntaxNode* current;
    node->ResetIterator();
    while ((current = node->GetNext()) != NOMEM) {
        ReduceUnaryNodes(current);
        if (current->GetReductionType() == unaryreduc) {
            ExpressionNode *expression = (ExpressionNode*)current;
            expression->ResetIterator();
            ExpressionNode *next = (ExpressionNode*)expression->GetNext();
            if (next->GetReductionType() == unaryreduc) {
                next->ResetIterator();
                SyntaxNode *temp = next->GetNext();
                next->Detach(temp);
                SyntaxNode *parent = expression->GetParent();
                parent->Replace(expression, temp);
                current = parent;
                current->ResetIterator();
            } else if (next->GetReductionType() == valuereduc) {
                NumericValueNode *valueNode = (NumericValueNode*)next;
                Number *number = valueNode->Evaluate();
                Number *modified = number->Unary();
                valueNode->ReplaceWith(modified);
                current->Detach(valueNode);
                SyntaxNode *parent = current->GetParent();
                parent->Replace(current, valueNode);
                current = parent;
                current->ResetIterator();
            }
        }
    }
}
void Optimizer::ReduceValueNodes (SyntaxNode * node) [private]
Definition at line 159 of file optimizer.cpp.
References Number::Add(), compladdreduc, complsubreduc, NumericValueNode::Evaluate(), expression, SyntaxNode::GetNext(), SyntaxNode::GetNodeType(), SyntaxNode::GetParent(), SyntaxNode::GetReductionType(), NumericValueNode::GetReductionType(), NumericValueNode::NumericValueNode(), Number::PureComplexValue(), ReduceValueNodes(), SyntaxNode::Replace(), SyntaxNode::ResetIterator(), Number::Sub(), and valuereduc.
Referenced by Optimize(), and ReduceValueNodes().
{
    SyntaxNode* current;
    node->ResetIterator();
    while ((current = node->GetNext()) != NOMEM) {
        if (current->GetNodeType() == expression) {
            ExpressionNode *expression = (ExpressionNode*)current;
            ReductionType reduction = expression->GetReductionType();
            if (reduction == compladdreduc || reduction == complsubreduc) {
                expression->ResetIterator();
                NumericValueNode *first = (NumericValueNode*)expression->GetNext();
                NumericValueNode *second = (NumericValueNode*)expression->GetNext();
                if (
                    first->GetReductionType() == valuereduc && second->GetReductionType() == valuereduc &&
                    ((first->Evaluate()->PureComplexValue() && !second->Evaluate()->PureComplexValue()) ||
                     (!first->Evaluate()->PureComplexValue() && second->Evaluate()->PureComplexValue()))
                ) {
                    Number *number =
                        reduction == compladdreduc ?
                        first->Evaluate()->Add(second->Evaluate()):
                        first->Evaluate()->Sub(second->Evaluate());
                    NumericValueNode *reducedNode = new NumericValueNode(number);
                    SyntaxNode *parent = current->GetParent();
                    parent->Replace(current, reducedNode);
                    current = parent;
                    current->ResetIterator();
                }
            }
        }
        ReduceValueNodes(current);
    }
}
void Optimizer::TagChildren (SyntaxNode * node) [private]
Definition at line 53 of file optimizer.cpp.
References SyntaxNode::GetNext(), SyntaxNode::ResetIterator(), SyntaxNode::SetParent(), and TagChildren().
Referenced by Optimize(), and TagChildren().
{
    SyntaxNode* current;
    node->ResetIterator();
    while ((current = node->GetNext()) != NOMEM) {
        current->SetParent(node);
        TagChildren(current);
    }
}
void Optimizer::TagStartNode (SyntaxNode * node) [private]
Definition at line 195 of file optimizer.cpp.
References SyntaxNode::GetNext(), SyntaxNode::ResetIterator(), SyntaxNode::SetFirstNode(), and TagStartNode().
Referenced by Optimize(), and TagStartNode().
{
    node->ResetIterator();
    SyntaxNode* next = node->GetNext();
    if (next != NOMEM) {
        TagStartNode(next);
    } else {
        node->SetFirstNode();
    }
}
Member Data Documentation
SyntaxNode* Optimizer::root [private]
Definition at line 52 of file optimizer.h.
Referenced by GetRoot(), Optimize(), and Optimizer().
Author
Generated automatically by Doxygen for amath from the source code.