OutputStatement
NAME
OutputStatement - Change numeral output system.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
OutputStatement ()
Constructor used to show number of active digits.
OutputStatement (unsigned int base)
Constructor used to set number of active digits.
~OutputStatement ()
char * Execute ()
Private Attributes
unsigned int base
Additional Inherited Members
Detailed Description
Change numeral output system.
Definition at line 224 of file statements.h.
Constructor & Destructor Documentation
OutputStatement::OutputStatement ()
Constructor used to show number of active digits.
Definition at line 495 of file statements.cpp.
References base.
Referenced by Parser::ParseNumeralStatement().
                                 :
    base(0) { }
OutputStatement::OutputStatement (unsigned int base)
Constructor used to set number of active digits.
Definition at line 502 of file statements.cpp.
References base, and StatementNode::StatementNode().
Referenced by Parser::ParseNumeralStatement().
                                                  :
    StatementNode(), base(base) { }
OutputStatement::~OutputStatement () [inline]
Definition at line 228 of file statements.h.
{ }
Member Function Documentation
char * OutputStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 505 of file statements.cpp.
References CharBuffer::Append(), base, CharBuffer::Empty(), CharBuffer::EnsureSize(), NumeralSystem::GetDigits(), NumeralSystem::GetName(), CharBuffer::GetString(), Program::NewPositionalOutput(), Program::Output, SyntaxNode::output, and StrLen().
{
    const char *text;
    if (base != 0) {
        int digits = Program->Output->GetDigits();
        Program->NewPositionalOutput(base, digits);
        text = HELPOUTPSETT;
    } else {
        text = HELPOUTPSHOW;
    }
    const char *desc = Program->Output->GetName();
    output->Empty();
    output->EnsureSize(StrLen(text) + StrLen(desc) + StrLen(NEWLINE) + 1);
    output->Append(text);
    output->Append(desc);
    output->Append(NEWLINE);
    return output->GetString();
}
Member Data Documentation
unsigned int OutputStatement::base [private]
Definition at line 232 of file statements.h.
Referenced by Execute(), and OutputStatement().
Author
Generated automatically by Doxygen for amath from the source code.