.TH "app/main/parser.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/parser.h \- Application logic tied to \fBParser\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main/nodes\&.h'\fP
.br
\fC#include 'main/lexer\&.h'\fP
.br
\fC#include 'main/values\&.h'\fP
.br
\fC#include 'main/functions\&.h'\fP
.br
\fC#include 'main/statements\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParser\fP"
.br
.RI "\fIEncapsulates a recursive descent parser\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Application logic tied to \fBParser\fP\&. 


.PP
Definition in file \fBparser\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
