.TH "app/main/parser.cpp" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/parser.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/numb\&.h'\fP
.br
\fC#include 'lib/real\&.h'\fP
.br
\fC#include 'lib/cplex\&.h'\fP
.br
\fC#include 'main/parser\&.h'\fP
.br
\fC#include 'main/values\&.h'\fP
.br
\fC#include 'main/operators\&.h'\fP
.br
\fC#include 'main/functions\&.h'\fP
.br
\fC#include 'main/statements\&.h'\fP
.br
\fC#include 'localize/text\&.h'\fP
.br
\fC#include 'system/program\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
