.TH "PiNode" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PiNode \- Use of PI in a syntax tree\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <values\&.h>\fP
.PP
Inherits \fBNumericValueNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPiNode\fP ()"
.br
.ti -1c
.RI "\fBReductionType\fP \fBGetReductionType\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Use of PI in a syntax tree\&. 
.PP
Definition at line 178 of file values\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PiNode::PiNode ()"

.PP
Definition at line 417 of file values\&.cpp\&.
.PP
References NumericValueNode::NumericValueNode(), and RealNumber::RealNumber()\&.
.PP
Referenced by Parser::ParseAtomic()\&.
.PP
.nf
417                :
418     NumericValueNode(new RealNumber(PI)) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * PiNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBNumericValueNode\fP\&.
.PP
Definition at line 425 of file values\&.cpp\&.
.PP
.nf
426 {
427     return (char*)"pi";
428 }
.fi
.SS "\fBReductionType\fP PiNode::GetReductionType ()\fC [virtual]\fP"

.PP
Reimplemented from \fBNumericValueNode\fP\&.
.PP
Definition at line 420 of file values\&.cpp\&.
.PP
References nonereduc\&.
.PP
.nf
421 {
422     return nonereduc;
423 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
