PiNode
NAME
PiNode - Use of PI in a syntax tree.
SYNOPSIS
#include <values.h>
Inherits NumericValueNode.
Public Member Functions
PiNode ()
ReductionType GetReductionType ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Use of PI in a syntax tree.
Definition at line 178 of file values.h.
Constructor & Destructor Documentation
PiNode::PiNode ()
Definition at line 417 of file values.cpp.
References NumericValueNode::NumericValueNode(), and RealNumber::RealNumber().
Referenced by Parser::ParseAtomic().
               :
    NumericValueNode(new RealNumber(PI)) { }
Member Function Documentation
char * PiNode::GetNodeText () [protected], [virtual]
Reimplemented from NumericValueNode.
Definition at line 425 of file values.cpp.
{
    return (char*)"pi";
}
ReductionType PiNode::GetReductionType () [virtual]
Reimplemented from NumericValueNode.
Definition at line 420 of file values.cpp.
References nonereduc.
{
    return nonereduc;
}
Author
Generated automatically by Doxygen for amath from the source code.