.TH "lib/platform.h" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/platform.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stddef\&.h>\fP
.br
\fC#include 'mem\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBEMPTYSTRING\fP   ''"
.br
.ti -1c
.RI "#define \fBSPACE\fP   ' '"
.br
.ti -1c
.RI "#define \fBDOT\fP   '\&.'"
.br
.ti -1c
.RI "#define \fBNEWLINE\fP   '\\n'"
.br
.ti -1c
.RI "#define \fBNOMEM\fP   0"
.br
.ti -1c
.RI "#define \fBLONG_BIT\fP   32"
.br
.ti -1c
.RI "#define \fBwsize\fP   sizeof(unsigned int)"
.br
.ti -1c
.RI "#define \fBwmask\fP   (\fBwsize\fP \- 1)"
.br
.ti -1c
.RI "#define \fBtrue\fP   1"
.br
.ti -1c
.RI "#define \fBfalse\fP   0"
.br
.ti -1c
.RI "#define \fBHEADLINE\fP   \fBEMPTYSTRING\fP"
.br
.RI "\fIhttps://sourceforge.net/p/predef/wiki/Compilers/ \fP"
.ti -1c
.RI "#define \fBSYNTAXHIGHLIGHT\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBNORMALTEXT\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBBOLD\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBITALICS\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBUNDERLINE\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBCOLOR01\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBCOLOR02\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBCOLOR03\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBCURSORFORWARD\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBCURSORBACKWARD\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBERASEINLINE\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBINSERT1CHAR\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBDELETE1CHAR\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBDELETELINE\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBCLEARWINDOW\fP   \fBEMPTYSTRING\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef int \fBbool\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOLD   \fBEMPTYSTRING\fP"

.PP
Definition at line 296 of file platform\&.h\&.
.SS "#define CLEARWINDOW   \fBEMPTYSTRING\fP"

.PP
Definition at line 308 of file platform\&.h\&.
.SS "#define COLOR01   \fBEMPTYSTRING\fP"

.PP
Definition at line 299 of file platform\&.h\&.
.SS "#define COLOR02   \fBEMPTYSTRING\fP"

.PP
Definition at line 300 of file platform\&.h\&.
.SS "#define COLOR03   \fBEMPTYSTRING\fP"

.PP
Definition at line 301 of file platform\&.h\&.
.SS "#define CURSORBACKWARD   \fBEMPTYSTRING\fP"

.PP
Definition at line 303 of file platform\&.h\&.
.SS "#define CURSORFORWARD   \fBEMPTYSTRING\fP"

.PP
Definition at line 302 of file platform\&.h\&.
.SS "#define DELETE1CHAR   \fBEMPTYSTRING\fP"

.PP
Definition at line 306 of file platform\&.h\&.
.SS "#define DELETELINE   \fBEMPTYSTRING\fP"

.PP
Definition at line 307 of file platform\&.h\&.
.SS "#define DOT   '\&.'"

.PP
Definition at line 35 of file platform\&.h\&.
.SS "#define EMPTYSTRING   ''"

.PP
Definition at line 33 of file platform\&.h\&.
.SS "#define ERASEINLINE   \fBEMPTYSTRING\fP"

.PP
Definition at line 304 of file platform\&.h\&.
.SS "#define false   0"

.PP
Definition at line 52 of file platform\&.h\&.
.SS "#define HEADLINE   \fBEMPTYSTRING\fP"

.PP
https://sourceforge.net/p/predef/wiki/Compilers/ 
.PP
Definition at line 293 of file platform\&.h\&.
.SS "#define INSERT1CHAR   \fBEMPTYSTRING\fP"

.PP
Definition at line 305 of file platform\&.h\&.
.SS "#define ITALICS   \fBEMPTYSTRING\fP"

.PP
Definition at line 297 of file platform\&.h\&.
.SS "#define LONG_BIT   32"

.PP
Definition at line 45 of file platform\&.h\&.
.SS "#define NEWLINE   '\\n'"

.PP
Definition at line 40 of file platform\&.h\&.
.SS "#define NOMEM   0"

.PP
Definition at line 43 of file platform\&.h\&.
.SS "#define NORMALTEXT   \fBEMPTYSTRING\fP"

.PP
Definition at line 295 of file platform\&.h\&.
.SS "#define SPACE   ' '"

.PP
Definition at line 34 of file platform\&.h\&.
.SS "#define SYNTAXHIGHLIGHT   \fBEMPTYSTRING\fP"

.PP
Definition at line 294 of file platform\&.h\&.
.SS "#define true   1"

.PP
Definition at line 51 of file platform\&.h\&.
.SS "#define UNDERLINE   \fBEMPTYSTRING\fP"

.PP
Definition at line 298 of file platform\&.h\&.
.SS "#define wmask   (\fBwsize\fP \- 1)"

.PP
Definition at line 47 of file platform\&.h\&.
.SS "#define wsize   sizeof(unsigned int)"

.PP
Definition at line 46 of file platform\&.h\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef int \fBbool\fP"

.PP
Definition at line 50 of file platform\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
