PlotStatement
NAME
PlotStatement -
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
PlotStatement (const char *name, const char *parameter, const char *file)
PlotStatement (const char *name, const char *parameter)
~PlotStatement ()
char * Execute ()
Private Attributes
char * name
char * parameter
char * file
Additional Inherited Members
Detailed Description
Definition at line 302 of file statements.h.
Constructor & Destructor Documentation
PlotStatement::PlotStatement (const char * name, const char * parameter, const char * file)
Definition at line 756 of file statements.cpp.
References AllocAndCopy(), file, name, parameter, and StatementNode::StatementNode().
                                                                                      :
    StatementNode()
{
    AllocAndCopy(&this->name, name);
    AllocAndCopy(&this->parameter, parameter);
    AllocAndCopy(&this->file, file);
}
PlotStatement::PlotStatement (const char * name, const char * parameter)
Definition at line 764 of file statements.cpp.
References AllocAndCopy(), file, name, parameter, and StatementNode::StatementNode().
Referenced by Parser::ParseDrawStatement().
                                                                    :
    StatementNode()
{
    AllocAndCopy(&this->name, name);
    AllocAndCopy(&this->parameter, parameter);
    file = NOMEM;
}
PlotStatement::~PlotStatement ()
Definition at line 772 of file statements.cpp.
References file, name, and parameter.
{
    delete [] name;
    delete [] parameter;
    if (file != NOMEM) {
        delete [] file;
    }
}
Member Function Documentation
char * PlotStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 782 of file statements.cpp.
References CharBuffer::Append(), DecimalSystem::DecimalSystem(), CharBuffer::Empty(), CharBuffer::EnsureGrowth(), Program::Functions, FunctionList::GetFunctionDef(), Grid::GetHorizontalResolution(), Grid::GetScreenCoordinates(), CharBuffer::GetString(), NumeralSystem::GetText(), Grid::Grid(), name, SyntaxNode::output, parameter, RealNumber::RealNumber(), Grid::SetFunctionBounderies(), RealNumber::SetRealValue(), and Grid::SetScreenBounderues().
{
    UserFunction *function = Program->Functions->GetFunctionDef(name, parameter);
    if (function == NOMEM) {
        return (char*)("Function does not exists." NEWLINE);
    }
    output->Empty();
    Grid *grid = new Grid(function);
    static const int width = 400;
    static const int height = 300;
    grid->SetScreenBounderues(0, width, 20, height);
    bool first = true;
    static const double min = -5.0;
    static const double max = +5.0;
    grid->SetFunctionBounderies(min, max);
    double x = min;
    double step = grid->GetHorizontalResolution();
    int screenX;
    int screenY;
    RealNumber *n = new RealNumber();
    NumeralSystem *ns = new DecimalSystem(5);
    while (x < max) {
        grid->GetScreenCoordinates(x, &screenX, &screenY);
        output->EnsureGrowth(32);
        if (screenX != -1 && screenY != -1) {
            if (first) {
                output->Append('(');
                n->SetRealValue(screenX);
                output->Append(ns->GetText(n));
                output->Append(',');
                n->SetRealValue(height - screenY);
                output->Append(ns->GetText(n));
                output->Append(')');
                output->Append(NEWLINE);
                first = false;
            } else {
                output->Append('(');
                n->SetRealValue(screenX);
                output->Append(ns->GetText(n));
                output->Append(',');
                n->SetRealValue(height - screenY);
                output->Append(ns->GetText(n));
                output->Append(')');
                output->Append(NEWLINE);
            }
        }
        x = x + step;
    }
    delete n;
    delete ns;
    return output->GetString();
}
Member Data Documentation
char* PlotStatement::file [private]
Definition at line 312 of file statements.h.
Referenced by PlotStatement(), and ~PlotStatement().
char* PlotStatement::name [private]
Definition at line 310 of file statements.h.
Referenced by Execute(), PlotStatement(), and ~PlotStatement().
char* PlotStatement::parameter [private]
Definition at line 311 of file statements.h.
Referenced by Execute(), PlotStatement(), and ~PlotStatement().
Author
Generated automatically by Doxygen for amath from the source code.