PositionalNumeralSystem
NAME
PositionalNumeralSystem - Base class for all numeral systems with a positional notation.
SYNOPSIS
#include <ntext.h>
Inherits NumeralSystem.
Inherited by DecimalSystem.
Public Member Functions
PositionalNumeralSystem (unsigned int base, unsigned int digits, const char fractionpoint)
~PositionalNumeralSystem ()
virtual const char * GetName ()
virtual const char * GetPrefix ()
virtual unsigned int GetDigits ()
virtual void SetDigits (unsigned int digits)
virtual const char GetFractionPoint ()
virtual void SetFractionPoint (const char fractionpoint)
virtual const char * GetText (Number *number)
virtual Number * Parse (const char *text, unsigned int *length, char **end)
Protected Attributes
double base
unsigned int digits
char fractionpoint
Private Member Functions
const char * GetText (double number)
void IntegerToBuffer (double value, unsigned int digits, int *outdigits)
Detailed Description
Base class for all numeral systems with a positional notation.
More info on positional notation is available at Wikipedia: http://en.wikipedia.org/wiki/Positional_notation
Definition at line 74 of file ntext.h.
Constructor & Destructor Documentation
PositionalNumeralSystem::PositionalNumeralSystem (unsigned int base, unsigned int digits, const char fractionpoint)
Definition at line 58 of file ntext.cpp.
References base, digits, and fractionpoint.
Referenced by DecimalSystem::DecimalSystem(), Program::NewPositionalInput(), and Program::NewPositionalOutput().
                              :
    base(base * 1.0), digits(digits) {
    this->fractionpoint = fractionpoint;
}
PositionalNumeralSystem::~PositionalNumeralSystem ()
Definition at line 66 of file ntext.cpp.
{ }
Member Function Documentation
unsigned int PositionalNumeralSystem::GetDigits () [virtual]
Implements NumeralSystem.
Definition at line 107 of file ntext.cpp.
References digits.
{
    return digits;
}
const char PositionalNumeralSystem::GetFractionPoint () [virtual]
Implements NumeralSystem.
Definition at line 117 of file ntext.cpp.
References fractionpoint.
{
    return (const char)this->fractionpoint;
}
const char * PositionalNumeralSystem::GetName () [virtual]
Implements NumeralSystem.
Definition at line 69 of file ntext.cpp.
References CharBuffer::Append(), base, NumeralSystem::buf, DecimalSystem::DecimalSystem(), CharBuffer::Empty(), CharBuffer::EnsureSize(), CharBuffer::GetString(), NumeralSystem::GetText(), RealNumber::RealNumber(), and StrLen().
{
    switch ((int)base) {
    case 2:
        return "binary";
        break;
    case 8:
        return "octal";
        break;
    case 10:
        return "decimal";
        break;
    case 16:
        return "hexadecimal";
        break;
    }
    const char *text = "base ";
    Number *n = new RealNumber(base);
    NumeralSystem *ns = new DecimalSystem(2);
    const char *numtext = ns->GetText(n);
    buf->EnsureSize(StrLen(text) + StrLen(numtext) + 1);
    buf->Empty();
    buf->Append(text);
    buf->Append(numtext);
    delete ns;
    delete n;
    return buf->GetString();
}
const char * PositionalNumeralSystem::GetPrefix () [virtual]
Implements NumeralSystem.
Definition at line 101 of file ntext.cpp.
{
    // TODO: Implement
    return "";
}
const char * PositionalNumeralSystem::GetText (Number * number) [virtual]
Implements NumeralSystem.
Reimplemented in DecimalSystem.
Definition at line 127 of file ntext.cpp.
References CharBuffer::Append(), NumeralSystem::buf, CharBuffer::CharBuffer(), cimag(), CharBuffer::Copy(), creal(), CharBuffer::Empty(), ComplexNumber::GetComplexValue(), Number::GetRealValue(), CharBuffer::GetString(), GetText(), nsysreal, and Number::system.
{
    if (number->system == nsysreal) {
        return GetText(number->GetRealValue());
    }
    complex w = ((ComplexNumber*)number)->GetComplexValue();
    double a = creal(w);
    double b = cimag(w);
    if (a == 0.0 && b == 0.0) {
        buf->Empty();
        buf->Append('0');
        return buf->GetString();
    }
    CharBuffer *val = new CharBuffer(512);
    val->Empty();
    if (a != 0.0) {
        const char *real = GetText(a);
        val->Append(real);
    }
    const char *imag = GetText(b);
    if (a != 0.0 && b > 0.0) {
        val->Append('+');
    }
    if (b != 0.0) {
        val->Append(imag);
        val->Append('i');
    }
    buf->Copy(val);
    delete val;
    return buf->GetString();
}
const char * PositionalNumeralSystem::GetText (double number) [private]
Definition at line 167 of file ntext.cpp.
References CharBuffer::Append(), base, NumeralSystem::buf, digits, CharBuffer::Empty(), finite(), fractionpoint, CharBuffer::GetString(), IntegerToBuffer(), CharBuffer::Is(), isnan(), pow(), CharBuffer::RemoveTrailing(), round(), and trunc().
Referenced by GetText().
{
    if (!finite(number)) {
        return "Inf";
    } else if (isnan(number)) {
        return "NaN";
    } else if (number == 0.0) {
        return "0";
    }
    buf->Empty();
    double dnumber = number;
    if (dnumber < 0.0) {
        buf->Append('-');
        dnumber = -dnumber;
    }
    double expborder = log2p(base, dnumber);
    int exponent = 0;
    // Find exponent
    if (expborder > 6.0 || expborder < -5.0) {
        double dexp = trunc(log2p(base, dnumber));
        // Adjust to keep one digits before dot.
        if (dexp < 0.0) {
            dexp -= 1.0;
        }
        dnumber = dnumber * pow(base, -dexp);
        exponent = (int)dexp;
    }
    int digitout;
    int intdigits;
    // NOTICE: 1.5.3 Scaled trunc
    int intvalue = (int)(trunc(dnumber * base) / base);
    IntegerToBuffer(intvalue, digits, &intdigits);
    int fragdigits = digits - intdigits;
    if (fragdigits > 0) {
        buf->Append('.');
        // TODO: Fix fraction error (try 1.5439)
        double fraction = fabs(round((dnumber - round(dnumber)) * pow(base, fragdigits)));
        // NOTICE: 1.5.3 Changed from trunc to round
        double actualdigits = round(log2p(base, fraction));
        int padding = fragdigits - (finite(actualdigits) == 1 ? (int)actualdigits : 0) - 1;
        // Pad zeros if needed
        while (padding-- > 0) {
            buf->Append('0');
        }
        // NOTICE: 1.5.3 Scaled trunc
        intvalue = (int)(trunc(fraction * base) / base);
        IntegerToBuffer(intvalue, digits - intdigits, &digitout);
        // Remove trailing zeros
        while (buf->RemoveTrailing('0'))
            ;
        buf->RemoveTrailing(fractionpoint);
    }
    // Add exponent
    if (exponent != 0) {
        buf->Append('e');
        buf->Append(exponent > 0 ? '+' : '-');
        IntegerToBuffer(abs(exponent), 3, &digitout);
    }
    // Make sure no rounding error is returned
    if (buf->Is("-0")) {
        buf->Empty();
        buf->Append('0');
    }
    return buf->GetString();
}
void PositionalNumeralSystem::IntegerToBuffer (double value, unsigned int digits, int * outdigits) [private]
Definition at line 251 of file ntext.cpp.
References CharBuffer::Append(), base, NumeralSystem::buf, and trunc().
Referenced by GetText().
{
    static const char *alphaNumerics = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    unsigned int count = 0;
    char *chars = new char[128]; // TODO: Find correct size
    char *start = chars;
    do {
        count++;
        unsigned int intremainder = (unsigned int) trunc(fmod(value, base));
        *chars++ = alphaNumerics[intremainder];
        value /= base;
    } while (value >= 1.0);
    unsigned int n = count;
    unsigned int q = digits;
    chars--;
    while (n-- != 0 && q-- != 0) {
        buf->Append(*chars--);
    }
    n++;
    while (n-- != 0) {
        buf->Append('0');
    }
    *outdigits = count;
    delete [] start;
}
Number * PositionalNumeralSystem::Parse (const char * text, unsigned int * length, char ** end) [virtual]
Implements NumeralSystem.
Definition at line 282 of file ntext.cpp.
References base, fractionpoint, pow(), and RealNumber::RealNumber().
{
    unsigned int intbase = (unsigned int)base;
    char maxNumeric = (intbase > 10 ? 10 : intbase) + '0' - 1;
    char maxAlpha = intbase > 10 ? intbase + 'A' - 11 : 0;
    unsigned int pos = 0;
    double integer = 0;
    double addition;
    while (*text != '\0' && ((*text >= '0' && *text <= maxNumeric) || (maxAlpha != 0 && *text >= 'A' && *text <= maxAlpha))) {
        addition = ((*text >= '0' && *text <= maxNumeric) ? (*text - '0') : (*text - 'A' + 10)) * 1.0;
        integer = integer * base + addition;
        text++;
        pos++;
    }
    // Digits not found
    if (pos == 0) {
        *length = 0;
        *end = (char*)text;
        return new RealNumber();
    }
    double fraction = 0.0;
    double divisor = 1.0;
    if (*text == fractionpoint) {
        text++;
        pos++;
        while (*text != '\0' && ((*text >= '0' && *text <= maxNumeric) || (maxAlpha != '\0' && *text >= 'A' && *text <= maxAlpha))) {
            addition = ((*text >= '0' && *text <= maxNumeric) ? (*text - '0') : (*text - 'A' + 10));
            fraction = fraction * base + addition;
            divisor *= base;
            text++;
            pos++;
        }
    }
    double exp = 0;
    if (*text == 'e' || *text == 'E') {
        text++;
        pos++;
        double sign = *text == '+' ? 1.0 : *text == '-' ? -1.0 : 0.0;
        if (sign != 0.0) {
            text++;
            pos++;
            while (*text != '\0' && ((*text >= '0' && *text <= maxNumeric) || (maxAlpha != 0 && *text >= 'A' && *text <= maxAlpha))) {
                addition = ((*text >= '0' && *text <= maxNumeric) ? (*text - '0') : (*text - 'A' + 10)) * 1.0;
                exp = exp * base + addition;
                text++;
                pos++;
            }
            exp *= sign;
        } else {
            text--;
            pos--;
        }
    }
    *length = pos;
    *end = (char*)text;
    double dnumber = (integer + (fraction / divisor)) * pow(base, exp);
    return new RealNumber(dnumber);
}
void PositionalNumeralSystem::SetDigits (unsigned int digits) [virtual]
Implements NumeralSystem.
Definition at line 112 of file ntext.cpp.
References digits.
{
    this->digits = digits;
}
void PositionalNumeralSystem::SetFractionPoint (const char fractionpoint) [virtual]
Implements NumeralSystem.
Definition at line 122 of file ntext.cpp.
References fractionpoint.
{
    this->fractionpoint = fractionpoint;
}
Member Data Documentation
double PositionalNumeralSystem::base [protected]
Definition at line 89 of file ntext.h.
Referenced by GetName(), GetText(), IntegerToBuffer(), Parse(), and PositionalNumeralSystem().
unsigned int PositionalNumeralSystem::digits [protected]
Definition at line 90 of file ntext.h.
Referenced by GetDigits(), DecimalSystem::GetRealText(), GetText(), PositionalNumeralSystem(), and SetDigits().
char PositionalNumeralSystem::fractionpoint [protected]
Definition at line 91 of file ntext.h.
Referenced by GetFractionPoint(), DecimalSystem::GetRealText(), GetText(), Parse(), PositionalNumeralSystem(), and SetFractionPoint().
Author
Generated automatically by Doxygen for amath from the source code.