PowerNode
NAME
PowerNode -
SYNOPSIS
#include <operators.h>
Inherits NumericOperator.
Public Member Functions
PowerNode (ExpressionNode *left, ExpressionNode *right)
int GetPrecedence ()
Number * Evaluate ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 138 of file operators.h.
Constructor & Destructor Documentation
PowerNode::PowerNode (ExpressionNode * left, ExpressionNode * right)
Definition at line 403 of file operators.cpp.
References NumericOperator::NumericOperator().
Referenced by Parser::ParsePower().
                                                               :
    NumericOperator(left, right) { }
Member Function Documentation
Number * PowerNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 411 of file operators.cpp.
References ExpressionNode::Evaluate(), NumericOperator::left, Number::Raise(), ExpressionNode::result, and NumericOperator::right.
{
    Number* exponent = right->Evaluate();
    result = left->Evaluate()->Raise(exponent);
    return result;
}
char * PowerNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 418 of file operators.cpp.
{
    return (char*)"^";
}
int PowerNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 406 of file operators.cpp.
{
    return 4;
}
Author
Generated automatically by Doxygen for amath from the source code.