PrefsStatement
NAME
PrefsStatement - Load or save preferences.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
PrefsStatement ()
PrefsStatement (Symbol argument)
char * Execute ()
Private Attributes
Symbol argument
Additional Inherited Members
Detailed Description
Load or save preferences.
Definition at line 119 of file statements.h.
Constructor & Destructor Documentation
PrefsStatement::PrefsStatement ()
Definition at line 122 of file statements.cpp.
References argument.
Referenced by Parser::ParsePrefsStatement().
{
    argument = Symbol(0);
}
PrefsStatement::PrefsStatement (Symbol argument)
Definition at line 127 of file statements.cpp.
References argument.
Referenced by Parser::ParsePrefsStatement().
{
    this->argument = argument;
}
Member Function Documentation
char * PrefsStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 132 of file statements.cpp.
References argument, Program::Console, PreferencesBase::GetDescription(), PreferencesBase::GetDigits(), PreferencesBase::GetPrompt(), Program::Input, PreferencesBase::Keep(), PreferencesBase::Load(), Program::Output, Program::Preferences, PreferencesBase::Save(), NumeralSystem::SetDigits(), ConsoleBase::SetPrompt(), symload, and symsave.
{
    bool success;
    if (argument == symsave) {
        success = Program->Preferences->Keep();
        success &= Program->Preferences->Save();
        return (success ? HELPPREFSAVE : HELPPREFNOSA);
    } else if (argument == symload) {
        success = Program->Preferences->Load();
        if (success) {
            Program->Console->SetPrompt(
                Program->Preferences->GetPrompt());
            Program->Input->SetDigits(
                Program->Preferences->GetDigits());
            Program->Output->SetDigits(
                Program->Preferences->GetDigits());
            return(HELPPREFLOAD);
        } else {
            return(HELPPREFNOLO);
        }
    }
    return Program->Preferences->GetDescription();
}
Member Data Documentation
Symbol PrefsStatement::argument [private]
Definition at line 126 of file statements.h.
Referenced by Execute(), and PrefsStatement().
Author
Generated automatically by Doxygen for amath from the source code.