.TH "app/system/preferences_stdc.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/preferences_stdc.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'system/preferences\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStandardPreferences\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
