.TH "app/system/preferences.cpp" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/preferences.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/numb\&.h'\fP
.br
\fC#include 'lib/real\&.h'\fP
.br
\fC#include 'lib/ntext\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br
\fC#include 'main/lexer\&.h'\fP
.br
\fC#include 'main/nodes\&.h'\fP
.br
\fC#include 'main/parser\&.h'\fP
.br
\fC#include 'system/preferences\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
