.TH "app/system/preferences_stdc.cpp" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/preferences_stdc.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br
\fC#include 'system/preferences\&.h'\fP
.br
\fC#include 'system/preferences_stdc\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static const char * \fBtempname\fP = '/tmp/amath\&.prefs'"
.br
.ti -1c
.RI "static const char * \fBpermname\fP = '/usr/local/etc/amath\&.conf'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const char* permname = '/usr/local/etc/amath\&.conf'\fC [static]\fP"

.PP
Definition at line 38 of file preferences_stdc\&.cpp\&.
.PP
Referenced by StandardPreferences::Save()\&.
.SS "const char* tempname = '/tmp/amath\&.prefs'\fC [static]\fP"

.PP
Definition at line 37 of file preferences_stdc\&.cpp\&.
.PP
Referenced by StandardPreferences::Keep(), and StandardPreferences::Load()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
