.TH "app/system/preferences.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/preferences.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'lib/charbuf\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPreferencesBase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
