PreferencesBase
NAME
PreferencesBase -
SYNOPSIS
#include <preferences.h>
Inherited by AmigaPreferences, and StandardPreferences.
Public Member Functions
PreferencesBase ()
virtual ~PreferencesBase ()
char * GetDescription ()
char * GetPrompt ()
void SetPrompt (const char *prompt)
int GetDigits ()
void SetDigits (int digits)
void SetDefaults ()
virtual bool Load ()=0
virtual bool Keep ()=0
virtual bool Save ()=0
Protected Member Functions
void SetPrefs (char *prefs)
Private Attributes
CharBuffer * buf
char * prompt
int digits
Detailed Description
Definition at line 32 of file preferences.h.
Constructor & Destructor Documentation
PreferencesBase::PreferencesBase ()
Definition at line 37 of file preferences.cpp.
References buf, CharBuffer::CharBuffer(), and SetDefaults().
{
    buf = new CharBuffer();
    SetDefaults();
}
PreferencesBase::~PreferencesBase () [virtual]
Definition at line 43 of file preferences.cpp.
References buf, and prompt.
{
    delete buf;
    delete prompt;
}
Member Function Documentation
char * PreferencesBase::GetDescription ()
Definition at line 55 of file preferences.cpp.
References CharBuffer::Append(), buf, DecimalSystem::DecimalSystem(), CharBuffer::Empty(), CharBuffer::EnsureSize(), Lexer::FindKeyword(), GetDigits(), CharBuffer::GetString(), NumeralSystem::GetText(), prompt, RealNumber::RealNumber(), StrLen(), symdelimiter, symdigits, and symprompt.
Referenced by PrefsStatement::Execute(), and StandardPreferences::SavePrefs().
{
    static char *promptkw = Lexer::FindKeyword(symprompt);
    static char *digitkw = Lexer::FindKeyword(symdigits);
    static char delimiter = *(Lexer::FindKeyword(symdelimiter));
    static char promptq = '"';
    Number *d = new RealNumber(GetDigits());
    NumeralSystem *ns = new DecimalSystem(2);
    const char *dtext = ns->GetText(d);
    delete d;
    buf->Empty();
    buf->EnsureSize(
        StrLen(promptkw) + sizeof(SPACE) + sizeof(promptq) +
        StrLen(prompt) + sizeof(promptq) + sizeof(delimiter) +
        StrLen(digitkw) + sizeof(SPACE) + StrLen(dtext) + sizeof(delimiter) + sizeof(char));
    buf->Append(promptkw);
    buf->Append(SPACE);
    buf->Append(promptq);
    buf->Append(prompt);
    buf->Append(promptq);
    buf->Append(delimiter);
    buf->Append(digitkw);
    buf->Append(SPACE);
    buf->Append(dtext);
    buf->Append(delimiter);
    delete ns;
    return buf->GetString();
}
int PreferencesBase::GetDigits ()
Definition at line 112 of file preferences.cpp.
References digits.
Referenced by PrefsStatement::Execute(), GetDescription(), and Program::Program().
{
    return digits;
}
char * PreferencesBase::GetPrompt ()
Definition at line 101 of file preferences.cpp.
References prompt.
Referenced by PrefsStatement::Execute(), and StandardProgram::Initialize().
{
    return prompt;
}
virtual bool PreferencesBase::Keep () [pure virtual]
Implemented in StandardPreferences, and AmigaPreferences.
Referenced by PrefsStatement::Execute(), and Program::~Program().
virtual bool PreferencesBase::Load () [pure virtual]
Implemented in StandardPreferences, and AmigaPreferences.
Referenced by PrefsStatement::Execute(), and StandardProgram::Run().
virtual bool PreferencesBase::Save () [pure virtual]
Implemented in StandardPreferences, and AmigaPreferences.
Referenced by PrefsStatement::Execute().
void PreferencesBase::SetDefaults ()
Definition at line 49 of file preferences.cpp.
References AllocAndCopy(), digits, and prompt.
Referenced by PreferencesBase().
{
    AllocAndCopy(&this->prompt, "> ");
    digits = 9;
}
void PreferencesBase::SetDigits (int digits)
Definition at line 117 of file preferences.cpp.
References digits.
Referenced by DigitsStatement::Execute().
{
    this->digits = digits;
}
void PreferencesBase::SetPrefs (char * prefs) [protected]
Definition at line 88 of file preferences.cpp.
References SyntaxNode::Execute(), Parser::Parse(), and Parser::Parser().
Referenced by StandardPreferences::Load().
{
    if (prefs == NOMEM) {
        return;
    }
    Parser *parser = new Parser(prefs);
    SyntaxNode *node = parser->Parse();
    delete parser;
    node->Execute();
    delete node;
}
void PreferencesBase::SetPrompt (const char * prompt)
Definition at line 106 of file preferences.cpp.
References AllocAndCopy(), and prompt.
Referenced by Program::SetPrompt().
{
    delete this->prompt;
    AllocAndCopy(&this->prompt, prompt);
}
Member Data Documentation
CharBuffer* PreferencesBase::buf [private]
Definition at line 50 of file preferences.h.
Referenced by GetDescription(), PreferencesBase(), and ~PreferencesBase().
int PreferencesBase::digits [private]
Definition at line 52 of file preferences.h.
Referenced by GetDigits(), SetDefaults(), and SetDigits().
char* PreferencesBase::prompt [private]
Definition at line 51 of file preferences.h.
Referenced by GetDescription(), GetPrompt(), SetDefaults(), SetPrompt(), and ~PreferencesBase().
Author
Generated automatically by Doxygen for amath from the source code.