lib/cplex/prim.c
NAME
lib/cplex/prim.c -
SYNOPSIS
#include 'math.h'
#include 'prim.h'
#include 'complex.h'
Macros
#define REAL_PART(z) ((z).parts[0])
#define IMAG_PART(z) ((z).parts[1])
Functions
double creal (complex z)
Real part of complex number.
double cimag (complex z)
Imaginary part of complex number.
double cabs (complex z)
Absolute value of complex number.
complex conj (complex z)
complex cpack (double x, double y)
Pack two real numbers into a complex number.
complex ctrunc (complex z)
Truncated value of complex number.
complex cfloor (complex z)
Floor value of complex number.
complex cceil (complex z)
Ceiling value of complex number.
complex cround (complex z)
Division of two complex numbers.
complex cadd (complex y, complex z)
Addition of two complex numbers.
complex csub (complex y, complex z)
Subtraction of two complex numbers.
complex cmul (complex y, complex z)
Multiplication of two complex numbers.
complex cdiv (complex y, complex z)
Division of two complex numbers.
complex creci (complex z)
Reciprocal value of complex number.
void cchsh (double x, double *c, double *s)
Calculate cosh and sinh.
void cchc (double x, double *ch, double *c)
Calculate cosh and cos.
Macro Definition Documentation
#define IMAG_PART(z) ((z).parts[1])
Definition at line 32 of file prim.c.
#define REAL_PART(z) ((z).parts[0])
Definition at line 31 of file prim.c.
Function Documentation
double cabs (complex z)
Absolute value of complex number.
Definition at line 56 of file prim.c.
References cimag(), creal(), and hypot().
Referenced by ComplexNumber::Absolute(), clog(), cpow(), and csqrt().
{
    return hypot(creal(z), cimag(z));
}
complex cadd (complex y, complex z)
Addition of two complex numbers.
Definition at line 128 of file prim.c.
References cimag(), cpack(), and creal().
Referenced by ComplexNumber::Add(), cacos(), cacosh(), cacot(), cacoth(), cacsc(), cacsch(), casec(), casech(), casin(), casinh(), catan(), and catanh().
{
    complex w;
    w = cpack(creal(y) + creal(z), cimag(y) + cimag(z));
    return w;
}
complex cceil (complex z)
Ceiling value of complex number.
Definition at line 106 of file prim.c.
References cimag(), cpack(), and creal().
Referenced by ComplexNumber::Ceiling().
{
    complex w;
    w = cpack(ceil(creal(z)), ceil(cimag(z)));
    return w;
}
void cchc (double x, double * ch, double * c)
Calculate cosh and cos.
Definition at line 230 of file prim.c.
References cos(), and cosh().
{
    *ch = cosh(2.0 * x);
    *c = cos(2.0 * x);
}
void cchsh (double x, double * c, double * s)
Calculate cosh and sinh.
Definition at line 210 of file prim.c.
References cosh(), exp(), and sinh().
Referenced by ccos(), ccosh(), csin(), and csinh().
{
    double e, ei;
    if (fabs(x) <= 0.5) {
        *c = cosh(x);
        *s = sinh(x);
    } else {
        e = exp(x);
        ei = 0.5 / e;
        e = 0.5 * e;
        *s = e - ei;
        *c = e + ei;
    }
}
complex cdiv (complex y, complex z)
Division of two complex numbers.
Definition at line 170 of file prim.c.
References cimag(), cpack(), and creal().
Referenced by cacot(), cacsc(), casec(), catan(), clog10(), clogb(), and ComplexNumber::Div().
{
    complex w;
    double a, b, c, d;
    double q, v, x;
    a = creal(y);
    b = cimag(y);
    c = creal(z);
    d = cimag(z);
    q = c * c + d * d;
    v = a * c + b * d;
    x = b * c - a * d;
    w = cpack(v / q, x / q);
    return w;
}
complex cfloor (complex z)
Floor value of complex number.
Definition at line 95 of file prim.c.
References cimag(), cpack(), and creal().
Referenced by ComplexNumber::Floor().
{
    complex w;
    w = cpack(floor(creal(z)), floor(cimag(z)));
    return w;
}
double cimag (complex z)
Imaginary part of complex number.
Definition at line 47 of file prim.c.
Referenced by cabs(), cadd(), cceil(), ccos(), ccosh(), ccot(), ccoth(), ccsc(), ccsch(), cdiv(), cexp(), cfloor(), clog(), cmul(), cpow(), creci(), cround(), csec(), csech(), csgn(), csin(), csinh(), csqrt(), csub(), ctan(), ctanh(), ctrunc(), ComplexNumber::GetDefaultPrecedence(), ComplexNumber::GetImagValue(), ComplexNumber::GetPrecedence(), PositionalNumeralSystem::GetText(), DecimalSystem::GetText(), and ComplexNumber::Unary().
{
    return (IMAG_PART(z));
}
complex cmul (complex y, complex z)
Multiplication of two complex numbers.
Definition at line 150 of file prim.c.
References cimag(), cpack(), and creal().
Referenced by cacos(), cacosh(), cacot(), cacoth(), cacsc(), cacsch(), casec(), casech(), casin(), casinh(), catan(), catanh(), ccbrt(), and ComplexNumber::Mul().
{
    complex w;
    double a, b, c, d;
    // (a+bi)(c+di)
    a = creal(y);
    b = cimag(y);
    c = creal(z);
    d = cimag(z);
    // (ac -bd) + (ad + bc)i
    w = cpack(a * c - b * d, a * d + b * c);
    return w;
}
complex conj (complex z)
Definition at line 61 of file prim.c.
References cpack().
Referenced by creci().
{
    IMAG_PART(z) = -IMAG_PART(z);
    return cpack(REAL_PART(z), IMAG_PART(z));
}
complex cpack (double x, double y)
Pack two real numbers into a complex number.
Definition at line 71 of file prim.c.
Referenced by ComplexNumber::Add(), cacos(), cacosh(), cacot(), cacoth(), cacsc(), cacsch(), cadd(), casec(), casech(), casin(), casinh(), catan(), catanh(), ccbrt(), cceil(), ccos(), ccosh(), ccot(), ccoth(), ccsc(), ccsch(), cdiv(), cexp(), cfloor(), clog(), clog10(), clogb(), cmul(), ComplexNumber::ComplexNumber(), conj(), cpow(), creci(), cround(), csec(), csech(), csin(), csinh(), csqrt(), csub(), ctan(), ctanh(), ctrunc(), ComplexNumber::Div(), ComplexNumber::Mul(), ComplexNumber::Raise(), ComplexNumber::Sub(), and ComplexNumber::Unary().
{
    complex z;
    REAL_PART(z) = x;
    IMAG_PART(z) = y;
    return (z);
}
double creal (complex z)
Real part of complex number.
Definition at line 38 of file prim.c.
Referenced by cabs(), cadd(), cceil(), ccos(), ccosh(), ccot(), ccoth(), ccsc(), ccsch(), cdiv(), cexp(), cfloor(), clog(), cmul(), cpow(), creci(), cround(), csec(), csech(), csgn(), csin(), csinh(), csqrt(), csub(), ctan(), ctanh(), ctrunc(), ComplexNumber::GetDefaultPrecedence(), ComplexNumber::GetIntegerValue(), ComplexNumber::GetPrecedence(), ComplexNumber::GetRealValue(), PositionalNumeralSystem::GetText(), DecimalSystem::GetText(), ComplexNumber::PureComplexValue(), and ComplexNumber::Unary().
{
    return (REAL_PART(z));
}
complex creci (complex z)
Reciprocal value of complex number.
Definition at line 193 of file prim.c.
References cimag(), conj(), cpack(), and creal().
Referenced by cacsch(), casec(), casech(), and ComplexNumber::Reciprocal().
{
    complex w;
    double q, a, b;
    a = creal(z);
    b = cimag(conj(z));
    q = a * a + b * b;
    w = cpack(a / q, b / q);
    return w;
}
complex cround (complex z)
Division of two complex numbers.
Definition at line 117 of file prim.c.
References cimag(), cpack(), creal(), and round().
Referenced by ComplexNumber::Round().
{
    complex w;
    w = cpack(round(creal(z)), round(cimag(z)));
    return w;
}
complex csub (complex y, complex z)
Subtraction of two complex numbers.
Definition at line 139 of file prim.c.
References cimag(), cpack(), and creal().
Referenced by cacos(), cacosh(), cacot(), cacoth(), cacsc(), casec(), casech(), casin(), catan(), catanh(), and ComplexNumber::Sub().
{
    complex w;
    w = cpack(creal(y) - creal(z), cimag(y) - cimag(z));
    return w;
}
complex ctrunc (complex z)
Truncated value of complex number.
Definition at line 84 of file prim.c.
References cimag(), cpack(), creal(), and trunc().
Referenced by ComplexNumber::Trunc().
{
    complex w;
    w = cpack(trunc(creal(z)), trunc(cimag(z)));
    return w;
}
Author
Generated automatically by Doxygen for amath from the source code.