lib/real/prim.h
NAME
lib/real/prim.h -
SYNOPSIS
Classes
union ieee_float_shape_type
A union which permits us to convert between a float and a 32 bit int.
Macros
#define HUGE 1.7976931348623157e+308
#define EXTRACT_WORDS(ix0, ix1, d)
Get two 32 bit ints from a double.
#define GET_HIGH_WORD(i, d)
Get the more significant 32 bit int from a double.
#define GET_LOW_WORD(i, d)
Get the less significant 32 bit int from a double.
#define INSERT_WORDS(d, ix0, ix1)
Set a double from two 32 bit ints.
#define SET_HIGH_WORD(d, v)
Set the more significant 32 bits of a double from an int.
#define SET_LOW_WORD(d, v)
Set the less significant 32 bits of a double from an int.
#define GET_FLOAT_WORD(i, d)
Get a 32 bit int from a float.
#define SET_FLOAT_WORD(d, i)
Set a float from a 32 bit int.
Typedefs
typedef unsigned int uword
32 bit unsigned integer.
typedef signed int sword
32 bit signed integer.
Functions
double __kernel_cos (double x, double y)
Kernel cos function.
double __kernel_sin (double x, double y, int iy)
Kernel sin function.
double __kernel_tan (double x, double y, int iy)
Kernel tan function.
int __kernel_rem_pio2 (double *x, double *y, int e0, int nx, int prec, const int *ipio2)
Kernel reduction function.
Macro Definition Documentation
#define EXTRACT_WORDS(ix0, ix1, d)
Value:
do { \
    ieee_double_shape_type ew_u; \
    ew_u.value = (d); \
    (ix0) = ew_u.parts.msw; \
    (ix1) = ew_u.parts.lsw; \
  } while (0)
Get two 32 bit ints from a double.
Definition at line 153 of file prim.h.
#define GET_FLOAT_WORD(i, d)
Value:
do { \
  ieee_float_shape_type gf_u; \
  gf_u.value = (d); \
  (i) = gf_u.word; \
} while (0)
Get a 32 bit int from a float.
Definition at line 237 of file prim.h.
#define GET_HIGH_WORD(i, d)
Value:
do { \
    ieee_double_shape_type gh_u; \
    gh_u.value = (d); \
    (i) = gh_u.parts.msw; \
  } while (0)
Get the more significant 32 bit int from a double.
Definition at line 165 of file prim.h.
#define GET_LOW_WORD(i, d)
Value:
do { \
    ieee_double_shape_type gl_u; \
    gl_u.value = (d); \
    (i) = gl_u.parts.lsw; \
  } while (0)
Get the less significant 32 bit int from a double.
Definition at line 176 of file prim.h.
#define HUGE 1.7976931348623157e+308
Definition at line 52 of file prim.h.
#define INSERT_WORDS(d, ix0, ix1)
Value:
do { \
    ieee_double_shape_type iw_u; \
    iw_u.parts.msw = (ix0); \
    iw_u.parts.lsw = (ix1); \
    (d) = iw_u.value; \
  } while (0)
Set a double from two 32 bit ints.
Definition at line 187 of file prim.h.
#define SET_FLOAT_WORD(d, i)
Value:
do { \
  ieee_float_shape_type sf_u; \
  sf_u.word = (i); \
  (d) = sf_u.value; \
} while (0)
Set a float from a 32 bit int.
Definition at line 248 of file prim.h.
#define SET_HIGH_WORD(d, v)
Value:
do { \
    ieee_double_shape_type sh_u; \
    sh_u.value = (d); \
    sh_u.parts.msw = (v); \
    (d) = sh_u.value; \
  } while (0)
Set the more significant 32 bits of a double from an int.
Definition at line 199 of file prim.h.
#define SET_LOW_WORD(d, v)
Value:
do { \
    ieee_double_shape_type sl_u; \
    sl_u.value = (d); \
    sl_u.parts.lsw = (v); \
    (d) = sl_u.value; \
  } while (0)
Set the less significant 32 bits of a double from an int.
Definition at line 211 of file prim.h.
Typedef Documentation
typedef signed int sword
32 bit signed integer.
Definition at line 107 of file prim.h.
typedef unsigned int uword
32 bit unsigned integer.
Definition at line 101 of file prim.h.
Function Documentation
double __kernel_cos (double x, double y)
Kernel cos function.
Version:
1.4
Date:
96/03/07
Kernel cos function on [-pi/4, pi/4], pi/4 ~ 0.785398164
Input x is assumed to be bounded by ~pi/4 in magnitude.
Input y is the tail of x.
Algorithm
 1. Since cos(-x) = cos(x), we need only to consider positive x.
 2. if x < 2^-27 (hx<0x3e400000 0), return 1 with inexact if x!=0.
 3. cos(x) is approximated by a polynomial of degree 14 on
    [0,pi/4]
                         4 14
        cos(x) ~ 1 - x*x/2 + C1*x + ... + C6*x
    where the Remes error is
    | 2 4 6 8 10 12 14 | -58
    |cos(x)-(1-.5*x +C1*x +C2*x +C3*x +C4*x +C5*x +C6*x )| <= 2
    | |
                   4 6 8 10 12 14
 4. let r = C1*x +C2*x +C3*x +C4*x +C5*x +C6*x , then
        cos(x) = 1 - x*x/2 + r
    since cos(x+y) ~ cos(x) - sin(x)*y
          ~ cos(x) - x*y,
    a correction term is necessary in cos(x) and hence
    cos(x+y) = 1 - (x*x/2 - (r - x*y))
    For better accuracy when x > 0.3, let qx = |x|/4 with
    the last 32 bits mask off, and if x > 0.78125, let qx = 0.28125.
    Then
    cos(x+y) = (1-qx) - ((x*x/2-qx) - (r-x*y)).
    Note that 1-qx and (x*x/2-qx) is EXACT here, and the
    magnitude of the latter is at least a quarter of x*x/2,
    thus, reducing the rounding error in the subtraction.
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 100 of file kcos.c.
References C1, C2, C3, C4, C5, C6, and one.
Referenced by cos(), and sin().
{
    double a,hz,z,r,qx;
    sword ix;
    GET_HIGH_WORD(ix, x);
    ix &= 0x7fffffff; /* ix = |x|'s high word*/
    if(ix<0x3e400000) { /* if x < 2**27 */
        if(((int)x)==0) return one; /* generate inexact */
    }
    z = x*x;
    r = z*(C1+z*(C2+z*(C3+z*(C4+z*(C5+z*C6)))));
    if(ix < 0x3FD33333) /* if |x| < 0.3 */
        return one - (0.5*z - (z*r - x*y));
    else {
        if(ix > 0x3fe90000) { /* x > 0.78125 */
            qx = 0.28125;
        } else {
            INSERT_WORDS(qx,ix-0x00200000,0);
        }
        hz = 0.5*z-qx;
        a = one-qx;
        return a - (hz - (z*r-x*y));
    }
}
int __kernel_rem_pio2 (double * x, double * y, int e0, int nx, int prec, const int * ipio2)
Kernel reduction function.
Version:
1.4
Date:
96/03/07
__kernel_rem_pio2(x,y,e0,nx,prec,ipio2)
double x[],y[]; int e0,nx,prec; int ipio2[];
__kernel_rem_pio2 return the last three digits of N with
    y = x - N*pi/2
so that |y| < pi/2.
The method is to compute the integer (mod 8) and fraction parts of
(2/pi)*x without doing the full multiplication. In general we
skip the part of the product that are known to be a huge integer (
more accurately, = 0 mod 8 ). Thus the number of operations are
independent of the exponent of the input.
(2/pi) is represented by an array of 24-bit integers in ipio2[].
Input parameters:
    x[] The input value (must be positive) is broken into nx
    pieces of 24-bit integers in double precision format.
    x[i] will be the i-th 24 bit of x. The scaled exponent
    of x[0] is given in input parameter e0 (i.e., x[0]*2^e0
    match x's up to 24 bits.
    Example of breaking a double positive z into x[0]+x[1]+x[2]:
        e0 = ilogb(z)-23
        z = scalbn(z,-e0)
    for i = 0,1,2
        x[i] = floor(z)
        z = (z-x[i])*2**24
 y[] ouput result in an array of double precision numbers.
    The dimension of y[] is:
        24-bit precision 1
        53-bit precision 2
        64-bit precision 2
        113-bit precision 3
    The actual value is the sum of them. Thus for 113-bit
    precison, one may have to do something like:
    long double t,w,r_head, r_tail;
    t = (long double)y[2] + (long double)y[1];
    w = (long double)y[0];
    r_head = t+w;
    r_tail = w - (r_head - t);
 e0 The exponent of x[0]
 nx dimension of x[]
    prec an integer indicating the precision:
        0 24 bits (single)
        1 53 bits (double)
        2 64 bits (extended)
        3 113 bits (quad)
 ipio2[]
    integer array, contains the (24*i)-th to (24*i+23)-th
    bit of 2/pi after binary point. The corresponding
    floating value is
        ipio2[i] * 2^(-24(i+1)).
External function:
 double scalbn(), floor();
Here is the description of some local variables:
    jk jk+1 is the initial number of terms of ipio2[] needed
    in the computation. The recommended value is 2,3,4,
    6 for single, double, extended,and quad.
    jz local integer variable indicating the number of
    terms of ipio2[] used.
 jx nx - 1
 jv index for pointing to the suitable ipio2[] for the
    computation. In general, we want
        ( 2^e0*x[0] * ipio2[jv-1]*2^(-24jv) )/8
    is an integer. Thus
        e0-3-24*jv >= 0 or (e0-3)/24 >= jv
    Hence jv = max(0,(e0-3)/24).
 jp jp+1 is the number of terms in PIo2[] needed, jp = jk.
    q[] double array with integral value, representing the
    24-bits chunk of the product of x and 2/pi.
 q0 the corresponding exponent of q[0]. Note that the
    exponent for q[i] would be q0-24*i.
 PIo2[] double precision array, obtained by cutting pi/2
    into 24 bits chunks.
 f[] ipio2[] in floating point
 iq[] integer array by breaking up q[] in 24-bits chunk.
 fq[] final product of x*(2/pi) in fq[0],..,fq[jk]
 ih integer. If >0 it indicates q[] is >= 0.5, hence
    it also indicates the *sign* of the result.
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 190 of file kremp2.c.
References init_jk, one, PIo2, scalbn(), two24, twon24, and zero.
Referenced by rempio2().
{
    int jz,jx,jv,jp,jk,carry,n,iq[20],i,j,k,m,q0,ih;
    double z,fw,f[20],fq[20],q[20];
    /* initialize jk*/
    jk = init_jk[prec];
    jp = jk;
    /* determine jx,jv,q0, note that 3>q0 */
    jx = nx-1;
    jv = (e0-3)/24;
    if(jv<0) jv=0;
    q0 = e0-24*(jv+1);
    /* set up f[0] to f[jx+jk] where f[jx+jk] = ipio2[jv+jk] */
    j = jv-jx;
    m = jx+jk;
    for(i=0; i<=m; i++,j++) f[i] = (j<0)? zero : (double) ipio2[j];
    /* compute q[0],q[1],...q[jk] */
    for (i=0; i<=jk; i++) {
        for(j=0,fw=0.0; j<=jx; j++) fw += x[j]*f[jx+i-j];
        q[i] = fw;
    }
    jz = jk;
recompute:
    /* distill q[] into iq[] reversingly */
    for(i=0,j=jz,z=q[jz]; j>0; i++,j--) {
        fw = (double)((int)(twon24* z));
        iq[i] = (int)(z-two24*fw);
        z = q[j-1]+fw;
    }
    /* compute n */
    z = scalbn(z,q0); /* actual value of z */
    z -= 8.0*floor(z*0.125); /* trim off integer >= 8 */
    n = (int) z;
    z -= (double)n;
    ih = 0;
    if(q0>0) { /* need iq[jz-1] to determine n */
        i = (iq[jz-1]>>(24-q0));
        n += i;
        iq[jz-1] -= i<<(24-q0);
        ih = iq[jz-1]>>(23-q0);
    }
    else if(q0==0) ih = iq[jz-1]>>23;
    else if(z>=0.5) ih=2;
    if(ih>0) { /* q > 0.5 */
        n += 1;
        carry = 0;
        for(i=0; i<jz ; i++) { /* compute 1-q */
            j = iq[i];
            if(carry==0) {
                if(j!=0) {
                    carry = 1;
                    iq[i] = 0x1000000- j;
                }
            } else iq[i] = 0xffffff - j;
        }
        if(q0>0) { /* rare case: chance is 1 in 12 */
            switch(q0) {
            case 1:
                iq[jz-1] &= 0x7fffff;
                break;
            case 2:
                iq[jz-1] &= 0x3fffff;
                break;
            }
        }
        if(ih==2) {
            z = one - z;
            if(carry!=0) z -= scalbn(one,q0);
        }
    }
    /* check if recomputation is needed */
    if(z==zero) {
        j = 0;
        for (i=jz-1; i>=jk; i--) j |= iq[i];
        if(j==0) { /* need recomputation */
            for(k=1; iq[jk-k]==0; k++); /* k = no. of terms needed */
            for(i=jz+1; i<=jz+k; i++) { /* add q[jz+1] to q[jz+k] */
                f[jx+i] = (double) ipio2[jv+i];
                for(j=0,fw=0.0; j<=jx; j++) fw += x[j]*f[jx+i-j];
                q[i] = fw;
            }
            jz += k;
            goto recompute;
        }
    }
    /* chop off zero terms */
    if(z==0.0) {
        jz -= 1;
        q0 -= 24;
        while(iq[jz]==0) {
            jz--;
            q0-=24;
        }
    } else { /* break z into 24-bit if necessary */
        z = scalbn(z,-q0);
        if(z>=two24) {
            fw = (double)((int)(twon24*z));
            iq[jz] = (int)(z-two24*fw);
            jz += 1;
            q0 += 24;
            iq[jz] = (int) fw;
        } else iq[jz] = (int) z ;
    }
    /* convert integer "bit" chunk to floating-point value */
    fw = scalbn(one,q0);
    for(i=jz; i>=0; i--) {
        q[i] = fw*(double)iq[i];
        fw*=twon24;
    }
    /* compute PIo2[0,...,jp]*q[jz,...,0] */
    for(i=jz; i>=0; i--) {
        for(fw=0.0,k=0; k<=jp&&k<=jz-i; k++) fw += PIo2[k]*q[i+k];
        fq[jz-i] = fw;
    }
    /* compress fq[] into y[] */
    switch(prec) {
    case 0:
        fw = 0.0;
        for (i=jz; i>=0; i--) fw += fq[i];
        y[0] = (ih==0)? fw: -fw;
        break;
    case 1:
    case 2:
        fw = 0.0;
        for (i=jz; i>=0; i--) fw += fq[i];
        y[0] = (ih==0)? fw: -fw;
        fw = fq[0]-fw;
        for (i=1; i<=jz; i++) fw += fq[i];
        y[1] = (ih==0)? fw: -fw;
        break;
    case 3: /* painful */
        for (i=jz; i>0; i--) {
            fw = fq[i-1]+fq[i];
            fq[i] += fq[i-1]-fw;
            fq[i-1] = fw;
        }
        for (i=jz; i>1; i--) {
            fw = fq[i-1]+fq[i];
            fq[i] += fq[i-1]-fw;
            fq[i-1] = fw;
        }
        for (fw=0.0,i=jz; i>=2; i--) fw += fq[i];
        if(ih==0) {
            y[0] = fq[0];
            y[1] = fq[1];
            y[2] = fw;
        } else {
            y[0] = -fq[0];
            y[1] = -fq[1];
            y[2] = -fw;
        }
    }
    return n&7;
}
double __kernel_sin (double x, double y, int iy)
Kernel sin function.
Version:
1.3
Date:
95/01/18
Kernel sin function on [-pi/4, pi/4], pi/4 ~ 0.7854 Input x is assumed to be bounded by ~pi/4 in magnitude. Input y is the tail of x. Input iy indicates whether y is 0. (if iy=0, y assume to be 0).
Algorithm
1.
Since sin(-x) = -sin(x), we need only to consider positive x.
2.
if x < 2^-27 (hx<0x3e400000 0), return x with inexact if x!=0.
3.
sin(x) is approximated by a polynomial of degree 13 on [0,pi/4] 3 13 sin(x) ~ x + S1*x + ... + S6*x where
|sin(x) 2 4 6 8 10 12 | -58 |----- - (1+S1*x +S2*x +S3*x +S4*x +S5*x +S6*x )| <= 2 | x |
4.
sin(x+y) = sin(x) + sin'(x')*y ~ sin(x) + (1-x*x/2)*y For better accuracy, let 3 2 2 2 2 r = x *(S2+x *(S3+x *(S4+x *(S5+x *S6)))) then 3 2 sin(x) = x + (S1*x + (x *(r-y/2)+y))
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 92 of file ksin.c.
References half, S1, S2, S3, S4, S5, and S6.
Referenced by cos(), and sin().
{
    double z,r,v;
    sword ix;
    GET_HIGH_WORD(ix,x);
    ix &=0x7fffffff; /* high word of x */
    if(ix<0x3e400000) /* |x| < 2**-27 */
    {
        if((int)x==0) return x; /* generate inexact */
    }
    z = x*x;
    v = z*x;
    r = S2+z*(S3+z*(S4+z*(S5+z*S6)));
    if(iy==0) return x+v*(S1+z*r);
    else return x-((z*(half*y-v*r)-y)-v*S1);
}
double __kernel_tan (double x, double y, int iy)
Kernel tan function.
Version:
1.5
Date:
04/04/22
Kernel tan function on [-pi/4, pi/4], pi/4 ~ 0.7854 Input x is assumed to be bounded by ~pi/4 in magnitude. Input y is the tail of x. Input k indicates whether tan (if k = 1) or -1/tan (if k = -1) is returned.
Algorithm
1.
Since tan(-x) = -tan(x), we need only to consider positive x.
2.
if x < 2^-28 (hx<0x3e300000 0), return x with inexact if x!=0.
3.
tan(x) is approximated by a odd polynomial of degree 27 on [0,0.67434] 3 27 tan(x) ~ x + T1*x + ... + T13*x where
    |tan(x) 2 4 26 | -59.2
    |----- - (1+T1*x +T2*x +.... +T13*x )| <= 2
    | x |
Note: tan(x+y) = tan(x) + tan'(x)*y ~ tan(x) + (1+x*x)*y Therefore, for better accuracy in computing tan(x+y), let 3 2 2 2 2 r = x *(T2+x *(T3+x *(...+x *(T12+x *T13)))) then 3 2 tan(x+y) = x + (T1*x + (x *(r+y)+y))
4.
For x in [0.67434,pi/4], let y = pi/4 - x, then tan(x) = tan(pi/4-y) = (1-tan(y))/(1+tan(y)) = 1 - 2*(tan(y) - (tan(y)^2)/(1+tan(y)))
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 112 of file ktan.c.
Referenced by tan().
                                                {
    double z, r, v, w, s;
    sword ix, hx;
    GET_HIGH_WORD(hx,x); /* high word of x */
    ix = hx & 0x7fffffff; /* high word of |x| */
    if (ix < 0x3e300000) { /* x < 2**-28 */
        if ((int) x == 0) { /* generate inexact */
            uword low;
            GET_LOW_WORD(low,x);
            if (((ix | low) | (iy + 1)) == 0)
                return one / fabs(x);
            else {
                if (iy == 1)
                    return x;
                else { /* compute -1 / (x+y) carefully */
                    double a, t;
                    z = w = x + y;
                    SET_LOW_WORD(z,0);
                    v = y - (z - x);
                    t = a = -one / w;
                    SET_LOW_WORD(t,0);
                    s = one + t * z;
                    return t + a * (s + t * v);
                }
            }
        }
    }
    if (ix >= 0x3FE59428) { /* |x| >= 0.6744 */
        if (hx < 0) {
            x = -x;
            y = -y;
        }
        z = pio4 - x;
        w = pio4lo - y;
        x = z + w;
        y = 0.0;
    }
    z = x * x;
    w = z * z;
    /*
     * Break x^5*(T[1]+x^2*T[2]+...) into
     * x^5(T[1]+x^4*T[3]+...+x^20*T[11]) +
     * x^5(x^2*(T[2]+x^4*T[4]+...+x^22*[T12]))
     */
    r = T[1] + w * (T[3] + w * (T[5] + w * (T[7] + w * (T[9] +
                                            w * T[11]))));
    v = z * (T[2] + w * (T[4] + w * (T[6] + w * (T[8] + w * (T[10] +
                                     w * T[12])))));
    s = z * x;
    r = y + z * (s * (r + v) + y);
    r += T[0] * s;
    w = x + r;
    if (ix >= 0x3FE59428) {
        v = (double) iy;
        return (double) (1 - ((hx >> 30) & 2)) *
               (v - 2.0 * (x - (w * w / (w + v) - r)));
    }
    if (iy == 1)
        return w;
    else {
        /*
         * if allow error up to 2 ulp, simply return
         * -1.0 / (x+r) here
         */
        /* compute -1.0 / (x+r) accurately */
        double a, t;
        z = w;
        SET_LOW_WORD(z,0);
        v = r - (z - x); /* z+v = r+x */
        t = a = -1.0 / w; /* a = -1.0/w */
        SET_LOW_WORD(t,0);
        s = 1.0 + t * z;
        return t + a * (s + t * v);
    }
}
Author
Generated automatically by Doxygen for amath from the source code.