.TH "app/system/program_amiga.cpp" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/program_amiga.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br
\fC#include 'main/graphlist\&.h'\fP
.br
\fC#include 'main/evaluator\&.h'\fP
.br
\fC#include 'system/console\&.h'\fP
.br
\fC#include 'system/filesystem\&.h'\fP
.br
\fC#include 'system/program_amiga\&.h'\fP
.br
\fC#include 'system/console_amiga\&.h'\fP
.br
\fC#include 'system/window_amiga\&.h'\fP
.br
\fC#include 'system/language_amiga\&.h'\fP
.br
\fC#include 'system/filesystem_amiga\&.h'\fP
.br
\fC#include 'system/preferences_amiga\&.h'\fP
.br
\fC#include 'system/base/io\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
