.TH "Program" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Program \- Master control class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <program\&.h>\fP
.PP
Inherited by \fBAmigaProgram\fP, \fBStandardProgram\fP, and \fBTestProgram\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgram\fP ()"
.br
.ti -1c
.RI "virtual \fB~Program\fP ()"
.br
.ti -1c
.RI "virtual void \fBInitialize\fP (int argc, char **argv)=0"
.br
.ti -1c
.RI "virtual void \fBRun\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBExit\fP ()=0"
.br
.ti -1c
.RI "void \fBNewPositionalInput\fP (short unsigned int base, short unsigned int digits)"
.br
.ti -1c
.RI "void \fBNewPositionalOutput\fP (short unsigned int base, short unsigned int digits)"
.br
.ti -1c
.RI "void \fBSetLastResult\fP (\fBNumber\fP *number)"
.br
.ti -1c
.RI "void \fBSetPrompt\fP (const char *text)"
.br
.ti -1c
.RI "struct \fBNumber\fP * \fBGetLastResult\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "class \fBLanguage\fP * \fBLanguage\fP"
.br
.ti -1c
.RI "class \fBConsoleBase\fP * \fBConsole\fP"
.br
.ti -1c
.RI "class \fBPreferencesBase\fP * \fBPreferences\fP"
.br
.ti -1c
.RI "class \fBFilesystemBase\fP * \fBFilesystem\fP"
.br
.ti -1c
.RI "class \fBNumeralSystem\fP * \fBInput\fP"
.br
.ti -1c
.RI "class \fBNumeralSystem\fP * \fBOutput\fP"
.br
.ti -1c
.RI "class \fBVariableList\fP * \fBVariables\fP"
.br
.ti -1c
.RI "class \fBFunctionList\fP * \fBFunctions\fP"
.br
.ti -1c
.RI "class \fBGraphList\fP * \fBGraphs\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "struct \fBNumber\fP * \fBins\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Master control class\&. 

This control class handles all processes and data in the entire program\&. It usually only exist as a single instance\&. 
.PP
Definition at line 56 of file program\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Program::Program ()"

.PP
Definition at line 35 of file program\&.cpp\&.
.PP
References CreateFilesystem(), CreateLanguage(), CreatePreferences(), DecimalSystem::DecimalSystem(), Filesystem, FunctionList::FunctionList(), Functions, PreferencesBase::GetDigits(), Language::GetFractionPoint(), GraphList::GraphList(), Graphs, Input, ins, Output, Preferences, RealNumber::RealNumber(), VariableList::VariableList(), and Variables\&.
.PP
Referenced by StandardProgram::StandardProgram()\&.
.PP
.nf
36 {
37     Variables = new VariableList();
38     Functions = new FunctionList();
39     Graphs = new GraphList();
40     ins = new RealNumber();
41     Language = CreateLanguage();
42     Filesystem = CreateFilesystem();
43     Preferences = CreatePreferences();
44     Input = new DecimalSystem(Preferences->GetDigits(), Language->GetFractionPoint());
45     Output = new DecimalSystem(Preferences->GetDigits(), Language->GetFractionPoint());
46 }
.fi
.SS "Program::~Program ()\fC [virtual]\fP"

.PP
Definition at line 48 of file program\&.cpp\&.
.PP
References Filesystem, Functions, Graphs, Input, ins, PreferencesBase::Keep(), Output, Preferences, and Variables\&.
.PP
.nf
49 {
50     delete Variables;
51     delete Functions;
52     delete Graphs;
53     delete Filesystem;
54     delete Output;
55     delete Input;
56     delete Language;
57     delete ins;
58 
59     Preferences->Keep();
60     delete Preferences;
61 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void Program::Exit ()\fC [pure virtual]\fP"

.PP
Implemented in \fBTestProgram\fP, \fBAmigaProgram\fP, and \fBStandardProgram\fP\&.
.PP
Referenced by ExitStatement::Execute()\&.
.SS "\fBNumber\fP * Program::GetLastResult ()"

.PP
Definition at line 97 of file program\&.cpp\&.
.PP
References ins\&.
.PP
Referenced by InsVariableNode::Evaluate()\&.
.PP
.nf
98 {
99     return ins;
100 }
.fi
.SS "virtual void Program::Initialize (int argc, char ** argv)\fC [pure virtual]\fP"

.PP
Implemented in \fBTestProgram\fP, \fBAmigaProgram\fP, and \fBStandardProgram\fP\&.
.PP
Referenced by main()\&.
.SS "void Program::NewPositionalInput (short unsigned int base, short unsigned int digits)"

.PP
Definition at line 63 of file program\&.cpp\&.
.PP
References DecimalSystem::DecimalSystem(), Language::GetFractionPoint(), Input, and PositionalNumeralSystem::PositionalNumeralSystem()\&.
.PP
Referenced by InputStatement::Execute()\&.
.PP
.nf
64 {
65     delete Input;
66 
67     char fractionpoint = Language->GetFractionPoint();
68 
69     if (base == 10) {
70         Input = new DecimalSystem(digits, fractionpoint);
71     } else {
72         Input = new PositionalNumeralSystem(base, digits, fractionpoint);
73     }
74 }
.fi
.SS "void Program::NewPositionalOutput (short unsigned int base, short unsigned int digits)"

.PP
Definition at line 76 of file program\&.cpp\&.
.PP
References DecimalSystem::DecimalSystem(), Language::GetFractionPoint(), Output, and PositionalNumeralSystem::PositionalNumeralSystem()\&.
.PP
Referenced by OutputStatement::Execute()\&.
.PP
.nf
77 {
78     delete Output;
79 
80     char fractionpoint = Language->GetFractionPoint();
81 
82     if (base == 10) {
83         Output = new DecimalSystem(digits, fractionpoint);
84     } else {
85         Output = new PositionalNumeralSystem(base, digits, fractionpoint);
86     }
87 }
.fi
.SS "virtual void Program::Run ()\fC [pure virtual]\fP"

.PP
Implemented in \fBTestProgram\fP, \fBAmigaProgram\fP, and \fBStandardProgram\fP\&.
.PP
Referenced by main()\&.
.SS "void Program::SetLastResult (\fBNumber\fP * number)"

.PP
Definition at line 102 of file program\&.cpp\&.
.PP
References Number::Clone(), and ins\&.
.PP
Referenced by EvalStatement::Execute()\&.
.PP
.nf
103 {
104     delete ins;
105     ins = number->Clone();
106 }
.fi
.SS "void Program::SetPrompt (const char * text)"

.PP
Definition at line 89 of file program\&.cpp\&.
.PP
References Console, Preferences, PreferencesBase::SetPrompt(), and ConsoleBase::SetPrompt()\&.
.PP
Referenced by PromptStatement::Execute()\&.
.PP
.nf
90 {
91     if (Console != NOMEM) {
92         Console->SetPrompt(text);
93     }
94     Preferences->SetPrompt(text);
95 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "class \fBConsoleBase\fP* Program::Console"

.PP
Definition at line 69 of file program\&.h\&.
.PP
Referenced by ClearStatement::Execute(), PrefsStatement::Execute(), StandardProgram::Exit(), StandardProgram::Initialize(), StandardProgram::Run(), SetPrompt(), StandardProgram::StandardProgram(), and StandardProgram::~StandardProgram()\&.
.SS "class \fBFilesystemBase\fP* Program::Filesystem"

.PP
Definition at line 71 of file program\&.h\&.
.PP
Referenced by ShowStatement::Execute(), ListStatement::Execute(), LoadStatement::Execute(), SaveStatement::Execute(), ExecuteStatement::Execute(), Program(), and ~Program()\&.
.SS "class \fBFunctionList\fP* Program::Functions"

.PP
Definition at line 75 of file program\&.h\&.
.PP
Referenced by ListFunctionsStatement::Execute(), DeleteStatement::Execute(), SaveStatement::Execute(), PlotStatement::Execute(), DrawStatement::Execute(), Parser::ParseFunctionDef(), Parser::ParseIdent(), Program(), and ~Program()\&.
.SS "class \fBGraphList\fP* Program::Graphs"

.PP
Definition at line 76 of file program\&.h\&.
.PP
Referenced by DrawStatement::Execute(), Program(), and ~Program()\&.
.SS "class \fBNumeralSystem\fP* Program::Input"

.PP
Definition at line 72 of file program\&.h\&.
.PP
Referenced by PrefsStatement::Execute(), InputStatement::Execute(), DigitsStatement::Execute(), Lexer::GetDigitValue(), NumericValueNode::GetNodeText(), NewPositionalInput(), Parser::ParseNumber(), Program(), and ~Program()\&.
.SS "struct \fBNumber\fP* Program::ins\fC [private]\fP"

.PP
Definition at line 79 of file program\&.h\&.
.PP
Referenced by GetLastResult(), Program(), SetLastResult(), and ~Program()\&.
.SS "class \fBLanguage\fP* Program::Language"

.PP
Definition at line 68 of file program\&.h\&.
.SS "class \fBNumeralSystem\fP* Program::Output"

.PP
Definition at line 73 of file program\&.h\&.
.PP
Referenced by PrefsStatement::Execute(), EvalStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), VariableList::ListContent(), NewPositionalOutput(), Program(), and ~Program()\&.
.SS "class \fBPreferencesBase\fP* Program::Preferences"

.PP
Definition at line 70 of file program\&.h\&.
.PP
Referenced by PrefsStatement::Execute(), DigitsStatement::Execute(), StandardProgram::Initialize(), Program(), StandardProgram::Run(), SetPrompt(), and ~Program()\&.
.SS "class \fBVariableList\fP* Program::Variables"

.PP
Definition at line 74 of file program\&.h\&.
.PP
Referenced by ListVariablesStatement::Execute(), DeleteStatement::Execute(), SaveStatement::Execute(), Parser::ParseFunctionDef(), Parser::ParseIdent(), Program(), and ~Program()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
