.TH "app/system/program.cpp" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/program.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/numb\&.h'\fP
.br
\fC#include 'lib/ntext\&.h'\fP
.br
\fC#include 'main/values\&.h'\fP
.br
\fC#include 'main/functions\&.h'\fP
.br
\fC#include 'system/program\&.h'\fP
.br
\fC#include 'system/base/io\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
