.TH "app/system/program_test.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/program_test.h \- Tests for arithmetic logic\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lib/charbuf\&.h'\fP
.br
\fC#include 'system/program\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestProgram\fP"
.br
.RI "\fITest control class\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Tests for arithmetic logic\&. 


.PP
Definition in file \fBprogram_test\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
