.TH "app/system/program.h" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/program.h \- \fBProgram\fP flow and global states\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'lib/numb\&.h'\fP
.br
\fC#include 'lib/ntext\&.h'\fP
.br
\fC#include 'main/values\&.h'\fP
.br
\fC#include 'main/graphlist\&.h'\fP
.br
\fC#include 'main/functions\&.h'\fP
.br
\fC#include 'system/console\&.h'\fP
.br
\fC#include 'system/language\&.h'\fP
.br
\fC#include 'system/filesystem\&.h'\fP
.br
\fC#include 'system/preferences\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProgram\fP"
.br
.RI "\fIMaster control class\&. \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBProgram\fP * \fBProgram\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBProgram\fP flow and global states\&. 


.PP
Definition in file \fBprogram\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "class \fBProgram\fP* \fBProgram\fP"

.PP
Definition at line 69 of file io\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
