PromptStatement
NAME
PromptStatement - Set prompt string.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
PromptStatement (char *prompt)
~PromptStatement ()
char * Execute ()
Private Attributes
char * prompt
Additional Inherited Members
Detailed Description
Set prompt string.
Definition at line 105 of file statements.h.
Constructor & Destructor Documentation
PromptStatement::PromptStatement (char * prompt)
Definition at line 97 of file statements.cpp.
References AllocAndCopy(), and prompt.
Referenced by Parser::ParsePromptStatement().
{
    AllocAndCopy(&this->prompt,prompt);
}
PromptStatement::~PromptStatement ()
Definition at line 102 of file statements.cpp.
References prompt.
{
    delete prompt;
}
Member Function Documentation
char * PromptStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 107 of file statements.cpp.
References CharBuffer::Append(), CharBuffer::CharBuffer(), CharBuffer::ClearAndCopy(), CharBuffer::GetString(), prompt, CharBuffer::RemoveTrailing(), and Program::SetPrompt().
{
    CharBuffer *buf = new CharBuffer();
    buf->ClearAndCopy(prompt);
    while(buf->RemoveTrailing(' '));
    buf->Append(' ');
    Program->SetPrompt(buf->GetString());
    delete buf;
    return (char*)EMPTYSTRING;
}
Member Data Documentation
char* PromptStatement::prompt [private]
Definition at line 112 of file statements.h.
Referenced by Execute(), PromptStatement(), and ~PromptStatement().
Author
Generated automatically by Doxygen for amath from the source code.