.TH "app/lib/real.cpp" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/lib/real.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'math\&.h'\fP
.br
\fC#include 'lib/numb\&.h'\fP
.br
\fC#include 'lib/real\&.h'\fP
.br
\fC#include 'lib/cplex\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
