RealNumber
NAME
RealNumber - Represent a real number with 15 siginificant digits.
SYNOPSIS
#include <real.h>
Inherits Number.
Public Member Functions
RealNumber ()
RealNumber (double x)
RealNumber (signed int i)
RealNumber (unsigned int i)
~RealNumber ()
int IsNaN ()
int IsFinite ()
Number * Clone ()
int GetIntegerValue ()
double GetRealValue ()
void SetRealValue (double value)
bool PureComplexValue ()
int GetPrecedence ()
int GetDefaultPrecedence ()
Number * Unary ()
Number * Add (Number *other)
Number * Sub (Number *other)
Number * Mul (Number *other)
Number * Div (Number *other)
Number * Raise (Number *exponent)
Expontation function.
Number * Signum ()
Mathematical sign function.
Number * Trunc ()
Mathematical trunc function.
Number * Round ()
Mathematical round function.
Number * Floor ()
Mathematical floor function.
Number * Ceiling ()
Mathematical ceiling function.
Number * Absolute ()
Absolute value of number.
Number * SquareRoot ()
Square root function.
Number * CubeRoot ()
Cube root function.
Number * Reciprocal ()
Number * Log ()
Natural logarithm function (base e).
Number * Log2 ()
Binary logarithm function (base 2).
Number * Log10 ()
Base 10 logarithm function.
Number * Sine ()
Trigonometric sine function.
Number * Cosine ()
Trigonometric cosine function.
Number * Tangent ()
Trigonometric tangent function.
Number * Cosecant ()
Trigonometric cosecant function.
Number * Secant ()
Trigonometric secant function.
Number * Cotangent ()
Trigonometric cotangent function.
Number * ArcSine ()
Inverse trigonometric sine function.
Number * ArcCosine ()
Inverse trigonometric cosine function.
Number * ArcTangent ()
Inverse trigonometric tangent function.
Number * ArcCosecant ()
Inverse trigonometric cosecant function.
Number * ArcSecant ()
Inverse trigonometric secant function.
Number * ArcCotangent ()
Inverse trigonometric cotangent function.
Number * HypSine ()
Hyperbolic sine function.
Number * HypCosine ()
Hyperbolic cosine function.
Number * HypTangent ()
Hyperbolic tangent function.
Number * HypCosecant ()
Hyperbolic cosecant function.
Number * HypSecant ()
Hyperbolic secant function.
Number * HypCotangent ()
Hyperbolic cotangent function.
Number * HypArcSine ()
Inverse hyperbolic sine function.
Number * HypArcCosine ()
Inverse hyperbolic cosine function.
Number * HypArcTangent ()
Inverse hyperbolic tangent function.
Number * HypArcCosecant ()
Inverse hyperbolic cosecant function.
Number * HypArcSecant ()
Inverse hyperbolic secant function.
Number * HypArcCotangent ()
Inverse hyperbolic cotangent function.
Private Attributes
double x
Friends
struct ComplexNumber
Additional Inherited Members
Detailed Description
Represent a real number with 15 siginificant digits.
Calculations are done using 64 bit IEEE 754 arithmetics.
Definition at line 44 of file real.h.
Constructor & Destructor Documentation
RealNumber::RealNumber ()
Definition at line 33 of file real.cpp.
References nsysreal, Number::Number(), and x.
Referenced by PlotStatement::Execute(), Grid::Grid(), NumericValueNode::NumericValueNode(), PositionalNumeralSystem::Parse(), and Program::Program().
                       :
    Number(nsysreal) {
    x = 0;
}
RealNumber::RealNumber (double x)
Definition at line 38 of file real.cpp.
References nsysreal, Number::Number(), and x.
Referenced by ComplexNumber::Absolute(), Absolute(), Add(), ArcCosecant(), ArcCosine(), ArcCotangent(), ArcSecant(), ArcSine(), ArcTangent(), Ceiling(), Clone(), Cosecant(), Cosine(), Cotangent(), CubeRoot(), Div(), EulersNumberNode::EulersNumberNode(), Floor(), PositionalNumeralSystem::GetName(), HypArcCosecant(), HypArcCosine(), HypArcCotangent(), HypArcSecant(), HypArcSine(), HypArcTangent(), HypCosecant(), HypCosine(), HypCotangent(), HypSecant(), HypSine(), HypTangent(), Log(), Log10(), Log2(), Mul(), PositionalNumeralSystem::Parse(), PiNode::PiNode(), Raise(), Reciprocal(), Round(), Secant(), ComplexNumber::Signum(), Signum(), Sine(), SquareRoot(), Sub(), Tangent(), Trunc(), and Unary().
                               :
    Number(nsysreal) {
    this->x = x;
}
RealNumber::RealNumber (signed int i)
Definition at line 43 of file real.cpp.
References nsysreal, Number::Number(), and x.
Referenced by MemoryStatement::Execute(), and PreferencesBase::GetDescription().
                                   :
    Number(nsysreal) {
    x = i * 1.0;
}
RealNumber::RealNumber (unsigned int i)
Definition at line 48 of file real.cpp.
References nsysreal, Number::Number(), and x.
Referenced by DigitsStatement::Execute().
                                     :
    Number(nsysreal) {
    x = i * 1.0;
}
RealNumber::~RealNumber ()
Definition at line 53 of file real.cpp.
{ }
Member Function Documentation
Number * RealNumber::Absolute () [virtual]
Absolute value of number. See implementation in fabs(double)
Implements Number.
Definition at line 224 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(fabs(x));
}
Number * RealNumber::Add (Number * other) [virtual]
Implements Number.
Definition at line 106 of file real.cpp.
References Number::Add(), nsysreal, RealNumber(), Number::system, and x.
{
    if (other->system == nsysreal) {
        RealNumber *a = (RealNumber*)other;
        return new RealNumber(x + a->x);
    } else {
        return other->Add(this);
    }
}
Number * RealNumber::ArcCosecant () [virtual]
Inverse trigonometric cosecant function. See implementation of inverse trigonometric sine in asin(double)
Implements Number.
Definition at line 467 of file real.cpp.
References asin(), RealNumber(), and x.
{
    return new RealNumber(asin(1.0/x));
}
Number * RealNumber::ArcCosine () [virtual]
Inverse trigonometric cosine function. See implementation of inverse trigonometric cosine in acos(double)
Implements Number.
Definition at line 417 of file real.cpp.
References acos(), RealNumber(), and x.
{
    return new RealNumber(acos(x));
}
Number * RealNumber::ArcCotangent () [virtual]
Inverse trigonometric cotangent function. See implementation of inverse trigonometric tangent in atan(double)
Implements Number.
Definition at line 447 of file real.cpp.
References atan(), RealNumber(), and x.
{
    return new RealNumber(atan(1.0/x));
}
Number * RealNumber::ArcSecant () [virtual]
Inverse trigonometric secant function. See implementation of inverse trigonometric cosine in acos(double)
Implements Number.
Definition at line 427 of file real.cpp.
References acos(), RealNumber(), and x.
{
    return new RealNumber(acos(1.0/x));
}
Number * RealNumber::ArcSine () [virtual]
Inverse trigonometric sine function. See implementation of inverse trigonometric sine in asin(double)
Implements Number.
Definition at line 457 of file real.cpp.
References asin(), RealNumber(), and x.
{
    return new RealNumber(asin(x));
}
Number * RealNumber::ArcTangent () [virtual]
Inverse trigonometric tangent function. See implementation of inverse trigonometric tangent in atan(double)
Implements Number.
Definition at line 437 of file real.cpp.
References atan(), RealNumber(), and x.
{
    return new RealNumber(atan(x));
}
Number * RealNumber::Ceiling () [virtual]
Mathematical ceiling function. See implementation in ceil(double)
Implements Number.
Definition at line 214 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(ceil(x));
}
Number * RealNumber::Clone () [virtual]
Implements Number.
Definition at line 56 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(x);
}
Number * RealNumber::Cosecant () [virtual]
Trigonometric cosecant function. See implementation of sine function in sin(double)
Implements Number.
Definition at line 407 of file real.cpp.
References RealNumber(), sin(), and x.
{
    return new RealNumber(1.0/sin(x));
}
Number * RealNumber::Cosine () [virtual]
Trigonometric cosine function. See implementation of cosine function in cos(double)
Implements Number.
Definition at line 297 of file real.cpp.
References cos(), RealNumber(), and x.
{
    return new RealNumber(cos(x));
}
Number * RealNumber::Cotangent () [virtual]
Trigonometric cotangent function. See implementation of tangent function in tan(double)
Implements Number.
Definition at line 327 of file real.cpp.
References RealNumber(), tan(), and x.
{
    return new RealNumber(1.0/tan(x));
}
Number * RealNumber::CubeRoot () [virtual]
Cube root function. See implementation of cube root in cbrt(double)
Implements Number.
Definition at line 251 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(cbrt(x));
}
Number * RealNumber::Div (Number * other) [virtual]
Implements Number.
Definition at line 139 of file real.cpp.
References Mul(), nsysreal, RealNumber(), Number::Reciprocal(), Number::system, and x.
{
    if (other->system == nsysreal) {
        RealNumber *a = (RealNumber*)other;
        return new RealNumber(x / a->x);
    } else {
        Number *y = other->Reciprocal();
        Number *q = Mul(y);
        delete y;
        return q;
    }
}
Number * RealNumber::Floor () [virtual]
Mathematical floor function. See implementation in floor(double)
Implements Number.
Definition at line 204 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(floor(x));
}
int RealNumber::GetDefaultPrecedence () [virtual]
Implements Number.
Definition at line 86 of file real.cpp.
{
    return 0;
}
int RealNumber::GetIntegerValue () [virtual]
Implements Number.
Definition at line 61 of file real.cpp.
References x.
{
    return (int) x;
}
int RealNumber::GetPrecedence () [virtual]
Implements Number.
Definition at line 81 of file real.cpp.
References x.
{
    return (x < 0.0) ? -1 : 0;
}
double RealNumber::GetRealValue () [virtual]
Implements Number.
Definition at line 66 of file real.cpp.
References x.
{
    return x;
}
Number * RealNumber::HypArcCosecant () [virtual]
Inverse hyperbolic cosecant function. See implementation of inverse hyperbolic sine in asinh(double)
Implements Number.
Definition at line 507 of file real.cpp.
References asinh(), RealNumber(), and x.
{
    return new RealNumber(asinh(1.0/x));
}
Number * RealNumber::HypArcCosine () [virtual]
Inverse hyperbolic cosine function. See implementation of inverse hyperbolic cosine in acosh(double)
Implements Number.
Definition at line 477 of file real.cpp.
References acosh(), RealNumber(), and x.
{
    return new RealNumber(acosh(x));
}
Number * RealNumber::HypArcCotangent () [virtual]
Inverse hyperbolic cotangent function. See implementation hyperbolic tangent in atanh(double)
Implements Number.
Definition at line 527 of file real.cpp.
References atanh(), RealNumber(), and x.
{
    return new RealNumber(atanh(1.0/x));
}
Number * RealNumber::HypArcSecant () [virtual]
Inverse hyperbolic secant function. See implementation of inverse hyperbolic cosine in acosh(double)
Implements Number.
Definition at line 487 of file real.cpp.
References acosh(), RealNumber(), and x.
{
    return new RealNumber(acosh(1.0/x));
}
Number * RealNumber::HypArcSine () [virtual]
Inverse hyperbolic sine function. See implementation of inverse hyperbolic sine in asinh(double)
Implements Number.
Definition at line 497 of file real.cpp.
References asinh(), RealNumber(), and x.
{
    return new RealNumber(asinh(x));
}
Number * RealNumber::HypArcTangent () [virtual]
Inverse hyperbolic tangent function. See implementation hyperbolic tangent in atanh(double)
Implements Number.
Definition at line 517 of file real.cpp.
References atanh(), RealNumber(), and x.
{
    return new RealNumber(atanh(x));
}
Number * RealNumber::HypCosecant () [virtual]
Hyperbolic cosecant function. See implementation of hyperbolic sine function in sinh(double)
Implements Number.
Definition at line 347 of file real.cpp.
References RealNumber(), sinh(), and x.
{
    return new RealNumber(1.0/sinh(x));
}
Number * RealNumber::HypCosine () [virtual]
Hyperbolic cosine function. See implementation of hyperbolic cosine function in cosh(double)
Implements Number.
Definition at line 357 of file real.cpp.
References cosh(), RealNumber(), and x.
{
    return new RealNumber(cosh(x));
}
Number * RealNumber::HypCotangent () [virtual]
Hyperbolic cotangent function. See implementation of hyperbolic tangent function in tanh(double)
Implements Number.
Definition at line 387 of file real.cpp.
References RealNumber(), tanh(), and x.
{
    return new RealNumber(1.0/tanh(x));
}
Number * RealNumber::HypSecant () [virtual]
Hyperbolic secant function. See implementation of hyperbolic cosine function in cosh(double)
Implements Number.
Definition at line 367 of file real.cpp.
References cosh(), RealNumber(), and x.
{
    return new RealNumber(1.0/cosh(x));
}
Number * RealNumber::HypSine () [virtual]
Hyperbolic sine function. See implementation of hyperbolic sine function in sinh(double)
Implements Number.
Definition at line 337 of file real.cpp.
References RealNumber(), sinh(), and x.
{
    return new RealNumber(sinh(x));
}
Number * RealNumber::HypTangent () [virtual]
Hyperbolic tangent function. See implementation of hyperbolic tangent function in tanh(double)
Implements Number.
Definition at line 377 of file real.cpp.
References RealNumber(), tanh(), and x.
{
    return new RealNumber(tanh(x));
}
int RealNumber::IsFinite ()
Definition at line 91 of file real.cpp.
References finite(), and x.
{
    return finite(x);
}
int RealNumber::IsNaN ()
Definition at line 96 of file real.cpp.
References isnan(), and x.
{
    return isnan(x);
}
Number * RealNumber::Log () [virtual]
Natural logarithm function (base e). See implementation of natural logarithm in log(double)
Implements Number.
Definition at line 277 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(log(x));
}
Number * RealNumber::Log10 () [virtual]
Base 10 logarithm function. See implementation of base 10 logarithm in log10(double)
Implements Number.
Definition at line 287 of file real.cpp.
References log10(), RealNumber(), and x.
{
    return new RealNumber(log10(x));
}
Number * RealNumber::Log2 () [virtual]
Binary logarithm function (base 2). See implementation of natural logarithm in log(double)
Implements Number.
Definition at line 267 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(log(x)/log(2.0));
}
Number * RealNumber::Mul (Number * other) [virtual]
Implements Number.
Definition at line 129 of file real.cpp.
References Number::Mul(), nsysreal, RealNumber(), Number::system, and x.
Referenced by Div().
{
    if (other->system == nsysreal) {
        RealNumber *a = (RealNumber*)other;
        return new RealNumber(x * a->x);
    } else {
        return other->Mul(this);
    }
}
bool RealNumber::PureComplexValue () [virtual]
Implements Number.
Definition at line 76 of file real.cpp.
{
    return false;
}
Number * RealNumber::Raise (Number * exponent) [virtual]
Expontation function. See implementation in pow(double, double)
Implements Number.
Definition at line 157 of file real.cpp.
References ComplexNumber::ComplexNumber(), nsysreal, pow(), ComplexNumber::Raise(), RealNumber(), Number::system, and x.
{
    if (exponent->system == nsysreal) {
        return new RealNumber(pow(x, ((RealNumber*)exponent)->x));
    } else {
        ComplexNumber *y = new ComplexNumber(x, 0.0);
        Number *q = y->Raise(exponent);
        delete y;
        return q;
    }
}
Number * RealNumber::Reciprocal () [virtual]
Implements Number.
Definition at line 257 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(1/x);
}
Number * RealNumber::Round () [virtual]
Mathematical round function. See implementation in round(double)
Implements Number.
Definition at line 194 of file real.cpp.
References RealNumber(), round(), and x.
{
    return new RealNumber(round(x));
}
Number * RealNumber::Secant () [virtual]
Trigonometric secant function. See implementation of cosine function in cos(double)
Implements Number.
Definition at line 307 of file real.cpp.
References cos(), RealNumber(), and x.
{
    return new RealNumber(1.0/cos(x));
}
void RealNumber::SetRealValue (double value)
Definition at line 71 of file real.cpp.
References x.
Referenced by PlotStatement::Execute(), and Grid::FunctionValue().
{
    x = value;
}
Number * RealNumber::Signum () [virtual]
Mathematical sign function. See implementation in sgn(double)
Implements Number.
Definition at line 174 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(sgn(x));
}
Number * RealNumber::Sine () [virtual]
Trigonometric sine function. See implementation of sine function in sin(double)
Implements Number.
Definition at line 397 of file real.cpp.
References RealNumber(), sin(), and x.
{
    return new RealNumber(sin(x));
}
Number * RealNumber::SquareRoot () [virtual]
Square root function. See implementation of square root in sqrt(double)
Implements Number.
Definition at line 234 of file real.cpp.
References ComplexNumber::ComplexNumber(), RealNumber(), sqrt(), Number::SquareRoot(), and x.
{
    if (x > 0.0) {
        return new RealNumber(sqrt(x));
    }
    Number *n = new ComplexNumber(x, 0);
    Number *r = n->SquareRoot();
    delete n;
    return r;
}
Number * RealNumber::Sub (Number * other) [virtual]
Implements Number.
Definition at line 116 of file real.cpp.
References Number::Add(), nsysreal, RealNumber(), Number::system, Number::Unary(), and x.
{
    if (other->system == nsysreal) {
        RealNumber *a = (RealNumber*)other;
        return new RealNumber(x - a->x);
    } else {
        Number *y = other->Unary();
        Number *q = y->Add(this);
        delete y;
        return q;
    }
}
Number * RealNumber::Tangent () [virtual]
Trigonometric tangent function. See implementation of tangent function in tan(double)
Implements Number.
Definition at line 317 of file real.cpp.
References RealNumber(), tan(), and x.
{
    return new RealNumber(tan(x));
}
Number * RealNumber::Trunc () [virtual]
Mathematical trunc function. See implementation in trunc(double)
Implements Number.
Definition at line 184 of file real.cpp.
References RealNumber(), trunc(), and x.
{
    return new RealNumber(trunc(x));
}
Number * RealNumber::Unary () [virtual]
Implements Number.
Definition at line 101 of file real.cpp.
References RealNumber(), and x.
{
    return new RealNumber(-x);
}
Friends And Related Function Documentation
friend struct ComplexNumber [friend]
Definition at line 110 of file real.h.
Member Data Documentation
double RealNumber::x [private]
Definition at line 113 of file real.h.
Referenced by Absolute(), ComplexNumber::Add(), Add(), ArcCosecant(), ArcCosine(), ArcCotangent(), ArcSecant(), ArcSine(), ArcTangent(), Ceiling(), Clone(), Cosecant(), Cosine(), Cotangent(), CubeRoot(), ComplexNumber::Div(), Div(), Floor(), GetIntegerValue(), GetPrecedence(), GetRealValue(), HypArcCosecant(), HypArcCosine(), HypArcCotangent(), HypArcSecant(), HypArcSine(), HypArcTangent(), HypCosecant(), HypCosine(), HypCotangent(), HypSecant(), HypSine(), HypTangent(), IsFinite(), IsNaN(), Log(), Log10(), Log2(), ComplexNumber::Mul(), Mul(), ComplexNumber::Raise(), Raise(), RealNumber(), Reciprocal(), Round(), Secant(), SetRealValue(), Signum(), Sine(), SquareRoot(), ComplexNumber::Sub(), Sub(), Tangent(), Trunc(), and Unary().
Author
Generated automatically by Doxygen for amath from the source code.