.TH "release_page" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
release_page \- Release history 

.SH "Release history"
.PP
.SS "v1\&.6\&.2 January 24 2017"
.IP "\(bu" 2
Fixed bug in memory allocation
.IP "\(bu" 2
Fixed bug in native keybord input
.IP "\(bu" 2
Included build options in executables
.PP
.SS "v1\&.6\&.1 January 21 2017"
.IP "\(bu" 2
Fixed language bug in Windows
.IP "\(bu" 2
Fixed potential memory bugs
.IP "\(bu" 2
Clang compiler support
.IP "\(bu" 2
Update copyright texts
.IP "\(bu" 2
New doxygen documentation
.PP
.SS "v1\&.6\&.0 April 7 2016"
.IP "\(bu" 2
Complete internal restructure of source code\&.
.IP "\(bu" 2
Fixed several minor bugs in calculation\&.
.IP "\(bu" 2
Support for Windows & Linux\&.
.IP "\(bu" 2
Custom memory handling\&.
.IP "\(bu" 2
Localization support\&.
.PP
.SS "1\&.5\&.4 March 04 2015"
.IP "\(bu" 2
Fixed several bugs in output of significant digits\&.
.IP "\(bu" 2
Fixed sign bug in addition of negative complex numbers\&.
.IP "\(bu" 2
Fixed sign bug in inverse hyperbolic cosine of complex numbers\&.
.IP "\(bu" 2
Fixed sign bug in inverse hyperbolic secant of complex numbers\&.
.IP "\(bu" 2
Fixed calculation bug in division of real number with complex number\&.
.IP "\(bu" 2
Fixed calculation bug in exponentiation with complex number\&.
.IP "\(bu" 2
Implemented reduction of unary sign in expressions\&.
.IP "\(bu" 2
Implemented reduction of complex numbers in expressions\&.
.IP "\(bu" 2
Implemented internal optimization of expression trees\&.
.IP "\(bu" 2
Miscellaneous internal code optimization\&.
.IP "\(bu" 2
Changed to Amiga hosted GCC compiler (ADE)\&.
.IP "\(bu" 2
Verified calculation through 192 test cases\&.
.PP
.SS "1\&.5\&.3 October 26 2014"
.IP "\(bu" 2
Changed iconed versions to run directly from Workbench\&.
.IP "\(bu" 2
Reconfigured builds to avoid erroneous calculations\&.
.IP "\(bu" 2
Removed broken support for numeral systems\&.
.IP "\(bu" 2
Switched to new floating output library\&.
.IP "\(bu" 2
Reintroduced 68020 FPU and 68030 version\&.
.PP
.SS "1\&.5\&.2 October 11 2014"
.IP "\(bu" 2
Modified character handling code to comply with licenses\&.
.IP "\(bu" 2
Modified complex math code to comply with licenses\&.
.IP "\(bu" 2
Modified code base to work with Kickstart 2\&.04\&.
.IP "\(bu" 2
Square root of negative numbers now yield correct result\&.
.IP "\(bu" 2
Implemented scientific notation of numbers\&.
.IP "\(bu" 2
Infinity is now shown in division with 0\&.
.IP "\(bu" 2
Fixed bug in number code sometimes yielding 0\&.
.IP "\(bu" 2
Switched to Amiga memory allocation\&.
.IP "\(bu" 2
Fixed out-of-memory bug\&.
.IP "\(bu" 2
Miscellaneous bug fixes\&.
.IP "\(bu" 2
Removed dead code\&.
.IP "\(bu" 2
Added icons\&.
.PP
.SS "1\&.5\&.1 September 28 2014"
.IP "\(bu" 2
Improved navigation with arrow keys\&.
.IP "\(bu" 2
Improved text and color compositions\&.
.IP "\(bu" 2
Implemented missing complex functions\&.
.IP "\(bu" 2
Fixed bug in negative complex numbers\&.
.IP "\(bu" 2
Fixed file I/O bug in shell mode\&.
.IP "\(bu" 2
Fixed shell flush bug on AROS\&.
.IP "\(bu" 2
Fixed clear console bug on AROS\&.
.IP "\(bu" 2
Miscellaneous minor bug fixes\&.
.PP
.SS "1\&.5 September 21 2014"
.IP "\(bu" 2
Calculation with complex numbers\&.
.IP "\(bu" 2
Fixed command line version\&.
.IP "\(bu" 2
Miscellaneous bug fixed\&.
.IP "\(bu" 2
Fixed spelling mistakes in help files\&.
.IP "\(bu" 2
Documentation including class diagrams in HTML format\&.
.IP "\(bu" 2
Scripts for porting and building the source\&.
.PP
.SS "1\&.4 August 24 2014"
.IP "\(bu" 2
New math engine based on Sun Microsystems fdlibm (64 bit IEEE 754)\&.
.IP "\(bu" 2
Support for positional numeral systems including binary, octal and hexadecimal\&.
.IP "\(bu" 2
Added pure command line version (CLI) as addition to the stand-alone version\&.
.IP "\(bu" 2
Added statement to clear all in-memory variables and functions\&.
.IP "\(bu" 2
Fixed bug causing console to close when entering an empty statement\&.
.IP "\(bu" 2
Fixed bug causing application to hang when loading files with KS 2\&.0\&.4\&.
.IP "\(bu" 2
Fixed accuracy bug when using pi and e\&.
.IP "\(bu" 2
Restructured and improved built-in help\&.
.IP "\(bu" 2
Added new 68030 and FPU versions\&.
.PP
.SS "1\&.3\&.2 August 11 2014"
.IP "\(bu" 2
Fixed two severe bugs causing memory corruption\&.
.PP
.SS "1\&.3\&.1 August 08 2014"
.IP "\(bu" 2
AROS i386 version released\&.
.PP
.SS "1\&.3 August 06 2014"
.IP "\(bu" 2
All trigonometric and hyperbolic functions are now supported\&.
.IP "\(bu" 2
Runs in console window\&. amath no longer depends on a shell\&.
.IP "\(bu" 2
Hardened code\&. amath is no longer a beta version\&.
.IP "\(bu" 2
Added support for disk based activities\&.
.IP "\(bu" 2
Fixed bug in exponentiation operator\&.
.IP "\(bu" 2
Reverted back to clib math\&.
.IP "\(bu" 2
Fixed a few memory leak bugs\&.
.IP "\(bu" 2
Optimized generated binaries\&.
.IP "\(bu" 2
Comments added in source code\&.
.IP "\(bu" 2
Improved error handling\&.
.IP "\(bu" 2
Improved built-in help\&.
.IP "\(bu" 2
Simplified license\&.
.PP
.SS "1\&.2b July 21 2014"
.IP "\(bu" 2
Root functions added\&.
.IP "\(bu" 2
User defined functions added\&.
.IP "\(bu" 2
Improved error handling\&.
.IP "\(bu" 2
Improved build-in help\&.
.IP "\(bu" 2
Binary support for additional processors\&.
.IP "\(bu" 2
Miscellaneous bug fixes\&.
.IP "\(bu" 2
Source files restructured\&.
.PP
.SS "1\&.1b July 13 2014"
.IP "\(bu" 2
Minor bug fixes\&.
.IP "\(bu" 2
Source code released\&.
.PP
.SS "1\&.0b July 11 2014"
.IP "\(bu" 2
First public release\&. 
.PP

