.TH "lib/real/rint.c" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/real/rint.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'fdlibm\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBrint\fP (double x)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "static double \fBTWO52\fP [2]"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "double rint (double x)"

.PP
Definition at line 68 of file rint\&.c\&.
.PP
.nf
71 {
72     int i0,j0,sx;
73     unsigned i,i1;
74     double w,t;
75     i0 =  __HI(x);
76     sx = (i0>>31)&1;
77     i1 =  __LO(x);
78     j0 = ((i0>>20)&0x7ff)-0x3ff;
79     if(j0<20) {
80         if(j0<0) {
81             if(((i0&0x7fffffff)|i1)==0) return x;
82             i1 |= (i0&0x0fffff);
83             i0 &= 0xfffe0000;
84             i0 |= ((i1|-i1)>>12)&0x80000;
85             __HI(x)=i0;
86             w = TWO52[sx]+x;
87             t =  w-TWO52[sx];
88             i0 = __HI(t);
89             __HI(t) = (i0&0x7fffffff)|(sx<<31);
90             return t;
91         } else {
92             i = (0x000fffff)>>j0;
93             if(((i0&i)|i1)==0) return x; /* x is integral */
94             i>>=1;
95             if(((i0&i)|i1)!=0) {
96                 if(j0==19) i1 = 0x40000000;
97                 else
98                     i0 = (i0&(~i))|((0x20000)>>j0);
99             }
100         }
101     } else if (j0>51) {
102         if(j0==0x400) return x+x;   /* inf or NaN */
103         else return x;      /* x is integral */
104     } else {
105         i = ((unsigned)(0xffffffff))>>(j0-20);
106         if((i1&i)==0) return x; /* x is integral */
107         i>>=1;
108         if((i1&i)!=0) i1 = (i1&(~i))|((0x40000000)>>(j0-20));
109     }
110     __HI(x) = i0;
111     __LO(x) = i1;
112     w = TWO52[sx]+x;
113     return w-TWO52[sx];
114 }
.fi
.SH "Variable Documentation"
.PP 
.SS "double TWO52[2]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    4\&.50359962737049600000e+15, 
    -4\&.50359962737049600000e+15, 
}
.fi
.PP
Definition at line 60 of file rint\&.c\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
