lib/real/round.c
NAME
lib/real/round.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double round (double x)
Function Documentation
double round (double x)
Definition at line 30 of file round.c.
Referenced by cround(), DecimalSystem::GetRealText(), PositionalNumeralSystem::GetText(), and RealNumber::Round().
{
    return x > 0.0 ? floor(x + 0.5) : ceil(x - 0.5);
}
Author
Generated automatically by Doxygen for amath from the source code.