RoundNode
NAME
RoundNode - A rounding function in a syntax tree.
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
RoundNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
A rounding function in a syntax tree.
Round to nearest integer. See Number for implementation.
More info on the rounding function is available at Wikipedia: http://en.wikipedia.org/wiki/Rounding
Definition at line 220 of file functions.h.
Constructor & Destructor Documentation
RoundNode::RoundNode (ExpressionNode * expression)
Definition at line 537 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                               :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * RoundNode::Create (ExpressionNode * expression) [static]
Definition at line 540 of file functions.cpp.
References RoundNode().
{
    return new RoundNode(expression);
}
Number * RoundNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 545 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Round().
{
    result = expression->Evaluate()->Round();
    return result;
}
char * RoundNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 551 of file functions.cpp.
{
    return (char*)"round";
}
Author
Generated automatically by Doxygen for amath from the source code.