.TH "RoundNode" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RoundNode \- A rounding function in a syntax tree\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRoundNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A rounding function in a syntax tree\&. 

Round to nearest integer\&. See \fBNumber\fP for implementation\&.
.PP
More info on the rounding function is available at Wikipedia: http://en.wikipedia.org/wiki/Rounding 
.PP
Definition at line 220 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RoundNode::RoundNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 537 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
537                                                :
538     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * RoundNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 540 of file functions\&.cpp\&.
.PP
References RoundNode()\&.
.PP
.nf
541 {
542     return new RoundNode(expression);
543 }
.fi
.SS "\fBNumber\fP * RoundNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 545 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Round()\&.
.PP
.nf
546 {
547     result = expression->Evaluate()->Round();
548     return result;
549 }
.fi
.SS "char * RoundNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 551 of file functions\&.cpp\&.
.PP
.nf
552 {
553     return (char*)"round";
554 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
