.TH "SaveStatement" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SaveStatement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statements\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSaveStatement\fP (const char *\fBfile\fP)"
.br
.ti -1c
.RI "\fB~SaveStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "char * \fBfile\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 282 of file statements\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SaveStatement::SaveStatement (const char * file)"

.PP
Definition at line 678 of file statements\&.cpp\&.
.PP
References AllocAndCopy(), and file\&.
.PP
Referenced by Parser::ParseFileStatement()\&.
.PP
.nf
679 {
680     AllocAndCopy(&this->file, file);
681 }
.fi
.SS "SaveStatement::~SaveStatement ()"

.PP
Definition at line 683 of file statements\&.cpp\&.
.PP
References file\&.
.PP
.nf
684 {
685     delete [] file;
686 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * SaveStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 688 of file statements\&.cpp\&.
.PP
References CharBuffer::Append(), CharBuffer::CharBuffer(), CharBuffer::Empty(), file, Program::Filesystem, Program::Functions, CharBuffer::GetString(), VariableList::ListDefinitions(), FunctionList::ListDefinitions(), FilesystemBase::SaveTextFile(), StrLen(), and Program::Variables\&.
.PP
.nf
689 {
690     const char *vars = Program->Variables->ListDefinitions();
691     const char *funcs = Program->Functions->ListDefinitions();
692 
693     if (vars == NOMEM && funcs == NOMEM) {
694         return (char*)HELPSAVENOTH;
695     }
696 
697     int len = 1;
698     len += vars  != NOMEM ? StrLen(vars)  : 0;
699     len += funcs != NOMEM ? StrLen(funcs) : 0;
700 
701     CharBuffer *text = new CharBuffer(len);
702     text->Empty();
703 
704     if (vars != NOMEM) {
705         text->Append(vars);
706     }
707     if (funcs != NOMEM) {
708         text->Append(funcs);
709     }
710 
711     bool success = Program->Filesystem->SaveTextFile(file, text->GetString());
712     delete text;
713 
714     return (char*)(success ? HELPSAVESUCC : HELPSAVEFAIL);
715 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "char* SaveStatement::file\fC [private]\fP"

.PP
Definition at line 289 of file statements\&.h\&.
.PP
Referenced by Execute(), SaveStatement(), and ~SaveStatement()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
