SaveStatement
NAME
SaveStatement -
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
SaveStatement (const char *file)
~SaveStatement ()
char * Execute ()
Private Attributes
char * file
Additional Inherited Members
Detailed Description
Definition at line 282 of file statements.h.
Constructor & Destructor Documentation
SaveStatement::SaveStatement (const char * file)
Definition at line 678 of file statements.cpp.
References AllocAndCopy(), and file.
Referenced by Parser::ParseFileStatement().
{
    AllocAndCopy(&this->file, file);
}
SaveStatement::~SaveStatement ()
Definition at line 683 of file statements.cpp.
References file.
{
    delete [] file;
}
Member Function Documentation
char * SaveStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 688 of file statements.cpp.
References CharBuffer::Append(), CharBuffer::CharBuffer(), CharBuffer::Empty(), file, Program::Filesystem, Program::Functions, CharBuffer::GetString(), VariableList::ListDefinitions(), FunctionList::ListDefinitions(), FilesystemBase::SaveTextFile(), StrLen(), and Program::Variables.
{
    const char *vars = Program->Variables->ListDefinitions();
    const char *funcs = Program->Functions->ListDefinitions();
    if (vars == NOMEM && funcs == NOMEM) {
        return (char*)HELPSAVENOTH;
    }
    int len = 1;
    len += vars != NOMEM ? StrLen(vars) : 0;
    len += funcs != NOMEM ? StrLen(funcs) : 0;
    CharBuffer *text = new CharBuffer(len);
    text->Empty();
    if (vars != NOMEM) {
        text->Append(vars);
    }
    if (funcs != NOMEM) {
        text->Append(funcs);
    }
    bool success = Program->Filesystem->SaveTextFile(file, text->GetString());
    delete text;
    return (char*)(success ? HELPSAVESUCC : HELPSAVEFAIL);
}
Member Data Documentation
char* SaveStatement::file [private]
Definition at line 289 of file statements.h.
Referenced by Execute(), SaveStatement(), and ~SaveStatement().
Author
Generated automatically by Doxygen for amath from the source code.