.TH "SecantNode" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SecantNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSecantNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 382 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SecantNode::SecantNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 820 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
820                                                  :
821     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * SecantNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 823 of file functions\&.cpp\&.
.PP
References SecantNode()\&.
.PP
.nf
824 {
825     return new SecantNode(expression);
826 }
.fi
.SS "\fBNumber\fP * SecantNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 828 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Secant()\&.
.PP
.nf
829 {
830     result = expression->Evaluate()->Secant();
831     return result;
832 }
.fi
.SS "char * SecantNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 834 of file functions\&.cpp\&.
.PP
.nf
835 {
836     return (char*)"sec";
837 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
