SecantNode
NAME
SecantNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
SecantNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 382 of file functions.h.
Constructor & Destructor Documentation
SecantNode::SecantNode (ExpressionNode * expression)
Definition at line 820 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                 :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * SecantNode::Create (ExpressionNode * expression) [static]
Definition at line 823 of file functions.cpp.
References SecantNode().
{
    return new SecantNode(expression);
}
Number * SecantNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 828 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Secant().
{
    result = expression->Evaluate()->Secant();
    return result;
}
char * SecantNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 834 of file functions.cpp.
{
    return (char*)"sec";
}
Author
Generated automatically by Doxygen for amath from the source code.