.TH "ShowStatement" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShowStatement \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <statements\&.h>\fP
.PP
Inherits \fBStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBShowStatement\fP (const char *\fBfile\fP)"
.br
.ti -1c
.RI "\fB~ShowStatement\fP ()"
.br
.ti -1c
.RI "char * \fBExecute\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "char * \fBfile\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 251 of file statements\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ShowStatement::ShowStatement (const char * file)"

.PP
Definition at line 581 of file statements\&.cpp\&.
.PP
References AllocAndCopy(), and file\&.
.PP
Referenced by Parser::ParseFileStatement()\&.
.PP
.nf
582 {
583     AllocAndCopy(&this->file, file);
584 }
.fi
.SS "ShowStatement::~ShowStatement ()"

.PP
Definition at line 586 of file statements\&.cpp\&.
.PP
References file\&.
.PP
.nf
587 {
588     delete [] file;
589 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "char * ShowStatement::Execute ()\fC [virtual]\fP"

.PP
Implements \fBStatementNode\fP\&.
.PP
Definition at line 591 of file statements\&.cpp\&.
.PP
References file, Program::Filesystem, CharBuffer::GetString(), FilesystemBase::LoadTextFile(), and SyntaxNode::output\&.
.PP
.nf
592 {
593     CharBuffer *text = Program->Filesystem->LoadTextFile(file);
594     if (text == NOMEM)
595     {
596         return (char*)(MSGNOFILE);
597     }
598 
599     delete output;
600     output = text;
601     return text->GetString();
602 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "char* ShowStatement::file\fC [private]\fP"

.PP
Definition at line 258 of file statements\&.h\&.
.PP
Referenced by Execute(), ShowStatement(), and ~ShowStatement()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
