ShowStatement
NAME
ShowStatement -
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
ShowStatement (const char *file)
~ShowStatement ()
char * Execute ()
Private Attributes
char * file
Additional Inherited Members
Detailed Description
Definition at line 251 of file statements.h.
Constructor & Destructor Documentation
ShowStatement::ShowStatement (const char * file)
Definition at line 581 of file statements.cpp.
References AllocAndCopy(), and file.
Referenced by Parser::ParseFileStatement().
{
    AllocAndCopy(&this->file, file);
}
ShowStatement::~ShowStatement ()
Definition at line 586 of file statements.cpp.
References file.
{
    delete [] file;
}
Member Function Documentation
char * ShowStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 591 of file statements.cpp.
References file, Program::Filesystem, CharBuffer::GetString(), FilesystemBase::LoadTextFile(), and SyntaxNode::output.
{
    CharBuffer *text = Program->Filesystem->LoadTextFile(file);
    if (text == NOMEM)
    {
        return (char*)(MSGNOFILE);
    }
    delete output;
    output = text;
    return text->GetString();
}
Member Data Documentation
char* ShowStatement::file [private]
Definition at line 258 of file statements.h.
Referenced by Execute(), ShowStatement(), and ~ShowStatement().
Author
Generated automatically by Doxygen for amath from the source code.