.TH "SignumNode" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignumNode \- A signum function in a syntax tree\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSignumNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A signum function in a syntax tree\&. 

Extracts the sign of a real number\&. See \fBNumber\fP for implementation\&.
.PP
More info on the signum function is available at Wikipedia: http://en.wikipedia.org/wiki/Sign_function 
.PP
Definition at line 197 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SignumNode::SignumNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 514 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
514                                                  :
515     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * SignumNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 517 of file functions\&.cpp\&.
.PP
References SignumNode()\&.
.PP
.nf
518 {
519     return new SignumNode(expression);
520 }
.fi
.SS "\fBNumber\fP * SignumNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 522 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Signum()\&.
.PP
.nf
523 {
524     result = expression->Evaluate()->Signum();
525     return result;
526 }
.fi
.SS "char * SignumNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 528 of file functions\&.cpp\&.
.PP
.nf
529 {
530     return (char*)"sgn";
531 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
