SignumNode
NAME
SignumNode - A signum function in a syntax tree.
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
SignumNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
A signum function in a syntax tree.
Extracts the sign of a real number. See Number for implementation.
More info on the signum function is available at Wikipedia: http://en.wikipedia.org/wiki/Sign_function
Definition at line 197 of file functions.h.
Constructor & Destructor Documentation
SignumNode::SignumNode (ExpressionNode * expression)
Definition at line 514 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                 :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * SignumNode::Create (ExpressionNode * expression) [static]
Definition at line 517 of file functions.cpp.
References SignumNode().
{
    return new SignumNode(expression);
}
Number * SignumNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 522 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Signum().
{
    result = expression->Evaluate()->Signum();
    return result;
}
char * SignumNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 528 of file functions.cpp.
{
    return (char*)"sgn";
}
Author
Generated automatically by Doxygen for amath from the source code.