SineNode
NAME
SineNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
SineNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 332 of file functions.h.
Constructor & Destructor Documentation
SineNode::SineNode (ExpressionNode * expression)
Definition at line 744 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                             :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * SineNode::Create (ExpressionNode * expression) [static]
Definition at line 747 of file functions.cpp.
References SineNode().
{
    return new SineNode(expression);
}
Number * SineNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 752 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Sine().
{
    result = expression->Evaluate()->Sine();
    return result;
}
char * SineNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 758 of file functions.cpp.
{
    return (char*)"sin";
}
Author
Generated automatically by Doxygen for amath from the source code.