lib/real/sinh.c
NAME
lib/real/sinh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double sinh (double x)
Hyperbolic sine function.
Variables
static const double one = 1.0
static const double shuge = 1.0e307
Function Documentation
double sinh (double x)
Hyperbolic sine function.
Version:
1.3
Date:
95/01/18
Method :
mathematically sinh(x) if defined to be (exp(x)-exp(-x))/2
 1. Replace x by |x| (sinh(-x) = -sinh(x)).
 2.
                                        E + E/(E+1)
     0 <= x <= 22 : sinh(x) := --------------, E=expm1(x)
                                2
     22 <= x <= lnovft : sinh(x) := exp(x)/2
     lnovft <= x <= ln2ovft: sinh(x) := exp(x/2)/2 * exp(x/2)
     ln2ovft < x : sinh(x) := x*shuge (overflow)
Special cases:
 sinh(x) is |x| if x is +INF, -INF, or NaN.
 only sinh(0)=0 is exact for finite x.
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 81 of file sinh.c.
References exp(), expm1(), one, and shuge.
Referenced by cchsh(), ccot(), ccoth(), ccsc(), ccsch(), csec(), csech(), ctan(), ctanh(), RealNumber::HypCosecant(), and RealNumber::HypSine().
{
    double t,w,h;
    sword ix,jx;
    uword lx;
    /* High word of |x|. */
    GET_HIGH_WORD(jx,x);
    ix = jx&0x7fffffff;
    /* x is INF or NaN */
    if(ix>=0x7ff00000) return x+x;
    h = 0.5;
    if (jx<0) h = -h;
    /* |x| in [0,22], return sign(x)*0.5*(E+E/(E+1))) */
    if (ix < 0x40360000) { /* |x|<22 */
        if (ix<0x3e300000) /* |x|<2**-28 */
            if(shuge+x>one) return x;/* sinh(tiny) = tiny with inexact */
        t = expm1(fabs(x));
        if(ix<0x3ff00000) return h*(2.0*t-t*t/(t+one));
        return h*(t+t/(t+one));
    }
    /* |x| in [22, log(maxdouble)] return 0.5*exp(|x|) */
    if (ix < 0x40862E42) return h*exp(fabs(x));
    /* |x| in [log(maxdouble), overflowthresold] */
    lx = *( (((*(uword*)&one)>>29)) + (uword*)&x);
    if (ix<0x408633CE || ((ix==0x408633ce)&&(lx<=(uword)0x8fb9f87d))) {
        w = exp(0.5*fabs(x));
        t = h*w;
        return t*w;
    }
    /* |x| > overflowthresold, sinh(x) overflow */
    return x*shuge;
}
Variable Documentation
const double one = 1.0 [static]
Definition at line 51 of file sinh.c.
Referenced by sinh().
const double shuge = 1.0e307 [static]
Definition at line 51 of file sinh.c.
Referenced by sinh().
Author
Generated automatically by Doxygen for amath from the source code.