.TH "SquareRootNode" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SquareRootNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSquareRootNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 274 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SquareRootNode::SquareRootNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 629 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
629                                                          :
630     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * SquareRootNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 632 of file functions\&.cpp\&.
.PP
References SquareRootNode()\&.
.PP
.nf
633 {
634     return new SquareRootNode(expression);
635 }
.fi
.SS "\fBNumber\fP * SquareRootNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 637 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::SquareRoot()\&.
.PP
.nf
638 {
639     result = expression->Evaluate()->SquareRoot();
640     return result;
641 }
.fi
.SS "char * SquareRootNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 643 of file functions\&.cpp\&.
.PP
.nf
644 {
645     return (char*)"sqrt";
646 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
