SquareRootNode
NAME
SquareRootNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
SquareRootNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 274 of file functions.h.
Constructor & Destructor Documentation
SquareRootNode::SquareRootNode (ExpressionNode * expression)
Definition at line 629 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                         :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * SquareRootNode::Create (ExpressionNode * expression) [static]
Definition at line 632 of file functions.cpp.
References SquareRootNode().
{
    return new SquareRootNode(expression);
}
Number * SquareRootNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 637 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::SquareRoot().
{
    result = expression->Evaluate()->SquareRoot();
    return result;
}
char * SquareRootNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 643 of file functions.cpp.
{
    return (char*)"sqrt";
}
Author
Generated automatically by Doxygen for amath from the source code.