StandardConsole
NAME
StandardConsole - Encapsulates the IO of a console using Standard C and termios.
SYNOPSIS
#include <console_stdc.h>
Inherits ConsoleBase.
Public Member Functions
StandardConsole (const char *prompt, CharValidator *validator)
virtual ~StandardConsole ()
virtual int GetStackSize ()
virtual void Run ()
virtual void Exit ()
virtual void SetPrompt (const char *string)
virtual void WriteString (const char *string)
Private Member Functions
void ReadLine ()
void Write (const char *string, unsigned int length)
Private Attributes
AnsiConoleEngine * proc
const char * line
bool exit
Additional Inherited Members
Detailed Description
Encapsulates the IO of a console using Standard C and termios.
Definition at line 45 of file console_stdc.h.
Constructor & Destructor Documentation
StandardConsole::StandardConsole (const char * prompt, CharValidator * validator)
Definition at line 34 of file console_stdc.cpp.
References AnsiConoleEngine::AnsiConoleEngine(), ConsoleBase::ConsoleBase(), and proc.
Referenced by StandardProgram::Initialize().
                                                                             :
    ConsoleBase(prompt)
{
    proc = new AnsiConoleEngine(prompt, validator);
}
StandardConsole::~StandardConsole () [virtual]
Definition at line 40 of file console_stdc.cpp.
References proc.
{
    delete proc;
}
Member Function Documentation
void StandardConsole::Exit () [virtual]
Implements ConsoleBase.
Definition at line 66 of file console_stdc.cpp.
References exit.
{
    exit = true;
}
int StandardConsole::GetStackSize () [virtual]
Implements ThreadBase.
Definition at line 45 of file console_stdc.cpp.
{
    return 100000;
}
void StandardConsole::ReadLine () [private]
Definition at line 71 of file console_stdc.cpp.
References AnsiConoleEngine::GetLine(), AnsiConoleEngine::InputDone(), line, proc, AnsiConoleEngine::ProcessChar(), AnsiConoleEngine::StartInput(), and WriteString().
Referenced by Run().
{
#ifdef UNIX
    termios new_tio, old_tio;
    tcgetattr(STDIN_FILENO, &old_tio);
    new_tio = old_tio;
    new_tio.c_lflag &=(~ICANON & ~ECHO);
    tcsetattr(STDIN_FILENO, TCSANOW, &new_tio);
#endif
    proc->StartInput();
    while (!proc->InputDone()) {
        unsigned char c = getchar();
        //printf("%d ",c);
        const char *out = proc->ProcessChar((char)c);
        WriteString(out);
    }
    line = proc->GetLine();
#ifdef UNIX
    tcsetattr(STDIN_FILENO, TCSANOW, &old_tio);
#endif
}
void StandardConsole::Run () [virtual]
Implements ThreadBase.
Definition at line 50 of file console_stdc.cpp.
References Evaluator::Evaluate(), Evaluator::Evaluator(), exit, Evaluator::GetResult(), line, ConsoleBase::Prompt(), ReadLine(), ConsoleBase::StartMessage(), StrLen(), and Write().
{
    exit = false;
    StartMessage();
    while(!exit) {
        Prompt();
        ReadLine();
        Evaluator *evaluator = new Evaluator(line);
        evaluator->Evaluate();
        const char *res = evaluator->GetResult();
        Write(res, StrLen(res));
        delete evaluator;
    }
}
void StandardConsole::SetPrompt (const char * string) [virtual]
Reimplemented from ConsoleBase.
Definition at line 113 of file console_stdc.cpp.
References proc, ConsoleBase::SetPrompt(), and AnsiConoleEngine::SetPrompt().
{
    ConsoleBase::SetPrompt(string);
    proc->SetPrompt(string);
}
void StandardConsole::Write (const char * string, unsigned int length) [private]
Definition at line 102 of file console_stdc.cpp.
Referenced by Run(), and WriteString().
{
    unsigned int i = 0;
    while(i < length && string[i] != 0) {
        fputc(string[i], stdout);
        i++;
    }
    fflush(stdout);
}
void StandardConsole::WriteString (const char * string) [virtual]
Implements ConsoleBase.
Definition at line 97 of file console_stdc.cpp.
References StrLen(), and Write().
Referenced by ReadLine().
{
    Write(string, StrLen(string));
}
Member Data Documentation
bool StandardConsole::exit [private]
Definition at line 60 of file console_stdc.h.
Referenced by Exit(), and Run().
const char* StandardConsole::line [private]
Definition at line 59 of file console_stdc.h.
Referenced by ReadLine(), and Run().
AnsiConoleEngine* StandardConsole::proc [private]
Definition at line 58 of file console_stdc.h.
Referenced by ReadLine(), SetPrompt(), StandardConsole(), and ~StandardConsole().
Author
Generated automatically by Doxygen for amath from the source code.