StandardProgram
NAME
StandardProgram -
SYNOPSIS
#include <program_stdc.h>
Inherits Program.
Public Member Functions
StandardProgram ()
virtual ~StandardProgram ()
virtual void Initialize (int argc, char **argv)
virtual void Run ()
virtual void Exit ()
Private Attributes
CharBuffer * line
Additional Inherited Members
Detailed Description
Definition at line 30 of file program_stdc.h.
Constructor & Destructor Documentation
StandardProgram::StandardProgram ()
Definition at line 37 of file program_stdc.cpp.
References Program::Console, line, and Program::Program().
Referenced by CreateProgram().
    : Program()
{
    Console = NOMEM;
    line = NOMEM;
}
StandardProgram::~StandardProgram () [virtual]
Definition at line 44 of file program_stdc.cpp.
References Program::Console, and line.
{
    if (Console != NULL) {
        delete Console;
    }
    if (line != NULL) {
        delete line;
    }
}
Member Function Documentation
void StandardProgram::Exit () [virtual]
Implements Program.
Definition at line 99 of file program_stdc.cpp.
References Program::Console, and ConsoleBase::Exit().
{
    Console->Exit();
}
void StandardProgram::Initialize (int argc, char ** argv) [virtual]
Implements Program.
Definition at line 55 of file program_stdc.cpp.
References CharBuffer::Append(), CharBuffer::CharBuffer(), Program::Console, CharBuffer::DeleteLastChar(), CharBuffer::Empty(), PreferencesBase::GetPrompt(), CharBuffer::Is(), line, Program::Preferences, StandardConsole::StandardConsole(), and StrLen().
{
    if(argc < 2) {
        // STDC version only has a console
        Console = new StandardConsole(Preferences->GetPrompt());
        return;
    }
    unsigned int len = 1;
    for(int i = 1; i < argc; i++) {
        len += StrLen(argv[i]) + 1;
    }
    line = new CharBuffer(len);
    line->Empty();
    for(int i = 1; i < argc; i++) {
        line->Append(argv[i]);
        line->Append(' ');
    }
    line->DeleteLastChar();
    if (line->Is("shell")) {
        Console = new StandardConsole(Preferences->GetPrompt());
    }
}
void StandardProgram::Run () [virtual]
Implements Program.
Definition at line 83 of file program_stdc.cpp.
References Program::Console, Evaluator::Evaluate(), Evaluator::Evaluator(), Evaluator::GetResult(), CharBuffer::GetString(), line, PreferencesBase::Load(), Program::Preferences, ThreadBase::Run(), and WriteToShell().
{
    Preferences->Load();
    if (Console != NOMEM) {
        Console->Run();
        return;
    }
    Evaluator *evaluator = new Evaluator(line->GetString());
    evaluator->Evaluate();
    const char *res = evaluator->GetResult();
    WriteToShell(res);
    delete evaluator;
}
Member Data Documentation
CharBuffer* StandardProgram::line [private]
Definition at line 39 of file program_stdc.h.
Referenced by Initialize(), Run(), StandardProgram(), and ~StandardProgram().
Author
Generated automatically by Doxygen for amath from the source code.