StandardPreferences
NAME
StandardPreferences -
SYNOPSIS
#include <preferences_stdc.h>
Inherits PreferencesBase.
Public Member Functions
virtual bool Load ()
virtual bool Keep ()
virtual bool Save ()
Private Member Functions
bool SavePrefs (const char *file)
Additional Inherited Members
Detailed Description
Definition at line 32 of file preferences_stdc.h.
Member Function Documentation
bool StandardPreferences::Keep () [virtual]
Implements PreferencesBase.
Definition at line 76 of file preferences_stdc.cpp.
References SavePrefs(), and tempname.
{
    return SavePrefs(tempname);
}
bool StandardPreferences::Load () [virtual]
Implements PreferencesBase.
Definition at line 44 of file preferences_stdc.cpp.
References CharBuffer::Append(), CharBuffer::CharBuffer(), CharBuffer::Empty(), CharBuffer::EnsureSize(), CharBuffer::GetString(), PreferencesBase::SetPrefs(), and tempname.
{
#ifdef UNIX
    FILE *file = fopen(tempname, "r");
    if (!file) {
        return false;
    }
    CharBuffer *text = new CharBuffer();
    text->Empty();
    const int bufsize = 64;
    char* buf = new char[bufsize];
    char* c;
    int s = 1;
    do {
        c = fgets(buf, bufsize, file);
        if (c != NULL) {
            text->EnsureSize(s++);
            text->Append(c);
        }
    } while (c != NULL);
    delete [] buf;
    fclose(file);
    SetPrefs(text->GetString());
    delete text;
#endif
    return true;
}
bool StandardPreferences::Save () [virtual]
Implements PreferencesBase.
Definition at line 81 of file preferences_stdc.cpp.
References permname, and SavePrefs().
{
    return SavePrefs(permname);
}
bool StandardPreferences::SavePrefs (const char * file) [private]
Definition at line 86 of file preferences_stdc.cpp.
References PreferencesBase::GetDescription().
Referenced by Keep(), and Save().
{
#ifdef UNIX
    FILE *file = fopen(name, "w");
    if (!file) {
        return false;
    }
    char *out = GetDescription();
    fputs(out, file);
    fclose(file);
#endif
    return true;
}
Author
Generated automatically by Doxygen for amath from the source code.