StandardFilesystem
NAME
StandardFilesystem -
SYNOPSIS
#include <filesystem_stdc.h>
Inherits FilesystemBase.
Public Member Functions
CharBuffer * ListDirectory (const char *path)
CharBuffer * LoadTextFile (const char *name)
bool SaveTextFile (const char *name, const char *text)
Static Private Attributes
static const int blocksize = 512
Detailed Description
Definition at line 42 of file filesystem_stdc.h.
Member Function Documentation
CharBuffer * StandardFilesystem::ListDirectory (const char * path) [virtual]
Implements FilesystemBase.
Definition at line 39 of file filesystem_stdc.cpp.
References CharBuffer::Append(), CharBuffer::CharBuffer(), CharBuffer::Empty(), CharBuffer::EnsureGrowth(), CharBuffer::EnsureSize(), CharBuffer::GetString(), StrIsEqual(), and StrLen().
{
#ifdef UNIX
    CharBuffer *pathbuf = new CharBuffer();
    pathbuf->Empty();
    if (path == NOMEM) {
        pathbuf->Append(".");
    } else {
        pathbuf->EnsureSize(StrLen(path) + 1);
        pathbuf->Append(path);
    }
    DIR *dir;
    if ((dir = opendir(pathbuf->GetString())) == NULL) {
        CharBuffer *res = new CharBuffer();
        const char *msg = MSGNODIR;
        res->EnsureSize(StrLen(msg) + StrLen(pathbuf->GetString()) + StrLen(NEWLINE) + 1);
        res->Empty();
        res->Append(msg);
        res->Append(pathbuf->GetString());
        res->Append(NEWLINE);
        delete pathbuf;
        return res;
    }
    CharBuffer *lines = new CharBuffer();
    lines->Empty();
    bool first = true;
    struct dirent *entry;
    while ((entry = readdir(dir)) != NULL) {
        if (StrIsEqual(entry->d_name, ".") || StrIsEqual(entry->d_name, "..")) {
            continue;
        }
        if (first) {
            const char *header = TXTLISTDIRHEADER;
            lines->EnsureSize(StrLen(header) + 1);
            lines->Empty();
            lines->Append(header);
            first = false;
        }
        const char *type;
        switch (entry->d_type) {
        case DT_REG:
            type = TXTLISTDIRTFILE;
            break;
        case DT_DIR:
            type = TXTLISTDIRTDIR;
            break;
        default:
            type = TXTLISTDIRTUNKNOWN;
        }
        const unsigned short colsize = 12;
        unsigned int a = StrLen(type) > colsize ? colsize : StrLen(type);
        unsigned int b = colsize - a;
        lines->EnsureGrowth(colsize + StrLen(entry->d_name) + StrLen(NEWLINE) + 1);
        lines->Append(type);
        lines->Append(' ', b);
        lines->Append(entry->d_name);
        lines->Append(NEWLINE);
    }
    closedir(dir);
    delete pathbuf;
    return lines;
#else
    CharBuffer *lines = new CharBuffer();
    lines->Empty();
    return lines;
#endif
}
CharBuffer * StandardFilesystem::LoadTextFile (const char * name) [virtual]
Implements FilesystemBase.
Definition at line 117 of file filesystem_stdc.cpp.
References CharBuffer::Append(), blocksize, CharBuffer::CharBuffer(), CharBuffer::Empty(), and CharBuffer::EnsureSize().
{
    FILE *file;
#if !defined(_WIN32)
    file = fopen(name, "r");
#else
    fopen_s(&file, name, "r");
#endif
    if (!file) {
        return NOMEM;
    }
    CharBuffer *text = new CharBuffer();
    text->Empty();
    int blocks = 0;
    bool eof = false;
    while (!eof) {
        blocks++;
        text->EnsureSize(blocksize, blocks);
        int count = 0;
        do
        {
            int c = fgetc(file);
            eof = c == EOF;
            if (!eof) {
                text->Append((char)c);
                count++;
            }
        } while (!eof && count < blocksize);
    }
    fclose(file);
    return text;
}
bool StandardFilesystem::SaveTextFile (const char * name, const char * text) [virtual]
Implements FilesystemBase.
Definition at line 158 of file filesystem_stdc.cpp.
{
    FILE *file;
#if !defined(_WIN32)
    file = fopen(name, "w");
#else
    fopen_s(&file, name, "w");
#endif
    if (!file) {
        return false;
    }
    char *i = (char*)text;
    int r = EOF + 11;
    while (r != EOF && *i) {
        r = fputc(*i++, file);
    }
    fclose(file);
    return true;
}
Member Data Documentation
const int StandardFilesystem::blocksize = 512 [static], [private]
Definition at line 49 of file filesystem_stdc.h.
Referenced by LoadTextFile().
Author
Generated automatically by Doxygen for amath from the source code.