.TH "StandardProgram" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StandardProgram \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <program_stdc\&.h>\fP
.PP
Inherits \fBProgram\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStandardProgram\fP ()"
.br
.ti -1c
.RI "virtual \fB~StandardProgram\fP ()"
.br
.ti -1c
.RI "virtual void \fBInitialize\fP (int argc, char **argv)"
.br
.ti -1c
.RI "virtual void \fBRun\fP ()"
.br
.ti -1c
.RI "virtual void \fBExit\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBCharBuffer\fP * \fBline\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 30 of file program_stdc\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StandardProgram::StandardProgram ()"

.PP
Definition at line 37 of file program_stdc\&.cpp\&.
.PP
References Program::Console, line, and Program::Program()\&.
.PP
Referenced by CreateProgram()\&.
.PP
.nf
38     : Program()
39 {
40     Console = NOMEM;
41     line = NOMEM;
42 }
.fi
.SS "StandardProgram::~StandardProgram ()\fC [virtual]\fP"

.PP
Definition at line 44 of file program_stdc\&.cpp\&.
.PP
References Program::Console, and line\&.
.PP
.nf
45 {
46     if (Console != NULL) {
47         delete Console;
48     }
49 
50     if (line != NULL) {
51         delete line;
52     }
53 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void StandardProgram::Exit ()\fC [virtual]\fP"

.PP
Implements \fBProgram\fP\&.
.PP
Definition at line 99 of file program_stdc\&.cpp\&.
.PP
References Program::Console, and ConsoleBase::Exit()\&.
.PP
.nf
100 {
101     Console->Exit();
102 }
.fi
.SS "void StandardProgram::Initialize (int argc, char ** argv)\fC [virtual]\fP"

.PP
Implements \fBProgram\fP\&.
.PP
Definition at line 55 of file program_stdc\&.cpp\&.
.PP
References CharBuffer::Append(), CharBuffer::CharBuffer(), Program::Console, CharBuffer::DeleteLastChar(), CharBuffer::Empty(), PreferencesBase::GetPrompt(), CharBuffer::Is(), line, Program::Preferences, StandardConsole::StandardConsole(), and StrLen()\&.
.PP
.nf
56 {
57     if(argc < 2) {
58         // STDC version only has a console
59         Console = new StandardConsole(Preferences->GetPrompt());
60         return;
61     }
62 
63     unsigned int len = 1;
64     for(int i = 1; i < argc; i++) {
65         len += StrLen(argv[i]) + 1;
66     }
67 
68     line = new CharBuffer(len);
69     line->Empty();
70 
71     for(int i = 1; i < argc; i++) {
72         line->Append(argv[i]);
73         line->Append(' ');
74     }
75 
76     line->DeleteLastChar();
77 
78     if (line->Is("shell")) {
79         Console = new StandardConsole(Preferences->GetPrompt());
80     }
81 }
.fi
.SS "void StandardProgram::Run ()\fC [virtual]\fP"

.PP
Implements \fBProgram\fP\&.
.PP
Definition at line 83 of file program_stdc\&.cpp\&.
.PP
References Program::Console, Evaluator::Evaluate(), Evaluator::Evaluator(), Evaluator::GetResult(), CharBuffer::GetString(), line, PreferencesBase::Load(), Program::Preferences, ThreadBase::Run(), and WriteToShell()\&.
.PP
.nf
84 {
85     Preferences->Load();
86 
87     if (Console != NOMEM) {
88         Console->Run();
89         return;
90     }
91 
92     Evaluator *evaluator = new Evaluator(line->GetString());
93     evaluator->Evaluate();
94     const char *res = evaluator->GetResult();
95     WriteToShell(res);
96     delete evaluator;
97 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBCharBuffer\fP* StandardProgram::line\fC [private]\fP"

.PP
Definition at line 39 of file program_stdc\&.h\&.
.PP
Referenced by Initialize(), Run(), StandardProgram(), and ~StandardProgram()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
