StandardLanguage
NAME
StandardLanguage -
SYNOPSIS
#include <language_stdc.h>
Inherits Language.
Public Member Functions
StandardLanguage ()
~StandardLanguage ()
char GetFractionPoint ()
bool CharIsAlNum (unsigned long character)
bool CharIsAlpha (unsigned long character)
bool CharIsDigit (unsigned long character)
bool CharIsPunct (unsigned long character)
bool CharIsSpace (unsigned long character)
bool CharIsCntrl (unsigned long character)
bool StrIsEqualLoc (const char *s1, const char *s2)
Protected Member Functions
char * Translate (textdef *def)
char * Translate (helptextdef *def)
char * Translate (identhelpdef *def)
Private Member Functions
void LoadCatalogs ()
void LoadCatalog (char **dest, const char *file)
void GetNextPair (const char **key, const char **value)
void GetNextLine ()
void SkipComments ()
Private Attributes
char * textbase
char * helpbase
char * identbase
char * kwordbase
char * ptr
textdef * textcatalog
helptextdef * helpcatalog
identhelpdef * identcatalog
Additional Inherited Members
Detailed Description
Definition at line 35 of file language_stdc.h.
Constructor & Destructor Documentation
StandardLanguage::StandardLanguage ()
Definition at line 38 of file language_stdc.cpp.
References Language::Language(), and LoadCatalogs().
Referenced by CreateLanguage().
                                   :
    Language()
{
    LoadCatalogs();
}
StandardLanguage::~StandardLanguage ()
Definition at line 44 of file language_stdc.cpp.
References helpbase, identbase, kwordbase, and textbase.
{
    if (textbase != NOMEM) {
        delete textbase;
    }
    if (helpbase != NOMEM) {
        delete helpbase;
    }
    if (identbase != NOMEM) {
        delete identbase;
    }
    if (kwordbase != NOMEM) {
        delete kwordbase;
    }
}
Member Function Documentation
bool StandardLanguage::CharIsAlNum (unsigned long character) [virtual]
Implements Language.
Definition at line 90 of file language_stdc.cpp.
{
    return (character >= 'a' && character <= 'z') ||
           (character >= 'A' && character <= 'Z') ||
           (character >= '0' && character <= '9');
}
bool StandardLanguage::CharIsAlpha (unsigned long character) [virtual]
Implements Language.
Definition at line 97 of file language_stdc.cpp.
{
    return (character >= 'a' && character <= 'z') ||
           (character >= 'A' && character <= 'Z');
}
bool StandardLanguage::CharIsCntrl (unsigned long character) [virtual]
Implements Language.
Definition at line 118 of file language_stdc.cpp.
{
    return (character < 32 || character > 125);
}
bool StandardLanguage::CharIsDigit (unsigned long character) [virtual]
Implements Language.
Definition at line 103 of file language_stdc.cpp.
{
    return (character >= '0' && character <= '9');
}
bool StandardLanguage::CharIsPunct (unsigned long character) [virtual]
Implements Language.
Definition at line 108 of file language_stdc.cpp.
{
    return (character == '.');
}
bool StandardLanguage::CharIsSpace (unsigned long character) [virtual]
Implements Language.
Definition at line 113 of file language_stdc.cpp.
{
    return (character == 32);
}
char StandardLanguage::GetFractionPoint () [virtual]
Implements Language.
Definition at line 85 of file language_stdc.cpp.
{
    return '.';
}
void StandardLanguage::GetNextLine () [private]
Definition at line 204 of file language_stdc.cpp.
References ptr.
Referenced by GetNextPair(), and SkipComments().
{
    while ((*ptr) != '\0' && (*ptr) != '\n') {
        ptr++;
    }
    if ((*ptr) == '\n') {
        *ptr++ = '\0';
    }
}
void StandardLanguage::GetNextPair (const char ** key, const char ** value) [private]
Definition at line 194 of file language_stdc.cpp.
References GetNextLine(), ptr, and SkipComments().
Referenced by LoadCatalogs().
{
    SkipComments();
    *key = ptr;
    GetNextLine();
    SkipComments();
    *value = ptr;
    GetNextLine();
}
void StandardLanguage::LoadCatalog (char ** dest, const char * file) [private]
Definition at line 178 of file language_stdc.cpp.
References AllocAndCopy(), CreateFilesystem(), CharBuffer::GetString(), FilesystemBase::LoadTextFile(), and ptr.
Referenced by LoadCatalogs().
{
    FilesystemBase *filesystem = CreateFilesystem();
    CharBuffer *cbuf = filesystem->LoadTextFile(file);
    if (cbuf != NOMEM) {
        AllocAndCopy(dest, cbuf->GetString());
        ptr = *dest;
        delete cbuf;
    } else {
        *dest = NOMEM;
    }
    delete filesystem;
}
void StandardLanguage::LoadCatalogs () [private]
Definition at line 129 of file language_stdc.cpp.
References GetNextPair(), helpbase, helpcatalog, Language::helpcount, helptexts, identhelpdef::id, helptextdef::id, keyworddef::id, textdef::id, identhelpdef::ident, identbase, identcatalog, Language::identcount, Language::keywordcount, keywords, Language::keywordsloc, kwordbase, LoadCatalog(), keyworddef::name, helptextdef::symbol, keyworddef::symbol, identhelpdef::text, helptextdef::text, textdef::text, textbase, textcatalog, and Language::textcount.
Referenced by StandardLanguage().
{
    const char* key;
    const char* value;
    LoadCatalog(&textbase, "utext/dk-text.dict");
    if (textbase != NOMEM) {
        textcatalog = new textdef[textcount];
        for (unsigned int j = 0; j < textcount; j++) {
            GetNextPair(&key, &value);
            textcatalog[j].id = j;
            textcatalog[j].text = value;
        }
    }
    LoadCatalog(&helpbase, "utext/dk-help.dict");
    if (helpbase != NOMEM) {
        helpcatalog = new helptextdef[helpcount];
        for (unsigned int j = 0; j < helpcount; j++) {
            GetNextPair(&key, &value);
            helpcatalog[j].id = j;
            helpcatalog[j].symbol = helptexts[j].symbol;
            helpcatalog[j].text = value;
        }
    }
    LoadCatalog(&identbase, "utext/dk-ident.dict");
    if (identbase != NOMEM) {
        identcatalog = new identhelpdef[identcount];
        for (unsigned int j = 0; j < identcount; j++) {
            GetNextPair(&key, &value);
            identcatalog[j].id = j;
            identcatalog[j].ident = key;
            identcatalog[j].text = value;
        }
    }
    LoadCatalog(&kwordbase, "utext/dk-keyword.dict");
    if (kwordbase != NOMEM) {
        keywordsloc = new keyworddef[keywordcount];
        for (unsigned int j = 0; j < keywordcount; j++) {
            GetNextPair(&key, &value);
            keywordsloc[j].id = j;
            keywordsloc[j].name = value;
            keywordsloc[j].symbol = keywords[j].symbol;
        }
    }
}
void StandardLanguage::SkipComments () [private]
Definition at line 215 of file language_stdc.cpp.
References GetNextLine(), and ptr.
Referenced by GetNextPair().
{
    bool skipping;
    do {
        if ((*ptr) == ';') {
            GetNextLine();
            skipping = true;
        } else if ((*ptr) == '#' && *(ptr + sizeof(char)) == '#') {
            GetNextLine();
            skipping = true;
        } else {
            skipping = false;
        }
    } while (skipping);
}
bool StandardLanguage::StrIsEqualLoc (const char * s1, const char * s2) [virtual]
Implements Language.
Definition at line 123 of file language_stdc.cpp.
References StrIsEqual().
{
    return StrIsEqual(s1, s2);
}
char * StandardLanguage::Translate (textdef * def) [protected], [virtual]
Implements Language.
Definition at line 64 of file language_stdc.cpp.
References textdef::id, textdef::text, and textcatalog.
{
    return textcatalog == NOMEM ?
           (char*)def->text :
           (char*)textcatalog[def->id].text;
}
char * StandardLanguage::Translate (helptextdef * def) [protected], [virtual]
Implements Language.
Definition at line 71 of file language_stdc.cpp.
References helpcatalog, helptextdef::id, and helptextdef::text.
{
    return helpcatalog == NOMEM ?
           (char*)def->text :
           (char*)helpcatalog[def->id].text;
}
char * StandardLanguage::Translate (identhelpdef * def) [protected], [virtual]
Implements Language.
Definition at line 78 of file language_stdc.cpp.
References identhelpdef::id, identcatalog, and identhelpdef::text.
{
    return identcatalog == NOMEM ?
           (char*)def->text :
           (char*)identcatalog[def->id].text;
}
Member Data Documentation
char* StandardLanguage::helpbase [private]
Definition at line 61 of file language_stdc.h.
Referenced by LoadCatalogs(), and ~StandardLanguage().
helptextdef* StandardLanguage::helpcatalog [private]
Definition at line 67 of file language_stdc.h.
Referenced by LoadCatalogs(), and Translate().
char* StandardLanguage::identbase [private]
Definition at line 62 of file language_stdc.h.
Referenced by LoadCatalogs(), and ~StandardLanguage().
identhelpdef* StandardLanguage::identcatalog [private]
Definition at line 68 of file language_stdc.h.
Referenced by LoadCatalogs(), and Translate().
char* StandardLanguage::kwordbase [private]
Definition at line 63 of file language_stdc.h.
Referenced by LoadCatalogs(), and ~StandardLanguage().
char* StandardLanguage::ptr [private]
Definition at line 65 of file language_stdc.h.
Referenced by GetNextLine(), GetNextPair(), LoadCatalog(), and SkipComments().
char* StandardLanguage::textbase [private]
Definition at line 60 of file language_stdc.h.
Referenced by LoadCatalogs(), and ~StandardLanguage().
textdef* StandardLanguage::textcatalog [private]
Definition at line 66 of file language_stdc.h.
Referenced by LoadCatalogs(), and Translate().
Author
Generated automatically by Doxygen for amath from the source code.