.TH "app/localize/start.h" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/localize/start.h \- Start message and version text\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBTXTTEST\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBTXTFPU\fP   \fBEMPTYSTRING\fP"
.br
.ti -1c
.RI "#define \fBTXTARCH\fP   TXTCPU \fBTXTFPU\fP \fBTXTTEST\fP"
.br
.ti -1c
.RI "#define \fBRELDATESTAMP\fP   '(10\-01\-2017)'"
.br
.ti -1c
.RI "#define \fBTXTDOSVERSION\fP   '\\0$VER: amath 1\&.61' SPACE \fBRELDATESTAMP\fP \fBSPACE\fP \fBTXTARCH\fP"
.br
.ti -1c
.RI "#define \fBTXTTITLE\fP   'amath version 1\&.6\&.1'"
.br
.ti -1c
.RI "#define \fBTXTCOPYRIGHT\fP   '(c) 2017 Carsten Sonne Larsen'"
.br
.ti -1c
.RI "#define \fBTXTSTARTMSG\fP   \fBTXTTITLE\fP \fBSPACE\fP \fBTXTCOPYRIGHT\fP"
.br
.ti -1c
.RI "#define \fBTXTVERSMSG\fP   \fBTXTTITLE\fP \fBSPACE\fP \fBRELDATESTAMP\fP \fBSPACE\fP \fBTXTARCH\fP"
.br
.ti -1c
.RI "#define \fBTXTCOMPMSG\fP   'Compiled with ' COMP_NAME \fBSPACE\fP COMP_VERS"
.br
.ti -1c
.RI "#define \fBTXTEXTCOPYRIGHT\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Start message and version text\&. 


.PP
Definition in file \fBstart\&.h\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define RELDATESTAMP   '(10\-01\-2017)'"

.PP
Definition at line 97 of file start\&.h\&.
.SS "#define TXTARCH   TXTCPU \fBTXTFPU\fP \fBTXTTEST\fP"

.PP
Definition at line 96 of file start\&.h\&.
.SS "#define TXTCOMPMSG   'Compiled with ' COMP_NAME \fBSPACE\fP COMP_VERS"

.PP
Definition at line 104 of file start\&.h\&.
.SS "#define TXTCOPYRIGHT   '(c) 2017 Carsten Sonne Larsen'"

.PP
Definition at line 100 of file start\&.h\&.
.SS "#define TXTDOSVERSION   '\\0$VER: amath 1\&.61' SPACE \fBRELDATESTAMP\fP \fBSPACE\fP \fBTXTARCH\fP"

.PP
Definition at line 98 of file start\&.h\&.
.SS "#define TXTEXTCOPYRIGHT"
\fBValue:\fP
.PP
.nf
"This software contains copyrighted material by:" NEWLINE \
    "The Regents of the University of California" NEWLINE \
    "The NetBSD Foundation, Inc\&." NEWLINE \
    "Sun Microsystems, Inc\&." NEWLINE "Ryan Juckett" NEWLINE NEWLINE \
    "Portions of the code have been contributed by:" NEWLINE \
    "Stephen L\&. Moshier" NEWLINE "Stefan Haubenthal" NEWLINE \
    "Ryan Juckett" NEWLINE "Chris Torek" NEWLINE "Mike Hibler"
.fi
.PP
Definition at line 106 of file start\&.h\&.
.SS "#define TXTFPU   \fBEMPTYSTRING\fP"

.PP
Definition at line 93 of file start\&.h\&.
.SS "#define TXTSTARTMSG   \fBTXTTITLE\fP \fBSPACE\fP \fBTXTCOPYRIGHT\fP"

.PP
Definition at line 101 of file start\&.h\&.
.SS "#define TXTTEST   \fBEMPTYSTRING\fP"

.PP
Definition at line 87 of file start\&.h\&.
.SS "#define TXTTITLE   'amath version 1\&.6\&.1'"

.PP
Definition at line 99 of file start\&.h\&.
.SS "#define TXTVERSMSG   \fBTXTTITLE\fP \fBSPACE\fP \fBRELDATESTAMP\fP \fBSPACE\fP \fBTXTARCH\fP"

.PP
Definition at line 103 of file start\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
