.TH "app/main/statements.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/statements.h \- General statement nodes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'main/nodes\&.h'\fP
.br
\fC#include 'main/token\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClearStatement\fP"
.br
.RI "\fIClear the console window\&. \fP"
.ti -1c
.RI "class \fBExitStatement\fP"
.br
.RI "\fIExit program\&. \fP"
.ti -1c
.RI "class \fBEmptyStatement\fP"
.br
.RI "\fIAn empty statement\&. \fP"
.ti -1c
.RI "class \fBVersionStatement\fP"
.br
.RI "\fIShow version string\&. \fP"
.ti -1c
.RI "class \fBMemoryStatement\fP"
.br
.RI "\fIShow memory usage\&. \fP"
.ti -1c
.RI "class \fBPromptStatement\fP"
.br
.RI "\fISet prompt string\&. \fP"
.ti -1c
.RI "class \fBPrefsStatement\fP"
.br
.RI "\fILoad or save preferences\&. \fP"
.ti -1c
.RI "class \fBSilentStatement\fP"
.br
.RI "\fIMutes the output of another statement\&. \fP"
.ti -1c
.RI "class \fBEvalStatement\fP"
.br
.RI "\fIEvaluate arithmetic expression\&. \fP"
.ti -1c
.RI "class \fBHelpStatement\fP"
.br
.RI "\fILogic related to the help statement\&. \fP"
.ti -1c
.RI "class \fBDeleteStatement\fP"
.br
.RI "\fIDelete variable or function\&. \fP"
.ti -1c
.RI "class \fBInputStatement\fP"
.br
.RI "\fIChange numeral input system\&. \fP"
.ti -1c
.RI "class \fBOutputStatement\fP"
.br
.RI "\fIChange numeral output system\&. \fP"
.ti -1c
.RI "class \fBDigitsStatement\fP"
.br
.RI "\fISet number of significant digits to show\&. \fP"
.ti -1c
.RI "class \fBShowStatement\fP"
.br
.ti -1c
.RI "class \fBListStatement\fP"
.br
.ti -1c
.RI "class \fBLoadStatement\fP"
.br
.ti -1c
.RI "class \fBSaveStatement\fP"
.br
.ti -1c
.RI "class \fBExecuteStatement\fP"
.br
.ti -1c
.RI "class \fBPlotStatement\fP"
.br
.ti -1c
.RI "class \fBDrawStatement\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
General statement nodes\&. 

This file contains classes implementing statements in a syntax tree\&. All statements inherit from the \fBStatementNode\fP base class\&. 
.PP
Definition in file \fBstatements\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
