StatementNode
NAME
StatementNode - Base class for all statements in a syntax tree.
SYNOPSIS
#include <nodes.h>
Inherits SyntaxNode.
Inherited by ClearStatement [virtual], DeleteStatement [virtual], DigitsStatement [virtual], DrawStatement [virtual], EmptyStatement [virtual], EvalStatement [virtual], ExecuteStatement [virtual], ExitStatement [virtual], FunctionDefinitionNode, HelpStatement [virtual], InputStatement [virtual], ListFunctionsStatement, ListStatement [virtual], ListVariablesStatement [virtual], LoadStatement [virtual], MemoryStatement [virtual], OutputStatement [virtual], PlotStatement [virtual], PrefsStatement [virtual], PromptStatement [virtual], SaveStatement [virtual], ShowStatement [virtual], SilentStatement [virtual], and VersionStatement [virtual].
Public Member Functions
StatementNode ()
virtual ~StatementNode ()
NodeType GetNodeType ()
virtual SyntaxNode * GetNext ()
virtual char * GetTextCode ()
virtual char * Execute ()=0
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Additional Inherited Members
Detailed Description
Base class for all statements in a syntax tree.
Definition at line 111 of file nodes.h.
Constructor & Destructor Documentation
StatementNode::StatementNode ()
Definition at line 85 of file nodes.cpp.
References SyntaxNode::SyntaxNode().
Referenced by DeleteStatement::DeleteStatement(), EvalStatement::EvalStatement(), FunctionDefinitionNode::FunctionDefinitionNode(), HelpStatement::HelpStatement(), InputStatement::InputStatement(), ListFunctionsStatement::ListFunctionsStatement(), ListStatement::ListStatement(), ListVariablesStatement::ListVariablesStatement(), OutputStatement::OutputStatement(), and PlotStatement::PlotStatement().
                             :
    SyntaxNode() { }
virtual StatementNode::~StatementNode () [inline], [virtual]
Definition at line 114 of file nodes.h.
{ }
Member Function Documentation
void StatementNode::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Reimplemented in EvalStatement, and SilentStatement.
Definition at line 103 of file nodes.cpp.
{ }
void StatementNode::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Reimplemented in EvalStatement, and SilentStatement.
Definition at line 106 of file nodes.cpp.
{ }
virtual char* StatementNode::Execute () [pure virtual]
Implements SyntaxNode.
Implemented in DrawStatement, PlotStatement, ExecuteStatement, SaveStatement, LoadStatement, ListStatement, ShowStatement, DigitsStatement, OutputStatement, InputStatement, DeleteStatement, HelpStatement, EvalStatement, FunctionDefinitionNode, SilentStatement, ListFunctionsStatement, PrefsStatement, PromptStatement, MemoryStatement, ListVariablesStatement, VersionStatement, EmptyStatement, ExitStatement, and ClearStatement.
Referenced by SilentStatement::Execute().
SyntaxNode * StatementNode::GetNext () [virtual]
Implements SyntaxNode.
Reimplemented in EvalStatement, and SilentStatement.
Definition at line 98 of file nodes.cpp.
{
    return NOMEM;
}
NodeType StatementNode::GetNodeType () [virtual]
Implements SyntaxNode.
Definition at line 88 of file nodes.cpp.
References statement.
{
    return statement;
}
char * StatementNode::GetTextCode () [virtual]
Implements SyntaxNode.
Definition at line 93 of file nodes.cpp.
{
    return (char*)"STA";
}
void StatementNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Reimplemented in EvalStatement, and SilentStatement.
Definition at line 109 of file nodes.cpp.
{ }
Author
Generated automatically by Doxygen for amath from the source code.