.TH "StatementBlockElement" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatementBlockElement \- Used to create a linked list of statements\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <nodes\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSyntaxNode\fP * \fBstatement\fP"
.br
.ti -1c
.RI "\fBStatementBlockElement\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used to create a linked list of statements\&. 
.PP
Definition at line 178 of file nodes\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStatementBlockElement\fP* StatementBlockElement::next"

.PP
Definition at line 180 of file nodes\&.h\&.
.PP
Referenced by StatementBlockNode::Add(), StatementBlockNode::Execute(), and StatementBlockNode::~StatementBlockNode()\&.
.SS "\fBSyntaxNode\fP* StatementBlockElement::statement"

.PP
Definition at line 179 of file nodes\&.h\&.
.PP
Referenced by StatementBlockNode::Add(), StatementBlockNode::Execute(), and StatementBlockNode::~StatementBlockNode()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
