.TH "app/main/statements.cpp" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/statements.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mem\&.h'\fP
.br
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/real\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br
\fC#include 'localize/help\&.h'\fP
.br
\fC#include 'localize/text\&.h'\fP
.br
\fC#include 'localize/start\&.h'\fP
.br
\fC#include 'main/parser\&.h'\fP
.br
\fC#include 'main/graphlist\&.h'\fP
.br
\fC#include 'main/statements\&.h'\fP
.br
\fC#include 'system/console\&.h'\fP
.br
\fC#include 'system/program\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
