StatementBlockNode
NAME
StatementBlockNode - A sequence of statements in a syntax tree.
SYNOPSIS
#include <nodes.h>
Inherits SyntaxNode.
Public Member Functions
StatementBlockNode ()
~StatementBlockNode ()
NodeType GetNodeType ()
SyntaxNode * GetNext ()
void Add (SyntaxNode *node)
char * GetTextCode ()
char * Execute ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Private Attributes
StatementBlockElement * first
Additional Inherited Members
Detailed Description
A sequence of statements in a syntax tree.
Definition at line 156 of file nodes.h.
Constructor & Destructor Documentation
StatementBlockNode::StatementBlockNode ()
Definition at line 236 of file nodes.cpp.
References first, SyntaxNode::iterator, and SyntaxNode::SyntaxNode().
Referenced by Parser::Parse().
                                       :
    SyntaxNode() {
    first = NOMEM;
    iterator = NOMEM;
}
StatementBlockNode::~StatementBlockNode ()
Definition at line 242 of file nodes.cpp.
References first, StatementBlockElement::next, and StatementBlockElement::statement.
{
    StatementBlockElement *e = first;
    while (e != NOMEM) {
        StatementBlockElement *next = e->next;
        delete e->statement;
        delete e;
        e = next;
    }
}
Member Function Documentation
void StatementBlockNode::Add (SyntaxNode * node)
Definition at line 259 of file nodes.cpp.
References first, StatementBlockElement::next, and StatementBlockElement::statement.
Referenced by Parser::Parse().
{
    if (first == NOMEM) {
        first = new StatementBlockElement();
        first->statement = node;
        first->next = NOMEM;
        return;
    }
    StatementBlockElement *last = first;
    StatementBlockElement *current = first->next;
    while (current != NOMEM) {
        current = current->next;
        last = last->next;
    }
    current = new StatementBlockElement();
    current->statement = node;
    current->next = NOMEM;
    last->next = current;
}
void StatementBlockNode::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 308 of file nodes.cpp.
{ }
void StatementBlockNode::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 311 of file nodes.cpp.
{
    // TODO: IMPLEMENT
}
char * StatementBlockNode::Execute () [virtual]
Implements SyntaxNode.
Definition at line 287 of file nodes.cpp.
References CharBuffer::Append(), CharBuffer::ClearBuffer(), CharBuffer::Empty(), CharBuffer::EnsureGrowth(), SyntaxNode::Execute(), first, CharBuffer::GetString(), StatementBlockElement::next, SyntaxNode::output, StatementBlockElement::statement, and StrLen().
{
    output->ClearBuffer();
    output->Empty();
    StatementBlockElement *e = first;
    while (e != NOMEM) {
        const char *out = e->statement->Execute();
        output->EnsureGrowth(StrLen(out) + 1);
        output->Append(out);
        e = e->next;
    }
    return output->GetString();
}
SyntaxNode * StatementBlockNode::GetNext () [virtual]
Implements SyntaxNode.
Definition at line 303 of file nodes.cpp.
{
    return NOMEM; // TODO: Implement
}
NodeType StatementBlockNode::GetNodeType () [virtual]
Implements SyntaxNode.
Definition at line 254 of file nodes.cpp.
References statement.
{
    return statement;
}
char * StatementBlockNode::GetTextCode () [virtual]
Implements SyntaxNode.
Definition at line 282 of file nodes.cpp.
{
    return (char*)"SBLCK";
}
void StatementBlockNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Definition at line 316 of file nodes.cpp.
{
    // TODO: IMPLEMENT
}
Member Data Documentation
StatementBlockElement* StatementBlockNode::first [private]
Definition at line 171 of file nodes.h.
Referenced by Add(), Execute(), StatementBlockNode(), and ~StatementBlockNode().
Author
Generated automatically by Doxygen for amath from the source code.