lib/clib/strcmp.c
NAME
lib/clib/strcmp.c -
SYNOPSIS
#include 'clib.h'
Functions
bool StrIsEqual (const char *s1, const char *s2)
Compare two null terminated strings to each other.
Function Documentation
bool StrIsEqual (const char * s1, const char * s2)
Compare two null terminated strings to each other.
Definition at line 49 of file strcmp.c.
Referenced by VariableList::CreateVariable(), FunctionList::Delete(), Language::FindAlias(), FunctionList::GetFunctionCall(), FunctionList::GetFunctionDef(), Language::GetHelpText(), FunctionList::GetSystemFunction(), VariableList::GetVariable(), CharBuffer::Is(), StandardFilesystem::ListDirectory(), CharBuffer::RemoveTrailing(), StandardLanguage::StrIsEqualLoc(), and PosixLanguage::StrIsEqualLoc().
{
    int r;
    while (*s1 == *s2++)
        if (*s1++ == '\0')
            return true;
    r = (*(const unsigned char *)s1 - *(const unsigned char *)(s2 - 1));
    return r == 0;
}
Author
Generated automatically by Doxygen for amath from the source code.