.TH "lib/clib/strlen.c" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/clib/strlen.c \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBStrLen\fP (const char *string)"
.br
.RI "\fIGet the length of a null terminated string\&. \fP"
.in -1c
.SH "Function Documentation"
.PP 
.SS "int StrLen (const char * string)"

.PP
Get the length of a null terminated string\&. 
.PP
Definition at line 31 of file strlen\&.c\&.
.PP
Referenced by ErrorNode::ErrorNode(), VersionStatement::Execute(), MemoryStatement::Execute(), ErrorNode::Execute(), EvalStatement::Execute(), StatementBlockNode::Execute(), DeleteStatement::Execute(), InputStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), SaveStatement::Execute(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetName(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), NumericOperator::GetText(), StandardProgram::Initialize(), VariableList::ListContent(), FunctionList::ListContent(), StandardFilesystem::ListDirectory(), CharBuffer::RemoveTrailing(), StandardConsole::Run(), AnsiConoleEngine::ShowLast(), AnsiConoleEngine::ShowNext(), Language::UntagText(), and StandardConsole::WriteString()\&.
.PP
.nf
32 {
33     char *i = (char*)string;
34     char *s = i;
35     while (*i)
36         i++;
37     return i - s;
38 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
