lib/clib/strlen.c
NAME
lib/clib/strlen.c -
SYNOPSIS
Functions
int StrLen (const char *string)
Get the length of a null terminated string.
Function Documentation
int StrLen (const char * string)
Get the length of a null terminated string.
Definition at line 31 of file strlen.c.
Referenced by ErrorNode::ErrorNode(), VersionStatement::Execute(), MemoryStatement::Execute(), ErrorNode::Execute(), EvalStatement::Execute(), StatementBlockNode::Execute(), DeleteStatement::Execute(), InputStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), SaveStatement::Execute(), PreferencesBase::GetDescription(), PositionalNumeralSystem::GetName(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), NumericOperator::GetText(), StandardProgram::Initialize(), VariableList::ListContent(), FunctionList::ListContent(), StandardFilesystem::ListDirectory(), CharBuffer::RemoveTrailing(), StandardConsole::Run(), AnsiConoleEngine::ShowLast(), AnsiConoleEngine::ShowNext(), Language::UntagText(), and StandardConsole::WriteString().
{
    char *i = (char*)string;
    char *s = i;
    while (*i)
        i++;
    return i - s;
}
Author
Generated automatically by Doxygen for amath from the source code.