.TH "SubtractionNode" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SubtractionNode \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <operators\&.h>\fP
.PP
Inherits \fBNumericOperator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSubtractionNode\fP (\fBExpressionNode\fP *\fBleft\fP, \fBExpressionNode\fP *\fBright\fP)"
.br
.ti -1c
.RI "\fBReductionType\fP \fBGetReductionType\fP ()"
.br
.ti -1c
.RI "int \fBGetPrecedence\fP ()"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 107 of file operators\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SubtractionNode::SubtractionNode (\fBExpressionNode\fP * left, \fBExpressionNode\fP * right)"

.PP
Definition at line 329 of file operators\&.cpp\&.
.PP
References NumericOperator::NumericOperator()\&.
.PP
Referenced by Parser::ParseAddSubstract()\&.
.PP
.nf
329                                                                             :
330     NumericOperator(left, right) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBNumber\fP * SubtractionNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 342 of file operators\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), NumericOperator::left, ExpressionNode::result, NumericOperator::right, and Number::Sub()\&.
.PP
.nf
343 {
344     result = left->Evaluate()->Sub(right->Evaluate());
345     return result;
346 }
.fi
.SS "char * SubtractionNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 348 of file operators\&.cpp\&.
.PP
.nf
349 {
350     return (char*)"-";
351 }
.fi
.SS "int SubtractionNode::GetPrecedence ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 337 of file operators\&.cpp\&.
.PP
.nf
338 {
339     return 2;
340 }
.fi
.SS "\fBReductionType\fP SubtractionNode::GetReductionType ()\fC [virtual]\fP"

.PP
Reimplemented from \fBSyntaxNode\fP\&.
.PP
Definition at line 332 of file operators\&.cpp\&.
.PP
References complsubreduc\&.
.PP
.nf
333 {
334     return complsubreduc;
335 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
