SubtractionNode
NAME
SubtractionNode -
SYNOPSIS
#include <operators.h>
Inherits NumericOperator.
Public Member Functions
SubtractionNode (ExpressionNode *left, ExpressionNode *right)
ReductionType GetReductionType ()
int GetPrecedence ()
Number * Evaluate ()
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 107 of file operators.h.
Constructor & Destructor Documentation
SubtractionNode::SubtractionNode (ExpressionNode * left, ExpressionNode * right)
Definition at line 329 of file operators.cpp.
References NumericOperator::NumericOperator().
Referenced by Parser::ParseAddSubstract().
                                                                            :
    NumericOperator(left, right) { }
Member Function Documentation
Number * SubtractionNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 342 of file operators.cpp.
References ExpressionNode::Evaluate(), NumericOperator::left, ExpressionNode::result, NumericOperator::right, and Number::Sub().
{
    result = left->Evaluate()->Sub(right->Evaluate());
    return result;
}
char * SubtractionNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 348 of file operators.cpp.
{
    return (char*)"-";
}
int SubtractionNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 337 of file operators.cpp.
{
    return 2;
}
ReductionType SubtractionNode::GetReductionType () [virtual]
Reimplemented from SyntaxNode.
Definition at line 332 of file operators.cpp.
References complsubreduc.
{
    return complsubreduc;
}
Author
Generated automatically by Doxygen for amath from the source code.