SyntaxNode
NAME
SyntaxNode - Base class for all nodes in a syntax tree.
SYNOPSIS
#include <nodes.h>
Inherited by ErrorNode [virtual], ExpressionNode, StatementBlockNode [virtual], and StatementNode.
Public Member Functions
SyntaxNode ()
virtual ~SyntaxNode ()
void SetFirstNode ()
bool GetFirstNode ()
SyntaxNode * GetParent ()
void SetParent (SyntaxNode *node)
virtual NodeType GetNodeType ()=0
virtual ReductionType GetReductionType ()
virtual void ResetIterator ()
virtual SyntaxNode * GetNext ()=0
virtual char * GetTextCode ()=0
virtual char * Execute ()=0
virtual void Attach (SyntaxNode *node)=0
virtual void Detach (SyntaxNode *node)=0
virtual void Replace (SyntaxNode *n, SyntaxNode *x)=0
Protected Attributes
CharBuffer * output
SyntaxNode * parent
SyntaxNode * iterator
bool leftBottom
Detailed Description
Base class for all nodes in a syntax tree.
More info is available at Wikipedia: http://en.wikipedia.org/wiki/Abstract_syntax_tree
Definition at line 55 of file nodes.h.
Constructor & Destructor Documentation
SyntaxNode::SyntaxNode ()
Definition at line 38 of file nodes.cpp.
References CharBuffer::CharBuffer(), iterator, leftBottom, output, and parent.
Referenced by ErrorNode::ErrorNode(), ExpressionNode::ExpressionNode(), StatementBlockNode::StatementBlockNode(), and StatementNode::StatementNode().
{
    output = new CharBuffer();
    parent = NOMEM;
    iterator = NOMEM;
    leftBottom = false;
}
SyntaxNode::~SyntaxNode () [virtual]
Definition at line 46 of file nodes.cpp.
References output.
{
    delete output;
}
Member Function Documentation
virtual void SyntaxNode::Attach (SyntaxNode * node) [pure virtual]
Implemented in StatementBlockNode, UserFunctionNode, EvalStatement, NumericValueNode, SilentStatement, ErrorNode, StatementNode, VariableNode, NumericOperator, AbsoluteNode, FunctionNode, and UnaryNode.
Referenced by Optimizer::BalanceTree().
virtual void SyntaxNode::Detach (SyntaxNode * node) [pure virtual]
Implemented in StatementBlockNode, UserFunctionNode, EvalStatement, NumericValueNode, SilentStatement, ErrorNode, StatementNode, VariableNode, NumericOperator, AbsoluteNode, FunctionNode, and UnaryNode.
Referenced by Optimizer::BalanceTree(), and Optimizer::ReduceUnaryNodes().
virtual char* SyntaxNode::Execute () [pure virtual]
Implemented in DrawStatement, PlotStatement, ExecuteStatement, SaveStatement, LoadStatement, ListStatement, ShowStatement, DigitsStatement, OutputStatement, InputStatement, DeleteStatement, HelpStatement, StatementBlockNode, EvalStatement, FunctionDefinitionNode, SilentStatement, ListFunctionsStatement, ErrorNode, PrefsStatement, StatementNode, PromptStatement, ExpressionNode, MemoryStatement, ListVariablesStatement, VersionStatement, EmptyStatement, ExitStatement, and ClearStatement.
Referenced by Evaluator::Evaluate(), StatementBlockNode::Execute(), LoadStatement::Execute(), ExecuteStatement::Execute(), and PreferencesBase::SetPrefs().
bool SyntaxNode::GetFirstNode ()
Definition at line 56 of file nodes.cpp.
References leftBottom.
{
    return leftBottom;
}
virtual SyntaxNode* SyntaxNode::GetNext () [pure virtual]
Implemented in UserFunctionNode, StatementBlockNode, EvalStatement, NumericValueNode, SilentStatement, ErrorNode, StatementNode, VariableNode, NumericOperator, AbsoluteNode, FunctionNode, and UnaryNode.
Referenced by Optimizer::BalanceTree(), Optimizer::GetTreeDepth(), Optimizer::ReduceUnaryNodes(), Optimizer::ReduceValueNodes(), Optimizer::TagChildren(), and Optimizer::TagStartNode().
virtual NodeType SyntaxNode::GetNodeType () [pure virtual]
Implemented in StatementBlockNode, ErrorNode, StatementNode, and ExpressionNode.
Referenced by Optimizer::BalanceTree(), and Optimizer::ReduceValueNodes().
SyntaxNode * SyntaxNode::GetParent ()
Definition at line 66 of file nodes.cpp.
References parent.
Referenced by Optimizer::BalanceTree(), Optimizer::ReduceUnaryNodes(), and Optimizer::ReduceValueNodes().
{
    return parent;
}
ReductionType SyntaxNode::GetReductionType () [virtual]
Reimplemented in ComplexiNode, PiNode, EulersNumberNode, NumericValueNode, SubtractionNode, AdditionNode, and UnaryNode.
Definition at line 51 of file nodes.cpp.
References nonereduc.
Referenced by Optimizer::ReduceUnaryNodes(), and Optimizer::ReduceValueNodes().
{
    return nonereduc;
}
virtual char* SyntaxNode::GetTextCode () [pure virtual]
Implemented in StatementBlockNode, ErrorNode, StatementNode, and ExpressionNode.
virtual void SyntaxNode::Replace (SyntaxNode * n, SyntaxNode * x) [pure virtual]
Implemented in StatementBlockNode, UserFunctionNode, EvalStatement, NumericValueNode, SilentStatement, ErrorNode, StatementNode, VariableNode, NumericOperator, AbsoluteNode, FunctionNode, and UnaryNode.
Referenced by Optimizer::ReduceUnaryNodes(), and Optimizer::ReduceValueNodes().
void SyntaxNode::ResetIterator () [virtual]
Definition at line 76 of file nodes.cpp.
References iterator.
Referenced by Optimizer::BalanceTree(), Optimizer::GetTreeDepth(), Optimizer::ReduceUnaryNodes(), Optimizer::ReduceValueNodes(), Optimizer::TagChildren(), and Optimizer::TagStartNode().
{
    iterator = NOMEM;
}
void SyntaxNode::SetFirstNode ()
Definition at line 61 of file nodes.cpp.
References leftBottom.
Referenced by Optimizer::TagStartNode().
{
    leftBottom = true;
}
void SyntaxNode::SetParent (SyntaxNode * node)
Definition at line 71 of file nodes.cpp.
References parent.
Referenced by UnaryNode::Attach(), FunctionNode::Attach(), AbsoluteNode::Attach(), NumericOperator::Attach(), SilentStatement::Attach(), EvalStatement::Attach(), and Optimizer::TagChildren().
{
    parent = node;
}
Member Data Documentation
SyntaxNode* SyntaxNode::iterator [protected]
Definition at line 76 of file nodes.h.
Referenced by UnaryNode::GetNext(), FunctionNode::GetNext(), AbsoluteNode::GetNext(), NumericOperator::GetNext(), SilentStatement::GetNext(), EvalStatement::GetNext(), UserFunctionNode::GetNext(), NumericOperator::Replace(), ResetIterator(), StatementBlockNode::StatementBlockNode(), and SyntaxNode().
bool SyntaxNode::leftBottom [protected]
Definition at line 77 of file nodes.h.
Referenced by GetFirstNode(), NumericValueNode::GetPrecedence(), SetFirstNode(), and SyntaxNode().
CharBuffer* SyntaxNode::output [protected]
Definition at line 74 of file nodes.h.
Referenced by VersionStatement::Execute(), MemoryStatement::Execute(), ErrorNode::Execute(), FunctionDefinitionNode::Execute(), EvalStatement::Execute(), StatementBlockNode::Execute(), HelpStatement::Execute(), DeleteStatement::Execute(), InputStatement::Execute(), OutputStatement::Execute(), DigitsStatement::Execute(), ShowStatement::Execute(), ListStatement::Execute(), ExecuteStatement::Execute(), PlotStatement::Execute(), FunctionDefinitionNode::FunctionDefinitionNode(), NumericValueNode::GetNodeText(), UnaryNode::GetText(), FunctionNode::GetText(), AbsoluteNode::GetText(), NumericOperator::GetText(), FunctionDefinitionNode::GetText(), SyntaxNode(), and ~SyntaxNode().
SyntaxNode* SyntaxNode::parent [protected]
Definition at line 75 of file nodes.h.
Referenced by GetParent(), SetParent(), and SyntaxNode().
Author
Generated automatically by Doxygen for amath from the source code.