.TH "app/localize/tags.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/localize/tags.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'localize/start\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "static const \fBtexttag\fP \fBtexttags\fP []"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const \fBtexttag\fP texttags[]\fC [static]\fP"
\fBInitial value:\fP
.PP
.nf
= {
    { "#HEADLINE#", HEADLINE },
    { "#SYNTAXHIGHLIGHT#", SYNTAXHIGHLIGHT },
    { "#NORMALTEXT#", NORMALTEXT },
    { "#BOLD#", BOLD},
    { "#ITALICS#", ITALICS},
    { "#UNDERLINE#", UNDERLINE},
    { "#COLOR01#", COLOR01},
    { "#COLOR02#", COLOR02},
    { "#COLOR03#", COLOR03},
    { "#SPACE#", SPACE},
    { "#NEWLINE#", NEWLINE},
    { "#STARTMSG#", TXTSTARTMSG}
}
.fi
.PP
Definition at line 33 of file tags\&.h\&.
.PP
Referenced by Language::UntagText()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
