lib/real/tan.c
NAME
lib/real/tan.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double tan (double x)
Trigonometric tangent function.
Function Documentation
double tan (double x)
Trigonometric tangent function.
Version:
1.3
Date:
95/01/18
Return tangent function of x.
kernel function:
 __kernel_tan ... tangent function on [-pi/4,pi/4]
 __rem_pio2 ... argument reduction routine
Method.
     Let S,C and T denote the sin, cos and tan respectively on
 [-PI/4, +PI/4]. Reduce the argument x to y1+y2 = x-k*pi/2
 in [-pi/4 , +pi/4], and let n = k mod 4.
 We have
         n sin(x) cos(x) tan(x)
    ----------------------------------------------------------
     0 S C T
     1 C -S -1/T
     2 -S -C T
     3 -C S -1/T
    ----------------------------------------------------------
Special cases:
     Let trig be any of sin, cos, or tan.
     trig(+-INF) is NaN, with signals;
     trig(NaN) is that NaN;
Accuracy:
 TRIG(x) returns trig(x) nearly rounded
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 86 of file tan.c.
References __kernel_tan(), and rempio2().
Referenced by RealNumber::Cotangent(), and RealNumber::Tangent().
{
    double y[2],z=0.0;
    sword n, ix;
    /* High word of x. */
    GET_HIGH_WORD(ix,x);
    /* |x| ~< pi/4 */
    ix &= 0x7fffffff;
    if(ix <= 0x3fe921fb) return __kernel_tan(x,z,1);
    /* tan(Inf or NaN) is NaN */
    else if (ix>=0x7ff00000) return x-x; /* NaN */
    /* argument reduction needed */
    else {
        n = rempio2(x,y);
        return __kernel_tan(y[0],y[1],1-((n&1)<<1)); /* 1 -- n even
                            -1 -- n odd */
    }
}
Author
Generated automatically by Doxygen for amath from the source code.