TangentNode
NAME
TangentNode -
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
TangentNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
Definition at line 352 of file functions.h.
Constructor & Destructor Documentation
TangentNode::TangentNode (ExpressionNode * expression)
Definition at line 782 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                                   :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * TangentNode::Create (ExpressionNode * expression) [static]
Definition at line 785 of file functions.cpp.
References TangentNode().
{
    return new TangentNode(expression);
}
Number * TangentNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 790 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Tangent().
{
    result = expression->Evaluate()->Tangent();
    return result;
}
char * TangentNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 796 of file functions.cpp.
{
    return (char*)"tan";
}
Author
Generated automatically by Doxygen for amath from the source code.