lib/real/tanh.c
NAME
lib/real/tanh.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double tanh (double x)
Hyperbolic tangent function.
Variables
static const double one =1.0
static const double two =2.0
static const double tiny = 1.0e-300
Function Documentation
double tanh (double x)
Hyperbolic tangent function.
Version:
1.3
Date:
95/01/18
Return the Hyperbolic Tangent of x
Method :
                   x -x
                  e - e
 0. tanh(x) is defined to be -----------
                   x -x
                  e + e
 1. reduce x to non-negative by tanh(-x) = -tanh(x).
 2. 0 <= x <= 2**-55 : tanh(x) := x*(one+x)
                        -t
     2**-55 < x <= 1 : tanh(x) := -----; t = expm1(-2x)
                       t + 2
                         2
     1 <= x <= 22.0 : tanh(x) := 1- ----- ; t=expm1(2x)
                       t + 2
     22.0 < x <= INF : tanh(x) := 1.
Special cases:
 tanh(NaN) is NaN;
 only tanh(0)=0 is exact for finite argument.
Copyright:
Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved. Developed at SunSoft, a Sun Microsystems, Inc. business. Permission to use, copy, modify, and distribute this software is freely granted, provided that this notice is preserved.
Definition at line 83 of file tanh.c.
References expm1(), one, tiny, and two.
Referenced by RealNumber::HypCotangent(), and RealNumber::HypTangent().
{
    double t,z;
    sword jx,ix;
    /* High word of |x|. */
    GET_HIGH_WORD(jx,x);
    ix = jx&0x7fffffff;
    /* x is INF or NaN */
    if(ix>=0x7ff00000) {
        if (jx>=0) return one/x+one; /* tanh(+-inf)=+-1 */
        else return one/x-one; /* tanh(NaN) = NaN */
    }
    /* |x| < 22 */
    if (ix < 0x40360000) { /* |x|<22 */
        if (ix<0x3c800000) /* |x|<2**-55 */
            return x*(one+x); /* tanh(small) = small */
        if (ix>=0x3ff00000) { /* |x|>=1 */
            t = expm1(two*fabs(x));
            z = one - two/(t+two);
        } else {
            t = expm1(-two*fabs(x));
            z= -t/(t+two);
        }
        /* |x| > 22, return +-1 */
    } else {
        z = one - tiny; /* raised inexact flag */
    }
    return (jx>=0)? z: -z;
}
Variable Documentation
const double one =1.0 [static]
Definition at line 47 of file tanh.c.
Referenced by tanh().
const double tiny = 1.0e-300 [static]
Definition at line 47 of file tanh.c.
Referenced by tanh().
const double two =2.0 [static]
Definition at line 47 of file tanh.c.
Referenced by tanh().
Author
Generated automatically by Doxygen for amath from the source code.