.TH "TaskBase" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TaskBase \- Abstract base class encapsulating a system thread\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <task\&.h>\fP
.PP
Inherited by \fBStandardTask\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTaskBase\fP ()"
.br
.ti -1c
.RI "virtual \fB~TaskBase\fP ()"
.br
.ti -1c
.RI "virtual void \fBStart\fP (\fBThreadBase\fP *thread)=0"
.br
.ti -1c
.RI "virtual void \fBWaitExit\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Abstract base class encapsulating a system thread\&. 
.PP
Definition at line 42 of file task\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TaskBase::TaskBase ()\fC [inline]\fP"

.PP
Definition at line 44 of file task\&.h\&.
.PP
.nf
44 { }
.fi
.SS "virtual TaskBase::~TaskBase ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Definition at line 45 of file task\&.h\&.
.PP
.nf
45 { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "virtual void TaskBase::Start (\fBThreadBase\fP * thread)\fC [pure virtual]\fP"

.PP
Implemented in \fBStandardTask\fP\&.
.SS "virtual void TaskBase::WaitExit ()\fC [pure virtual]\fP"

.PP
Implemented in \fBStandardTask\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
