.TH "app/system/task_stdc.cpp" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/task_stdc.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'system/task_stdc\&.h'\fP
.br
\fC#include 'system/base/thread\&.h'\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
