.TH "app/system/task.h" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/task.h \- Generic task/process logic\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'system/base/thread\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTaskBase\fP"
.br
.RI "\fIAbstract base class encapsulating a system thread\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Generic task/process logic\&. 


.PP
Definition in file \fBtask\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
