.TH "textdef" 3 "Thu Jan 19 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
textdef \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <text\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "const char * \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 76 of file text\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "int textdef::id"

.PP
Definition at line 77 of file text\&.h\&.
.PP
Referenced by Language::GetText(), StandardLanguage::LoadCatalogs(), and StandardLanguage::Translate()\&.
.SS "const char* textdef::text"

.PP
Definition at line 78 of file text\&.h\&.
.PP
Referenced by StandardLanguage::LoadCatalogs(), StandardLanguage::Translate(), and PosixLanguage::Translate()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
