.TH "texttag" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
texttag \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clib\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBtag\fP"
.br
.ti -1c
.RI "const char * \fBtext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 42 of file clib\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "const char* texttag::tag"

.PP
Definition at line 43 of file clib\&.h\&.
.PP
Referenced by Untag()\&.
.SS "const char* texttag::text"

.PP
Definition at line 44 of file clib\&.h\&.
.PP
Referenced by Untag()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
