.TH "tFloatUnion32" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tFloatUnion32 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtB\fP \fBIsNegative\fP () const "
.br
.ti -1c
.RI "\fBtU32\fP \fBGetExponent\fP () const "
.br
.ti -1c
.RI "\fBtU32\fP \fBGetMantissa\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtF32\fP \fBm_floatingPoint\fP"
.br
.ti -1c
.RI "\fBtU32\fP \fBm_integer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 68 of file dprint\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBtU32\fP tFloatUnion32::GetExponent () const\fC [inline]\fP"

.PP
Definition at line 73 of file dprint\&.cpp\&.
.PP
References m_integer\&.
.PP
Referenced by PrintFloat32()\&.
.PP
.nf
73                              {
74         return (m_integer >> 23) & 0xFF;
75     }
.fi
.SS "\fBtU32\fP tFloatUnion32::GetMantissa () const\fC [inline]\fP"

.PP
Definition at line 76 of file dprint\&.cpp\&.
.PP
References m_integer\&.
.PP
Referenced by PrintFloat32()\&.
.PP
.nf
76                              {
77         return m_integer & 0x7FFFFF;
78     }
.fi
.SS "\fBtB\fP tFloatUnion32::IsNegative () const\fC [inline]\fP"

.PP
Definition at line 70 of file dprint\&.cpp\&.
.PP
References m_integer\&.
.PP
Referenced by PrintFloat32()\&.
.PP
.nf
70                              {
71         return (m_integer >> 31) != 0;
72     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBtF32\fP tFloatUnion32::m_floatingPoint"

.PP
Definition at line 80 of file dprint\&.cpp\&.
.PP
Referenced by PrintFloat32()\&.
.SS "\fBtU32\fP tFloatUnion32::m_integer"

.PP
Definition at line 81 of file dprint\&.cpp\&.
.PP
Referenced by GetExponent(), GetMantissa(), and IsNegative()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
