.TH "tFloatUnion64" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tFloatUnion64 \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtB\fP \fBIsNegative\fP () const "
.br
.ti -1c
.RI "\fBtU32\fP \fBGetExponent\fP () const "
.br
.ti -1c
.RI "\fBtU64\fP \fBGetMantissa\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtF64\fP \fBm_floatingPoint\fP"
.br
.ti -1c
.RI "\fBtU64\fP \fBm_integer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 90 of file dprint\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBtU32\fP tFloatUnion64::GetExponent () const\fC [inline]\fP"

.PP
Definition at line 95 of file dprint\&.cpp\&.
.PP
References m_integer\&.
.PP
Referenced by PrintFloat64()\&.
.PP
.nf
95                              {
96         return (m_integer >> 52) & 0x7FF;
97     }
.fi
.SS "\fBtU64\fP tFloatUnion64::GetMantissa () const\fC [inline]\fP"

.PP
Definition at line 98 of file dprint\&.cpp\&.
.PP
References m_integer\&.
.PP
Referenced by PrintFloat64()\&.
.PP
.nf
98                              {
99         return m_integer & 0xFFFFFFFFFFFFFull;
100     }
.fi
.SS "\fBtB\fP tFloatUnion64::IsNegative () const\fC [inline]\fP"

.PP
Definition at line 92 of file dprint\&.cpp\&.
.PP
References m_integer\&.
.PP
Referenced by PrintFloat64()\&.
.PP
.nf
92                              {
93         return (m_integer >> 63) != 0;
94     }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBtF64\fP tFloatUnion64::m_floatingPoint"

.PP
Definition at line 102 of file dprint\&.cpp\&.
.PP
Referenced by PrintFloat64()\&.
.SS "\fBtU64\fP tFloatUnion64::m_integer"

.PP
Definition at line 103 of file dprint\&.cpp\&.
.PP
Referenced by GetExponent(), GetMantissa(), and IsNegative()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
