tFloatUnion64
NAME
tFloatUnion64 -
SYNOPSIS
Public Member Functions
tB IsNegative () const
tU32 GetExponent () const
tU64 GetMantissa () const
Public Attributes
tF64 m_floatingPoint
tU64 m_integer
Detailed Description
Definition at line 90 of file dprint.cpp.
Member Function Documentation
tU32 tFloatUnion64::GetExponent () const [inline]
Definition at line 95 of file dprint.cpp.
References m_integer.
Referenced by PrintFloat64().
                             {
        return (m_integer >> 52) & 0x7FF;
    }
tU64 tFloatUnion64::GetMantissa () const [inline]
Definition at line 98 of file dprint.cpp.
References m_integer.
Referenced by PrintFloat64().
                             {
        return m_integer & 0xFFFFFFFFFFFFFull;
    }
tB tFloatUnion64::IsNegative () const [inline]
Definition at line 92 of file dprint.cpp.
References m_integer.
Referenced by PrintFloat64().
                             {
        return (m_integer >> 63) != 0;
    }
Member Data Documentation
tF64 tFloatUnion64::m_floatingPoint
Definition at line 102 of file dprint.cpp.
Referenced by PrintFloat64().
tU64 tFloatUnion64::m_integer
Definition at line 103 of file dprint.cpp.
Referenced by GetExponent(), GetMantissa(), and IsNegative().
Author
Generated automatically by Doxygen for amath from the source code.