tFloatUnion32
NAME
tFloatUnion32 -
SYNOPSIS
Public Member Functions
tB IsNegative () const
tU32 GetExponent () const
tU32 GetMantissa () const
Public Attributes
tF32 m_floatingPoint
tU32 m_integer
Detailed Description
Definition at line 68 of file dprint.cpp.
Member Function Documentation
tU32 tFloatUnion32::GetExponent () const [inline]
Definition at line 73 of file dprint.cpp.
References m_integer.
Referenced by PrintFloat32().
                             {
        return (m_integer >> 23) & 0xFF;
    }
tU32 tFloatUnion32::GetMantissa () const [inline]
Definition at line 76 of file dprint.cpp.
References m_integer.
Referenced by PrintFloat32().
                             {
        return m_integer & 0x7FFFFF;
    }
tB tFloatUnion32::IsNegative () const [inline]
Definition at line 70 of file dprint.cpp.
References m_integer.
Referenced by PrintFloat32().
                             {
        return (m_integer >> 31) != 0;
    }
Member Data Documentation
tF32 tFloatUnion32::m_floatingPoint
Definition at line 80 of file dprint.cpp.
Referenced by PrintFloat32().
tU32 tFloatUnion32::m_integer
Definition at line 81 of file dprint.cpp.
Referenced by GetExponent(), GetMantissa(), and IsNegative().
Author
Generated automatically by Doxygen for amath from the source code.