.TH "app/system/base/thread.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/base/thread.h \- Generic thread logic\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBThreadBase\fP"
.br
.RI "\fIAbstract base class encapsulating runable component\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Generic thread logic\&. 


.PP
Definition in file \fBthread\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
