Token
NAME
Token - Tokens are created by the Lexical Analyzer and provides an intermediate state for input consumed by the parser.
SYNOPSIS
#include <token.h>
Public Member Functions
Token (Token *last, Symbol symbol, int pos)
Token (Token *last, Symbol symbol, const char *text, int pos)
~Token ()
int GetPos ()
char * GetText ()
Token * GetLastToken ()
Token * GetNextToken ()
Public Attributes
Symbol symbol
Private Attributes
int pos
char * text
Token * last
Token * next
Friends
class Lexer
Detailed Description
Tokens are created by the Lexical Analyzer and provides an intermediate state for input consumed by the parser.
Definition at line 43 of file token.h.
Constructor & Destructor Documentation
Token::Token (Token * last, Symbol symbol, int pos)
Definition at line 34 of file token.cpp.
References last, next, pos, symbol, and text.
Referenced by Lexer::GetLitteral(), GetNextToken(), Lexer::GetNextToken(), and Lexer::GetOperator().
{
    this->last = last;
    this->symbol = symbol;
    this->pos = pos;
    this->text = NOMEM;
    this->next = NOMEM;
}
Token::Token (Token * last, Symbol symbol, const char * text, int pos)
Definition at line 43 of file token.cpp.
References AllocAndCopy(), last, next, pos, symbol, and text.
Referenced by Lexer::GetDigitValue(), Lexer::GetLitteral(), and Lexer::GetQuotedIdent().
{
    this->last = last;
    this->symbol = symbol;
    this->pos = pos;
    this->next = NOMEM;
    AllocAndCopy(&this->text, text);
}
Token::~Token ()
Definition at line 52 of file token.cpp.
References next, and text.
{
    if (text != NOMEM) {
        delete [] text;
    }
    if (next != NOMEM) {
        delete next;
    }
}
Member Function Documentation
Token * Token::GetLastToken ()
Definition at line 63 of file token.cpp.
References last.
Referenced by Parser::PutToken().
{
    return last;
}
Token * Token::GetNextToken ()
Definition at line 68 of file token.cpp.
References next, pos, symend, and Token().
Referenced by Parser::GetToken().
{
    // Always return a token if requested
    if (next == NOMEM) {
        next = new Token(this, symend, pos);
    }
    return next;
}
int Token::GetPos ()
Definition at line 83 of file token.cpp.
References pos.
Referenced by Parser::Expect(), Parser::Parse(), Parser::ParseAtomic(), Parser::ParseDeleteStatement(), Parser::ParseDigistStatement(), Parser::ParseFileStatement(), Parser::ParseFunctionDef(), Parser::ParseIdent(), Parser::ParseListStatement(), and Parser::ParseNumeralStatement().
{
    return pos;
}
char * Token::GetText ()
Definition at line 78 of file token.cpp.
References text.
Referenced by Parser::ParseDeleteStatement(), Parser::ParseDigistStatement(), Parser::ParseDrawStatement(), Parser::ParseFileStatement(), Parser::ParseFunctionDef(), Parser::ParseHelpStatement(), Parser::ParseIdent(), Parser::ParseListStatement(), Parser::ParseNumber(), Parser::ParseNumeralStatement(), and Parser::ParsePromptStatement().
{
    return text;
}
Friends And Related Function Documentation
friend class Lexer [friend]
Definition at line 60 of file token.h.
Member Data Documentation
Token* Token::last [private]
Definition at line 58 of file token.h.
Referenced by GetLastToken(), and Token().
Token* Token::next [private]
Definition at line 59 of file token.h.
Referenced by GetNextToken(), Token(), Lexer::Tokenize(), and ~Token().
int Token::pos [private]
Definition at line 56 of file token.h.
Referenced by GetNextToken(), GetPos(), and Token().
Symbol Token::symbol
Definition at line 49 of file token.h.
Referenced by Parser::Expect(), Parser::Parse(), Parser::ParseAddSubstract(), Parser::ParseAtomic(), Parser::ParseDeleteStatement(), Parser::ParseDigistStatement(), Parser::ParseDrawStatement(), Parser::ParseFactor(), Parser::ParseFileStatement(), Parser::ParseHelpStatement(), Parser::ParseIdent(), Parser::ParseListStatement(), Parser::ParseNumber(), Parser::ParseNumeralStatement(), Parser::ParsePower(), Parser::ParsePrefsStatement(), Parser::ParsePromptStatement(), Parser::ParseStatement(), Parser::ParseUnary(), Token(), Lexer::Tokenize(), and Parser::TryParseStatement().
char* Token::text [private]
Definition at line 57 of file token.h.
Referenced by GetText(), Token(), and ~Token().
Author
Generated automatically by Doxygen for amath from the source code.