.TH "Token" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Token \- Tokens are created by the Lexical Analyzer and provides an intermediate state for input consumed by the parser\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <token\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBToken\fP (\fBToken\fP *\fBlast\fP, \fBSymbol\fP \fBsymbol\fP, int \fBpos\fP)"
.br
.ti -1c
.RI "\fBToken\fP (\fBToken\fP *\fBlast\fP, \fBSymbol\fP \fBsymbol\fP, const char *\fBtext\fP, int \fBpos\fP)"
.br
.ti -1c
.RI "\fB~Token\fP ()"
.br
.ti -1c
.RI "int \fBGetPos\fP ()"
.br
.ti -1c
.RI "char * \fBGetText\fP ()"
.br
.ti -1c
.RI "\fBToken\fP * \fBGetLastToken\fP ()"
.br
.ti -1c
.RI "\fBToken\fP * \fBGetNextToken\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSymbol\fP \fBsymbol\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBpos\fP"
.br
.ti -1c
.RI "char * \fBtext\fP"
.br
.ti -1c
.RI "\fBToken\fP * \fBlast\fP"
.br
.ti -1c
.RI "\fBToken\fP * \fBnext\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBLexer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tokens are created by the Lexical Analyzer and provides an intermediate state for input consumed by the parser\&. 
.PP
Definition at line 43 of file token\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Token::Token (\fBToken\fP * last, \fBSymbol\fP symbol, int pos)"

.PP
Definition at line 34 of file token\&.cpp\&.
.PP
References last, next, pos, symbol, and text\&.
.PP
Referenced by Lexer::GetLitteral(), GetNextToken(), Lexer::GetNextToken(), and Lexer::GetOperator()\&.
.PP
.nf
35 {
36     this->last = last;
37     this->symbol = symbol;
38     this->pos = pos;
39     this->text = NOMEM;
40     this->next = NOMEM;
41 }
.fi
.SS "Token::Token (\fBToken\fP * last, \fBSymbol\fP symbol, const char * text, int pos)"

.PP
Definition at line 43 of file token\&.cpp\&.
.PP
References AllocAndCopy(), last, next, pos, symbol, and text\&.
.PP
Referenced by Lexer::GetDigitValue(), Lexer::GetLitteral(), and Lexer::GetQuotedIdent()\&.
.PP
.nf
44 {
45     this->last = last;
46     this->symbol = symbol;
47     this->pos = pos;
48     this->next = NOMEM;
49     AllocAndCopy(&this->text, text);
50 }
.fi
.SS "Token::~Token ()"

.PP
Definition at line 52 of file token\&.cpp\&.
.PP
References next, and text\&.
.PP
.nf
53 {
54     if (text != NOMEM) {
55         delete [] text;
56     }
57 
58     if (next != NOMEM) {
59         delete next;
60     }
61 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBToken\fP * Token::GetLastToken ()"

.PP
Definition at line 63 of file token\&.cpp\&.
.PP
References last\&.
.PP
Referenced by Parser::PutToken()\&.
.PP
.nf
64 {
65     return last;
66 }
.fi
.SS "\fBToken\fP * Token::GetNextToken ()"

.PP
Definition at line 68 of file token\&.cpp\&.
.PP
References next, pos, symend, and Token()\&.
.PP
Referenced by Parser::GetToken()\&.
.PP
.nf
69 {
70     // Always return a token if requested
71     if (next == NOMEM) {
72         next = new Token(this, symend, pos);
73     }
74 
75     return next;
76 }
.fi
.SS "int Token::GetPos ()"

.PP
Definition at line 83 of file token\&.cpp\&.
.PP
References pos\&.
.PP
Referenced by Parser::Expect(), Parser::Parse(), Parser::ParseAtomic(), Parser::ParseDeleteStatement(), Parser::ParseDigistStatement(), Parser::ParseFileStatement(), Parser::ParseFunctionDef(), Parser::ParseIdent(), Parser::ParseListStatement(), and Parser::ParseNumeralStatement()\&.
.PP
.nf
84 {
85     return pos;
86 }
.fi
.SS "char * Token::GetText ()"

.PP
Definition at line 78 of file token\&.cpp\&.
.PP
References text\&.
.PP
Referenced by Parser::ParseDeleteStatement(), Parser::ParseDigistStatement(), Parser::ParseDrawStatement(), Parser::ParseFileStatement(), Parser::ParseFunctionDef(), Parser::ParseHelpStatement(), Parser::ParseIdent(), Parser::ParseListStatement(), Parser::ParseNumber(), Parser::ParseNumeralStatement(), and Parser::ParsePromptStatement()\&.
.PP
.nf
79 {
80     return text;
81 }
.fi
.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBLexer\fP\fC [friend]\fP"

.PP
Definition at line 60 of file token\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBToken\fP* Token::last\fC [private]\fP"

.PP
Definition at line 58 of file token\&.h\&.
.PP
Referenced by GetLastToken(), and Token()\&.
.SS "\fBToken\fP* Token::next\fC [private]\fP"

.PP
Definition at line 59 of file token\&.h\&.
.PP
Referenced by GetNextToken(), Token(), Lexer::Tokenize(), and ~Token()\&.
.SS "int Token::pos\fC [private]\fP"

.PP
Definition at line 56 of file token\&.h\&.
.PP
Referenced by GetNextToken(), GetPos(), and Token()\&.
.SS "\fBSymbol\fP Token::symbol"

.PP
Definition at line 49 of file token\&.h\&.
.PP
Referenced by Parser::Expect(), Parser::Parse(), Parser::ParseAddSubstract(), Parser::ParseAtomic(), Parser::ParseDeleteStatement(), Parser::ParseDigistStatement(), Parser::ParseDrawStatement(), Parser::ParseFactor(), Parser::ParseFileStatement(), Parser::ParseHelpStatement(), Parser::ParseIdent(), Parser::ParseListStatement(), Parser::ParseNumber(), Parser::ParseNumeralStatement(), Parser::ParsePower(), Parser::ParsePrefsStatement(), Parser::ParsePromptStatement(), Parser::ParseStatement(), Parser::ParseUnary(), Token(), Lexer::Tokenize(), and Parser::TryParseStatement()\&.
.SS "char* Token::text\fC [private]\fP"

.PP
Definition at line 57 of file token\&.h\&.
.PP
Referenced by GetText(), Token(), and ~Token()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
