.TH "app/main/token.h" 3 "Sun Jan 22 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/token.h \- Application logic tied to \fBToken\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'localize/lex\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBToken\fP"
.br
.RI "\fITokens are created by the Lexical Analyzer and provides an intermediate state for input consumed by the parser\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Application logic tied to \fBToken\fP\&. 


.PP
Definition in file \fBtoken\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
