lib/real/trunc.c
NAME
lib/real/trunc.c -
SYNOPSIS
#include 'prim.h'
#include 'math.h'
Functions
double trunc (double x)
Function Documentation
double trunc (double x)
Definition at line 30 of file trunc.c.
Referenced by ctrunc(), DecimalSystem::GetRealText(), PositionalNumeralSystem::GetText(), PositionalNumeralSystem::IntegerToBuffer(), and RealNumber::Trunc().
{
    return x > 0.0 ? floor(x) : ceil(x);
}
Author
Generated automatically by Doxygen for amath from the source code.