.TH "TruncNode" 3 "Tue Jan 24 2017" "Version 1.6.2" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TruncNode \- A truncation function in a syntax tree\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <functions\&.h>\fP
.PP
Inherits \fBFunctionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTruncNode\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.ti -1c
.RI "\fBNumber\fP * \fBEvaluate\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBFunctionNode\fP * \fBCreate\fP (\fBExpressionNode\fP *\fBexpression\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "char * \fBGetNodeText\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
A truncation function in a syntax tree\&. 

Discard the number of digits right of the decimal point\&. See \fBNumber\fP for implementation\&.
.PP
More info on the truncation function is available at Wikipedia: http://en.wikipedia.org/wiki/Truncation 
.PP
Definition at line 240 of file functions\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TruncNode::TruncNode (\fBExpressionNode\fP * expression)"

.PP
Definition at line 560 of file functions\&.cpp\&.
.PP
References FunctionNode::FunctionNode()\&.
.PP
Referenced by Create()\&.
.PP
.nf
560                                                :
561     FunctionNode(expression) { }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBFunctionNode\fP * TruncNode::Create (\fBExpressionNode\fP * expression)\fC [static]\fP"

.PP
Definition at line 563 of file functions\&.cpp\&.
.PP
References TruncNode()\&.
.PP
.nf
564 {
565     return new TruncNode(expression);
566 }
.fi
.SS "\fBNumber\fP * TruncNode::Evaluate ()\fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 568 of file functions\&.cpp\&.
.PP
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Trunc()\&.
.PP
.nf
569 {
570     result = expression->Evaluate()->Trunc();
571     return result;
572 }
.fi
.SS "char * TruncNode::GetNodeText ()\fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBExpressionNode\fP\&.
.PP
Definition at line 574 of file functions\&.cpp\&.
.PP
.nf
575 {
576     return (char*)"trunc";
577 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
