TruncNode
NAME
TruncNode - A truncation function in a syntax tree.
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
TruncNode (ExpressionNode *expression)
Number * Evaluate ()
Static Public Member Functions
static FunctionNode * Create (ExpressionNode *expression)
Protected Member Functions
char * GetNodeText ()
Additional Inherited Members
Detailed Description
A truncation function in a syntax tree.
Discard the number of digits right of the decimal point. See Number for implementation.
More info on the truncation function is available at Wikipedia: http://en.wikipedia.org/wiki/Truncation
Definition at line 240 of file functions.h.
Constructor & Destructor Documentation
TruncNode::TruncNode (ExpressionNode * expression)
Definition at line 560 of file functions.cpp.
References FunctionNode::FunctionNode().
Referenced by Create().
                                               :
    FunctionNode(expression) { }
Member Function Documentation
FunctionNode * TruncNode::Create (ExpressionNode * expression) [static]
Definition at line 563 of file functions.cpp.
References TruncNode().
{
    return new TruncNode(expression);
}
Number * TruncNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 568 of file functions.cpp.
References ExpressionNode::Evaluate(), FunctionNode::expression, ExpressionNode::result, and Number::Trunc().
{
    result = expression->Evaluate()->Trunc();
    return result;
}
char * TruncNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 574 of file functions.cpp.
{
    return (char*)"trunc";
}
Author
Generated automatically by Doxygen for amath from the source code.