UnaryNode
NAME
UnaryNode -
SYNOPSIS
#include <operators.h>
Inherits ExpressionNode.
Public Member Functions
UnaryNode (ExpressionNode *expression)
~UnaryNode ()
ReductionType GetReductionType ()
int GetPrecedence ()
SyntaxNode * GetNext ()
char * GetText ()
Number * Evaluate ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Protected Member Functions
char * GetNodeText ()
Private Attributes
ExpressionNode * expression
Additional Inherited Members
Detailed Description
Definition at line 39 of file operators.h.
Constructor & Destructor Documentation
UnaryNode::UnaryNode (ExpressionNode * expression)
Definition at line 36 of file operators.cpp.
References expression, and ExpressionNode::ExpressionNode().
Referenced by Parser::ParseUnary().
                                               :
    ExpressionNode(), expression(expression) { }
UnaryNode::~UnaryNode ()
Definition at line 39 of file operators.cpp.
References expression.
{
    if (expression != NOMEM) {
        delete expression;
    }
}
Member Function Documentation
void UnaryNode::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 98 of file operators.cpp.
References expression, and SyntaxNode::SetParent().
{
    if (expression == NOMEM) {
        expression = (ExpressionNode*)node;
        node->SetParent(this);
    }
}
void UnaryNode::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 106 of file operators.cpp.
References expression.
{
    if (expression == node) {
        expression = NOMEM;
    }
}
Number * UnaryNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 82 of file operators.cpp.
References ExpressionNode::Evaluate(), expression, ExpressionNode::result, and Number::Unary().
{
    result = expression->Evaluate()->Unary();
    return result;
}
SyntaxNode * UnaryNode::GetNext () [virtual]
Implements SyntaxNode.
Definition at line 88 of file operators.cpp.
References expression, and SyntaxNode::iterator.
{
    if (iterator == NOMEM) {
        iterator = expression;
        return iterator;
    }
    return NOMEM;
}
char * UnaryNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 56 of file operators.cpp.
Referenced by GetText().
{
    return (char*)"-";
}
int UnaryNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 51 of file operators.cpp.
Referenced by GetText().
{
    return 7;
}
ReductionType UnaryNode::GetReductionType () [virtual]
Reimplemented from SyntaxNode.
Definition at line 46 of file operators.cpp.
References unaryreduc.
{
    return unaryreduc;
}
char * UnaryNode::GetText () [virtual]
Implements ExpressionNode.
Definition at line 61 of file operators.cpp.
References CharBuffer::Append(), CharBuffer::Empty(), CharBuffer::EnsureSize(), expression, GetNodeText(), GetPrecedence(), ExpressionNode::GetPrecedence(), CharBuffer::GetString(), ExpressionNode::GetText(), SyntaxNode::output, and StrLen().
{
    const char *expText = expression->GetText();
    const char *nodeText = GetNodeText();
    output->Empty();
    output->EnsureSize(StrLen(expText) + StrLen(nodeText) + 2 + 1);
    if (expression->GetPrecedence() != 0 && expression->GetPrecedence() != 5 && expression->GetPrecedence() <= GetPrecedence()) {
        output->Append(nodeText);
        output->Append("(");
        output->Append(expText);
        output->Append(")");
    } else {
        output->Append(nodeText);
        output->Append(expText);
    }
    return output->GetString();
}
void UnaryNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Definition at line 113 of file operators.cpp.
References expression.
{
    if (expression == n) {
        delete expression;
        expression = (ExpressionNode*)x;
    }
}
Member Data Documentation
ExpressionNode* UnaryNode::expression [private]
Definition at line 57 of file operators.h.
Referenced by Attach(), Detach(), Evaluate(), GetNext(), GetText(), Replace(), UnaryNode(), and ~UnaryNode().
Author
Generated automatically by Doxygen for amath from the source code.