.TH "lib/clib/untag.c" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/clib/untag.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBUntag\fP (char *destination, const char *source, \fBtexttag\fP tags[], unsigned int tagcount)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Untag (char * destination, const char * source, \fBtexttag\fP tags[], unsigned int tagcount)"

.PP
Definition at line 29 of file untag\&.c\&.
.PP
References texttag::tag, and texttag::text\&.
.PP
Referenced by Language::UntagText()\&.
.PP
.nf
30 {
31     const char *pos, *tmp, *tag;
32     char *dest;
33     int unsigned i, j, found;
34 
35     pos = source;
36     dest = destination;
37 
38     while (*pos != '\0') {
39         if (*pos != '#') {
40             (*dest++ = *pos++);
41         } else {
42             // Try to replace tag
43             found = 0;
44             for (i = 0; i < tagcount; i++) {
45                 tag = tags[i]\&.tag;
46                 tmp = pos;
47                 j = 0;
48                 while (*tmp != '\0' && *tag != '\0' && *tmp == *tag) {
49                     tmp++;
50                     tag++;
51                     j++;
52                 }
53 
54                 if (j > 1 && *(--tag) == '#') {
55                     // Tag found\&. Now replace\&.
56                     tag = tags[i]\&.text;
57                     while ((*dest++ = *tag++));
58                     dest--;
59                     pos = tmp;
60                     found = 1;
61                     break;
62                 }
63             }
64 
65             if(!found) {
66                 (*dest++ = *pos++);
67             }
68         }
69     }
70     *dest = '\0';
71 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
