UserFunction
NAME
UserFunction - A user defined function.
SYNOPSIS
#include <functions.h>
Public Member Functions
UserFunction (const char *name, const char *variable, ExpressionNode *expression)
UserFunction (const char *name)
~UserFunction ()
char * GetName ()
char * GetDefitionName ()
char * GetDefitionText ()
Variable * GetVariable ()
Variable * CreateVariable (const char *name)
ExpressionNode * GetExpression ()
void SetExpression (ExpressionNode *expression)
Public Attributes
UserFunction * Next
Private Member Functions
void InitializeTexts ()
Private Attributes
char * name
Variable * variable
ExpressionNode * expression
bool chainDelete
CharBuffer * defname
CharBuffer * defition
Friends
bool FunctionList::Delete (const char *name, const char *argument)
Detailed Description
A user defined function.
Definition at line 105 of file functions.h.
Constructor & Destructor Documentation
UserFunction::UserFunction (const char * name, const char * variable, ExpressionNode * expression)
Definition at line 106 of file functions.cpp.
References AllocAndCopy(), chainDelete, CharBuffer::CharBuffer(), defition, defname, expression, InitializeTexts(), name, Next, Variable::Variable(), and variable.
{
    AllocAndCopy(&this->name, name);
    this->variable = new Variable(variable);
    this->expression = expression;
    this->Next = NOMEM;
    defname = new CharBuffer();
    defition = new CharBuffer();
    InitializeTexts();
    chainDelete = true;
}
UserFunction::UserFunction (const char * name)
Definition at line 120 of file functions.cpp.
References AllocAndCopy(), chainDelete, CharBuffer::CharBuffer(), defition, defname, expression, name, Next, and variable.
Referenced by FunctionList::GetFunctionDef().
{
    AllocAndCopy(&this->name, name);
    this->variable = NOMEM;
    this->expression = NOMEM;
    this->Next = NOMEM;
    defname = new CharBuffer();
    defition = new CharBuffer();
    chainDelete = true;
}
UserFunction::~UserFunction ()
Definition at line 133 of file functions.cpp.
References chainDelete, defition, defname, expression, name, Next, and variable.
{
    delete [] name;
    delete defname;
    delete defition;
    if (variable != NOMEM) {
        delete variable;
    }
    if (expression != NOMEM) {
        delete expression;
    }
    if (chainDelete && Next != NOMEM) {
        delete Next;
    }
}
Member Function Documentation
Variable * UserFunction::CreateVariable (const char * name)
Definition at line 186 of file functions.cpp.
References InitializeTexts(), Variable::Variable(), and variable.
Referenced by Parser::ParseFunctionDef().
{
    if(variable != NOMEM) {
        delete variable;
    }
    variable = new Variable(name);
    InitializeTexts();
    return variable;
}
char * UserFunction::GetDefitionName ()
Definition at line 171 of file functions.cpp.
References defname, and CharBuffer::GetString().
{
    return defname->GetString();
}
char * UserFunction::GetDefitionText ()
Definition at line 176 of file functions.cpp.
References defition, and CharBuffer::GetString().
{
    return defition->GetString();
}
ExpressionNode * UserFunction::GetExpression ()
Definition at line 198 of file functions.cpp.
References expression.
Referenced by UserFunctionNode::Evaluate(), Grid::FunctionValue(), UserFunctionNode::GetNext(), and FunctionList::ListContent().
{
    return expression;
}
char * UserFunction::GetName ()
Definition at line 166 of file functions.cpp.
References name.
Referenced by FunctionList::Delete(), FunctionList::GetFunctionCall(), FunctionList::GetFunctionDef(), UserFunctionNode::GetNodeText(), and FunctionList::ListContent().
{
    return name;
}
Variable * UserFunction::GetVariable ()
Definition at line 181 of file functions.cpp.
References variable.
Referenced by FunctionList::Delete(), UserFunctionNode::Evaluate(), Grid::FunctionValue(), FunctionList::GetFunctionDef(), and FunctionList::ListContent().
{
    return variable;
}
void UserFunction::InitializeTexts () [private]
Definition at line 152 of file functions.cpp.
References CharBuffer::Append(), defition, defname, CharBuffer::Empty(), expression, Variable::GetName(), CharBuffer::GetString(), ExpressionNode::GetText(), name, and variable.
Referenced by CreateVariable(), SetExpression(), and UserFunction().
{
    defname->Empty();
    defname->Append(name);
    defname->Append('(');
    defname->Append(variable != NOMEM ? variable->GetName() : EMPTYSTRING);
    defname->Append(')');
    defition->Empty();
    defition->Append(defname->GetString());
    defition->Append('=');
    defition->Append(expression != NOMEM ? expression->GetText() : EMPTYSTRING);
}
void UserFunction::SetExpression (ExpressionNode * expression)
Definition at line 203 of file functions.cpp.
References expression, and InitializeTexts().
Referenced by Parser::ParseFunctionDef().
{
    delete this->expression;
    this->expression = expression;
    InitializeTexts();
}
Friends And Related Function Documentation
bool FunctionList::Delete (const char * name, const char * argument) [friend]
Member Data Documentation
bool UserFunction::chainDelete [private]
Definition at line 125 of file functions.h.
Referenced by FunctionList::Delete(), UserFunction(), and ~UserFunction().
CharBuffer* UserFunction::defition [private]
Definition at line 130 of file functions.h.
Referenced by GetDefitionText(), InitializeTexts(), UserFunction(), and ~UserFunction().
CharBuffer* UserFunction::defname [private]
Definition at line 129 of file functions.h.
Referenced by GetDefitionName(), InitializeTexts(), UserFunction(), and ~UserFunction().
ExpressionNode* UserFunction::expression [private]
Definition at line 124 of file functions.h.
Referenced by GetExpression(), InitializeTexts(), SetExpression(), UserFunction(), and ~UserFunction().
char* UserFunction::name [private]
Definition at line 122 of file functions.h.
Referenced by GetName(), InitializeTexts(), UserFunction(), and ~UserFunction().
UserFunction* UserFunction::Next
Definition at line 111 of file functions.h.
Referenced by FunctionList::Delete(), FunctionList::GetFunctionCall(), FunctionList::GetFunctionDef(), FunctionList::ListContent(), UserFunction(), and ~UserFunction().
Variable* UserFunction::variable [private]
Definition at line 123 of file functions.h.
Referenced by CreateVariable(), GetVariable(), InitializeTexts(), UserFunction(), and ~UserFunction().
Author
Generated automatically by Doxygen for amath from the source code.