UserFunctionNode
NAME
UserFunctionNode - An expression node able to compute a function value.
SYNOPSIS
#include <functions.h>
Inherits FunctionNode.
Public Member Functions
UserFunctionNode (UserFunction *function, ExpressionNode *parameter)
Number * Evaluate ()
SyntaxNode * GetNext ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Protected Member Functions
char * GetNodeText ()
Private Attributes
UserFunction * function
Additional Inherited Members
Detailed Description
An expression node able to compute a function value.
Definition at line 158 of file functions.h.
Constructor & Destructor Documentation
UserFunctionNode::UserFunctionNode (UserFunction * function, ExpressionNode * parameter)
Definition at line 214 of file functions.cpp.
References function, and FunctionNode::FunctionNode().
Referenced by FunctionList::GetFunctionCall().
                                                                                    :
    FunctionNode(parameter), function(function) { }
Member Function Documentation
void UserFunctionNode::Attach (SyntaxNode * node) [virtual]
Reimplemented from FunctionNode.
Definition at line 239 of file functions.cpp.
{
    // TODO: Implement
}
void UserFunctionNode::Detach (SyntaxNode * node) [virtual]
Reimplemented from FunctionNode.
Definition at line 244 of file functions.cpp.
{
    // TODO: Implement
}
Number * UserFunctionNode::Evaluate () [virtual]
Implements ExpressionNode.
Definition at line 222 of file functions.cpp.
References Variable::AssignValue(), ExpressionNode::Evaluate(), FunctionNode::expression, function, UserFunction::GetExpression(), and UserFunction::GetVariable().
{
    // Set value of function parameter and then evaluate function.
    function->GetVariable()->AssignValue(expression->Evaluate());
    return function->GetExpression()->Evaluate();
}
SyntaxNode * UserFunctionNode::GetNext () [virtual]
Reimplemented from FunctionNode.
Definition at line 229 of file functions.cpp.
References function, UserFunction::GetExpression(), and SyntaxNode::iterator.
{
    if (iterator == NOMEM) {
        iterator = function->GetExpression();
        return iterator;
    }
    return NOMEM;
}
char * UserFunctionNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Definition at line 217 of file functions.cpp.
References function, and UserFunction::GetName().
{
    return function->GetName();
}
void UserFunctionNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Reimplemented from FunctionNode.
Definition at line 249 of file functions.cpp.
{
    // TODO: Implement
}
Member Data Documentation
UserFunction* UserFunctionNode::function [private]
Definition at line 171 of file functions.h.
Referenced by Evaluate(), GetNext(), GetNodeText(), and UserFunctionNode().
Author
Generated automatically by Doxygen for amath from the source code.