Variable
NAME
Variable - A user defined variable.
SYNOPSIS
#include <values.h>
Public Member Functions
Variable (const char *name)
~Variable ()
char * GetName ()
Number * GetValue ()
void AssignValue (Number *value)
Public Attributes
Variable * Next
Private Attributes
char * name
Number * value
bool chainDelete
Friends
bool VariableList::Delete (const char *name)
Detailed Description
A user defined variable.
Definition at line 72 of file values.h.
Constructor & Destructor Documentation
Variable::Variable (const char * name)
Definition at line 42 of file values.cpp.
References AllocAndCopy(), chainDelete, name, Next, and value.
Referenced by VariableList::CreateVariable(), UserFunction::CreateVariable(), and UserFunction::UserFunction().
{
    AllocAndCopy(&this->name, name);
    value = NOMEM;
    Next = NOMEM;
    chainDelete = true;
}
Variable::~Variable ()
Definition at line 50 of file values.cpp.
References chainDelete, name, Next, and value.
{
    delete [] name;
    if (value != NOMEM) {
        delete value;
    }
    if (chainDelete && Next != NOMEM) {
        delete Next;
    }
}
Member Function Documentation
void Variable::AssignValue (Number * value)
Definition at line 73 of file values.cpp.
References Number::Clone(), and value.
Referenced by VariableNode::AssignValue(), UserFunctionNode::Evaluate(), and Grid::FunctionValue().
{
    if (this->value != NOMEM) {
        delete this->value;
    }
    this->value = value->Clone();
}
char * Variable::GetName ()
Definition at line 63 of file values.cpp.
References name.
Referenced by VariableList::CreateVariable(), FunctionList::Delete(), FunctionList::GetFunctionDef(), VariableNode::GetNodeText(), VariableNode::GetText(), VariableList::GetVariable(), UserFunction::InitializeTexts(), VariableList::ListContent(), and FunctionList::ListContent().
{
    return name;
}
Number * Variable::GetValue ()
Definition at line 68 of file values.cpp.
References Number::Clone(), and value.
Referenced by VariableNode::Evaluate(), and VariableList::ListContent().
{
    return value->Clone();;
}
Friends And Related Function Documentation
bool VariableList::Delete (const char * name) [friend]
Member Data Documentation
bool Variable::chainDelete [private]
Definition at line 86 of file values.h.
Referenced by VariableList::Delete(), Variable(), and ~Variable().
char* Variable::name [private]
Definition at line 84 of file values.h.
Referenced by GetName(), Variable(), and ~Variable().
Variable* Variable::Next
Definition at line 81 of file values.h.
Referenced by VariableList::CreateVariable(), VariableList::Delete(), VariableList::GetVariable(), VariableList::InsertTemporaryVariable(), VariableList::ListContent(), VariableList::RemoveTemporaryVariable(), Variable(), and ~Variable().
Number* Variable::value [private]
Definition at line 85 of file values.h.
Referenced by AssignValue(), GetValue(), Variable(), and ~Variable().
Author
Generated automatically by Doxygen for amath from the source code.