VariableList
NAME
VariableList - A list of user defined variables.
SYNOPSIS
#include <values.h>
Public Member Functions
VariableList ()
~VariableList ()
void Clear ()
bool Delete (const char *name)
Variable * GetFirstVariable ()
Variable * GetVariable (const char *name)
Variable * CreateVariable (const char *name)
Variable * InsertTemporaryVariable (Variable *variable)
void RemoveTemporaryVariable ()
char * List ()
char * ListDefinitions ()
Private Member Functions
char * ListContent (bool cmdFormat)
Private Attributes
CharBuffer * buf
Variable * first
Detailed Description
A list of user defined variables.
Definition at line 46 of file values.h.
Constructor & Destructor Documentation
VariableList::VariableList ()
Definition at line 86 of file values.cpp.
References buf, CharBuffer::CharBuffer(), and first.
Referenced by Program::Program().
{
    first = NOMEM;
    buf = new CharBuffer();
}
VariableList::~VariableList ()
Definition at line 92 of file values.cpp.
References buf, and first.
{
    if (first != NOMEM) {
        delete first;
    }
    delete buf;
}
Member Function Documentation
void VariableList::Clear ()
Definition at line 101 of file values.cpp.
References buf, CharBuffer::ClearBuffer(), and first.
Referenced by DeleteStatement::Execute().
{
    if (first != NOMEM) {
        delete first;
        first = NOMEM;
    }
    buf->ClearBuffer();
}
Variable * VariableList::CreateVariable (const char * name)
Definition at line 159 of file values.cpp.
References first, Variable::GetName(), Variable::Next, StrIsEqual(), and Variable::Variable().
Referenced by Parser::ParseIdent().
{
    if (first == NOMEM) {
        first = new Variable(name);
        return first;
    }
    Variable* current = first;
    Variable* last = NOMEM;
    while (current != NOMEM) {
        if (StrIsEqual(name, current->GetName())) {
            return current;
        }
        last = current;
        current = current->Next;
    }
    current = new Variable(name);
    last->Next = current;
    return current;
}
bool VariableList::Delete (const char * name)
Definition at line 111 of file values.cpp.
References Variable::chainDelete, first, GetVariable(), and Variable::Next.
Referenced by DeleteStatement::Execute().
{
    Variable* var = GetVariable(name);
    if (var == NOMEM) {
        return false;
    }
    if (var == first) {
        first = var->Next;
        var->chainDelete = false;
        delete var;
        return true;
    }
    Variable *current = first->Next;
    Variable *last = first;
    while (current != var) {
        current = current->Next;
        last = last->Next;
    }
    last->Next = var->Next;
    // Only delete this variable. Not the whole chain.
    var->chainDelete = false;
    delete var;
    return true;
}
Variable * VariableList::GetFirstVariable ()
Definition at line 143 of file values.cpp.
References first.
Referenced by ListContent().
{
    return first;
}
Variable * VariableList::GetVariable (const char * name)
Definition at line 148 of file values.cpp.
References first, Variable::GetName(), Variable::Next, and StrIsEqual().
Referenced by Delete(), and Parser::ParseIdent().
{
    Variable* current = first;
    while (current != NOMEM && !StrIsEqual(current->GetName(), name)) {
        current = current->Next;
    }
    return current;
}
Variable * VariableList::InsertTemporaryVariable (Variable * variable)
Definition at line 184 of file values.cpp.
References first, and Variable::Next.
Referenced by Parser::ParseFunctionDef().
{
    // Temporary variables are always inserted at the beginning of the list.
    Variable* oldFirst = first;
    first = variable;
    variable->Next = oldFirst;
    return variable;
}
char * VariableList::List ()
Definition at line 202 of file values.cpp.
References ListContent().
Referenced by ListVariablesStatement::Execute().
{
    return ListContent(false);
}
char * VariableList::ListContent (bool cmdFormat) [private]
Definition at line 212 of file values.cpp.
References CharBuffer::Append(), buf, CharBuffer::Empty(), CharBuffer::EnsureSize(), GetFirstVariable(), Variable::GetName(), CharBuffer::GetString(), NumeralSystem::GetText(), Variable::GetValue(), Variable::Next, Program::Output, and StrLen().
Referenced by List(), and ListDefinitions().
{
    buf->Empty();
    if (GetFirstVariable() == NOMEM) {
        return (char*)(cmdFormat ? NOMEM : HELPVARSNDEF);
    }
    int len = 0;
    Variable* current = GetFirstVariable();
    while (current != NOMEM) {
        len += StrLen(current->GetName());
        len += 3;
        len += 32; // Max length of value
        len += cmdFormat ? 2 : 1;
        current = current->Next;
    }
    current = GetFirstVariable();
    buf->EnsureSize(len);
    while (current != NOMEM) {
        buf->Append(current->GetName());
        buf->Append(" = ");
        Number *num = current->GetValue();
        const char *val = Program->Output->GetText(num);
        buf->Append(val);
        delete num;
        if (cmdFormat) {
            buf->Append(';');
        }
        buf->Append(NEWLINE);
        current = current->Next;
    }
    return buf->GetString();
}
char * VariableList::ListDefinitions ()
Definition at line 207 of file values.cpp.
References ListContent().
Referenced by SaveStatement::Execute().
{
    return ListContent(true);
}
void VariableList::RemoveTemporaryVariable ()
Definition at line 194 of file values.cpp.
References first, and Variable::Next.
Referenced by Parser::ParseFunctionDef().
{
    // Temporary variables are not owned by the variable list. Do not free memory.
    Variable *newFirst = first->Next;
    first->Next = NOMEM;
    first = newFirst;
}
Member Data Documentation
CharBuffer* VariableList::buf [private]
Definition at line 64 of file values.h.
Referenced by Clear(), ListContent(), VariableList(), and ~VariableList().
Variable* VariableList::first [private]
Definition at line 65 of file values.h.
Referenced by Clear(), CreateVariable(), Delete(), GetFirstVariable(), GetVariable(), InsertTemporaryVariable(), RemoveTemporaryVariable(), VariableList(), and ~VariableList().
Author
Generated automatically by Doxygen for amath from the source code.