VariableNode
NAME
VariableNode - Use of a variable in a syntax tree.
SYNOPSIS
#include <values.h>
Inherits ExpressionNode.
Inherited by InsVariableNode.
Public Member Functions
VariableNode (Variable *variable)
char * GetText ()
Number * Evaluate ()
void AssignValue (Number *value)
int GetPrecedence ()
SyntaxNode * GetNext ()
void Attach (SyntaxNode *node)
void Detach (SyntaxNode *node)
void Replace (SyntaxNode *n, SyntaxNode *x)
Protected Member Functions
char * GetNodeText ()
Private Attributes
Variable * variable
Additional Inherited Members
Detailed Description
Use of a variable in a syntax tree.
Definition at line 104 of file values.h.
Constructor & Destructor Documentation
VariableNode::VariableNode (Variable * variable)
Definition at line 271 of file values.cpp.
References ExpressionNode::ExpressionNode(), and variable.
Referenced by InsVariableNode::InsVariableNode(), and Parser::ParseIdent().
                                            :
    ExpressionNode(), variable(variable) { }
Member Function Documentation
void VariableNode::AssignValue (Number * value)
Definition at line 285 of file values.cpp.
References Variable::AssignValue(), and variable.
Referenced by AssignmentNode::Evaluate().
{
    variable->AssignValue(value);
}
void VariableNode::Attach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 305 of file values.cpp.
{ }
void VariableNode::Detach (SyntaxNode * node) [virtual]
Implements SyntaxNode.
Definition at line 308 of file values.cpp.
{ }
Number * VariableNode::Evaluate () [virtual]
Implements ExpressionNode.
Reimplemented in InsVariableNode.
Definition at line 279 of file values.cpp.
References Variable::GetValue(), ExpressionNode::result, and variable.
Referenced by AssignmentNode::Evaluate().
{
    result = variable->GetValue();
    return result;
}
SyntaxNode * VariableNode::GetNext () [virtual]
Implements SyntaxNode.
Definition at line 300 of file values.cpp.
{
    return NOMEM;
}
char * VariableNode::GetNodeText () [protected], [virtual]
Implements ExpressionNode.
Reimplemented in InsVariableNode.
Definition at line 295 of file values.cpp.
References Variable::GetName(), and variable.
{
    return variable->GetName();
}
int VariableNode::GetPrecedence () [virtual]
Implements ExpressionNode.
Definition at line 274 of file values.cpp.
{
    return 0;
}
char * VariableNode::GetText () [virtual]
Implements ExpressionNode.
Reimplemented in InsVariableNode.
Definition at line 290 of file values.cpp.
References Variable::GetName(), and variable.
{
    return variable->GetName();
}
void VariableNode::Replace (SyntaxNode * n, SyntaxNode * x) [virtual]
Implements SyntaxNode.
Definition at line 311 of file values.cpp.
{ }
Member Data Documentation
Variable* VariableNode::variable [private]
Definition at line 120 of file values.h.
Referenced by AssignValue(), Evaluate(), GetNodeText(), GetText(), and VariableNode().
Author
Generated automatically by Doxygen for amath from the source code.