VersionStatement
NAME
VersionStatement - Show version string.
SYNOPSIS
#include <statements.h>
Inherits StatementNode.
Public Member Functions
VersionStatement ()
~VersionStatement ()
char * Execute ()
Additional Inherited Members
Detailed Description
Show version string.
Definition at line 83 of file statements.h.
Constructor & Destructor Documentation
VersionStatement::VersionStatement () [inline]
Definition at line 85 of file statements.h.
Referenced by Parser::ParseStatement().
{ }
VersionStatement::~VersionStatement () [inline]
Definition at line 86 of file statements.h.
{ }
Member Function Documentation
char * VersionStatement::Execute () [virtual]
Implements StatementNode.
Definition at line 73 of file statements.cpp.
References CharBuffer::Append(), CharBuffer::Empty(), CharBuffer::EnsureSize(), CharBuffer::GetString(), SyntaxNode::output, and StrLen().
{
    output->Empty();
    output->EnsureSize(
        StrLen(BOLD) +
        StrLen(TXTVERSMSG) +
        StrLen(NEWLINE) * 2 +
        StrLen(NORMALTEXT) +
        StrLen(TXTCOMPMSG));
    output->Append(BOLD);
    output->Append(TXTVERSMSG);
    output->Append(NORMALTEXT);
    output->Append(NEWLINE);
    output->Append(TXTCOMPMSG);
    output->Append(NEWLINE);
    return output->GetString();
}
Author
Generated automatically by Doxygen for amath from the source code.