.TH "app/main/viewer.cpp" 3 "Fri Jan 20 2017" "Version 1.6.0" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/main/viewer.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/charbuf\&.h'\fP
.br
\fC#include 'main/viewer\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
