.TH "app/system/window_amiga.cpp" 3 "Sat Jan 21 2017" "Version 1.6.1" "amath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
app/system/window_amiga.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'clib\&.h'\fP
.br
\fC#include 'lib/aengine\&.h'\fP
.br
\fC#include 'localize/start\&.h'\fP
.br
\fC#include 'main/evaluator\&.h'\fP
.br
\fC#include 'system/window_amiga\&.h'\fP
.br
\fC#include 'system/base/io\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for amath from the source code\&.
